### ISSUE TITLE
PTVS causes the VS to crash while opening a sln

### ISSUE THREAD

**Issue by mlovato** [Microsoft/PTVS#1058]
I've installed Python Tools 2.2.31105.00 in VS 2015 Professional Update 1.
Every time I open a sln the VS crashes while loading a particular project. But the same project can be opened from the vcproj file.

This is an extract from the PythonTools diagnostics Info. At the end of the info you can find the exception that is thrown.

Projects: 
Environments: 
    Microsoft.PythonTools.Project.LoadedProjectInterpreterFactoryProvider
    Microsoft.PythonTools.Interpreter.ConfigurablePythonInterpreterFactoryProvider
    Microsoft.PythonTools.Interpreter.CPythonInterpreterFactoryProvider
        Id: 2af0f10d-7135-4994-9156-5d01c9c11b7e
        Factory: Python 2.7
        Version: 2.7
        Arch: X86
        Prefix Path: C:\Python27\
        Path: C:\Python27\python.exe
        Windows Path: C:\Python27\pythonw.exe
        Lib Path: C:\Python27\lib
        Path Env: PYTHONPATH

        Id: 9a7a9026-48c1-4688-9d5d-e5699d47d074
        Factory: Python 64-bit 3.4
        Version: 3.4
        Arch: Amd64
        Prefix Path: C:\Python34\
        Path: C:\Python34\python.exe
        Windows Path: C:\Python34\pythonw.exe
        Lib Path: C:\Python34\lib
        Path Env: PYTHONPATH

    Microsoft.IronPythonTools.Interpreter.IronPythonInterpreterFactoryProvider
    Microsoft.PythonTools.Uwp.Interpreter.PythonUwpInterpreterFactoryProvider
Launchers:
    Launcher: Microsoft.PythonTools.Project.DefaultLauncherProvider
        Launches and debugs Python programs. This is the default.
        Standard Python launcher

    Launcher: Microsoft.PythonTools.Project.Web.PythonWebLauncherProvider
        Launches web sites using the Python debugger. This enables launching and starting a web browser automatically, using the commands specified in the project file.
        Web launcher

    Launcher: Microsoft.PythonTools.Django.Debugger.DjangoLauncherProvider
        Launches Django web sites using the Python debugger. This enables launching and starting a web browser automatically. It launches using manage.py and passes the runserver flag as well as additional options to configure the port and other settings.
        Django launcher

    Launcher: Microsoft.IronPythonTools.Debugger.IronPythonLauncherProvider
        Launches IronPython scripts using the .NET debugger.  This enables debugging both IronPython code as well as other .NET code such as C# or VB.NET.
        IronPython (.NET) launcher

Logged events/stats:
Installed Interpreters: 2
Configured Interpreters: 0
Debug Launches: 0
Normal Launches: 0

System events:
Time: 2016-01-15T07:54:47
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException
   at EnvDTE.Configuration.get_OutputGroups()
   at Microsoft.VisualStudioTools.Project.ProjectReferenceNode.get_ReferencedProjectOutputPath()
   at Microsoft.PythonTools.Project.PythonProjectReferenceNode+<AddAnalyzedAssembly>d__14.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudioTools.TaskExtensions+<DoNotWait>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

**Comment by mlovato** [comment]
Reinstalling PTVS fixed the issue
