### ISSUE TITLE
Cannot debug script that uses colorama

### ISSUE THREAD

**Issue by willyd** [Microsoft/PTVS#1070]
When I try to debug this simple script:

```Python
import colorama
colorama.init()
```
```
I get the following error:
Traceback (most recent call last):
  File "C:\Work\src\test.py", line 2, in
<module>
    colorama.init()
  File "C:\Anaconda\lib\site-packages\colorama\initialise.py", line 31, in init
    wrap_stream(orig_stdout, convert, strip, autoreset, wrap)
  File "C:\Anaconda\lib\site-packages\colorama\initialise.py", line 61, in wrap_
stream
    convert=convert, strip=strip, autoreset=autoreset)
  File "C:\Anaconda\lib\site-packages\colorama\ansitowin32.py", line 68, in __in
it__
    convert = on_windows and not wrapped.closed and not on_emulated_windows and
is_a_tty(wrapped)
AttributeError: '_ReplOutput' object has no attribute 'closed'
Press any key to continue . . .
```
Adding
```
self.closed = False
```
to class `_ReplOutput` fixes the problem. I am not sure what is the proper way of fixing this. With some hints I could send a PR.

Thanks

**Comment by zooba** [comment]
The easiest fix is to add `closed = False` underneath the `errors = None` line in `_ReplOutput`. A pull request would be great! It'll make it into our 2.2.3 release (coming in the next few months).
