### ISSUE TITLE
Error creating virtual environment

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#1114]
PTVS 3.0
CPython 3.4 (the one we link to from the F5 No Interpreters Page) and IronPython 2.7.5 installed.

Downloaded the zip file for azure-sdk-for-python repository: https://github.com/Azure/azure-sdk-for-python/archive/master.zip
Open the solution in VS.
Add New Virtual Environment, based on Python 3.4
Check Download and Install Packages
Click Create and close dialog.

```
---------------------------
Python Tools for Visual Studio
---------------------------
An unexpected error occurred.



You can get more information by running Visual Studio with the /log parameter on the command line, and then examining the file 'censored', or by checking the Event Log.
---------------------------
OK   
---------------------------

```

Output window:

```
Virtual environment is being created at 'C:\Projects\azure-sdk-for-python-master\env'
Virtual environment was successfully created at 'C:\Projects\azure-sdk-for-python-master\env'
Installing packages from 'C:\Projects\azure-sdk-for-python-master\requirements.txt'

```

From event viewer:

```
Unhandled exception in Microsoft.PythonTools.Project.AddVirtualEnvironment.Save_Executed (C:\VSOAgent\_work\3\s\Python\Product\PythonTools\PythonTools\Project\AddVirtualEnvironment.xaml.cs:127)
System.IO.FileNotFoundException: (null)
   at Microsoft.PythonTools.PythonInterpreterFactoryRunnableExtensions.ThrowIfNotRunnable(IPythonInterpreterFactory factory, String parameterName)
   at Microsoft.PythonTools.Project.Pip.<Install>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Project.AddVirtualEnvironmentOperation.<Run>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Project.AddVirtualEnvironmentView.<Create>d__105.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
```

**Comment by zooba** [comment]
We are not handling exceptions in `AddVirtualEnvironmentOperation.Run()` when installing packages.
