### ISSUE TITLE
Show full details of .NET exceptions, including inner exception

### ISSUE THREAD

**Issue by shift-evgeny** [Microsoft/PTVS#1192]
Visual Studio 2015 Update 1, IronPython 2.7.5 (2.7.5.0) on .NET 4.0.30319.42000 (64-bit)

In an Interactive window run:

```
>>> from System import Exception
>>> raise Exception("outer", Exception("inner"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
Exception: outer
```

No details of the inner exception are shown, which makes it impossible to debug many problems in .NET.

I tried -X:ShowClrExceptions and -X:PassExceptions and these work when running ipy64.exe from the command line, but seem to have no effect in the Visual Studio Interactive window (even though I can see in Process Hacker that it runs ipy64.exe with those parameters).

**Comment by denfromufa** [comment]
this works great in pythonnet:

```
Python 3.5.3 |Anaconda custom (64-bit)| (default, Feb 22 2017, 21:28:42) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import clr
>>> raise Exception("outer", Exception("inner"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
Exception: ('outer', Exception('inner',))
```
