### ISSUE TITLE
Crash in GetZipFileName

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#1269]
From event log:

```
Application: Microsoft.PythonTools.Analyzer.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Microsoft.PythonTools.Intellisense.OutOfProcProjectAnalyzer.GetZipFileName(Microsoft.PythonTools.Analysis.IProjectEntry)
   at Microsoft.PythonTools.Intellisense.OutOfProcProjectAnalyzer.ParseFile(Microsoft.PythonTools.Analysis.IProjectEntry, System.Collections.Generic.IDictionary`2<Int32,CodeInfo>)
   at Microsoft.PythonTools.Intellisense.OutOfProcProjectAnalyzer+<>c__DisplayClass84_0.<UpdateContent>b__0()
   at Microsoft.PythonTools.Intellisense.OutOfProcProjectAnalyzer+<>c__DisplayClass134_0.<EnqueWorker>b__0(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by int19h** [comment]
@zooba, so did we regress on .zip file support when migrating out-of-proc, or does it just live elsewhere now?

**Comment by zooba** [comment]
Not sure - @DinoV ?
