### ISSUE TITLE
Bogus error message

### ISSUE THREAD

**Issue by gbritton1** [Microsoft/PTVS#1287]
I have a simple helper module (helpers.py):

```
import re
pattern = re.compile('^<.*>$')

def get_properties(obj):
    for member in filter(lambda x: not x.startswith('__'), dir(obj)):
        try:
            if not callable(getattr(obj, member)):
                if not pattern.match(str(getattr(obj, member))):
                    yield member, getattr(obj, member)
        except Exception as ex: 
            # Not every member is available in every SQL Server edition
            continue

def print_properties(obj):
    for prop, value in get_properties(obj):
        print '{:50}: {}'.format(prop, value)
```

A simple IronPython program run from the command line:

```
C:\Users\brittg2\Projects\Python\TestPy\IronPythonApplication1>"\Program Files (
x86)\IronPython 2.7\ipy.exe"
IronPython 2.7.5 (2.7.5.0) on .NET 4.0.30319.34209 (32-bit)
Type "help", "copyright", "credits" or "license" for more information.

>>> from helpers import get_properties, print_properties
>>> class A:
...     foo = 42
...
>>> a = A()
>>> print_properties(a)
foo                                               : 42
>>>
```

works fine.  Run from PTVS it fails:

```
>>> from helpers import get_properties, print_properties
>>> class A:
...     foo = 42
... 
>>> a = A()
>>> print_properties(a)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\brittg2\Projects\Python\TestPy\IronPythonApplication1\helpers.py", line 15, in print_properties
    for prop, value in get_properties(obj):
  File "C:\Users\brittg2\Projects\Python\TestPy\IronPythonApplication1\helpers.py", line 5, in get_properties
    for member in filter(lambda x: not x.startswith('__'), dir(obj)):
  File "C:\Users\brittg2\Projects\Python\TestPy\IronPythonApplication1\helpers.py", line 5, in <lambda$253>
    for member in filter(lambda x: not x.startswith('__'), dir(obj)):
AttributeError: 'str' object has no attribute 'StartsWith'
>>> 
```

Not only does it fail, but the error message makes no sense. str objects do indeed have attributes called startswith (though not the camelcase StartsWith) as called

**Comment by DinoV** [comment]
Are you running in the REPL from PTVS?

This looks like it might be an IronPython bug.  You can try adding an "import clr" to the top of your helpers file to try and work around it...

**Comment by gbritton1** [comment]
The error occurred in the vs interactive window. Running ipy from the
command line works with the same code.  That pretty much rules out an ipy
bug I think. I don't need the CLR module in the helpers.

**Comment by gbritton1** [comment]
FWIW adding "import clr" to the helpers module had no effect.  But then why would it?  The test example is not using any clr code.  It runs fine in other Python environments, where there is no clr to import.

**Comment by gbritton1** [comment]
BTW Installing the latest version of 2.1 seemed to cure the problem
