### ISSUE TITLE
Upgrading pydocumentdb from PTVS

### ISSUE THREAD

**Issue by rnagpal** [Microsoft/PTVS#1310]
My version of PTVS comes with pydocumentdb 1.2.0 and I tried upgrading it to 1.7.0(latest one) by right clicking on **Python 64-bit 2.7** in my Solution Explorer and I typed **pydocumentdb --upgrade** in the command line hoping to upgrade it to 1.7.0.

From the log before it looks like it got installed but I got the following error(at the end). I do see pydocumentdb-1.7.0.dist-info and pydocumentdb folder being created in the site-packages folder on my machine but cannot find pydocumentdb-1.2.0-py2.7.egg.

Is this an issue with our package management? Our SDK code is on GitHub in case you want to look at our setup.py or any other setup related files in case that's a bug on our side. Here is the GitHub link: https://github.com/Azure/azure-documentdb-python 

```
Installing 'pydocumentdb --upgrade'
Collecting pydocumentdb
  Downloading pydocumentdb-1.7.0-py2-none-any.whl
Installing collected packages: pydocumentdb
  Found existing installation: pydocumentdb 1.2.0
    Uninstalling pydocumentdb-1.2.0:
      Successfully uninstalled pydocumentdb-1.2.0
Successfully installed pydocumentdb
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\lib\site-packages\pip\__main__.py", line 19, in <module>
    sys.exit(pip.main())
  File "C:\Python27\lib\site-packages\pip\__init__.py", line 217, in main
    return command.main(cmd_args)
  File "C:\Python27\lib\site-packages\pip\basecommand.py", line 248, in main
    pip_version_check(session)
  File "C:\Python27\lib\site-packages\pip\utils\outdated.py", line 102, in pip_version_check
    installed_version = get_installed_version("pip")
  File "C:\Python27\lib\site-packages\pip\utils\__init__.py", line 858, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "C:\Python27\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 629, in __init__
    self.add_entry(entry)
  File "C:\Python27\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 685, in add_entry
    for dist in find_distributions(entry, True):
  File "C:\Python27\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2075, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "C:\Python27\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1605, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "C:\Python27\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1963, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "C:\Python27\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1843, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "C:\Python27\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1783, in load
    mtime = os.stat(path).st_mtime
WindowsError: [Error 2] The system cannot find the file specified: 'C:\\Python27\\lib\\site-packages\\pydocumentdb-1.2.0-py2.7.egg'
'pydocumentdb --upgrade' failed to install. Exit code: 1
```

PTVS and VS details below:

Python Tools for Visual Studio   2.2.40315.00
Python Tools for Visual Studio provides IntelliSense, projects, templates, Interactive windows, and other support for Python developers.

Microsoft Visual Studio Enterprise 2015
Version 14.0.25123.00 Update 2
Microsoft .NET Framework
Version 4.6.01038

Installed Version: Enterprise

**Comment by zooba** [comment]
I wonder whether it had previously been installed with `easy_install` rather than `pip`? That's the only way it could have ended up with an .egg file there, though then pip shouldn't have been able to remove it.

In fact, I just tried exactly that and got the same error:
```
PS E:\Temp> py -2.7 -m virtualenv testenv
... creating virtualenv
PS E:\Temp> .\testenv\Scripts\easy_install.exe pydocumentdb==1.2.0
... installed
PS E:\Temp> .\testenv\Scripts\pip install pydocumentdb==1.7.*
... failed - same error
```

If I do the same thing with pip instead of `easy_install`, there are no issues. So this is a pip/setuptools fight that we aren't involved in.
