### ISSUE TITLE
Crash in DisableBreakPoint

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/PTVS#1316]
**Repro steps:**
1. Set a break-point in python code and start debugging
2. After the break-point is hit, press "stop debugging" 
3. You will get this exception.

```
System.ObjectDisposedException was unhandled by user code
  HResult=-2146232798
  Message=Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.
  ObjectName=System.Net.Sockets.NetworkStream
  Source=System
  StackTrace:
       at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
       at Microsoft.PythonTools.Debugger.Extensions.Write(Stream stream, Byte[] b) in D:\GitHubProjects\PTVS\Python\Product\Debugger\Debugger\Extensions.cs:line 140
       at Microsoft.PythonTools.Debugger.PythonProcess.DisableBreakPoint(PythonBreakpoint unboundBreakpoint) in D:\GitHubProjects\PTVS\Python\Product\Debugger\Debugger\PythonProcess.cs:line 1185
       at Microsoft.PythonTools.Debugger.PythonProcess.RemoveBreakPoint(PythonBreakpoint unboundBreakpoint) in D:\GitHubProjects\PTVS\Python\Product\Debugger\Debugger\PythonProcess.cs:line 1175
       at Microsoft.PythonTools.Debugger.PythonBreakpoint.Remove() in D:\GitHubProjects\PTVS\Python\Product\Debugger\Debugger\PythonBreakpoint.cs:line 89
       at Microsoft.PythonTools.Debugger.DebugEngine.AD7BoundBreakpoint.Microsoft.VisualStudio.Debugger.Interop.IDebugBoundBreakpoint2.Delete() in D:\GitHubProjects\PTVS\Python\Product\Debugger\Debugger\DebugEngine\AD7BoundBreakpoint.cs:line 55
  InnerException: 
```

**Comment by huguesv** [comment]
Debugger protocol was all rewritten since then, and this doesn't repro anymore.
