### ISSUE TITLE
unknown error from external (venv) project_path>pip3 install browser-cookie3 w/ VS2015 IntelliSense refresh while selected venv (Python 3.5) in Python Environments

### ISSUE THREAD

**Issue by mklump** [Microsoft/PTVS#1333]
```
[Window Title]
Python Tools for Visual Studio

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
System.UnauthorizedAccessException: Access to the path 'C:\Users\Matthew James\Documents\Visual Studio 2015\Projects\codeguild_finalproject_fxalarm\finalproject_fxalarm\venv\.ptvs\django' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at Microsoft.PythonTools.EnvironmentsList.DBPackageView.<FromModuleList>d__5.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.PythonTools.EnvironmentsList.DBEnvironmentView.<RefreshPackagesAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.EnvironmentsList.DBEnvironmentView.<Provider_ModulesChanged>d__12.MoveNext()
```

**Comment by zooba** [comment]
Thanks! I think we've already fixed this in our latest versions (we added a special directory enumerator that doesn't crash with these errors), but we'll take another look before closing.
