### ISSUE TITLE
Python Tools for VS 2015 community update 2

### ISSUE THREAD

**Issue by cdwaddell23** [Microsoft/PTVS#1344]
[Window Title]
Python Tools for Visual Studio

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[V] Show details  [Close]

[Expanded Information]
System.UnauthorizedAccessException: Access to the path 'D:\DeanSystems\DIYIntegration\theDIYPlanner.com\planner\diyplanner\.ptvs\ebcli' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at Microsoft.PythonTools.EnvironmentsList.DBPackageView.<FromModuleList>d__5.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.PythonTools.EnvironmentsList.DBEnvironmentView.<RefreshPackagesAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.EnvironmentsList.DBEnvironmentView.<Provider_ModulesChanged>d__12.MoveNext()

**Comment by AnneTheAgile** [comment]
you don't give steps to reproduce.

**Comment by zooba** [comment]
In this case, there aren't really any steps - it's come from a background update that's trying to scan directories. But the general rule of including repro steps is still a good one :)

Also, we've already fixed this issue, so I'll close this.
