### ISSUE TITLE
Out-of-proc analyzer requires probing path for MSBuild

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#1399]
To deal with errors like this:

```
7/5/2016 11:59:04 AM Operation Failed System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Build, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Microsoft.PythonTools.Interpreter.MSBuildProjectInterpreterFactoryProvider.Provider_ProjectContextsChanged(Object sender, EventArgs e)
   at Microsoft.PythonTools.Interpreter.MSBuildProjectInterpreterFactoryProvider.EnsureInitialized()
   at Microsoft.PythonTools.Interpreter.MSBuildProjectInterpreterFactoryProvider.<GetInterpreterConfigurations>d__13.MoveNext()
   at Microsoft.PythonTools.Interpreter.InterpreterRegistryService.GetConfigurations()
   at Microsoft.PythonTools.Interpreter.InterpreterRegistryService.get_Configurations()
   at Microsoft.PythonTools.Intellisense.OutOfProcProjectAnalyzer.Initialize(InitializeRequest request)
   at Microsoft.PythonTools.Intellisense.OutOfProcProjectAnalyzer.<RequestHandler>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Ipc.Json.Connection.<ProcessRequest>d__19.MoveNext()
```

**Comment by zooba** [comment]
Resolved this with #1448
