### ISSUE TITLE
DB Intellisense doesn't work for weird/custom Python installs (QGIS)

### ISSUE THREAD

**Issue by MattReimer** [Microsoft/PTVS#1431]
For context I'm trying to develop QGIS plugins. QGIS Installs as part of OSGEO4W and it uses a custom version of Python27. I've successfully gotten this to work on Eclipse and PyCharm but I really want to use MSVC 2015. 

The problem is that the intellisense DB refresh isn't working when the binary files are separated from the `Lib` folder.

### Here's the batch file I use to launch MSVS 2015:

```
@echo off
call "..\..\bin\o4w_env.bat"
@echo off
path %OSGEO4W_ROOT%\apps\qgis\bin;%PATH%
set QGIS_PREFIX_PATH=%OSGEO4W_ROOT:\=/%/apps/qgis
set GDAL_FILENAME_IS_UTF8=YES
rem Set VSI cache to be used as buffer, see #6448
set VSI_CACHE=TRUE
set VSI_CACHE_SIZE=1000000
set QT_PLUGIN_PATH=%OSGEO4W_ROOT%\apps\qgis\qtplugins;%OSGEO4W_ROOT%\apps\qt4\plugins
set PYTHONPATH=%OSGEO4W_ROOT%\apps\qgis\python;%PYTHONPATH%
"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe"
```

### Here are my initial python environment settings:

```
Prefix Path: C:\OSGeo4W64\bin
Interpreter Path: C:\OSGeo4W64\bin\python.exe
Windowed Interpreter Path: C:\OSGeo4W64\bin\pythonw.exe
Library Path: C:\OSGeo4W64\apps\Python27\Lib   <-- Notice very different from bins
Langauge version: 2.7
Architecture: 64-bit
Path Environment Variable: PYTHONPATH
```

### And here's the error from my `Python Tools\CompletionDB\14.0\AnalysisLog.txt` file:

It's just a modification of the one that launches QGis:

```
2016-07-14T14:34:47: Start analysis
2016-07-14T14:35:24: IncludeModulesFromModulePath = win32com
2016-07-14T14:36:11: Deleting 0 files
2016-07-14T14:36:11: Scraping builtin modules
2016-07-14T14:36:11: Command: C:\OSGeo4W64\apps\Python27\python.exe "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio\2.2\PythonScraper.py" "C:\Users\Matt\AppData\Local\Python Tools\CompletionDB\14.0\a0f354e1-5da1-486a-b3cb-1493f62a06b9\2.7\\" "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio\2.2\CompletionDB\\"
2016-07-14T14:36:11: [WARNING] Errors
ImportError: No module named site
2016-07-14T14:36:11: [ERROR] Failed to scrape builtin modules (Exit Code: 1)
2016-07-14T14:36:11: [ERROR] Analysis failed
System.InvalidOperationException: Failed to scrape builtin modules
   at Microsoft.PythonTools.Analysis.PyLibAnalyzer.<Scrape>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Analysis.PyLibAnalyzer.<RunWorker>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Analysis.PyLibAnalyzer.<Run>d__30.MoveNext()
```

the `ImportError: No module named site` error makes me think that there is a problem since I went to the Library path and `site.py` is right there.

**Comment by MattReimer** [comment]
As kind of a hail-mary pass we just tried copying the `python.exe` and `pythonw.exe` files next to where the `Lib` folder lives. 

Now we have:

```
Prefix Path: C:\OSGeo4W64\apps\Python27
Interpreter Path: C:\OSGeo4W64\apps\Python27\python.exe
Windowed Interpreter Path: C:\OSGeo4W64\apps\Python27\pythonw.exe
Library Path: C:\OSGeo4W64\apps\Python27\Lib
Langauge version: 2.7
Architecture: 64-bit
Path Environment Variable: PYTHONPATH
```

The intellisense DB is now able to populate. I don't understand why this works.

**Comment by zooba** [comment]
I think the problem is that we suppress `PYTHONPATH`, since 99% of the time it isn't going to be reliable. (As you're launching VS from a batch file that sets it specially, you are in that other 1%.)

There's an option under Tools, Options, Python Tools, General to stop suppressing `PYTHONPATH`, but I have a feeling it doesn't actually affect the IntelliSense DB. I'll look at whether we can bypass that easily, but I suspect it's going to require some fairly significant code changes in PTVS...

Ideally (with my CPython core developer hat on), QGIS would stop using an unsupported layout - Python itself is not designed to work like that, so they should either change the interpreter or use the supported layout.

**Comment by MattReimer** [comment]
I did have the suppression of`PYTHONPATH` turned off and was really hoping this would fix all my problems. My terminal and debugging seems happy but intellisense is not pleased, even when `PYTHONPATH` is correctly set which makes me inclined to believe your theory.

I agree that QGIS having such a non-standard python install is weird but I am a small fish in that pond and I don't know why they do it in the first place so I'm kind of stuck with it and my kludgy hack.

**Comment by zooba** [comment]
FWIW, I think your "hack" is actually an improvement, but in any case we should ensure that the option to not blank out `PYTHONPATH` is flowed through correctly.
