### ISSUE TITLE
Mixed stdin and stdout in VS 2015 interactive window

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#145]
Unmodified session - the three numbers and then empty line are what I typed into stdin:

```
Python interactive window. Type $help for a list of commands.
>>> x = 5
>>> while x > 0:
...     x = int(input('Give a number'))
... 
Give a numberGive a numberGive a numberGive a numberTraceback (most recent call last):
  File "<stdin>", line 2, in <module>
ValueError: invalid literal for int() with base 10: ''
1
2
3

>>> 
```

I'd expect stdin and stdout/stderr to be intermingled properly.

**Comment by zooba** [comment]
Similar strange things also happen when images appear in the repl, and especially when you start zooming in and out.

**Comment by zooba** [comment]
The debug repl evaluator tests mostly seem to be failing as well:

```
Initialization method PythonToolsTests.DebugReplEvaluatorTests35.TestInit threw exception. System.NullReferenceException: System.NullReferenceException: Object reference not set to an instance of an object..
    at Microsoft.PythonTools.Repl.BasePythonReplEvaluator.GetInteractiveCommands(IServiceProvider serviceProvider, IInteractiveWindow window, IInteractiveEvaluator eval) in C:\Source\Python\Product\PythonTools\PythonTools\Repl\BasePythonReplEvaluator.cs:line 1712
   at Microsoft.PythonTools.Repl.PythonDebugReplEvaluator.InitializeAsync() in C:\Source\Python\Product\PythonTools\PythonTools\Repl\PythonDebugReplEvaluator.cs:line 564
   at TestUtilities.Mocks.MockReplWindow..ctor(IInteractiveEvaluator eval, String contentType) in C:\Source\Common\Tests\Utilities\Mocks\MockReplWindow.cs:line 58
   at PythonToolsTests.DebugReplEvaluatorTests.TestInit() in C:\Source\Python\Tests\Core\DebugReplEvaluatorTests.cs:line 72
```

**Comment by zooba** [comment]
ANSI colour codes in IPython errors are not translated at all:

```
[1;31merror[0m: syntax error
```

**Comment by smortaz** [comment]
also recall that whenever there is an error in the repl, there is a very
long pause before errors are spit out.

**Comment by huguesv** [comment]
Integers get printed fine on VS 2013, but not on VS 2015.

![replnointegers](https://cloud.githubusercontent.com/assets/1696845/7657485/02aece9e-fae7-11e4-94a8-e1f136641d1f.png)

They're not invisible, ie. if I select all and copy to notepad, they are not there.

**Comment by zooba** [comment]
Removed the issues that have been fixed, leaving the original which has not.

**Comment by zooba** [comment]
This has been fixed in later builds of VS, but still exists in 2015 RC.
