### ISSUE TITLE
Assertion Fails in TransformStatementToken

### ISSUE THREAD

**Issue by crwilcox** [Microsoft/PTVS#147]
Assertion on ln 348 (Debug.Assert(_start >= 0);) fails.  

``` python
def setup_some(param, param_1):
    urlparse(
    pass
```

I typed the '(') in url parse when this failed

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------




   at Microsoft.PythonTools.Parsing.Tokenizer.TransformStatementToken(Token token) in e:\PTVS\Python\Product\Analysis\Parsing\Tokenizer.cs:line 348

   at Microsoft.PythonTools.Parsing.Tokenizer.ReadName() in e:\PTVS\Python\Product\Analysis\Parsing\Tokenizer.cs:line 1356

   at Microsoft.PythonTools.Parsing.Tokenizer.Next() in e:\PTVS\Python\Product\Analysis\Parsing\Tokenizer.cs:line 611

   at Microsoft.PythonTools.Parsing.Tokenizer.GetNextToken() in e:\PTVS\Python\Product\Analysis\Parsing\Tokenizer.cs:line 438

   at Microsoft.PythonTools.Parsing.Parser.FetchLookahead() in e:\PTVS\Python\Product\Analysis\Parsing\Parser.cs:line 4587

   at Microsoft.PythonTools.Parsing.Parser.NextToken() in e:\PTVS\Python\Product\Analysis\Parsing\Parser.cs:line 4578

   at Microsoft.PythonTools.Parsing.Parser.AddTrailers(Expression ret, Boolean allowGeneratorExpression) in e:\PTVS\Python\Product\Analysis\Parsing\Parser.cs:line 3157

   at Microsoft.PythonTools.Parsing.Parser.AddTrailers(Expression ret) in e:\PTVS\Pyth......

<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------
```

We don't seem to use _start in this method and are leaving it in a bad state when exiting this method.  We quite possibly handle this well since the assertion doesn't seem to break much other than alerting us of a bad state.

**Comment by zooba** [comment]
No repro
