### ISSUE TITLE
Invalid cross thread call when start debugging

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#1502]
I used the debug repl during my previous debug session,  When I hit F5 the next time, I got this assert.

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Invalid cross-thread call



   at Microsoft.VisualStudioTools.VsExtensions.MustBeCalledFromUIThread(UIThreadBase self, String message) in C:\Projects\huguesv\PTVS\Common\Product\SharedProject\VsExtensions.cs:line 109

   at Microsoft.PythonTools.Extensions.GetPythonToolsService(IServiceProvider serviceProvider) in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Extensions.cs:line 655

   at Microsoft.PythonTools.Repl.PythonInteractiveEvaluator.set_CurrentWindow(IInteractiveWindow value) in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Repl\PythonInteractiveEvaluator.cs:line 231

   at Microsoft.PythonTools.Repl.PythonDebugReplEvaluator.AttachProcess(PythonProcess process, IThreadIdMapper threadIdMapper) in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Repl\PythonDebugReplEvaluator.cs:line 405

   at Microsoft.PythonTools.Repl.PythonDebugReplEvaluator.OnEngineAttached(Object sender, AD7EngineEventArgs e) in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Repl\PythonDebugReplEvaluator.cs:line 374

   at Microsoft.PythonTools.Debugger.DebugEngine.AD7Engine.SendLoadComplete(AD7Thread thread) in C:\Projects\huguesv\PTVS\Python\Product\Debugger\Debugger\DebugEngine\AD7Engine.cs:line 401

   at Microsoft.PythonTools.Debugger.DebugEngine.AD7Engine.OnProcessLoaded(Object sender, ThreadEventArgs e) in C:\Projects\huguesv\PTVS\Python\Product\Debugger\Debugger\DebugEngine\AD7Engine.cs:line 1356

   at Microsoft.PythonTools.Debugger.PythonProcess.HandleProcessLoad(Stream stream) in C:\Projects\huguesv\PTVS\Python\Product\Debugger\Debugger\PythonProcess.cs:line 830

   at Microsoft.PythonTools.Debugger.PythonProcess.DebugEventThread() in C:\Projects\huguesv\PTVS\Python\Product\Debugger\Debugger\PythonProcess.cs:line 458

   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Threading.ThreadHelper.ThreadStart()


---------------------------
Abort   Retry   Ignore   
---------------------------

```

**Comment by zooba** [comment]
Thanks! Just FYI, 99% of the time it's safe to ignore this and continue, so don't let it stop your debugging session. (The problem is the other 1% where VS will crash for no obvious reason, which is why we have to stop getting VS services from off the UI thread.)

**Comment by huguesv** [comment]
I got this too, when typing 0 and hitting enter in debug repl or regular repl.  Might be same root cause.

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
System.NullReferenceException: Object reference not set to an instance of an object.

   at Microsoft.PythonTools.Debugger.DebugEngine.AD7Engine.GetEngineForProcess(Process process) in C:\Projects\huguesv\PTVS\Python\Product\Debugger\Debugger\DebugEngine\AD7Engine.cs:line 1504

   at Microsoft.PythonTools.Extensions.<RefreshVariableViews>d__49.MoveNext() in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Extensions.cs:line 898

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()

   at Microsoft.PythonTools.Repl.PythonInteractiveEvaluator.<ExecuteCodeAsync>d__89.MoveNext() in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Repl\PythonInteractiveEvaluator.cs:line 459



   at Microsoft.PythonTools.Repl.PythonInteractiveEvaluator.<ExecuteCodeAsync>d__89.MoveNext() in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Repl\PythonInteractiveEvaluator.cs:line 461

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass4_0.<OutputAsyncCausalityEvents>b__0()

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke()

   at System.Runtime.CompilerServices.TaskAwaiter.<>c__DisplayClass11_0.<OutputWaitEtwEvents>b__0()

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke()

   at System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation.<>c.<.cctor>b__8_0(Object state)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.DispatcherOperation.InvokeImpl()

   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Windows.Threading.DispatcherOperation.Invoke()

   at System.Windows.Threading.Dispatcher.ProcessQueue()

   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)

   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)


---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by zooba** [comment]
Same symptom, but not the same root cause. Every one of these stack traces is valuable.
