### ISSUE TITLE
Failed to terminate TaskProvider worker thread assertion when quitting

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#1503]
I had other assertions related to debugging in the same VS session, so this could be a fallout from that.

I got 2 of these before VS quit.

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Failed to terminate TaskProvider worker thread



   at Microsoft.PythonTools.Intellisense.TaskProvider.Dispose(Boolean disposing) in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\TaskProvider.cs:line 385

   at Microsoft.PythonTools.Intellisense.TaskProvider.Dispose() in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\TaskProvider.cs:line 368

   at Microsoft.VisualStudio.Shell.Package.Dispose(Boolean disposing)

   at Microsoft.VisualStudioTools.CommonPackage.Dispose(Boolean disposing) in C:\Projects\huguesv\PTVS\Common\Product\SharedProject\CommonPackage.cs:line 100

   at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.Close()


---------------------------
Abort   Retry   Ignore   
---------------------------

```

**Comment by zooba** [comment]
I see this fairly frequently - it's a very complex deadlock between the UI thread, a worker thread and the out-of-proc analyzer.

Luckily it's harmless, but slightly annoying. I occasionally try and track it down to resolve it, but it's been difficult.

**Comment by huguesv** [comment]
Haven't seen this in a while.
