### ISSUE TITLE
Profiling not supported for the Anaconda installed by VS

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#1506]
Dev 15
Anaconda 4.1.1 64-bit 3.5

I'm getting this error when I launch profiling:
```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\VS15Preview\Common7\IDE\Extensions\Microsoft\Python\Profiling\proflaun.py", line 35, in <module>
    vspyprof.profile(__file__, globals(), locals(), profdll)
  File "C:\Program Files (x86)\Microsoft Visual Studio\VS15Preview\Common7\IDE\Extensions\Microsoft\Python\Profiling\vspyprof.py", line 74, in profile
    raise NotImplementedError("Profiling is currently not supported for " + sys.version)
NotImplementedError: Profiling is currently not supported for 3.5.2 |Anaconda 4.1.1 (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)]
Press any key to continue . . .
```

**Comment by huguesv** [comment]
FYI I get the same error for the (C) Python 64-bit 2.7.

**Comment by zooba** [comment]
In VsPyProf we assume that `VsPerf150.dll` will be installed into the system directory, but this is likely not the case. We need to properly support resolving this DLL.

**Comment by zooba** [comment]
Looks like it is currently still the case, but only the 32-bit DLL is being installed. Pinging the team to see what their plans are.

**Comment by zooba** [comment]
Not our bug - the internal bug number is 246996
