### ISSUE TITLE
autocomplete throws error 

### ISSUE THREAD

**Issue by big-kahuna-burger** [Microsoft/PTVS#1538]
![2016-08-12 11_44_29-microsoft visual studio](https://cloud.githubusercontent.com/assets/11753867/17618886/749f2984-6082-11e6-8ff8-30c5ead54ab1.png)

**Comment by big-kahuna-burger** [comment]
to be more precise, Ctrl + Space throws this

**Comment by zooba** [comment]
Whereabouts is the cursor when you press Ctrl+Space?

Also, which version of Python Tools are you using?

**Comment by big-kahuna-burger** [comment]
cursor was next to __SETS__.ma...

Python Tools dll 2.0.2.2015,
Python interperter 2.7

**Comment by zooba** [comment]
We may need to fix this in the existing release and not just 3.0, but I'll put it in that milestone for now so we don't lose track.

**Comment by zooba** [comment]
Here's the full error from the latest VS 2017 build:

```
System.ArgumentException: The Selection Status may not be set to a completion that isn't part of the completion/builder list in the completion set
Parameter name: value
   at Microsoft.VisualStudio.Language.Intellisense.CompletionSet.set_SelectionStatus(CompletionSelectionStatus value)
   at Microsoft.PythonTools.Intellisense.FuzzyCompletionSet.SelectSingleBest()
   at Microsoft.PythonTools.Intellisense.IntellisenseController.SelectSingleBestCompletion(ICompletionSession session)
   at Microsoft.PythonTools.Intellisense.IntellisenseController.TriggerCompletionSession(Boolean completeWord, Nullable`1 commitByDefault)
   at Microsoft.PythonTools.Language.EditFilter.ExecWorker(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.PythonTools.Language.EditFilter.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
```

It's annoying, but non fatal, so we'll have to push it out to an update.
