### ISSUE TITLE
Exception triggering completions

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#1540]
It is apparently possible to trigger string literal completions without being inside a string, and these don't work very well. Exception info below.

```
System.ArgumentOutOfRangeException: Index and length must refer to a location within the string. Parameter name: length
 at System.String.Substring(Int32 startIndex, Int32 length)
 at Microsoft.PythonTools.Intellisense.StringLiteralCompletionList.GetDirectoryAndPrefix(String text, String cwd, String user, String& dir, String& prefix, String& prefixReplacement)
 at Microsoft.PythonTools.Intellisense.StringLiteralCompletionList.GetEntryInfo(String text, String cwd, String user)
 at Microsoft.PythonTools.Intellisense.StringLiteralCompletionList.GetCompletions(IGlyphService glyphService)
 at Microsoft.PythonTools.Intellisense.CompletionSource.AugmentCompletionSession(ICompletionSession session, IList`1 completionSets)
 at Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionSession.Start()
 at Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionBroker.TriggerCompletion(ITextView textView)
 at Microsoft.PythonTools.Intellisense.IntellisenseController.TriggerCompletionSession(Boolean completeWord, Nullable`1 commitByDefault)
 at Microsoft.PythonTools.Intellisense.IntellisenseController.HandleChar(Char ch)
 at Microsoft.PythonTools.Intellisense.IntellisenseController.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
 at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
 at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
 at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.SendCommand(Guid cmdGroup, UInt32 cmdID, Object inParam)
 at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.TextInput(TextCompositionEventArgs args)
 at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c.<DispatchTextInputEvents>b__6_0(KeyProcessor p, TextCompositionEventArgs args)
 at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c__DisplayClass10_1`1.<Dispatch>b__0()
 at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)
```

**Comment by zooba** [comment]
Already fixed
