### ISSUE TITLE
Assert for unobserved exception

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#1541]
VS 2015 Update 3, latest PTVS from master

I pasted code from a web page that had some invisible unicode characters which appear to be spaces but are not (like those at https://www.cs.tut.fi/~jkorpela/chars/spaces.html).

I started editing and got this assertion:

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
An exception in a task was not observed. See ActivityLog.xml for more details.

System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.InvalidOperationException: Failed to parse packet: Additional text encountered after finished reading JSON content: C. Path '', line 1, position 275.

   at Microsoft.PythonTools.Ipc.Json.Connection.<WriteError>d__24.MoveNext() in C:\Projects\huguesv\PTVS\Python\Product\Ipc.Json\Connection.cs:line 373

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()

   at Microsoft.PythonTools.Ipc.Json.Connection.<ProcessMessages>d__16.MoveNext() in C:\Projects\huguesv\PTVS\Python\Product\Ipc.Json\Connection.cs:line 158

   --- End of inner exception stack trace ---

---> (Inner Exception #0) System.InvalidOperationException: Failed to parse packet: Additional text encountered after finished reading JSON content: C. Path '', line 1, position 275.

   at Microsoft.PythonTools.Ipc.Json.Connection.<WriteError>d__24.MoveNext() in C:\Projects\huguesv\PTVS\Python\Product\Ipc.Json\Connection.cs:line 373

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()

   at Microsoft.PythonTools.Ipc.Json.Connection.<ProcessMessages>d__16.MoveNext() in C:\Projects\huguesv\PTVS\Python\Product\Ipc.Json\Connection.cs:line 158<---



   at Microsoft.PythonTools.PythonToolsPackage.<>c.<.ctor>b__4_0(Object sender, UnobservedTaskExceptionEventArgs e) in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonToolsPackage.cs:line 203

   at System.Threading.Tasks.TaskScheduler.PublishUnobservedTaskException(Object sender, UnobservedTaskExceptionEventArgs ueea)

   at System.Threading.Tasks.TaskExceptionHolder.Finalize()


---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by zooba** [comment]
I've added better error handling for when the analyser process crashes or exits, which seem to be the usual causes of this problem. We shouldn't see this any more.
