### ISSUE TITLE
Diagnostics window error

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#1545]
VS 15 Preview 4 daily

Got an error when opened in diagnostics window.

```
Unhandled exception in Microsoft.PythonTools.Commands.DiagnosticsCommand.DoCommand (F:\A\_work\11\s\Python\Product\PythonTools\PythonTools\Commands\DiagnosticsCommand.cs:93)
System.InvalidOperationException: Invoke or BeginInvoke cannot be called on a control until the window handle has been created.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Delegate method)
   at Microsoft.PythonTools.Commands.DiagnosticsCommand.GetData(Control ui)
   at Microsoft.PythonTools.Commands.DiagnosticsCommand.<>c__DisplayClass5_0.<DoCommand>b__0(Object x)
```

(that's what shows up in the textbox instead of the diagnostics results)

Also, it's an inconsistent repro, sometimes it works fine.

**Comment by zooba** [comment]
This code is completely removed now.
