### ISSUE TITLE
Error trying update 2+ python libs in VS15 Preview 4, Python Environments.

### ISSUE THREAD

**Issue by tcyan** [Microsoft/PTVS#1599]
Upgrade method asked for rights elevation first time but becomes silent for next library. First library is  updated successfully and second one failed.

[Window Title]
Python Tools for Visual Studio

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Закрыть]

[Expanded Information]
```
System.Net.Sockets.SocketException (0x80004005): Сделана попытка доступа к сокету методом, запрещенным правами доступа
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.TcpListener.Start(Int32 backlog)
   at Microsoft.PythonTools.Infrastructure.ProcessOutput.RunElevated(String filename, IEnumerable`1 arguments, String workingDirectory, IEnumerable`1 env, Redirector redirector, Boolean quoteArgs, Boolean elevate, Encoding outputEncoding, Encoding errorEncoding)
   at Microsoft.PythonTools.Infrastructure.ProcessOutput.Run(String filename, IEnumerable`1 arguments, String workingDirectory, IEnumerable`1 env, Boolean visible, Redirector redirector, Boolean quoteArgs, Boolean elevate, Encoding outputEncoding, Encoding errorEncoding)
   at Microsoft.PythonTools.EnvironmentsList.PipExtensionProvider.<InstallPackage>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.EnvironmentsList.PipExtension.<UpgradePackage_Executed>d__10.MoveNext()
```

**Comment by zooba** [comment]
For my own reference, the error message translates as "An attempt is made to access the socket method prohibited privileges".

I'll have to look into how this can happen. Possibly we are trying to run two things at once with the same port?
