### ISSUE TITLE
Race condition in PythonNavigateToItemProvider

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#1603]
I am using Visual Studio 2015 Community with Update 3 and Python Tools in version 2.2.4 and I still have this error when I type `ĆTRL+,`

```
Unhandled exception in Microsoft.PythonTools.Navigation.NavigateTo.PythonNavigateToItemProvider.StartSearch (D:\PTVS\PTVS22\Python\Product\PythonTools\PythonTools\Navigation\NavigateTo\PythonNavigateToItemProvider.cs:162)
System.ObjectDisposedException: The CancellationTokenSource has been disposed.
   at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
   at Microsoft.PythonTools.Navigation.NavigateTo.PythonNavigateToItemProvider.<>c__DisplayClass6_0.<StartSearch>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudioTools.VsTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
```

**Comment by zooba** [comment]
This still exists in 3.0 - we should fix it before release.

**Comment by zooba** [comment]
It may also be the cause of #1932
