### ISSUE TITLE
Test Explorer does not recognize tests generated using nose_parameterized

### ISSUE THREAD

**Issue by hweemiin** [microsoft/PTVS#1669]
I wrote data-driven tests using https://pypi.python.org/pypi/nose-parameterized/0.5.0 but unfortunately Test Explorer unable to load those tests:

Test Name:  test_init
Test Outcome:   Failed
Result StandardError:  
Traceback (most recent call last):
  File "C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\EXTENSIONS\MICROSOFT\PYTHON TOOLS FOR VISUAL STUDIO\2.2\visualstudio_py_testlauncher.py", line 69, in <module>
    main()
  File "C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\EXTENSIONS\MICROSOFT\PYTHON TOOLS FOR VISUAL STUDIO\2.2\visualstudio_py_testlauncher.py", line 62, in main
    test = unittest.defaultTestLoader.loadTestsFromNames(opts.tests, module)
  File "C:\ActivePython2.7.8.10-x64\lib\unittest\loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "C:\ActivePython2.7.8.10-x64\lib\unittest\loader.py", line 124, in loadTestsFromName
    raise TypeError("don't know how to make test from: %s" % obj)
TypeError: don't know how to make test from: None

**Comment by huguesv** [comment]
Thanks for the report. Right now, only plain unittest tests can be discovered/executed, unfortunately.  Also see https://github.com/Microsoft/PTVS/issues/80.
