### ISSUE TITLE
Unobserved exception after creating virtual env

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#1774]
I'm on the latest from master.

Create new python application
Create virtual env based on CPython 3.5 32-bit

I went to do other stuff, came back and had this message box:
```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
An exception in a task was not observed. See ActivityLog.xml for more details.

System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.ObjectDisposedException: The semaphore has been disposed.

   at System.Threading.SemaphoreSlim.CheckDispose()

   at System.Threading.SemaphoreSlim.Release(Int32 releaseCount)

   at System.Threading.SemaphoreSlim.Release()

   at Microsoft.PythonTools.Ipc.Json.Connection.<SendMessage>d__23.MoveNext() in C:\Projects\huguesv\PTVS\Python\Product\Ipc.Json\Connection.cs:line 362

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()

   at Microsoft.PythonTools.Ipc.Json.Connection.<SendRequestAsync>d__13`1.MoveNext() in C:\Projects\huguesv\PTVS\Python\Product\Ipc.Json\Connection.cs:line 84

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()

   at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.<SendRequestAsync>d__122`1.MoveNext() in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\ProjectAnalyzer.cs:line 1473

   --- End of inner exception stack trace ---

---> (Inner Exception #0) System.ObjectDisposedException: The semaphore has been disposed.

   at System.Threading.SemaphoreSlim.CheckDispose()

   at System.Threading.SemaphoreSlim.Release(Int32 releaseCount)

   at System.Threading.SemaphoreSlim.Release()

   at Microsoft.PythonTools.Ipc.Json.Connection.<SendMessage>d__23.MoveNext() in C:\Projects\huguesv\PTVS\Python\Product\Ipc.Json\Connection.cs:line 362

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()

   at Microsoft.PythonTools.Ipc.Json.Connection.<SendRequestAsync>d__13`1.MoveNext() in C:\Projects\huguesv\PTVS\Python\Product\Ipc.Json\Connection.cs:line 84

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()

   at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.<SendRequestAsync>d__122`1.MoveNext() in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\ProjectAnalyzer.cs:line 1473<---



   at Microsoft.PythonTools.PythonToolsPackage.<>c.<.ctor>b__3_0(Object sender, UnobservedTaskExceptionEventArgs e) in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonToolsPackage.cs:line 200

   at System.Threading.Tasks.TaskScheduler.PublishUnobservedTaskException(Object sender, UnobservedTaskExceptionEventArgs ueea)

   at System.Threading.Tasks.TaskExceptionHolder.Finalize()


---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by zooba** [comment]
This is fallout from fixing the FXCop complaints. We're not handling that exception in the right place.
