### ISSUE TITLE
Task not observed assert

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#1782]
Looks different from what I've seen before.  Using dev 15 with ptvs 16301.2.

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
An exception in a task was not observed. See ActivityLog.xml for more details.

System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.ComponentModel.Win32Exception: Access is denied

   at System.Diagnostics.Process.Kill()

   at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.<Dispose>b__39_0(Task`1 t) in E:\A\_work\3\s\Python\Product\PythonTools\PythonTools\Intellisense\ProjectAnalyzer.cs:line 287

   at System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()

   at System.Threading.Tasks.Task.Execute()

   --- End of inner exception stack trace ---

---> (Inner Exception #0) System.ComponentModel.Win32Exception (0x80004005): Access is denied

   at System.Diagnostics.Process.Kill()

   at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.<Dispose>b__39_0(Task`1 t) in E:\A\_work\3\s\Python\Product\PythonTools\PythonTools\Intellisense\ProjectAnalyzer.cs:line 287

   at System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()

   at System.Threading.Tasks.Task.Execute()<---



   at Microsoft.PythonTools.PythonToolsPackage.<>c.<.ctor>b__3_0(Object sender, UnobservedTaskExceptionEventArgs e) in E:\A\_work\3\s\Python\Product\PythonTools\PythonToolsPackage.cs:line 200

   at System.Threading.Tasks.TaskScheduler.PublishUnobservedTaskException(Object sender, UnobservedTaskExceptionEventArgs ueea)

   at System.Threading.Tasks.TaskExceptionHolder.Finalize()


---------------------------
Abort   Retry   Ignore   
---------------------------

```

**Comment by huguesv** [comment]
Followed by this:
```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
An exception in a task was not observed. See ActivityLog.xml for more details.

System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.ObjectDisposedException: The semaphore has been disposed.

   at System.Threading.SemaphoreSlim.CheckDispose()

   at System.Threading.SemaphoreSlim.Release(Int32 releaseCount)

   at System.Threading.SemaphoreSlim.Release()

   at Microsoft.PythonTools.Ipc.Json.Connection.<SendMessage>d__23.MoveNext() in E:\A\_work\3\s\Python\Product\Ipc.Json\Connection.cs:line 362

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()

   at Microsoft.PythonTools.Ipc.Json.Connection.<SendRequestAsync>d__13`1.MoveNext() in E:\A\_work\3\s\Python\Product\Ipc.Json\Connection.cs:line 84

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()

   at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.<SendRequestAsync>d__122`1.MoveNext() in E:\A\_work\3\s\Python\Product\PythonTools\PythonTools\Intellisense\ProjectAnalyzer.cs:line 1473

   --- End of inner exception stack trace ---

---> (Inner Exception #0) System.ObjectDisposedException: The semaphore has been disposed.

   at System.Threading.SemaphoreSlim.CheckDispose()

   at System.Threading.SemaphoreSlim.Release(Int32 releaseCount)

   at System.Threading.SemaphoreSlim.Release()

   at Microsoft.PythonTools.Ipc.Json.Connection.<SendMessage>d__23.MoveNext() in E:\A\_work\3\s\Python\Product\Ipc.Json\Connection.cs:line 362

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()

   at Microsoft.PythonTools.Ipc.Json.Connection.<SendRequestAsync>d__13`1.MoveNext() in E:\A\_work\3\s\Python\Product\Ipc.Json\Connection.cs:line 84

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()

   at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.<SendRequestAsync>d__122`1.MoveNext() in E:\A\_work\3\s\Python\Product\PythonTools\PythonTools\Intellisense\ProjectAnalyzer.cs:line 1473<---



   at Microsoft.PythonTools.PythonToolsPackage.<>c.<.ctor>b__3_0(Object sender, UnobservedTaskExceptionEventArgs e) in E:\A\_work\3\s\Python\Product\PythonTools\PythonToolsPackage.cs:line 200

   at System.Threading.Tasks.TaskScheduler.PublishUnobservedTaskException(Object sender, UnobservedTaskExceptionEventArgs ueea)

   at System.Threading.Tasks.TaskExceptionHolder.Finalize()


---------------------------
Abort   Retry   Ignore   
---------------------------
```

Then I hit backspace on the few letters I had managed to type in the editor, completion list came up with standard message that completions may no be complete because it's analyzing.

Anyway, I hit ESC once or twice to get rid of completions, and got this:
```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Unhandled exception in Microsoft.PythonTools.Language.EditFilter.Exec (E:\A\_work\3\s\Python\Product\PythonTools\PythonTools\Navigation\EditFilter.cs:635)

System.NullReferenceException: Object reference not set to an instance of an object.

   at Microsoft.PythonTools.Intellisense.IntellisenseController.OnCompletionSessionDismissedOrCommitted(Object sender, EventArgs e) in E:\A\_work\3\s\Python\Product\PythonTools\PythonTools\Intellisense\IntellisenseController.cs:line 877

   at System.EventHandler.Invoke(Object sender, EventArgs e)

   at Microsoft.VisualStudio.Language.Intellisense.Implementation.BaseIntellisenseSession.RaiseDismissed()

   at Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionSession.Dismiss()

   at Microsoft.VisualStudio.Language.Intellisense.Implementation.DefaultCompletionSessionPresenter.ExecuteKeyboardCommand(IntellisenseKeyboardCommand command)

   at Microsoft.VisualStudio.Language.Intellisense.Implementation.IntellisenseSessionStack.ExecuteKeyboardCommand(I......

<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------

```

**Comment by huguesv** [comment]
I moved to build 16301.4 and got an Access is Denied Win32 exception from analyzer in that build too.
