### ISSUE TITLE
Exception in analysis log

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#1784]
These occurred on the same machine and at the time I got the task unobserved asserts from https://github.com/Microsoft/PTVS/issues/1782

```
2016-10-28T10:10:05 START_STDLIB "C:\Program Files (x86)\Microsoft Visual Studio\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\Microsoft.PythonTools.Analyzer.exe" /id Global|PythonCore|3.5 /version 3.5 /python "C:\Program Files\Python35\python.exe" /outdir "C:\Users\huvalo\AppData\Local\Python Tools\CompletionDB\Debug\3.0.16301.4\Global\PythonCore\3.5" /basedb "C:\Program Files (x86)\Microsoft Visual Studio\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\CompletionDB" /log "C:\Users\huvalo\AppData\Local\Python Tools\CompletionDB\Debug\3.0.16301.4\Global\PythonCore\3.5\AnalysisLog.txt" /glog "C:\Users\huvalo\AppData\Local\Python Tools\CompletionDB\Debug\3.0.16301.4\AnalysisLog.txt" /wait ""
FAIL_STDLIB: (-3) "C:\Program Files (x86)\Microsoft Visual Studio\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\Microsoft.PythonTools.Analyzer.exe" /id Global|PythonCore|3.5 /version 3.5 /python "C:\Program Files\Python35\python.exe" /outdir "C:\Users\huvalo\AppData\Local\Python Tools\CompletionDB\Debug\3.0.16301.4\Global\PythonCore\3.5" /basedb "C:\Program Files (x86)\Microsoft Visual Studio\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\CompletionDB" /log "C:\Users\huvalo\AppData\Local\Python Tools\CompletionDB\Debug\3.0.16301.4\Global\PythonCore\3.5\AnalysisLog.txt" /glog "C:\Users\huvalo\AppData\Local\Python Tools\CompletionDB\Debug\3.0.16301.4\AnalysisLog.txt" /wait ""
This interpreter is already being analyzed.
FAIL_STDLIB: (-3) "C:\Program Files (x86)\Microsoft Visual Studio\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\Microsoft.PythonTools.Analyzer.exe" /id Global|PythonCore|3.5 /version 3.5 /python "C:\Program Files\Python35\python.exe" /outdir "C:\Users\huvalo\AppData\Local\Python Tools\CompletionDB\Debug\3.0.16301.4\Global\PythonCore\3.5" /basedb "C:\Program Files (x86)\Microsoft Visual Studio\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\CompletionDB" /log "C:\Users\huvalo\AppData\Local\Python Tools\CompletionDB\Debug\3.0.16301.4\Global\PythonCore\3.5\AnalysisLog.txt" /glog "C:\Users\huvalo\AppData\Local\Python Tools\CompletionDB\Debug\3.0.16301.4\AnalysisLog.txt" /wait ""
This interpreter is already being analyzed.
2016-10-28T10:15:22 START_STDLIB "C:\Program Files (x86)\Microsoft Visual Studio\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\Microsoft.PythonTools.Analyzer.exe" /id "MSBuild|env|c:\Users\huvalo\Documents\Visual Studio 2017\Projects\BottleWebProject2\BottleWebProject2\BottleWebProject2.pyproj" /version 3.5 /python "c:\Users\huvalo\Documents\Visual Studio 2017\Projects\BottleWebProject2\BottleWebProject2\env\Scripts\python.exe" /outdir "c:\Users\huvalo\Documents\Visual Studio 2017\Projects\BottleWebProject2\BottleWebProject2\env\.ptvs\\" /basedb "C:\Program Files (x86)\Microsoft Visual Studio\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\CompletionDB" /log "c:\Users\huvalo\Documents\Visual Studio 2017\Projects\BottleWebProject2\BottleWebProject2\env\.ptvs\AnalysisLog.txt" /glog "C:\Users\huvalo\AppData\Local\Python Tools\CompletionDB\Debug\3.0.16301.4\AnalysisLog.txt" /wait ""
2016-10-28T10:16:24 FAIL_STDLIB
System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GetTypeName(String moduleName, String className) in E:\A\_work\3\s\Python\Product\Analysis\SaveAnalysis.cs:line 533
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GenerateTypeName(IPythonType type) in E:\A\_work\3\s\Python\Product\Analysis\SaveAnalysis.cs:line 625
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GenerateTypeName(AnalysisValue baseClass, Boolean isRef) in E:\A\_work\3\s\Python\Product\Analysis\SaveAnalysis.cs:line 602
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GenerateTypeName(AnalysisValue baseClass, Boolean isRef) in E:\A\_work\3\s\Python\Product\Analysis\SaveAnalysis.cs:line 617
   at Microsoft.PythonTools.Analysis.SaveAnalysis.<>c__DisplayClass35_0.<GenerateTypeName>b__0(AnalysisValue ns) in E:\A\_work\3\s\Python\Product\Analysis\SaveAnalysis.cs:line 591
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<DistinctIterator>d__63`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GenerateTypeName(IAnalysisSet name, Boolean isRef) in E:\A\_work\3\s\Python\Product\Analysis\SaveAnalysis.cs:line 591
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GenerateParameter(Parameter param, IAnalysisSet typeInfo) in E:\A\_work\3\s\Python\Product\Analysis\SaveAnalysis.cs:line 754
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GenerateArgInfo(FunctionInfo fi, IAnalysisSet[] parameters) in E:\A\_work\3\s\Python\Product\Analysis\SaveAnalysis.cs:line 730
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GenerateOverloads(FunctionInfo fi) in E:\A\_work\3\s\Python\Product\Analysis\SaveAnalysis.cs:line 719
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GenerateFunction(FunctionInfo fi) in E:\A\_work\3\s\Python\Product\Analysis\SaveAnalysis.cs:line 678
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GetMemberValueInternal(AnalysisValue type, ModuleInfo declModule, Boolean isRef) in E:\A\_work\3\s\Python\Product\Analysis\SaveAnalysis.cs:line 361
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GetMemberValue(IAnalysisSet types, ModuleInfo declModule, Boolean isRef) in E:\A\_work\3\s\Python\Product\Analysis\SaveAnalysis.cs:line 332
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GetMemberValue(VariableDef variableDef, ModuleInfo declModule, Boolean isRef) in E:\A\_work\3\s\Python\Product\Analysis\SaveAnalysis.cs:line 314
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GenerateMember(VariableDef variableDef, ModuleInfo declModule, Boolean isRef) in E:\A\_work\3\s\Python\Product\Analysis\SaveAnalysis.cs:line 297
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GenerateMembers(ModuleInfo moduleInfo, IEnumerable`1 children) in E:\A\_work\3\s\Python\Product\Analysis\SaveAnalysis.cs:line 141
   at Microsoft.PythonTools.Analysis.SaveAnalysis.SerializeModule(ModuleInfo moduleInfo) in E:\A\_work\3\s\Python\Product\Analysis\SaveAnalysis.cs:line 101
   at Microsoft.PythonTools.Analysis.SaveAnalysis.Save(PythonAnalyzer state, String outDir) in E:\A\_work\3\s\Python\Product\Analysis\SaveAnalysis.cs:line 49
   at Microsoft.PythonTools.Analysis.PyLibAnalyzer.Analyze() in E:\A\_work\3\s\Python\Product\Analyzer\PyLibAnalyzer.cs:line 1366
   at Microsoft.PythonTools.Analysis.PyLibAnalyzer.<RunWorker>d__33.MoveNext() in E:\A\_work\3\s\Python\Product\Analyzer\PyLibAnalyzer.cs:line 203
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.PythonTools.Analysis.PyLibAnalyzer.<Run>d__32.MoveNext() in E:\A\_work\3\s\Python\Product\Analyzer\PyLibAnalyzer.cs:line 159 "C:\Program Files (x86)\Microsoft Visual Studio\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\Microsoft.PythonTools.Analyzer.exe" /id Global|PythonCore|3.5 /version 3.5 /python "C:\Program Files\Python35\python.exe" /outdir "C:\Users\huvalo\AppData\Local\Python Tools\CompletionDB\Debug\3.0.16301.4\Global\PythonCore\3.5" /basedb "C:\Program Files (x86)\Microsoft Visual Studio\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\CompletionDB" /log "C:\Users\huvalo\AppData\Local\Python Tools\CompletionDB\Debug\3.0.16301.4\Global\PythonCore\3.5\AnalysisLog.txt" /glog "C:\Users\huvalo\AppData\Local\Python Tools\CompletionDB\Debug\3.0.16301.4\AnalysisLog.txt" /wait ""
2016-10-28T10:21:05 FAIL_STDLIB
System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GetTypeName(String moduleName, String className) in E:\A\_work\3\s\Python\Product\Analysis\SaveAnalysis.cs:line 533
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GenerateTypeName(IPythonType type) in E:\A\_work\3\s\Python\Product\Analysis\SaveAnalysis.cs:line 625
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GenerateTypeName(AnalysisValue baseClass, Boolean isRef) in E:\A\_work\3\s\Python\Product\Analysis\SaveAnalysis.cs:line 602
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GenerateTypeName(AnalysisValue baseClass, Boolean isRef) in E:\A\_work\3\s\Python\Product\Analysis\SaveAnalysis.cs:line 617
   at Microsoft.PythonTools.Analysis.SaveAnalysis.<>c__DisplayClass35_0.<GenerateTypeName>b__0(AnalysisValue ns) in E:\A\_work\3\s\Python\Product\Analysis\SaveAnalysis.cs:line 591
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<DistinctIterator>d__63`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GenerateTypeName(IAnalysisSet name, Boolean isRef) in E:\A\_work\3\s\Python\Product\Analysis\SaveAnalysis.cs:line 591
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GenerateParameter(Parameter param, IAnalysisSet typeInfo) in E:\A\_work\3\s\Python\Product\Analysis\SaveAnalysis.cs:line 754
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GenerateArgInfo(FunctionInfo fi, IAnalysisSet[] parameters) in E:\A\_work\3\s\Python\Product\Analysis\SaveAnalysis.cs:line 730
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GenerateOverloads(FunctionInfo fi) in E:\A\_work\3\s\Python\Product\Analysis\SaveAnalysis.cs:line 719
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GenerateFunction(FunctionInfo fi) in E:\A\_work\3\s\Python\Product\Analysis\SaveAnalysis.cs:line 678
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GetMemberValueInternal(AnalysisValue type, ModuleInfo declModule, Boolean isRef) in E:\A\_work\3\s\Python\Product\Analysis\SaveAnalysis.cs:line 361
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GetMemberValue(IAnalysisSet types, ModuleInfo declModule, Boolean isRef) in E:\A\_work\3\s\Python\Product\Analysis\SaveAnalysis.cs:line 320
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GetMemberValue(VariableDef variableDef, ModuleInfo declModule, Boolean isRef) in E:\A\_work\3\s\Python\Product\Analysis\SaveAnalysis.cs:line 314
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GenerateMember(VariableDef variableDef, ModuleInfo declModule, Boolean isRef) in E:\A\_work\3\s\Python\Product\Analysis\SaveAnalysis.cs:line 297
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GenerateMembers(ModuleInfo moduleInfo, IEnumerable`1 children) in E:\A\_work\3\s\Python\Product\Analysis\SaveAnalysis.cs:line 141
   at Microsoft.PythonTools.Analysis.SaveAnalysis.SerializeModule(ModuleInfo moduleInfo) in E:\A\_work\3\s\Python\Product\Analysis\SaveAnalysis.cs:line 101
   at Microsoft.PythonTools.Analysis.SaveAnalysis.Save(PythonAnalyzer state, String outDir) in E:\A\_work\3\s\Python\Product\Analysis\SaveAnalysis.cs:line 49
   at Microsoft.PythonTools.Analysis.PyLibAnalyzer.Analyze() in E:\A\_work\3\s\Python\Product\Analyzer\PyLibAnalyzer.cs:line 1366
   at Microsoft.PythonTools.Analysis.PyLibAnalyzer.<RunWorker>d__33.MoveNext() in E:\A\_work\3\s\Python\Product\Analyzer\PyLibAnalyzer.cs:line 203
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.PythonTools.Analysis.PyLibAnalyzer.<Run>d__32.MoveNext() in E:\A\_work\3\s\Python\Product\Analyzer\PyLibAnalyzer.cs:line 159 "C:\Program Files (x86)\Microsoft Visual Studio\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\Microsoft.PythonTools.Analyzer.exe" /id "MSBuild|env|c:\Users\huvalo\Documents\Visual Studio 2017\Projects\BottleWebProject2\BottleWebProject2\BottleWebProject2.pyproj" /version 3.5 /python "c:\Users\huvalo\Documents\Visual Studio 2017\Projects\BottleWebProject2\BottleWebProject2\env\Scripts\python.exe" /outdir "c:\Users\huvalo\Documents\Visual Studio 2017\Projects\BottleWebProject2\BottleWebProject2\env\.ptvs\\" /basedb "C:\Program Files (x86)\Microsoft Visual Studio\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\CompletionDB" /log "c:\Users\huvalo\Documents\Visual Studio 2017\Projects\BottleWebProject2\BottleWebProject2\env\.ptvs\AnalysisLog.txt" /glog "C:\Users\huvalo\AppData\Local\Python Tools\CompletionDB\Debug\3.0.16301.4\AnalysisLog.txt" /wait ""
2016-10-28T10:49:43 START_STDLIB "C:\Program Files (x86)\Microsoft Visual Studio\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\Microsoft.PythonTools.Analyzer.exe" /id "MSBuild|env|c:\Users\huvalo\Documents\Visual Studio 2017\Projects\BottleWebProject2\BottleWebProject2\BottleWebProject2.pyproj" /version 3.5 /python "c:\Users\huvalo\Documents\Visual Studio 2017\Projects\BottleWebProject2\BottleWebProject2\env\Scripts\python.exe" /outdir "c:\Users\huvalo\Documents\Visual Studio 2017\Projects\BottleWebProject2\BottleWebProject2\env\.ptvs\\" /basedb "C:\Program Files (x86)\Microsoft Visual Studio\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\CompletionDB" /log "c:\Users\huvalo\Documents\Visual Studio 2017\Projects\BottleWebProject2\BottleWebProject2\env\.ptvs\AnalysisLog.txt" /glog "C:\Users\huvalo\AppData\Local\Python Tools\CompletionDB\Debug\3.0.16301.4\AnalysisLog.txt" /wait ""
```

**Comment by zooba** [comment]
Dup of #1793
