### ISSUE TITLE
Unhandled exception after project from existing code

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#1786]
Created a web app using Brett's cookiecutter template
New Project, From Existing Code
In first page, pick the location of where code was generated

Defaults on everything else except for last page, customize project type to Generic Web Project

Result:

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Unhandled exception in Microsoft.PythonTools.Project.PythonProjectNode.UpdateAnalyzerSearchPaths (E:\A\_work\3\s\Python\Product\PythonTools\PythonTools\Project\PythonProjectNode.cs:881)

System.ArgumentNullException: Value cannot be null.

   at System.Threading.Monitor.ReliableEnter(Object obj, Boolean& lockTaken)

   at System.Threading.Monitor.Enter(Object obj, Boolean& lockTaken)

   at System.Threading.SemaphoreSlim.<WaitUntilCountOrTimeoutAsync>d__31.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()

   at Microsoft.PythonTools.Ipc.Json.Connection.<SendMessage>d__23.MoveNext() in E:\A\_work\3\s\Python\Product\Ipc.Json\Connection.cs:line 353

--- End of stack trace from previous location ......

<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by zooba** [comment]
Looks like another race condition when disposing the analyzer.
