### ISSUE TITLE
Adding the Watson Developer Cloud package to my Anaconda Python 64-bit 3.5 environment

### ISSUE THREAD

**Issue by AlanDickman** [Microsoft/PTVS#1800]
I'm trying to add the Watson Developer Cloud package to my Anaconda Python 64-bit 3.5 environment. I got this error trace.

[Window Title]
Python Tools for Visual Studio

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
System.Runtime.InteropServices.COMException (0x8000FFFF): Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.ErrorHandler.ThrowOnFailure(Int32 hr, Int32[] expectedHRFailure)
   at Microsoft.VisualStudioTools.Project.OutputWindowRedirector.<ShowAndActivate>b__11_0()
   at Microsoft.VisualStudioTools.UIThread.Invoke(Action action)
   at Microsoft.VisualStudioTools.Project.OutputWindowRedirector.ShowAndActivate()
   at Microsoft.PythonTools.InterpreterList.InterpreterListToolWindow.PipExtensionProvider_OperationStarted(Object sender, ValueEventArgs`1 e)
   at Microsoft.PythonTools.EnvironmentsList.PipExtensionProvider.OnOperationStarted(String operation)
   at Microsoft.PythonTools.EnvironmentsList.PipExtensionProvider.<InstallPackage>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.EnvironmentsList.PipExtension.<InstallPackage_Executed>d__12.MoveNext()

**Comment by AlanDickman** [comment]
It turns out that I get this error trying to add anything in the pip.

**Comment by zooba** [comment]
See whether opening the Output window (View, Output) and then trying again helps. The problem seems to be activating that window, so if it's already active, it should work better.

I believe we have fixed this for our next version though.
