### ISSUE TITLE
Unhandled error opening mixed C/Python projects

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#1860]
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.ErrorHandler.ThrowOnFailure(Int32 hr, Int32[] expectedHRFailure)
   at Microsoft.VisualStudio.ErrorHandler.ThrowOnFailure(Int32 hr)
   at Microsoft.VisualStudioTools.Project.ProjectReferenceNode.get_ReferencedProjectBuildOutputs() in C:\Projects\Work\Python\PTVS\Common\Product\SharedProject\ProjectReferenceNode.cs:line 231
   at Microsoft.PythonTools.Project.PythonProjectReferenceNode.get_ReferencedProjectOutputPath() in C:\Projects\Work\Python\PTVS\Python\Product\PythonTools\PythonTools\Project\PythonProjectReferenceNode.cs:line 84
   at Microsoft.PythonTools.Project.PythonProjectReferenceNode.Initialize() in C:\Projects\Work\Python\PTVS\Python\Product\PythonTools\PythonTools\Project\PythonProjectReferenceNode.cs:line 56
```

**Comment by zooba** [comment]
Not sure when, but this has been fixed.
