### ISSUE TITLE
Refresh DB always fails on Visual Studio 2017 RC

### ISSUE THREAD

**Issue by vitskr** [Microsoft/PTVS#1883]
Refresh DB always fails on Visual Studio 2017 RC. It works just fine on same PC within Visual Studio 2015. I tried Anaconda3 both x64 and x86. Tried Python 2.7, Python 3.5 all bitness. But it always fails. Attached diagnostics info. Right now i have anaconda3 4.2.0 installed and set as default environment

[Diagnostic Info 2016-11-24T091428.txt](https://github.com/Microsoft/PTVS/files/610672/Diagnostic.Info.2016-11-24T091428.txt)

**Comment by yongyi781** [comment]
I'm getting this too.

**Comment by ryan413** [comment]
same issue.

thanks

**Comment by Molkree** [comment]
The same issue here.
[Diagnostic Info 2016-11-27T151823.txt](https://github.com/Microsoft/PTVS/files/614685/Diagnostic.Info.2016-11-27T151823.txt)

**Comment by zooba** [comment]
Thanks everyone for the reports! It's great that you're all jumping on VS 2017 and passing on the feedback - we really appreciate it.

In this case, we found the bug *just* before release and weren't able to get a fix ready in time, but it's coming in the next update. Until then, I'm afraid there's no easy workaround (though if you're missing a particular library, what you _can_ do now is add a search path to your site-packages folder and we won't run out of memory anymore - as this is the feature that caused this bug, it's somewhat fitting that it's the best available workaround right now).

I'll leave this bug open for now to save people filing it again, but rest assured, there will be a fix soon.

**Comment by zooba** [comment]
Just for reference, this was also reported as #1784, #1793, #1878 and was fixed in #1797.

To tell if you're hitting this issue, collect your Diagnostic Info, copy it into Notepad or somewhere you can search the text, and look for the message below (the dates will be different). If you can't find anything like this, please create a new issue with your diagnostic info.

```
2016-11-18T12:14:31: Analysis complete
2016-11-18T12:14:31: Saving group "c:\python35\lib"
2016-11-18T12:14:31: [ERROR] Analysis failed
System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GetTypeName(String moduleName, String className)
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GenerateTypeName(AnalysisValue baseClass, Boolean isRef)
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GenerateTypeName(AnalysisValue baseClass, Boolean isRef)
   at Microsoft.PythonTools.Analysis.SaveAnalysis.<>c__DisplayClass35_0.<GenerateTypeName>b__0(AnalysisValue ns)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<DistinctIterator>d__63`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GenerateTypeName(IAnalysisSet name, Boolean isRef)
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GenerateParameter(Parameter param, IAnalysisSet typeInfo)
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GenerateArgInfo(FunctionInfo fi, IAnalysisSet[] parameters)
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GenerateOverloads(FunctionInfo fi)
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GenerateFunction(FunctionInfo fi)
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GetMemberValueInternal(AnalysisValue type, ModuleInfo declModule, Boolean isRef)
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GetMemberValue(IAnalysisSet types, ModuleInfo declModule, Boolean isRef)
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GenerateMember(VariableDef variableDef, ModuleInfo declModule, Boolean isRef)
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GenerateMembers(ModuleInfo moduleInfo, IEnumerable`1 children)
   at Microsoft.PythonTools.Analysis.SaveAnalysis.SerializeModule(ModuleInfo moduleInfo)
   at Microsoft.PythonTools.Analysis.SaveAnalysis.Save(PythonAnalyzer state, String outDir)
   at Microsoft.PythonTools.Analysis.PyLibAnalyzer.Analyze()
   at Microsoft.PythonTools.Analysis.PyLibAnalyzer.<RunWorker>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Analysis.PyLibAnalyzer.<Run>d__32.MoveNext()
```

**Comment by mrnameless123** [comment]
I have the same problem when I want to use Anaconda3 and code autocomplete does work well

**Comment by zooba** [comment]
The fix for this is in the latest update of VS 2017 RC. If you install it today (or in the last 2-3 weeks), you should have the fix. Otherwise, make sure you install the updates when it prompts you in VS.
