### ISSUE TITLE
Assertion failed: Unhandled exception when launching web project

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#1887]
I created a Bottle Web Project, picked to create a virtual env based on Python 2.7.
F5 and got this assertion:
```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Unhandled exception in Microsoft.PythonTools.Project.Web.PythonWebLauncher.LaunchProject (C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\WebProject\PythonWebLauncher.cs:100)

System.InvalidCastException: Specified cast is not valid.

   at Microsoft.PythonTools.Logging.InMemoryLogger.LogEvent(PythonLogEvent logEvent, Object argument) in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Logging\InMemoryLogger.cs:line 45

   at Microsoft.PythonTools.Logging.PythonToolsLogger.LogEvent(PythonLogEvent logEvent, Object data) in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Logging\PythonToolsLogger.cs:line 31

   at Microsoft.PythonTools.Project.Web.PythonWebLauncher.LaunchProject(Boolean debug) in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\WebProject\PythonWebLauncher.cs:line 94



   at Microsoft.PythonTools.Project.Web.PythonWebLauncher.LaunchProject(Boolean debug) in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\WebProject\PythonWebLauncher.cs:line 100

   at Microsoft.VisualStudioTools.Project.CommonProjectConfig.DebugLaunch(UInt32 flags) in C:\Projects\huguesv\PTVS\Common\Product\SharedProject\CommonProjectConfig.cs:line 42

   at Microsoft.PythonTools.Project.PythonProjectConfig.DebugLaunch(UInt32 flags) in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Project\PythonProjectConfig.cs:line 57


---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by huguesv** [comment]
Fixed by https://github.com/Microsoft/PTVS/pull/1892
