### ISSUE TITLE
Database check was not triggered assertion

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#1889]
I created a bottle web project, and created a virtual env for it (based on 2.7 32-bit).
After using that for a while, I went to New Project, Flask/Jade Web Project.
I got this assertion, at the time the dialog was up, solution explorer still showed by bottle project.

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Database check was not triggered for Global|PythonCore|3.5-32

   at Microsoft.PythonTools.Interpreter.PythonInterpreterFactoryWithDatabase..ctor(InterpreterConfiguration config, InterpreterFactoryCreationOptions options) in C:\Projects\huguesv\PTVS\Python\Product\Analysis\Interpreter\PythonInterpreterFactoryWithDatabase.cs:line 99

   at Microsoft.PythonTools.Interpreter.Default.CPythonInterpreterFactory..ctor(InterpreterConfiguration configuration, InterpreterFactoryCreationOptions options) in C:\Projects\huguesv\PTVS\Python\Product\Analysis\Interpreter\Default\CPythonInterpreterFactory.cs:line 22

   at Microsoft.PythonTools.Interpreter.InterpreterFactoryCreator.CreateInterpreterFactory(InterpreterConfiguration configuration, InterpreterFactoryCreationOptions options) in C:\Projects\huguesv\PTVS\Python\Product\Analysis\Interpreter\InterpreterFactoryCreator.cs:line 43

   at Microsoft.PythonTools.Interpreter.PythonInterpreterInformation.EnsureFactory() in C:\Projects\huguesv\PTVS\Python\Product\VSInterpr......

<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------

```

**Comment by zooba** [comment]
This is typically a non-fatal warning, but because of the call chain it goes through we end up blocking on a network request long enough to trigger the warning.

`PipPackageCache.GetCache` should be able to return without blocking on that network request.
