### ISSUE TITLE
Cancelling elevation during uninstall throws error

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/PTVS#1909]
System.ComponentModel.Win32Exception (0x80004005): The operation was canceled by the user
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.PythonTools.Infrastructure.ProcessOutput..ctor(Process process, Redirector redirector)
----- Error while uninstalling 'azure' -----

**Comment by zooba** [comment]
We shouldn't have to use ShellExecute here anymore, as we're launching our own properly manifested executable that will elevate by itself. We may still get an unexpected exit code if the user cancels though.
