### ISSUE TITLE
Installing packages some times causes a crash

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/PTVS#1913]
```
Application: devenv.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.ArgumentOutOfRangeException
 at System.ThrowHelper.ThrowArgumentOutOfRangeException(System.ExceptionArgument, System.ExceptionResource)
 at System.Collections.Generic.List`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].System.Collections.IList.get_Item(Int32)
 at System.Windows.Data.ListCollectionView.InternalItemAt(Int32)
 at System.Windows.Data.ListCollectionView.GetItemAt(Int32)
 at System.Windows.Controls.ItemCollection.GetItemAt(Int32)
 at System.Windows.Controls.ItemCollection.get_Item(Int32)
 at System.Windows.Controls.VirtualizingStackPanel.MeasureOverrideImpl(System.Windows.Size, System.Nullable`1<Double> ByRef, System.Collections.Generic.List`1<Double> ByRef, System.Nullable`1<Double> ByRef, Boolean)
 at System.Windows.Controls.VirtualizingStackPanel.MeasureOverride(System.Windows.Size)
 at System.Windows.FrameworkElement.MeasureCore(System.Windows.Size)
 at System.Windows.UIElement.Measure(System.Windows.Size)
 at System.Windows.ContextLayoutManager.UpdateLayout()
 at System.Windows.ContextLayoutManager.UpdateLayoutCallback(System.Object)
 at System.Windows.Media.MediaContext+InvokeOnRenderCallback.DoWork()
 at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
 at System.Windows.Media.MediaContext.RenderMessageHandlerCore(System.Object)
 at System.Windows.Media.MediaContext.RenderMessageHandler(System.Object)
 at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
 at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
 at System.Windows.Threading.DispatcherOperation.InvokeImpl()
 at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
 at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
 at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
 at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
 at System.Windows.Threading.DispatcherOperation.Invoke()
 at System.Windows.Threading.Dispatcher.ProcessQueue()
 at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
 at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
 at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
 at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
 at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
 at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
 at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr) 
```

**Comment by zooba** [comment]
Looks like a race condition, as I don't know of any other way to create this issue.
