### ISSUE TITLE
Django project issue

### ISSUE THREAD

**Issue by Jesuszilla** [Microsoft/PTVS#1940]
```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: length
   at Microsoft.VisualStudio.Text.Span..ctor(Int32 start, Int32 length)
   at Microsoft.PythonTools.Intellisense.LocationTracker.TranslateForward(Span from)
   at Microsoft.PythonTools.Intellisense.TaskProviderItem.CreateSquiggleSpan(SimpleTagger`1 tagger)
   at Microsoft.PythonTools.Intellisense.TaskProvider.<>c__DisplayClass28_0.<RefreshAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Intellisense.TaskProvider.<RefreshAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Intellisense.TaskProvider.Refresh()
```

Not really sure what's going on, but I can't build my project, either. Doesn't show any errors.

**Comment by zooba** [comment]
Actually, I think I may have fixed this already, but the fix hasn't been released yet. It should be in the next update for VS 2017 RC.
