### ISSUE TITLE
Asserts when loading project

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2063]
Using latest from master

I created a new ironpython wpf app
I realized I was missing IronPython so I closed VS, I installed IronPython 2.7.7
I start VS, open my previously created project.

This first assert happens every time:
```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Analyzer initialization failed with no result



   at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.<.ctor>b__27_3(Task`1 task) in C:\Projects\GitHub\huguesv\ptvs\Python\Product\PythonTools\PythonTools\Intellisense\ProjectAnalyzer.cs:line 184

   at System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()

   at System.Threading.Tasks.Task.Execute()

   at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)

   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)

   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()

   at System.Threading.ThreadPoolWorkQueue.Dispatch()

   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()


---------------------------
Abort   Retry   Ignore   
---------------------------
```

This one I only saw once:
```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
An exception in a task was not observed. See ActivityLog.xml for more details.

System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.ArgumentException: Stream was not readable.

   at System.IO.StreamReader..ctor(Stream stream, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean leaveOpen)

   at System.IO.StreamReader..ctor(Stream stream, Encoding encoding)

   at Microsoft.PythonTools.Ipc.Json.Connection.<ProcessMessages>d__16.MoveNext() in C:\Projects\GitHub\huguesv\ptvs\Python\Product\Ipc.Json\Connection.cs:line 144

   --- End of inner exception stack trace ---

---> (Inner Exception #0) System.ArgumentException: Stream was not readable.

   at System.IO.StreamReader..ctor(Stream stream, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean leaveOpen)

   at System.IO.StreamReader..ctor(Stream stream, Encoding encoding)

   at Microsoft.PythonTools.Ipc.Json.Connection.<ProcessMessages>d__16.MoveNext() in C:\Projects\GitHub\huguesv\ptvs\Python\Product\Ipc.Json\Connection.cs:line 144<---



   at Microsoft.PythonTools.PythonToolsPackage.<>c.<.ctor>b__3_0(Object sender, UnobservedTaskExceptionEventArgs e) in C:\Projects\GitHub\huguesv\ptvs\Python\Product\PythonTools\PythonToolsPackage.cs:line 200

   at System.Threading.Tasks.TaskScheduler.PublishUnobservedTaskException(Object sender, UnobservedTaskExceptionEventArgs ueea)

   at System.Threading.Tasks.TaskExceptionHolder.Finalize()


---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by huguesv** [comment]
In `private async Task<Response> Initialize(AP.InitializeRequest request)`, this call is terminating the analyzer process:
```
var interpreter = factory.CreateInterpreter();
```

My project is set to use IronPython 32-bit.

**Comment by huguesv** [comment]
This isn't strictly for IronPython projects.

"Analyzer initialization failed with no result" happens sometimes when loading a project during UI tests (like the ones in DebugProject test class), which results in test failure.

**Comment by zooba** [comment]
If it's terminating the analyzer process, we should have event log details. Do you see anything there? (If it doesn't kill the process, we should get a response with the error details.)

**Comment by huguesv** [comment]
I don't see anything in event viewer.

Is it normal to have 2 analyzer processes started with the same command line args:
![image](https://cloud.githubusercontent.com/assets/1696845/24016942/4df5d346-0a4b-11e7-8cc9-711696aeea3b.png)

At the point where I get the null back, one of the 2 is gone.

**Comment by huguesv** [comment]
I'm loading TestData/DjangoDebugProject.sln and the assert happens most of the time.

**Comment by zooba** [comment]
I'd guess those two processes are actually different, but the command line appears to be cut off - TestResults directories go much deeper, and there should always be a .pyproj at the end.
