### ISSUE TITLE
Assert on completions when REPL env is unknown

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2065]
Sometimes when I reopen my VS, and the REPL is recreated, it will say `Environment: <unknown>`.

If I type:
```
import <space>
```

I get this assert:

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Failed to get project entry for buffer Python:"import "



   at Microsoft.PythonTools.Intellisense.CompletionAnalysis.GetAnalysisEntry() in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\CompletionAnalysis.cs:line 112

   at Microsoft.PythonTools.Intellisense.CompletionAnalysis.GetModules(String[] package, Boolean modulesOnly) in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\CompletionAnalysis.cs:line 123

   at Microsoft.PythonTools.Intellisense.ImportCompletionAnalysis.GetCompletions(IGlyphService glyphService) in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\ImportCompletionAnalysis.cs:line 98

   at Microsoft.PythonTools.Intellisense.CompletionSource.AugmentCompletionSession(ICompletionSession session, IList`1 completionSets) in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\CompletionSource.cs:line 68

   at Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionSes......

<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------
```

![image](https://cloud.githubusercontent.com/assets/1696845/21906502/66993602-d8c0-11e6-8f6a-a368ff5bbd31.png)

**Comment by zooba** [comment]
Yeah, this sucks, but it should be "okay" to ignore the assertion. When this happens in release builds the assertion won't be shown and you'll just get no completions (or possibly code snippets, depending on which combination of bugs you have).

The bug that I'm most interested in here is that we shouldn't restore a REPL without knowing which environment is attached. Figuring out what made that happen would be useful

**Comment by zooba** [comment]
I think the "unknown REPL" issue has already been fixed, but now I'm fixing the assertion too (since it affects the debug repl)
