### ISSUE TITLE
devenv.exe ran out of memory after leaving VS idle with python project overnight

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2066]
devenv.exe ran out of memory.

I was running yesterday's latest sources in EXP, but not under debugger.

I had a project open, and a REPL initialized (but it wasn't executing anything).  Active Interpreter CPython 3.5 virtual environment, with numpy.

See picture in https://github.com/Microsoft/PTVS/issues/2065, that's approximately what my window looked like before it died (from what I saw of the taskbar thumbnail).

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
An unhandled exception is about to terminate the process:

Exception of type 'System.OutOfMemoryException' was thrown.

System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.

   at System.Threading.Thread.StartInternal(IPrincipal principal, StackCrawlMark& stackMark)

   at System.Threading.Thread.Start(StackCrawlMark& stackMark)

   at System.Threading.Thread.Start()

   at Microsoft.PythonTools.Analysis.Analyzer.AnalyzerStatusUpdaterImplementation..ctor(Action`1 callback, TimeSpan period) in C:\Projects\huguesv\PTVS\Python\Product\Analysis\Analyzer\AnalyzerStatusUpdater.cs:line 274

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at Microsoft.PythonTools.Analysis.Analyzer.AnalyzerStatusUpdaterImplementation.ThrowPendingExceptions() in C:\Projects\huguesv\PTVS\Python\Product\Analysis\Analyzer\AnalyzerStatusUpdater.cs:line 321

   at Microsoft.PythonTools.EnvironmentsList.ToolWindow.CreateListener() in C:\Projects\huguesv\PTVS\Python\Product\EnvironmentsList\ToolWindow.xaml.cs:line 190

   at System.Threading.Tasks.Task.InnerInvoke()

   at System.Threading.Tasks.Task.Execute()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()

   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext() in C:\Projects\huguesv\PTVS\Python\Product\VSCommon\Infrastructure\VSTaskExtensions.cs:line 182

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()

   at Microsoft.PythonTools.Infrastructure.TaskExtensions.<DoNotWait>d__0.MoveNext() in C:\Projects\huguesv\PTVS\Python\Product\Common\Infrastructure\TaskExtensions.cs:line 29

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)

   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()

   at System.Threading.ThreadPoolWorkQueue.Dispatch()

   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

   at Microsoft.VisualStudioTools.CommonPackage.<>c.<.ctor>b__8_0(Object sender, UnhandledExceptionEventArgs e) in C:\Projects\huguesv\PTVS\Common\Product\SharedProject\CommonPackage.cs:line 58

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)

   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()

   at System.Threading.ThreadPoolWorkQueue.Dispatch()

   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()


---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by huguesv** [comment]
Found one possible culprit. I left VS running (in debugger this time) last night, and ran out of memory again.

The main thread call stack is interesting:
```
 	WindowsBase.dll!System.Windows.Threading.DispatcherSynchronizationContext.Wait(System.IntPtr[] waitHandles, bool waitAll, int millisecondsTimeout)	Unknown
 	mscorlib.dll!System.Threading.SynchronizationContext.InvokeWaitMethodHelper(System.Threading.SynchronizationContext syncContext, System.IntPtr[] waitHandles, bool waitAll, int millisecondsTimeout)	Unknown
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	System.dll!System.Diagnostics.TraceInternal.Fail(string message)	Unknown
 	System.dll!System.Diagnostics.Debug.Fail(string message)	Unknown
 	Microsoft.PythonTools.dll!Microsoft.PythonTools.Intellisense.ExpansionCompletionSource.GetAvailableSnippets() Line 81	C#
 	Microsoft.PythonTools.dll!Microsoft.PythonTools.Intellisense.ExpansionCompletionSource.ExpansionCompletionSource(System.IServiceProvider serviceProvider) Line 36	C#
>	Microsoft.PythonTools.dll!Microsoft.PythonTools.PythonToolsService.OnIdleInitialization(object sender, Microsoft.VisualStudioTools.ComponentManagerEventArgs e) Line 107	C#
 	Microsoft.PythonTools.dll!Microsoft.VisualStudioTools.IdleManager.FDoIdle(uint grfidlef) Line 73	C#
```

Turns out, on IDLE, we keep creating new expansion completion source:
```
        internal PythonToolsService(IServiceContainer container) {
            _container = container;
            ...
            _idleManager.OnIdle += OnIdleInitialization;
        }

        private void OnIdleInitialization(object sender, ComponentManagerEventArgs e) {
            Site.AssertShellIsInitialized();

            _expansionCompletions = new ExpansionCompletionSource(Site);
            InitializeLogging();
        }

```

which calls into expansion mgr to enumerate all snippets.

It looks like the code assumed this was going to be a one time initialization, which isn't the case, it's called over and over on idle.

**Comment by zooba** [comment]
Hahaha, whoops :)
