### ISSUE TITLE
Unexpected Error Occur

### ISSUE THREAD

**Issue by dgsantana** [Microsoft/PTVS#2098]
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[V] Show details  [Close]

[Expanded Information]
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.PythonTools.Navigation.PythonFileChildren.GetChildren()
   at Microsoft.PythonTools.Navigation.ObjectBrowserChildren.EnsureChildren()
   at Microsoft.PythonTools.Navigation.ObjectBrowserChildren.GetEnumerator()
   at Microsoft.VisualStudioTools.Navigation.LibraryNode.Visit(ILibraryNodeVisitor visitor, CancellationToken ct)
   at Microsoft.VisualStudioTools.Navigation.LibraryNode.Visit(ILibraryNodeVisitor visitor, CancellationToken ct)
   at Microsoft.VisualStudioTools.Navigation.LibraryNode.Visit(ILibraryNodeVisitor visitor, CancellationToken ct)
   at Microsoft.VisualStudioTools.Navigation.Library.<>c__DisplayClass22_0.<VisitNodesAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudioTools.Navigation.Library.<VisitNodesAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Navigation.NavigateTo.PythonNavigateToItemProvider.<StartSearch>d__8.MoveNext()
```

**Comment by huguesv** [comment]
There are 2 places in PythonFileLibraryNode.cs where the result of `GetAnalysisEntry` is not checked for `null`.

Though I'm not sure if that code is active anymore.
