### ISSUE TITLE
Build error on VS 2017

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2137]
I'm on the today's build of VS 2017, I had these errors with a week old build, upgraded to today's but it made no difference.

Note I also have VS 2015 Update 3 on the same machine.

```
57>  Uwp -> C:\Projects\GitHub\huguesv\ptvs\BuildOutput\Debug15.0\raw\binaries\Microsoft.PythonTools.Uwp.dll
57>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\VSSDK\Microsoft.VsSDK.targets(966,5): error : CreatePkgDef : error : ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
57>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\VSSDK\Microsoft.VsSDK.targets(966,5): error :    at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
57>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\VSSDK\Microsoft.VsSDK.targets(966,5): error :    at System.Reflection.RuntimeModule.GetTypes()
57>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\VSSDK\Microsoft.VsSDK.targets(966,5): error :    at System.Reflection.Assembly.GetTypes()
57>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\VSSDK\Microsoft.VsSDK.targets(966,5): error :    at Microsoft.VisualStudio.Tools.CreatePkgDef.ProcessAssembly(String fileName, Hive hive, PkgDefContext context, Boolean register, RegistrationMode mode) in F:\dd\src\vssdk\VSIntegration\Tools\src\CreatePkgDef\CreatePkgDef.cs:line 261
57>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\VSSDK\Microsoft.VsSDK.targets(966,5): error :    at Microsoft.VisualStudio.Tools.CreatePkgDef.DoCreatePkgDef(InputArguments inputArguments) in F:\dd\src\vssdk\VSIntegration\Tools\src\CreatePkgDef\CreatePkgDef.cs:line 164
57>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\VSSDK\Microsoft.VsSDK.targets(966,5): error :    at Microsoft.VisualStudio.Tools.CreatePkgDef.Main(String[] arguments) in F:\dd\src\vssdk\VSIntegration\Tools\src\CreatePkgDef\CreatePkgDef.cs:line 85
57>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\VSSDK\Microsoft.VsSDK.targets(966,5): error : Could not load file or assembly 'Microsoft.VisualStudio.Debugger.Engine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)
57>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\VSSDK\Microsoft.VsSDK.targets(966,5): error : 
```

```
C:\Projects\GitHub\huguesv\PTVS\BuildOutput\Debug15.0\raw\binaries>sn -vf Microsoft.VisualStudio.Debugger.Engine.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Microsoft.VisualStudio.Debugger.Engine.dll is a delay-signed or test-signed assembly
```

**Comment by huguesv** [comment]
```
C:\Projects\GitHub\huguesv\PTVS\Python\References\Dev15.0>sn -vf Microsoft.VisualStudio.Debugger.Engine.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Microsoft.VisualStudio.Debugger.Engine.dll is a delay-signed or test-signed assembly

C:\Projects\GitHub\huguesv\PTVS\Python\References\Dev15.0>cd C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VSSDK\VisualStudioIntegration\Common\Assemblies\v4.0

C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VSSDK\VisualStudioIntegration\Common\Assemblies\v4.0>sn -vf Microsoft.VisualStudio.Debugger.Engine.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Assembly 'Microsoft.VisualStudio.Debugger.Engine.dll' is valid
Assembly 'Microsoft.VisualStudio.Debugger.Engine.dll' is verified with a key other than the identity key

C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VSSDK\VisualStudioIntegration\Common\Assemblies\v4.0>cd C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE

C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE>sn -vf Microsoft.VisualStudio.Debugger.Engine.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Assembly 'Microsoft.VisualStudio.Debugger.Engine.dll' is valid
Assembly 'Microsoft.VisualStudio.Debugger.Engine.dll' is verified with a key other than the identity key

C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE>
```

**Comment by zooba** [comment]
Did we accidentally copy this file from a test-signed build? Or is it unsigned in the VS build you're using?
