### ISSUE TITLE
Traceback of an "internal error detected"

### ISSUE THREAD

**Issue by MMeketon** [microsoft/PTVS#2176]
I was trying to change a test case in SKLEARN.  I setup a VS project, added class_weights.py and test_class_weights.py from my sklearn/utils directory.  Tried run it using the debugger, received the below including it's request to post the traceback.  So here it is...

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio\2.2\visualstudio_py_debugger.py", line 66, in <module>
    _vspr = visualstudio_py_repl
NameError: name 'visualstudio_py_repl' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio\2.2\visualstudio_py_debugger.py", line 69, in <module>
    import visualstudio_py_repl as _vspr
  File "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio\2.2\visualstudio_py_repl.py", line 39, in <module>
    import random
  File "c:\Anaconda3_64\Lib\site-packages\sklearn\utils\random.py", line 5, in <module>
    import numpy as np
  File "C:\Anaconda3_64\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import add_newdocs
  File "C:\Anaconda3_64\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "C:\Anaconda3_64\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "C:\Anaconda3_64\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "C:\Anaconda3_64\lib\site-packages\numpy\core\__init__.py", line 58, in <module>
    from numpy.testing.nosetester import _numpy_tester
  File "C:\Anaconda3_64\lib\site-packages\numpy\testing\__init__.py", line 12, in <module>
    from . import decorators as dec
  File "C:\Anaconda3_64\lib\site-packages\numpy\testing\decorators.py", line 21, in <module>
    from .utils import SkipTest
  File "C:\Anaconda3_64\lib\site-packages\numpy\testing\utils.py", line 15, in <module>
    from tempfile import mkdtemp, mkstemp
  File "C:\Anaconda3_64\lib\tempfile.py", line 45, in <module>
    from random import Random as _Random
ImportError: cannot import name 'Random'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio\2.2\ptvsd\visualstudio_py_debugger.py", line 66, in <module>
    _vspr = visualstudio_py_repl
NameError: name 'visualstudio_py_repl' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio\2.2\visualstudio_py_launcher.py", line 25, in <module>
    import visualstudio_py_debugger as vspd
  File "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio\2.2\visualstudio_py_debugger.py", line 71, in <module>
    import ptvsd.visualstudio_py_repl as _vspr
  File "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio\2.2\ptvsd\__init__.py", line 17, in <module>
    from ptvsd.attach_server import enable_attach, wait_for_attach, break_into_debugger, settrace, is_attached, AttachAlreadyEnabledError
  File "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio\2.2\ptvsd\attach_server.py", line 35, in <module>
    import ptvsd.visualstudio_py_debugger as vspd
  File "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio\2.2\ptvsd\visualstudio_py_debugger.py", line 69, in <module>
    import visualstudio_py_repl as _vspr
  File "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio\2.2\visualstudio_py_repl.py", line 39, in <module>
    import random
  File "c:\Anaconda3_64\Lib\site-packages\sklearn\utils\random.py", line 5, in <module>
    import numpy as np
  File "C:\Anaconda3_64\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import add_newdocs
  File "C:\Anaconda3_64\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "C:\Anaconda3_64\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "C:\Anaconda3_64\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
AttributeError: module 'numpy' has no attribute 'core'

**Internal error detected. Please copy the above traceback and report at
http://go.microsoft.com/fwlink/?LinkId=293415**

Press Enter to close. . .
```

**Comment by zooba** [comment]
Interesting.

The relevant part of the traceback is this:

```
  File "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio\2.2\visualstudio_py_debugger.py", line 69, in <module>
    import visualstudio_py_repl as _vspr
  File "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio\2.2\visualstudio_py_repl.py", line 39, in <module>
    import random
  File "c:\Anaconda3_64\Lib\site-packages\sklearn\utils\random.py", line 5, in <module>
    import numpy as np
```

When we go to `import tempfile`, it tries to import the standard `random` module but appears to be getting `sklearn.utils.random` instead. I assume this mean you have a search path set (or are running from the sklearn/utils directory, which would make sense if you're modifying it).

This is how Python naturally works and it does occasionally cause confusion, but I think we can protect our code against it when we are trying to import modules. Thanks for letting us know!
