### ISSUE TITLE
Can't build the Django solution for App Service

### ISSUE THREAD

**Issue by bearxu83** [Microsoft/PTVS#2181]
[Update: It seems that the error disappear after I update the python from 2.7.10 to 2.7.13.]

In VS 2015 community + PTVS 2.2.6, if I try to build the solution using the Django Web Project/Blank Django Web Project template, the build will fail so that I can not publish it to the App Service.

The description of the error is:
Severity	Code	Description	Project	File	Line	Suppression State
Error		The "RunPythonCommand" task failed unexpectedly.
System.ComponentModel.Win32Exception (0x80004005): The parameter is incorrect
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Microsoft.PythonTools.BuildTasks.RunPythonCommand.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	Solution	C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Python Tools\Microsoft.PythonTools.Django.targets	64

**Comment by zooba** [comment]
This typically indicates a misconfiguration, such as the path to python.exe being incorrect. Possibly your registry became corrupted (maybe by installing/uninstalling another distro of Python?) and installing the latest Python 2.7 fixed it.
