### ISSUE TITLE
Assert while editing

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2220]
Using latest source from master.

Start with a file with this exact content:
```
name = 'PythonTools_{0}_{1}_{2:%Y%m%d%H%M%S}.log'.format(' debugger', '123', datetime.datetime.now())
```

Put the cursor after the open parenthese, hit delete so the single quote of `' debugger'` is removed, then type a letter, `c` for example.

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Getting completions for non-Python buffer


   at Microsoft.PythonTools.Intellisense.StringLiteralCompletionList.GetCompletions(IGlyphService glyphService) in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\StringLiteralCompletionList.cs:line 191

   at Microsoft.PythonTools.Intellisense.CompletionSource.AugmentCompletionSession(ICompletionSession session, IList`1 completionSets) in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\CompletionSource.cs:line 65

   at Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionSession.Start()

   at Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionBroker.TriggerCompletion(ITextView textView)

   at Microsoft.PythonTools.Intellisense.IntellisenseController.TriggerCompletionSession(Boolean completeWord, Nullable`1 commitByDefault) in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\IntellisenseController.cs:line 840

   at Microsoft.PythonTools.I......

<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------

```

**Comment by huguesv** [comment]
No longer repros.
