### ISSUE TITLE
Assert after pasting code

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2221]
I pasted code and got this assert. Nothing bad happened if I continued.

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
583 + 371 <= 948 end was 948



   at Microsoft.PythonTools.OutliningTaggerProvider.OutliningTagger.GetTagSpan(ITextSnapshot snapshot, Int32 start, Int32 end, Int32 headerIndex) in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\OutliningTaggerProvider.cs:line 193

   at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.<ConvertOutliningTags>d__158.MoveNext() in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\ProjectAnalyzer.cs:line 2099

   at System.Linq.Enumerable.<ConcatIterator>d__58`1.MoveNext()

   at System.Linq.Enumerable.<ConcatIterator>d__58`1.MoveNext()

   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)

   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)

   at Microsoft.PythonTools.OutliningTaggerProvider.OutliningTagger.<>c__DisplayClass13_1.<OnNewParseTree>b__0() in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\OutliningTaggerProvider.cs:line 112

   at System.Threading.Tasks.Task`1.InnerInvoke()

   at System.Threading.Tasks.Task.Execute()

   at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)

   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)

   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()

   at System.Threading.ThreadPoolWorkQueue.Dispatch()

   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()


---------------------------
Abort   Retry   Ignore   
---------------------------
```

Here's a screenshot:

![image](https://cloud.githubusercontent.com/assets/1696845/23565949/a171e1fa-0004-11e7-864d-4f024595c67d.png)

And here's some of the locals at that assert:

![image](https://cloud.githubusercontent.com/assets/1696845/23565956/aea6126a-0004-11e7-94c2-dcc0dc80a439.png)

Here's the original code:
```
import random

guesses_made = 0
name = raw_input('Hello! What is your name?\n')
number = random.randint(1, 20)
print 'Well, {0}, I am thinking of a number between 1 and 20.'.format(name)

while guesses_made < 6:
    guess = int(raw_input('Take a guess: '))
    guesses_made += 1
    if guess < number:
        print 'Your guess is too low.'
    if guess > number:
        print 'Your guess is too high.'
    if guess == number:
        break
if guess == number:
    print 'Good job, {0}! You guessed my number in {1} guesses!'.format(name, guesses_made)
else:
    print 'Nope. The number I was thinking of was {0}'.format(number)


```

And the code that I pasted in:
```
        import datetime
        import os.path
        import tempfile

        process_id = 0
        name = 'PythonTools_{0}_{1}_{2:%Y%m%d%H%M%S}.log'.format('DebuggerServer', process_id, datetime.datetime.now())
        logfile = open(os.path.join(tempfile.gettempdir(), name), 'wt')
```

**Comment by huguesv** [comment]
You can also just create a new empty file and paste this in it, and you'll see the assertion.
```
import keras
from keras.datasets import cifar10
from keras.preprocessing.image import ImageDataGenerator
from keras.utils import np_utils
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Dense, Dropout, Activation, Flatten

batch_size = 32
num_classes = 10
epochs = 200
data_augmentation = True

def load_dataset():
    model = Sequential()

    if not data_augmentation:
        model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs,
                  validation_data=(x_test, y_test),
                  shuffle=True)
    else:
        datagen = ImageDataGenerator(
            featurewise_center=False,
            samplewise_center=False,
            featurewise_std_normalization=False,
            samplewise_std_normalization=False,
            zca_whitening=False,
            rotation_range=0,
            width_shift_range=0.1,
            height_shift_range=0.1,
            horizontal_flip=True,
            vertical_flip=False)
        datagen.fit_generator(datagen.flo


```

**Comment by huguesv** [comment]
Still happens. Note that since we have a blank line by default in our template, you'll need to completely empty the file first, save, close and reopen then paste the above code to see the assert.

**Comment by huguesv** [comment]
We're closing old issues with no recent activity. If this is still important, please open a new issue.
