### ISSUE TITLE
Error while editing

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#225]
VS 2013 Update 4
PTVS 2.2 Dev 2015-05-19

Activity log error:
```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
 at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
 at System.Collections.Generic.Dictionary`2.ValueCollection.Enumerator.MoveNext()
 at System.Linq.Enumerable.<SelectManyIterator>d__1`2.MoveNext()
 at Microsoft.PythonTools.Analysis.Analyzer.FunctionScope.<GetMergedVariables>d__12.MoveNext()
 at Microsoft.PythonTools.Analysis.Analyzer.InterpreterScope.GetMergedVariableTypes(String name)
 at Microsoft.PythonTools.Analysis.Analyzer.ExpressionEvaluator.LookupAnalysisSetByName(Node node, String name, Boolean addRef)
 at Microsoft.PythonTools.Analysis.Analyzer.ExpressionEvaluator.EvaluateName(ExpressionEvaluator ee, Node node)
 at Microsoft.PythonTools.Analysis.Analyzer.ExpressionEvaluator.EvaluateWorker(Node node)
 at Microsoft.PythonTools.Analysis.ModuleAnalysis.GetMembers(String exprText, SourceLocation location, GetMemberOptions options)
 at Microsoft.PythonTools.Intellisense.NormalCompletionAnalysis.GetCompletions(IGlyphService glyphService)
 at Microsoft.PythonTools.Intellisense.CompletionSource.AugmentCompletionSession(ICompletionSession session, IList`1 completionSets)
 at Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionSession.Start()
 at Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionBroker.TriggerCompletion(ITextView textView)
 at Microsoft.PythonTools.Intellisense.IntellisenseController.TriggerCompletionSession(Boolean completeWord)
 at Microsoft.PythonTools.Intellisense.IntellisenseController.HandleChar(Char ch)
 at Microsoft.PythonTools.Intellisense.IntellisenseController.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
 at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
 at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
 at MadsKristensen.EditorExtensions.CommandTargetBase`1.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
 at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
 at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
 at MadsKristensen.EditorExtensions.CommandTargetBase`1.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
 at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
 at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
 at MadsKristensen.EditorExtensions.CommandTargetBase`1.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
 at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
 at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
 at MadsKristensen.EditorExtensions.CommandTargetBase`1.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
 at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
 at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
 at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.SendCommand(Guid cmdGroup, UInt32 cmdID, Object inParam)
 at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.TextInput(TextCompositionEventArgs args)
 at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<DispatchTextInputEvents>b__0(KeyProcessor p, TextCompositionEventArgs args)
 at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c__DisplayClass1e`1.<Dispatch>b__1a()
 at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)
```

Happened when I typed the '.' on line 165.

![editing-crash2](https://cloud.githubusercontent.com/assets/1696845/7735763/1d6f0f30-fef4-11e4-9c3e-64081bdeaa1e.png)

**Comment by zooba** [comment]
It's a cross-thread race condition. We need to add a lot of locking throughout the analyzer to deal with these...
