### ISSUE TITLE
Go to definition or Find references not working

### ISSUE THREAD

**Issue by andyp05** [microsoft/PTVS#2271]
Using latest preview Release Date: March 7, 2017 (build 26304.00).

Hitting F12 will work to find definition of functions in imported or inherited modules, but won't find variable definitions. If in same module, it works fine. Get a 'Cannot go to definition' error.

The same issue for Ctrl-K,R Find all references.

**Comment by zooba** [comment]
So I can F12 to a variable definition in another module just fine, though trying to rename it crashed VS (trace below). FAR also found all the references I expected, though some of the lines showed as blank in the results window.

I was working in our Flask web project template. Perhaps there's something about your project layout that's causing us trouble? Can you share your folder/file structure and show the ones where variables should be resolved properly?


```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentOutOfRangeException
   at System.Globalization.CompareInfo.Compare(System.String, Int32, Int32, System.String, Int32, Int32, System.Globalization.CompareOptions)
   at System.String.Compare(System.String, Int32, System.String, Int32, Int32)
   at Microsoft.PythonTools.Refactoring.LocationPreviewItem..ctor(Microsoft.PythonTools.Intellisense.VsProjectAnalyzer, Microsoft.PythonTools.Refactoring.FilePreviewItem, Microsoft.PythonTools.Intellisense.AnalysisLocation, Microsoft.PythonTools.Analysis.VariableType)
   at Microsoft.PythonTools.Refactoring.PreviewChangesEngine.CreatePreviewItems()
   at Microsoft.PythonTools.Refactoring.PreviewChangesEngine..ctor(System.IServiceProvider, Microsoft.PythonTools.Refactoring.IRenameVariableInput, System.String, Microsoft.PythonTools.Refactoring.RenameVariableRequest, System.String, System.String, Microsoft.PythonTools.Intellisense.VsProjectAnalyzer, System.Collections.Generic.IEnumerable`1<Microsoft.PythonTools.Intellisense.AnalysisVariable>)
   at Microsoft.PythonTools.Refactoring.VariableRenamer+<RenameVariable>d__4.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.PythonTools.Infrastructure.TaskExtensions+<DoNotWait>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

**Comment by andyp05** [comment]
Interesting...It seems to work once if I click F12 on self.var1 in module1.py, if I click on self.func it seems to always work. If I go back and click on self.var1 again it says 'Cannot go to definition.'  I have two very small test files.

**PythonApplication1.py**

```
class Parent(object):
    def __init__(self):
        self.var1  = 'test'
        self.var2  = 'data'

    def func1(self, s):
        print(s)
```

**module1.py**

```
from PythonApplication1 import Parent

class Child(Parent):

    def __init__(self):
        super().__init__()

    def test(self):
        self.func1(self.var1);

if __name__ == '__main__':
    c = Child()
    c.test()
```

**Comment by andyp05** [comment]
Forgot to attach image...

![image](https://cloud.githubusercontent.com/assets/14006401/23915566/e195594c-08bf-11e7-9e19-232d9094943e.png)

**Comment by zooba** [comment]
Ah, I see. Attribute definition is a different code path in our analyzer (also different from method definitions), so it doesn't necessarily have to match top-level variable definition behavior. We'll take a look.

**Comment by zooba** [comment]
Clearing the milestone - the crash was urgent to fix, but the problem of attributes not associating properly between classes and subclasses can be deferred while we focus on higher priorities.

The cause of this issue is that `ClassScope.AssignVariable` does not check whether the variable has already been assigned in a superclass, so we end up with multiple distinct variables for the name instead of sharing it.

**Comment by lcorrigan** [comment]
I often use the F12/GoToDefinition, to jump to function definitions - this works in VS2015 but has never worked for me in VS2012.  Tried VS2017 vs VS2015 on 2 Different machines, running the same project from SVN.  I don't get an error message in VS2017 for this, it just doesn't do anything.

**Comment by zooba** [comment]
@lcorrigan You may be hitting a different issue where if you've selected the whole word (and the cursor is right at the end) then we don't recognize it. This has been fixed for our next release. Putting the cursor in the middle of the name should let you go to definition.

If you're selecting in the middle of the name and it's still not working, and the name is _not_ an inherited attribute, you've got a different problem from this one, so please create a new issue.

**Comment by lcorrigan** [comment]
@zooba I see what you mean about the cursor vs the whole word - but only when I'm lucky to get that far.  I'm seeing a mixed bag of intellisense problems/responsiveness even after a re-install and cleaning / renewing the completion database.  I see many tickets for intellisense so I won't muddy the water here. Thanks.

**Comment by syagev** [comment]
I'm completely unable to Go To Definition or Find All References with VS 15.5.2 and PTVS v3.0.17320.1
Not variables, top-level methods, or class instance properties and methods.

Also, the drop-down list boxes at the top of the editor which used to contain the list of methods for quick navigation are also gone.

I get no error message or message box, simply nothing happens.

This used to work for me but I'm not sure if in the previous update or the one before it.

**Comment by lcorrigan** [comment]
I was able to get things working again the usual 'uninstall everything you can and start over' method
* I uninstalled Visual Studio (2015 and 2017 in my case). I recommend using Revo Uninstaller, to remove the remnants that VS doesn't remove.
* Did the same to remove my IronPython and my always troublesome Anaconda.
* Delete all folders it installs or saves anything in, including the PTVS plugin folder on in %APPDATA%
* I ran Glary Utiltities, which found another slew of things that were not cleaned up even by Revo.
From there I did this:
* Reboot and run VS2017 installer with Python support + .NET support an no other python-related anything.
* Installed IronPython 
* Installed Miniconda (less bloat than full Anaconda) as a separate package.
* Installed my few favorites for CPython like Matplotlib, pandas, numpy, pythonnet etc. 
== Intellisense back to normal / go-to-whatever is working again. Even pandas lookup is fast again.

I think my 2 years of installing/uninstalling different VS's, PTVS's, Anaconda's created for a typically windows registry soup that makes the python intellisense database creator go haywire. My CPU had been running like mad every time I opened VS.  
I also wonder if having CPython in the same large project as IronPython had anything to do with it.  Seems like things also degraded fast over time dating back to when I made that decision.
