### ISSUE TITLE
While adding an existing virtual environment to new project with existing code, following error message comes up.

### ISSUE THREAD

**Issue by paplet** [Microsoft/PTVS#2274]
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
System.ArgumentException: Parameter "include" cannot have zero length.
   at Microsoft.Build.Shared.ErrorUtilities.VerifyThrowArgumentLength(String parameter, String parameterName)
   at Microsoft.Build.Construction.ProjectRootElement.AddItem(String itemType, String include, IEnumerable`1 metadata)
   at Microsoft.Build.Evaluation.Project.AddItem(String itemType, String unevaluatedInclude, IEnumerable`1 metadata)
   at Microsoft.PythonTools.Project.PythonProjectNode.AddInterpreterReference(InterpreterConfiguration config)
   at Microsoft.PythonTools.Project.PythonProjectNode.<CreateOrAddVirtualEnvironment>d__181.MoveNext()
```

**Comment by huguesv** [comment]
`ImportWizardTests.ImportWizardVirtualEnv` fails with this same error.
