### ISSUE TITLE
Unhandled exception in InstallRequirementsWizard

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2290]
Created a Django Web Project, got this assertion.

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Unhandled exception in Microsoft.PythonTools.ProjectWizards.InstallRequirementsWizard.ProjectFinishedGenerating (C:\Projects\huguesv\PTVS\Python\Product\ProjectWizards\InstallRequirementsWizard.cs:60)

System.InvalidOperationException: Operation is not valid due to the current state of the object.

   at Microsoft.VisualStudio.TestWindow.Controller.OperationData.Microsoft.VisualStudio.TestWindow.Controller.IOperationData.OperationSetFinished(Operation operation)

   at Microsoft.VisualStudio.TestWindow.Controller.Operation.<ExecuteWithEvents>d__38.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.VisualStudio.TestWindow.Controller.Operation.<Execute>d__39.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.Compile......

<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------

```

**Comment by huguesv** [comment]
Things went bad after ignoring the assert and closing the unhandled exception dialog.  I can't active VS window anymore, there was a blank window I managed to close with taskbar, but I still can't active VS (keeps beeping).

**Comment by huguesv** [comment]
Haven't seen this again.
