### ISSUE TITLE
Editing django project settings causes analysis assert

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2295]
Open project settings
In debug tab, change the launch url or port number.
Close the project settings document.

Result:
```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------




   at Microsoft.PythonTools.Intellisense.ProjectEntryMap.Add(String filename, IProjectEntry node) in C:\Projects\huguesv\PTVS\Python\Product\Analyzer\Intellisense\ProjectEntryMap.cs:line 37

   at Microsoft.PythonTools.Intellisense.OutOfProcProjectAnalyzer.AddNewFile(String path, String addingFromDirectory, Int32& fileId) in C:\Projects\huguesv\PTVS\Python\Product\Analyzer\Intellisense\OutOfProcProjectAnalyzer.cs:line 1875

   at Microsoft.PythonTools.Intellisense.OutOfProcProjectAnalyzer.<AnalyzeFileAsync>d__72.MoveNext() in C:\Projects\huguesv\PTVS\Python\Product\Analyzer\Intellisense\OutOfProcProjectAnalyzer.cs:line 1536

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.PythonTools.Intellisense.OutOfProcProjectAnalyzer.AnalyzeFileAsync(AddFileRequest request, Func`2 done)

   at Microsoft.PythonTools.Intellisense.OutOfProcProjectAnalyzer.<RequestHandler>d__22.MoveNext() in C:\Projects\huguesv\PTVS\Python\Product\Analyzer\......

<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------
```

I'm trying to repro again so I can write down what filename is.  I remember from yesterday it was something like: <full path to the pyproj>;<guid>

**Comment by huguesv** [comment]
Can't repro again.
