### ISSUE TITLE
An unexpected error occurred

### ISSUE THREAD

**Issue by awf** [Microsoft/PTVS#2318]
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
System.Runtime.InteropServices.COMException (0x8000FFFF): Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.ErrorHandler.ThrowOnFailure(Int32 hr, Int32[] expectedHRFailure)
   at Microsoft.VisualStudioTools.Project.ProjectReferenceNode.get_ReferencedProjectBuildOutputs()
   at Microsoft.PythonTools.Project.PythonProjectReferenceNode.get_ReferencedProjectOutputPath()
   at Microsoft.PythonTools.Project.PythonProjectReferenceNode.Initialize()
```

**Comment by zooba** [comment]
Did you encounter this on Visual Studio 2015? If so, this is a known issue that can be ignored, but won't be fixed.

It has already been fixed for VS 2017.
