### ISSUE TITLE
opening project on vs2017 preview causes unexpected error related to GetTestCases

### ISSUE THREAD

**Issue by kdriedger-simutech** [Microsoft/PTVS#2344]
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.PythonTools.TestAdapter.TestAnalyzer.GetTestCases(String data)
   at Microsoft.PythonTools.TestAdapter.TestContainerDiscoverer.ProjectInfo.<UpdateTestCasesAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__3`1.MoveNext()
```

**Comment by zooba** [comment]
Thanks.

Are you seeing this on VS 2015? Or VS 2017? I'm having trouble finding a place in our code for VS 2017 where this could occur, so it'll help to know if I'm reading the wrong source.

**Comment by kdriedger-simutech** [comment]
Weirdness then, it is indeed vs2017 preview (as I indicated in the title of this issue).    

Surely, it's not finding my vs2015 install and using the code from there?

**Comment by zooba** [comment]
Ah, so you did :)

Possibly there was some optimization in our build then and the stack trace is missing function calls. I'll try a couple things, but we'll probably just end up being more protective of this section of code.

**Comment by huguesv** [comment]
Fixed by https://github.com/Microsoft/PTVS/pull/2489
