### ISSUE TITLE
Hash code changed when merging AnalysisValues

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2355]
I had a Python project open.
I loaded a different project.
This assert came up.

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Hash code changed when merging AnalysisValues



   at Microsoft.PythonTools.Analysis.AnalysisSetDetails.AnalysisHashSet.AddOne(Bucket[] buckets, AnalysisValue key, Int32 hc) in C:\Projects\huguesv\PTVS\Python\Product\Analysis\AnalysisHashSet.cs:line 366

   at Microsoft.PythonTools.Analysis.AnalysisSetDetails.AnalysisHashSet.EnsureSize(Int32 newSize) in C:\Projects\huguesv\PTVS\Python\Product\Analysis\AnalysisHashSet.cs:line 300

   at Microsoft.PythonTools.Analysis.AnalysisSetDetails.AnalysisHashSet.CheckGrow() in C:\Projects\huguesv\PTVS\Python\Product\Analysis\AnalysisHashSet.cs:line 268

   at Microsoft.PythonTools.Analysis.AnalysisSetDetails.AnalysisHashSet.AddOne(AnalysisValue key) in C:\Projects\huguesv\PTVS\Python\Product\Analysis\AnalysisHashSet.cs:line 258

   at Microsoft.PythonTools.Analysis.AnalysisSetDetails.AnalysisHashSet.Add(AnalysisValue item, Boolean& wasChanged, Boolean canMutate) in C:\Projects\huguesv\PTVS\Python\Product\Analysis\AnalysisHashSet.cs:line 133

   at Microsoft.PythonToo......

<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by zooba** [comment]
Unless you can repro it reliably with a certain code file(s), there's not much we can do from this information. The assertion is intended to allow debugging at that point, and it isn't helpful later on.
