### ISSUE TITLE
ArgumentOutOfRangeException in REPL

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#237]
VS 2015 RC
PTVS Dev 2015-05-19

I was scrolling up in the REPL (Python 2.7) to check the results of prior execution when I got the activity log error msg box.

```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index
at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
at Microsoft.PythonTools.Repl.ReplOutputClassifier.GetClassificationSpans(SnapshotSpan span)
at Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierTagger.<GetTags>d__1.MoveNext()
at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<GetTagsForBuffer>d__1.MoveNext()
```

I was able to repro a second time.  Here's the code I used:
```
Python interactive window. Type $help for a list of commands.
>>> import requests
>>> s = requests.Session()
>>> client_id = '04b07795-8ddb-461a-bbee-02f9e1bf7b46'# the client id we can borrow from azure xplat cli
... 
>>> grant_type = 'password'
... 
>>> username = 'hugues@ptvsaaaaaoutlook.onmicrosoft.com'
>>> password = 'censoredpassword'
>>> resource = 'https://management.core.windows.net/'
>>> url = 'https://login.windows.net/common/oauth2/token'
... 
>>> payload = {
...     'grant_type': grant_type,
...     'client_id': client_id,
...     'username': username,
...     'password': password,
...     'resource' : resource
...     };
... 
>>> r = requests.post(url, data=payload)
>>> r.text

```

After you execute the last command `r.text`, scroll up with the mouse wheel.

**Comment by zooba** [comment]
Dup of #228, the code doesn't make a difference to the repro here.
