### ISSUE TITLE
OutOfMemoryException when rebuilding Intellisense DB for large packages

### ISSUE THREAD

**Issue by Dresel** [Microsoft/PTVS#24]
When rebuilding the Intellisense DB I get an OutOfMemoryException:

    2015-04-23T12:43:12: Starting analysis of 270 modules
    2015-04-23T12:46:51: [ERROR] Analysis failed
    System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
        at System.Collections.Generic.HashSet`1.Initialize(Int32 capacity)
        at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value)
        at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
        at Microsoft.PythonTools.Analysis.VariableDef.EstimateTypeCount(IAnalysisSet extraTypes)
        at Microsoft.PythonTools.Analysis.Values.IterableInfo.AddTypes(AnalysisUnit unit, IAnalysisSet[] types)
        at Microsoft.PythonTools.Analysis.Analyzer.ExpressionEvaluator.MakeSequence(ExpressionEvaluator ee, Node node)
        at Microsoft.PythonTools.Analysis.Analyzer.ExpressionEvaluator.EvaluateSequence(ExpressionEvaluator ee, Node node)
        at Microsoft.PythonTools.Analysis.Analyzer.ExpressionEvaluator.EvaluateWorker(Node node)
        at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(AssignmentStatement node)
        at Microsoft.PythonTools.Parsing.Ast.AssignmentStatement.Walk(PythonWalker walker)
        at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(SuiteStatement node)
        at Microsoft.PythonTools.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker)
        at Microsoft.PythonTools.Analysis.Analyzer.FunctionAnalysisUnit.AnalyzeWorker(DDG ddg, CancellationToken cancel)
        at Microsoft.PythonTools.Analysis.Analyzer.DDG.Analyze(Deque`1 queue, CancellationToken cancel, Action`1 reportQueueSize, Int32 reportQueueInterval)
        at Microsoft.PythonTools.Analysis.PythonAnalyzer.AnalyzeQueuedEntries(CancellationToken cancel)
        at Microsoft.PythonTools.Analysis.PyLibAnalyzer.Analyze()
        at Microsoft.PythonTools.Analysis.PyLibAnalyzer.<Run>d__30.MoveNext()

My development machine has a total of 16 GB memory and there is still ~50% left when the process crashes with a  usage of about ~1.7 GB.

Is there anything I can do so that PythonTools uses more memory?

**Comment by zooba** [comment]
It's a 32-bit process, so that limit is basically fixed. We shouldn't ever be getting up to that amount of memory usage though, so having a lower limit just means we'll see these issues sooner.

In the lines above what you've quoted from the log it should show which package is being analyzed. Can you give us the exact version of that package and the version of PTVS you are using? There's probably something about their code structure that we are not handling correctly.

**Comment by Dresel** [comment]
I tried it with PTVS 2.1 and 2.2 Beta.

I'm using the package [pyxb](https://github.com/pabigot/pyxb) 1.2.4 with the optional OpenGis [bundle](http://pyxb.sourceforge.net/bundles.html), which is quite heavy:

> This bundle is not populated in the distributed versions of PyXB because it requires some 168MB of space to hold the schemas, generated bindings, and archive files.

Without this bundle the analysis "only" takes up 700-800 MB of memory. I don't know if this is enough to locate the problem.

I generated the OpenGis bundle via

    maintainer/genbundles @ opengis

as advised [here](https://github.com/pabigot/pyxb/issues/28#issuecomment-74427824).

Please let me know if you need further information.

**Comment by zooba** [comment]
Hmm, we may just legitimately be running out of memory here - that's a lot of code.

Fixing this is too big a change for our current release, unfortunately, since we won't have enough time to determine all the unintended effects.

It shouldn't be too hard to rebuild just the Analysis and Analyzer projects from our source in 64-bit mode and gain access to more memory that way (happy to help you with that if it has potential), but what we really need to do is simplify some parts of our analyzer to keep good results without needing so much memory.

**Comment by Dresel** [comment]
Well if you could provide a 64-bit version that would be really great.

**Comment by zooba** [comment]
Not anytime soon I'm afraid - fairly swamped with the upcoming release and the related marketing/conference circuit etc. Someone else on the team may be able to do it, but it won't be part of the actual release - it'll be a few files you'll need to drop in manually.

**Comment by Dresel** [comment]
I created a 64x build myself - had to disable signing though - and replaced the files within the python tools folder.

After that the rebuilding ran through with a peak of 3.7 GB memory usage.

**Comment by Dresel** [comment]
Can the generated database be reused or do I have to rebuild it on all development machines?

**Comment by zooba** [comment]
Thanks for the info.

You won't have to rebuild the database for each machine, though there are a few things to be aware of when moving them.

1. We do last-modified-time comparisons with the installed library, so if the DB looks older than the source file we will regenerate it
2. We validate the filenames embedded in the DB, and if they don't exist we will regenerate it. You can strip filenames with [strip_idb_filenames.py](https://github.com/Microsoft/PTVS/blob/master/Python/Tests/strip_idb_filenames.py) before moving it (which will break Go To Definition), or ensure that packages are installed to the same location on each machine.
3. Custom environments won't necessarily have the same GUID on every machine. I think you're using a regular CPython though, so this won't be an issue.

We do have some vague ideas about enabling this more generally, but for now it's possible with only a few potential problems.

**Comment by zooba** [comment]
Closing this because it's a known general issue (with multiple open bugs) and keeping this one open is not any more helpful.
