### ISSUE TITLE
Opening the Python Environments tab from Tools\Python\Python Environments causes VS2017 to crash & restart.

### ISSUE THREAD

**Issue by JeffHanna** [Microsoft/PTVS#2447]
Every time I open the Python Environments tab it opens, changes my cursor to a wait cursor, and then crashes VS 2017. I've uninstalled/reinstalled Python 3.6, the Python workflow in VS 2017 Community Preview, and VS 2017 Preview entirely. Nothing fixes this issue. 

[PTVS_Diagnostics_utf8.txt](https://github.com/Microsoft/PTVS/files/958835/PTVS_Diagnostics_utf8.txt)

**Comment by zooba** [comment]
For convenience, I've copied the exception below. 

Typically this would occur because of an odd or unsupported path format, though I don't see anything in the log that would be the cause of that.

```
Description: The process was terminated due to an unhandled exception.
Exception Info: System.UriFormatException
   at System.Uri.CreateThis(System.String, Boolean, System.UriKind)
   at System.Uri..ctor(System.String, System.UriKind)
   at Microsoft.PythonTools.Infrastructure.PathUtils.MakeUri(System.String, Boolean, System.UriKind, System.String)

Exception Info: System.ArgumentException
   at Microsoft.PythonTools.Infrastructure.PathUtils.MakeUri(System.String, Boolean, System.UriKind, System.String)
   at Microsoft.PythonTools.Infrastructure.PathUtils.GetAbsoluteDirectoryPath(System.String, System.String)
   at Microsoft.PythonTools.Repl.PythonInteractiveEvaluator.GetScriptsPath(System.IServiceProvider, System.String, Microsoft.PythonTools.Interpreter.InterpreterConfiguration, Boolean)
   at Microsoft.PythonTools.InterpreterList.InterpreterListToolWindow.GetScriptPath(Microsoft.PythonTools.EnvironmentsList.EnvironmentView)
   at Microsoft.PythonTools.InterpreterList.InterpreterListToolWindow.OpenInteractiveScripts_CanExecute(System.Object, System.Windows.Input.CanExecuteRoutedEventArgs)
   at System.Windows.Input.CommandBinding.OnCanExecute(System.Object, System.Windows.Input.CanExecuteRoutedEventArgs)
   at System.Windows.Input.CommandManager.FindCommandBinding(System.Windows.Input.CommandBindingCollection, System.Object, System.Windows.RoutedEventArgs, System.Windows.Input.ICommand, Boolean)
   at System.Windows.Input.CommandManager.FindCommandBinding(System.Object, System.Windows.RoutedEventArgs, System.Windows.Input.ICommand, Boolean)
   at System.Windows.Input.CommandManager.OnCanExecute(System.Object, System.Windows.Input.CanExecuteRoutedEventArgs)
   at System.Windows.UIElement.OnCanExecuteThunk(System.Object, System.Windows.Input.CanExecuteRoutedEventArgs)
   at System.Windows.Input.CanExecuteRoutedEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.Input.RoutedCommand.CriticalCanExecuteWrapper(System.Object, System.Windows.IInputElement, Boolean, System.Windows.Input.CanExecuteRoutedEventArgs)
   at System.Windows.Input.RoutedCommand.CanExecuteImpl(System.Object, System.Windows.IInputElement, Boolean, Boolean ByRef)
   at System.Windows.Input.RoutedCommand.CriticalCanExecute(System.Object, System.Windows.IInputElement, Boolean, Boolean ByRef)
   at MS.Internal.Commands.CommandHelpers.CanExecuteCommandSource(System.Windows.Input.ICommandSource)
   at System.Windows.Controls.Primitives.ButtonBase.UpdateCanExecute()
   at System.Windows.Controls.Primitives.ButtonBase.OnCanExecuteChanged(System.Object, System.EventArgs)
   at System.Windows.Input.CanExecuteChangedEventManager+HandlerSink.OnCanExecuteChanged(System.Object, System.EventArgs)
   at System.Windows.WeakEventManager+ListenerList.DeliverEvent(Listener ByRef, System.Object, System.EventArgs, System.Type)
   at System.Windows.WeakEventManager+ListenerList.DeliverEvent(System.Object, System.EventArgs, System.Type)
   at System.Windows.WeakEventManager.DeliverEvent(System.Object, System.EventArgs)
   at System.Windows.Input.CommandManager+RequerySuggestedEventManager.OnRequerySuggested(System.Object, System.EventArgs)
   at System.Windows.Input.CommandManager.RaiseRequerySuggested(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

**Comment by zooba** [comment]
@JeffHanna I don't suppose you've done something unusual with your Documents folder? Like relocated it to another drive or a networked file share? I think the code that is failing here is starting from your Documents folder and trying to look for the "Visual Studio 2017" folder that gets created in there.

(FWIW, I think we're locating this directory incorrectly, but that doesn't explain the crash...)

**Comment by JeffHanna** [comment]
@zooba that was it! On my Surface Pro 3 I had redirected Documents to a OneDrive folder I had on a MicroSD card. I didn't realize that card wasn't being recognized (it's flaky on SP3s). Redirecting Documents back to c:\users\<user>\documents and resetting settings in Visual Studio did the trick. Thank you.

**Comment by zooba** [comment]
Do you know what the path to that looked like? The error we were getting makes it look like an invalid path - we weren't trying to access it, so even if it didn't exist it should still have worked.

**Comment by JeffHanna** [comment]
@zooba The path was d:\OneDrive, with D: being an SD card that wasn't inserted.

**Comment by zooba** [comment]
Thanks. I can't see a reason for that to be throwing, but we've added handling for any error like this, so it shouldn't bring down all of VS any more.
