### ISSUE TITLE
Unexpected error after adding unit test

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2456]
Microsoft Visual Studio Enterprise 2017 Int Preview
Version 15.2 (26424.2-Preview) d15rel Internal Preview - Dogfood
VisualStudio.15.IntPreview/15.2.0-Preview+26424.2.d15rel

I created a new python application
I opened test explorer
I added a new unit test
The test appeared in test explorer, then I got the unexpected message box.

[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 3.0.17114.1

System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Microsoft.PythonTools.TestAdapter.TestContainerDiscoverer.ProjectInfo.<UpdateTestCasesAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__3`1.MoveNext()
```

**Comment by huguesv** [comment]
If it doesn't repro, close test explorer, close VS and then follow the instructions in that exact order.

**Comment by zooba** [comment]
We need to lock that dictionary access - guessing it's being hit from a background thread.
