### ISSUE TITLE
InvalidOperationException IronPython+pip on VS 2017

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2495]
I tried both IronPython 2.7.5 and 2.7.7, same behavior.
Type in the name of a package to install and hit enter, you'll get:

[Window Title]
Visual Studio - Python support

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 3.0.1000.00

System.InvalidOperationException: Operation cannot be started because the environment is not configured.
   at Microsoft.PythonTools.Interpreter.PipPackageManager.<AbortIfNotReady>d__24.MoveNext() in C:\Projects\huguesv\PTVS\Python\Product\VSInterpreters\PipPackageManager.cs:line 133
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.PythonTools.Interpreter.PipPackageManager.<InstallAsync>d__35.MoveNext() in C:\Projects\huguesv\PTVS\Python\Product\VSInterpreters\PipPackageManager.cs:line 277
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.PythonTools.EnvironmentsList.PipExtensionProvider.<InstallPackage>d__38.MoveNext() in C:\Projects\huguesv\PTVS\Python\Product\EnvironmentsList\PipExtensionProvider.cs:line 171
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.PythonTools.EnvironmentsList.PipExtension.<InstallPackage_Executed>d__14.MoveNext() in C:\Projects\huguesv\PTVS\Python\Product\EnvironmentsList\PipExtension.xaml.cs:line 132
```

**Comment by zooba** [comment]
Is pip installed in any of these?

I'm seeing the main problems being:
* pip is not installed and the "Install pip" button does not appear
* package install can be triggered even though we know pip is not installed

**Comment by zooba** [comment]
I can fix the "Install pip" button not appearing easily enough, but it seems like IronPython can't install setuptools right now - https://github.com/IronLanguages/main/issues/1570

**Comment by huguesv** [comment]
Pip wasn't installed, they were fresh installs of IronPython.

**Comment by huguesv** [comment]
FYI Same bug on Python 2.6, where pip isn't installed.
