### ISSUE TITLE
Crash when staring VS 2017 community preview

### ISSUE THREAD

**Issue by trisst** [Microsoft/PTVS#2499]
A message about Google test adapter being upgraded flashed on screen briefly, then:

[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 3.0.17114.1

System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Microsoft.PythonTools.TestAdapter.TestContainerDiscoverer.ProjectInfo.<UpdateTestCasesAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__3`1.MoveNext()
```

**Comment by huguesv** [comment]
Thanks! We've fixed this already for an upcoming release.
https://github.com/Microsoft/PTVS/pull/2489
