### ISSUE TITLE
Failed on opening .pyproj

### ISSUE THREAD

**Issue by Baldstrom** [Microsoft/PTVS#2535]
Attempted to open python project in VS2017 Preview and an error occurred. After the error, I can no longer open any project or try to close VS without seeing this:
```
Expected 1 export(s) with contract name "Microsoft.Internal.VisualStudio.PlatformUI.SolutionAttachedCollectionService" but found 0 after applying applicable constraints.
```
This is the initial Error: 
(FYI System restart did not fix the issue, but opening up the Experimental Instance of VS2017 Preview did work)
```
Build: 3.0.17114.1

System.AggregateException: One or more errors occurred. ---> Microsoft.VisualStudio.Composition.CompositionFailedException: Expected 1 export(s) with contract name "Microsoft.Internal.VisualStudio.PlatformUI.ISolutionAttachedCollectionService" but found 0 after applying applicable constraints.
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports(ImportDefinition importDefinition)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports[T,TMetadataView](String contractName, ImportCardinality cardinality)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T,TMetadataView](String contractName)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T](String contractName)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T]()
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExportedValue[T]()
   at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetService[T]()
   at Microsoft.Internal.VisualStudio.PlatformUI.PivotNavigatorServices.get_AttachedCollectionService()
   at Microsoft.VisualStudio.PlatformUI.SolutionNavigatorPane.RefillNavigator()
   at Microsoft.VisualStudio.PlatformUI.SolutionNavigatorPane.OnAfterInvalidateItems(Object sender, HierarchyItemEventArgs eventArgs)
   at Microsoft.VisualStudio.PlatformUI.ExtensionMethods.RaiseEvent[TEventArgs](EventHandler`1 eventHandler, Object source, TEventArgs args)
   at Microsoft.VisualStudio.PlatformUI.HierarchyEventSink.OnInvalidateItems(UInt32 itemidParent)
   at Microsoft.VisualStudio.PlatformUI.HierarchyEventSink.<>c__DisplayClass31_0.<Microsoft.VisualStudio.Shell.Interop.IVsHierarchyEvents.OnInvalidateItems>b__0()
   at Microsoft.VisualStudio.Shell.ThreadHelper.Invoke[TResult](Func`1 method)
   at Microsoft.VisualStudio.PlatformUI.HierarchyEventSink.Microsoft.VisualStudio.Shell.Interop.IVsHierarchyEvents.OnInvalidateItems(UInt32 itemidParent)
   at Microsoft.VisualStudioTools.Project.ProjectNode.OnInvalidateItems(HierarchyNode parent)
   at Microsoft.PythonTools.Project.InterpretersNode.<>c__DisplayClass24_0.<RefreshPackagesAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Project.InterpretersNode.<RefreshPackagesAsync>d__24.MoveNext()
   --- End of inner exception stack trace ---
   at System.AggregateException.Handle(Func`2 predicate)
   at Microsoft.PythonTools.Infrastructure.TaskExtensions.<>c__6`1.<SilenceException>b__6_0(Task t)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
---> (Inner Exception #0) Microsoft.VisualStudio.Composition.CompositionFailedException: Expected 1 export(s) with contract name "Microsoft.Internal.VisualStudio.PlatformUI.ISolutionAttachedCollectionService" but found 0 after applying applicable constraints.
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports(ImportDefinition importDefinition)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports[T,TMetadataView](String contractName, ImportCardinality cardinality)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T

**Comment by huguesv** [comment]
You should try deleting the MEF cache.  Close all instances of VS, and delete this folder. VS will recreate the cache on startup.  Note that there's a separate cache for Exp vs regular instance, so if your regular instance cache is corrupted, that would explain why the Exp instance works.

%localappdata%\Microsoft\VisualStudio\15.0_<your instance id>\ComponentModelCache

**Comment by Baldstrom** [comment]
So, before I deleted that folder, I opened up VS again just to see what was up, and I got this error message:

![ptvs_error_editor_package](https://cloud.githubusercontent.com/assets/9986091/26016669/dc189b6c-371a-11e7-8f12-de5bb21bd823.png)

Then I deleted the ComponentModelCache, which didn't work, so I deleted the MEF Cache Backup and the ComponentModelCache which also didn't fix the issue. However, I haven't had the above error since. Also what is weird is that I have not seen the very initial error since yesterday.

But it's still locked up with this message:

```
Expected 1 export(s) with contract name "Microsoft.Internal.VisualStudio.PlatformUI.SolutionAttachedCollectionService" but found 0 after applying applicable constraints.
```

Let me know if you have any other ideas or need any information, for now I am going to continue using the experimental instance.

Should I update my VS preview to the latest build? It should not be very far behind, I  just installed it on Monday I believe.

**Comment by zooba** [comment]
We just released a very significant update on Wednesday, so if you haven't updated since then you may find this has been fixed. Though Preview has had many updates, and other things may have been broken along the way.

You could also switch to non-preview VS now, which includes Python support (again as of Wednesday).

**Comment by Baldstrom** [comment]
Oh, cool!

I updated my regular VS and installed the python tools and it seems to be working fine!

Thanks!
