### ISSUE TITLE
NullReferenceException in UpdateTestCasesAsync on project load

### ISSUE THREAD

**Issue by kunom** [Microsoft/PTVS#2540]
[Window Title]
devenv.exe

--------

[Main Instruction]
An unexpected error occurred

[Expanded Information]
```
Build: 3.0.17114.1

System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Microsoft.PythonTools.TestAdapter.TestContainerDiscoverer.ProjectInfo.<UpdateTestCasesAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__3`1.MoveNext()
```

**Comment by huguesv** [comment]
Thanks. We discovered and fixed this too late to make it in 15.2.  It will be part of the next release.
