### ISSUE TITLE
ModuleNotFoundError: No module named 'visualstudio_ipython_repl.IPythonBackend'; 'visualstudio_ipython_repl' is not a package

### ISSUE THREAD

**Issue by CoderCoderCoder** [Microsoft/PTVS#2577]
Hi,
I have installed Python+Data Science package in VS 2017 15.2 (the latest version), and trying to execute some basic Python code in the interactive Python window (Shift + Alt + F5).
What I see as an output is:

Error using selected REPL back-end:
Traceback (most recent call last):
  File "E:\Visual Studio 2017\Common7\IDE\Extensions\Microsoft\Python\Core\visualstudio_py_repl.py", line 1350, in _run_repl
    backend_type = getattr(__import__(backend_mod_name), backend_name)
ModuleNotFoundError: No module named 'visualstudio_ipython_repl.IPythonBackend'; 'visualstudio_ipython_repl' is not a package

Using standard backend instead
FileNotFoundError: [Errno 2] No such file or directory: ''

I have fully reinstalled Python+Data Science in the hope that it might fix the issue, but it didn't help :(. Please help, thanks!

**Comment by CoderCoderCoder** [comment]
Solved the issue. In the Python project there was no start file (to be executed by F5) specified. Once set the file the problem was solved. Probably the error message should be more explanatory, thx.

**Comment by huguesv** [comment]
Thanks for letting us know!

On debug build, I got an an unhandled exception assertion (on debug build), then unexpected error dialog.

- New Python application
- Delete the startup file (or open .pyproj and remove startup file)
- Shift-Alt-F5

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Unhandled exception in Microsoft.PythonTools.Commands.ExecuteInReplCommand.DoCommand (C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Commands\ExecuteInReplCommand.cs:135)

System.Threading.Tasks.TaskCanceledException: A task was canceled.

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

   at Microsoft.PythonTools.Repl.PythonInteractiveEvaluator.CommandProcessorThread.<ExecuteFile>d__67.MoveNext() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Repl\PythonInteractiveEvaluator.CommandProcessorThread.cs:line 734

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task ......

<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by zooba** [comment]
We don't have any handling for a null startup file. Really, this could be anywhere from `ExecuteFile()` raising when no filename is provided, through to checking the filename before trying to run anything. 

Perhaps when there's no startup file we should go back to running the current file instead of the project?

**Comment by zooba** [comment]
Same underlying problem as #2285
