### ISSUE TITLE
IDE Crash

### ISSUE THREAD

**Issue by aydinzaman** [Microsoft/PTVS#2599]
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 3.0.17114.1

System.ArgumentException: The Selection Status may not be set to a completion that isn't part of the completion/builder list in the completion set
Parameter name: value
   at Microsoft.VisualStudio.Language.Intellisense.CompletionSet.set_SelectionStatus(CompletionSelectionStatus value)
   at Microsoft.PythonTools.Intellisense.FuzzyCompletionSet.SelectSingleBest()
   at Microsoft.PythonTools.Intellisense.IntellisenseController.SelectSingleBestCompletion(ICompletionSession session)
   at Microsoft.PythonTools.Intellisense.IntellisenseController.TriggerCompletionSession(Boolean completeWord, Nullable`1 commitByDefault)
   at Microsoft.PythonTools.Language.EditFilter.ExecWorker(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.PythonTools.Language.EditFilter.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
```

**Comment by huguesv** [comment]
Thanks for the bug report!

**Comment by zooba** [comment]
Closing this and keeping #2965
