### ISSUE TITLE
NullReferenceException in some RefactorRenameTests

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2620]
RefactorRenameTests.SanityClassField
RefactorRenameTests.PrivateMemberManging
(and possibly a few more)

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
System.NullReferenceException: Object reference not set to an instance of an object.

   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)

   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)

   at Microsoft.PythonTools.Analysis.Values.InstanceInfo.GetMember(Node node, AnalysisUnit unit, String name) in C:\Projects\huguesv\PTVS\Python\Product\Analysis\Values\InstanceInfo.cs:line 172

   at Microsoft.PythonTools.Analysis.AnalysisSetExtensions.GetMember(IAnalysisSet self, Node node, AnalysisUnit unit, String name) in C:\Projects\huguesv\PTVS\Python\Product\Analysis\AnalysisSetExtensions.cs:line 39

   at Microsoft.PythonTools.Analysis.Analyzer.ExpressionEvaluator.EvaluateMember(ExpressionEvaluator ee, Node node) in C:\Projects\huguesv\PTVS\Python\Product\Analysis\Analyzer\ExpressionEvaluator.cs:line 249

   at Microsoft.PythonTools.Analysis.Analyzer.ExpressionEvaluator.EvaluateWorker(Node node) in C:\Projects\huguesv\PTVS\Python\Product\Analysi......

<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by zooba** [comment]
Probably a race condition.

**Comment by int19h** [comment]
I'm seeing these also - `InheritedClassField` and a few others in my case.

It seems to be much more likely to repro in a full test run. 

```
System.NullReferenceException: Object reference not set to an instance of an object.

   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)

   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)

   at Microsoft.PythonTools.Analysis.Values.InstanceInfo.GetMember(Node node, AnalysisUnit unit, String name) in C:\git\PTVS\Python\Product\Analysis\Values\InstanceInfo.cs:line 172

   at Microsoft.PythonTools.Analysis.AnalysisSetExtensions.GetMember(IAnalysisSet self, Node node, AnalysisUnit unit, String name) in C:\git\PTVS\Python\Product\Analysis\AnalysisSetExtensions.cs:line 39

   at Microsoft.PythonTools.Analysis.Analyzer.ExpressionEvaluator.EvaluateMember(ExpressionEvaluator ee, Node node) in C:\git\PTVS\Python\Product\Analysis\Analyzer\ExpressionEvaluator.cs:line 249

   at Microsoft.PythonTools.Analysis.Analyzer.ExpressionEvaluator.EvaluateWorker(Node node) in C:\git\PTVS\Python\Product\Analysis\Analyzer\ExpressionEvaluator.cs:line 170

   at Microsoft.PythonTools.Analysis.Analyzer.ExpressionEvaluator.Evaluate(Expression node) in C:\git\PTVS\Python\Product\Analysis\Analyzer\ExpressionEvaluator.cs:line 54

   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(ExpressionStatement node) in C:\git\PTVS\Python\Product\Analysis\Analyzer\DDG.cs:line 207

   at Microsoft.PythonTools.Parsing.Ast.ExpressionStatement.Walk(PythonWalker walker) in C:\git\PTVS\Python\Product\Analysis\Parsing\Ast\ExpressionStatement.cs:line 33

   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(SuiteStatement node) in C:\git\PTVS\Python\Product\Analysis\Analyzer\DDG.cs:line 515

   at Microsoft.PythonTools.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker) in C:\git\PTVS\Python\Product\Analysis\Parsing\Ast\SuiteStatement.cs:line 34

   at Microsoft.PythonTools.Parsing.Ast.PythonAst.Walk(PythonWalker walker) in C:\git\PTVS\Python\Product\Analysis\Parsing\Ast\PythonAst.cs:line 69

   at Microsoft.PythonTools.Analysis.AnalysisUnit.AnalyzeWorker(DDG ddg, CancellationToken cancel) in C:\git\PTVS\Python\Product\Analysis\AnalysisUnit.cs:line 165

   at Microsoft.PythonTools.Analysis.AnalysisUnit.Analyze(DDG ddg, CancellationToken cancel) in C:\git\PTVS\Python\Product\Analysis\AnalysisUnit.cs:line 148

   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Analyze(Deque`1 queue, CancellationToken cancel, Action`1 reportQueueSize, Int32 reportQueueInterval) in C:\git\PTVS\Python\Product\Analysis\Analyzer\DDG.cs:line 75

   at Microsoft.PythonTools.Analysis.PythonAnalyzer.AnalyzeQueuedEntries(CancellationToken cancel) in C:\git\PTVS\Python\Product\Analysis\PythonAnalyzer.cs:line 979

   at Microsoft.PythonTools.Intellisense.AnalysisQueue.GroupAnalysis.Analyze(CancellationToken cancel) in C:\git\PTVS\Python\Product\Analyzer\Intellisense\AnalysisQueue.cs:line 248

   at Microsoft.PythonTools.Intellisense.AnalysisQueue.Worker(Object threadStarted) in C:\git\PTVS\Python\Product\Analyzer\Intellisense\AnalysisQueue.cs:line 200



   at Microsoft.PythonTools.Intellisense.OutOfProcProjectAnalyzer.<SendUnhandledException>d__24.MoveNext() in C:\git\PTVS\Python\Product\Analyzer\Intellisense\OutOfProcProjectAnalyzer.cs:line 222

   at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.PythonTools.Intellisense.OutOfProcProjectAnalyzer.SendUnhandledException(Exception ex)

   at Microsoft.PythonTools.Intellisense.OutOfProcProjectAnalyzer.ReportUnhandledException(Exception ex) in C:\git\PTVS\Python\Product\Analyzer\Intellisense\OutOfProcProjectAnalyzer.cs:line 214

   at Microsoft.PythonTools.Intellisense.AnalysisQueue.Worker(Object threadStarted) in C:\git\PTVS\Python\Product\Analyzer\Intellisense\AnalysisQueue.cs:line 206

   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Threading.ThreadHelper.ThreadStart(Object obj)
```

**Comment by zooba** [comment]
So we shouldn't actually have any race conditions in the analyzer - it's meant to be single threaded.

We really need to capture the complete thread state when these are occurring and see what's up. I suspect we are not killing a previous analysis properly at the end of a test, but even in that case we shouldn't be sharing an analyzer.

In any case, this should not be a real issue in deployed code, since we only run one analyzer per process.
