### ISSUE TITLE
Another unexpected error occurred

### ISSUE THREAD

**Issue by kdriedger** [Microsoft/PTVS#2633]
I searched the open issues for something related to this one...  Doesn't appear to have been reported.

Visual Studio 2017 Preview.  I expect the build number below should be enough.

Does not reproduce on second launch.

This happened immediately after Windows 10 rebooted for new updates.

Steps leading up to this:
===============

1. Windows installed updates
1. Reboots
1. Log in
1. Windows automatically restarts the processes that were running before the automatic reboot
1. Crash as seen below==>

==================

[Window Title]

devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 3.0.17114.1

System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Microsoft.PythonTools.TestAdapter.TestContainerDiscoverer.ProjectInfo.<UpdateTestCasesAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.TestAdapter.TestContainerDiscoverer.ProjectInfo.<UpdateTestCasesAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
```

**Comment by zooba** [comment]
It's been reported and fixed, so you'll only find it among the closed issues. Should be available either in the current update of Preview (I don't remember if 17114.1 is our latest released build or not) or it will be coming very soon.

**Comment by kdriedger-simutech** [comment]
Next time, I'll check the closed bugs as well.   Thanks for your response.    Yes, I'm on 17114.1.

Will check in vNext.
