### ISSUE TITLE
CompletionTests unhandled exceptions on background thread cause agent to terminate

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2635]
Test run shows about 90 tests not executed, and it's due to our friend:
```
System.InvalidCastException: 'Unable to cast object of type 'TestUtilities.Mocks.MockTextVersion' to type 'Microsoft.VisualStudio.Text.ITextVersion2'.'
```

Ex: CompletionTests.SignatureHelp

ReportUnhandledException tries to take care of the InvalidCastException, but it tries to show a dialog, and TaskDialog.ForException calls into MockVsUIShell methods that are not implemented, and the end result is that the NotImplementedException takes down the test agent.

ReportUnhandledException should find a way of failing the test without taking down the test agent, and without trying to show UI.

**Comment by zooba** [comment]
ReportUnhandledException should be asserting first, which should bring the test down before it tries to display UI.

**Comment by huguesv** [comment]
Here the test ouput:
```
Test Name:	SignatureHelp
Test FullName:	PythonToolsMockTests.CompletionTests.SignatureHelp
Test Source:	C:\Projects\huguesv\PTVS\Python\Tests\PythonToolsMockTests\CompletionTests.cs : line 349
Test Outcome:	Failed
Test Duration:	0:00:00

Result Message:	The agent process was stopped while the test was running.

```

And the 'Tests' view in VS output window:
```
------ Run test started ------
Warning: Test Run deployment issue: The assembly or module 'Microsoft.VisualStudio.Shell.15.0' directly or indirectly referenced by the test container 'c:\projects\huguesv\ptvs\buildoutput\debug15.0\raw\binaries\pythontoolsmocktests.dll' was not found.
Warning: Test Run deployment issue: The assembly or module 'Microsoft.VisualStudio.Shell.Framework' directly or indirectly referenced by the test container 'c:\projects\huguesv\ptvs\buildoutput\debug15.0\raw\binaries\pythontoolsmocktests.dll' was not found.
Warning: Test Run deployment issue: The assembly or module 'StreamJsonRpc' directly or indirectly referenced by the test container 'c:\projects\huguesv\ptvs\buildoutput\debug15.0\raw\binaries\pythontoolsmocktests.dll' was not found.
Warning: Test Run deployment issue: The assembly or module 'Microsoft.ServiceHub.Client' directly or indirectly referenced by the test container 'c:\projects\huguesv\ptvs\buildoutput\debug15.0\raw\binaries\pythontoolsmocktests.dll' was not found.
Warning: Test Run deployment issue: The assembly or module 'Microsoft.VisualStudioTools.VSTestHost.15.0' directly or indirectly referenced by the test container 'c:\projects\huguesv\ptvs\buildoutput\debug15.0\raw\binaries\pythontoolsmocktests.dll' was not found.
One of the background threads threw exception: 
System.NotImplementedException: The method or operation is not implemented.
   at Microsoft.VisualStudioTools.MockVsTests.MockVsUIShell.GetDialogOwnerHwnd(IntPtr& phwnd) in C:\Projects\huguesv\PTVS\Common\Tests\MockVsTests\MockVsUIShell.cs:line 81
   at Microsoft.PythonTools.Infrastructure.TaskDialog.ShowModal() in C:\Projects\huguesv\PTVS\Python\Product\VSCommon\Infrastructure\TaskDialog.cs:line 167
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.ReportUnhandledException(Exception ex, IServiceProvider site, Type callerType, String callerFile, Int32 callerLineNumber, String callerName, Boolean allowUI) in C:\Projects\huguesv\PTVS\Python\Product\VSCommon\Infrastructure\VSTaskExtensions.cs:line 91
   at Microsoft.PythonTools.Intellisense.TaskProvider.Worker(Object param) in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\TaskProvider.cs:line 537
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
========== Run test finished: 1 run (0:00:44.3308614) ==========

```
