### ISSUE TITLE
"An unexpected error occurred" when starting VS 2017

### ISSUE THREAD

**Issue by revz79** [Microsoft/PTVS#2643]
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

Build: 3.0.17114.1

System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Microsoft.PythonTools.TestAdapter.TestContainerDiscoverer.ProjectInfo.<UpdateTestCasesAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__3`1.MoveNext()
```

**Comment by zooba** [comment]
Thanks for the report! We've fixed this in the next update, so when that is offered to you this error should no longer appear.
