### ISSUE TITLE
NullReferenceException in CreateInteractiveWindowInternal in REPL UI tests

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2701]
Not sure yet if this is a potential issue for user, or only for tests.

After we call `windowFactory2.Create`, we immediately try to use `replWindow.InteractiveWindow`, which is sometimes `null`.

```
Result StackTrace:	
at Microsoft.PythonTools.Repl.InteractiveWindowProvider.CreateInteractiveWindowInternal(IInteractiveEvaluator evaluator, IContentType contentType, Boolean alwaysCreate, Int32 id, String title, Guid languageServiceGuid, String replId) in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Repl\InteractiveWindowProvider.cs:line 256
   at Microsoft.PythonTools.Repl.InteractiveWindowProvider.Create(String replId, Int32 curId) in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Repl\InteractiveWindowProvider.cs:line 134
   at Microsoft.PythonTools.Repl.InteractiveWindowProvider.OpenOrCreate(String replId) in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Repl\InteractiveWindowProvider.cs:line 122
   at TestUtilities.UI.Python.PythonReplWindowProxySettings.<>c__DisplayClass4_0.<ActivateInteractiveWindow>b__1() in C:\Projects\huguesv\PTVS\Python\Tests\Utilities.Python\PythonReplWindowProxySettings.cs:line 83
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.VisualStudioTools.UIThread.Invoke[T](Func`1 func) in C:\Projects\huguesv\PTVS\Common\Product\SharedProject\UIThread.cs:line 86
   at TestUtilities.UI.Python.PythonReplWindowProxySettings.ActivateInteractiveWindow(VisualStudioApp app, String executionMode) in C:\Projects\huguesv\PTVS\Python\Tests\Utilities.Python\PythonReplWindowProxySettings.cs:line 81
   at TestUtilities.UI.ReplWindowProxy.OpenInteractive(VisualStudioApp app, ReplWindowProxySettings settings, String executionMode) in C:\Projects\huguesv\PTVS\Common\Tests\Utilities.UI\UI\ReplWindowProxy.cs:line 199
   at TestUtilities.UI.ReplWindowProxy.Prepare(ReplWindowProxySettings settings, Boolean useIPython) in C:\Projects\huguesv\PTVS\Common\Tests\Utilities.UI\UI\ReplWindowProxy.cs:line 158
   at ReplWindowUITests.ReplWindowPythonSmokeTests.Prepare(Boolean enableAttach, Boolean useIPython, Boolean addNewLineAtEndOfFullyTypedWord) in C:\Projects\huguesv\PTVS\Python\Tests\ReplWindowUITests\ReplWindowPythonSmokeTests.cs:line 72
   at ReplWindowUITests.ReplWindowPythonTests.TestPydocRedirected() in C:\Projects\huguesv\PTVS\Python\Tests\ReplWindowUITests\ReplWindowPythonTests.cs:line 299
Result Message:	
Test method ReplWindowUITests.ReplWindowPython36x64Tests.TestPydocRedirected threw exception: 
System.NullReferenceException: Object reference not set to an instance of an object.
```

**Comment by zooba** [comment]
Probably only tests, but it's going to be okay to spin for a little bit waiting for the window to be fully initialized.
