### ISSUE TITLE
Classifier incorrect for '{{' failure in django editing tests

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2720]
Unsure if this is revealing a product bug, or just an incorrect test. Labeling as bug to be safe.

Affected test:
DjangoUITests.DjangoEditingTests.Insertion2

```
Result StackTrace:	
at TestUtilities.Classification.Verify(IList`1 spans, Classification[] expected) in C:\Projects\GitHub\huguesv\PTVS\Common\Tests\Utilities\Classification.cs:line 56
   at DjangoUITests.DjangoEditingTests.InsertionDeletionTest(String filename, Int32 line, Int32 column, String insertionText, Classification[] expectedFirst, Classification[] expectedAfter) in C:\Projects\GitHub\huguesv\PTVS\Python\Tests\Django.UI\DjangoEditingTests.cs:line 1373
   at DjangoUITests.DjangoEditingTests.Insertion2() in C:\Projects\GitHub\huguesv\PTVS\Python\Tests\Django.UI\DjangoEditingTests.cs:line 438
Result Message:	Assert.IsTrue failed. Classifier incorrect for '{{'.  Expected:Django template tag Actual:HtmlClientTemplateSeparator
```

**Comment by zooba** [comment]
It's probably a race condition. I think the HTML editor's classification comes first, and then ours overrides it slightly later.

Either way, we need to be working with the HTML editor team again to get proper extensibility from them.
