### ISSUE TITLE
Invalid path parsing stack frame

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#2749]
Reported at https://developercommunity.visualstudio.com/content/problem/73597/django-testing-views-causes-vs-crash.html

Call stack:
```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.IO.Path.CheckInvalidPathChars(System.String, Boolean)
   at System.IO.Path.GetFileName(System.String)
   at Microsoft.VisualStudio.TestWindow.Extensibility.StackFrame..ctor(System.String, System.String, Int32)
   at Microsoft.PythonTools.TestAdapter.PythonStackTraceParser+<GetStackFrames>d__2.MoveNext()
   at System.Collections.Generic.List`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]..ctor(System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at System.Linq.Enumerable.ToList[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at Microsoft.VisualStudio.TestWindow.Extensibility.StackTrace..ctor(System.Collections.Generic.IEnumerable`1<Microsoft.VisualStudio.TestWindow.Extensibility.StackFrame>)
   at Microsoft.VisualStudio.TestWindow.Model.StackTraceParsersProvider.GetStackTrace(System.Uri, System.String)
   at Microsoft.VisualStudio.TestWindow.Model.Result..ctor(Microsoft.VisualStudio.TestWindow.Data.TestResultData, Microsoft.VisualStudio.TestWindow.Extensibility.IStackTraceParsersProvider)
   at Microsoft.VisualStudio.TestWindow.Model.TestObjectFactory.CreateResult(Microsoft.VisualStudio.TestWindow.Data.TestResultData)
   at Microsoft.VisualStudio.TestWindow.Model.TestDetail.<GetResults>b__18_0(Microsoft.VisualStudio.TestWindow.Data.TestResultData)
   at System.Linq.Enumerable+WhereSelectEnumerableIterator`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Collections.Generic.List`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]..ctor(System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at System.Linq.Enumerable.ToList[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at Microsoft.VisualStudio.TestWindow.Model.TestDetail+<UpdateResultIfNeeded>d__28.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.TestWindow.Model.TestDetail+<LoadResultsAsync>d__27.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.TestWindow.Model.TestDetail+<OnUnitTestChanged>d__26.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by huguesv** [comment]
This is because the user doesn't have the necessary call to `django.setup()` like we have in our Django template.
```
class ViewTest(TestCase):
    """Tests for the application views."""

    if django.VERSION[:2] >= (1, 7):
        # Django 1.7 requires an explicit setup() when running tests in PTVS
        @classmethod
        def setUpClass(cls):
            super(ViewTest, cls).setUpClass()
            django.setup()

    def test_home(self):
        """Tests the home page."""
        response = self.client.get(reverse('home'))
        print(response)
        self.assertContains(response, 'Home Page', 1, 200)
```

When you remove it, our stack parser receives this stack:
```
  File "C:\Users\huvalo\AppData\Local\Programs\Python\Python36-32\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Users\huvalo\AppData\Local\Programs\Python\Python36-32\lib\unittest\case.py", line 601, in run
    testMethod()
  File "C:\Projects\Temp\VigorB\app\tests.py", line 24, in test_home
    response = self.client.get(reverse('home'))
  File "C:\Projects\Temp\VigorB\env\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "C:\Projects\Temp\VigorB\env\lib\site-packages\django\urls\resolvers.py", line 436, in _reverse_with_prefix
    self._populate()
  File "C:\Projects\Temp\VigorB\env\lib\site-packages\django\urls\resolvers.py", line 288, in _populate
    for pattern in reversed(self.url_patterns):
  File "C:\Projects\Temp\VigorB\env\lib\site-packages\django\utils\functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Projects\Temp\VigorB\env\lib\site-packages\django\urls\resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Projects\Temp\VigorB\env\lib\site-packages\django\utils\functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Projects\Temp\VigorB\env\lib\site-packages\django\urls\resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Users\huvalo\AppData\Local\Programs\Python\Python36-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "C:\Projects\Temp\VigorB\VigorB\urls.py", line 7, in <module>
    import django.contrib.auth.views
  File "C:\Projects\Temp\VigorB\env\lib\site-packages\django\contrib\auth\views.py", line 11, in <module>
    from django.contrib.auth.forms import (
  File "C:\Projects\Temp\VigorB\env\lib\site-packages\django\contrib\auth\forms.py", line 12, in <module>
    from django.contrib.auth.models import User
  File "C:\Projects\Temp\VigorB\env\lib\site-packages\django\contrib\auth\models.py", line 4, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "C:\Projects\Temp\VigorB\env\lib\site-packages\django\contrib\auth\base_user.py", line 52, in <module>
    class AbstractBaseUser(models.Model):
  File "C:\Projects\Temp\VigorB\env\lib\site-packages\django\db\models\base.py", line 110, in __new__
    app_config = apps.get_containing_app_config(module)
  File "C:\Projects\Temp\VigorB\env\lib\site-packages\django\apps\registry.py", line 247, in get_containing_app_config
    self.check_apps_ready()
  File "C:\Projects\Temp\VigorB\env\lib\site-packages\django\apps\registry.py", line 125, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

And we return `<frozen importlib._bootstrap>` as a file name, causing the above exception.
