### ISSUE TITLE
Error when attempting to "Open interactive window" in VS 2017

### ISSUE THREAD

**Issue by Grauenwolf** [Microsoft/PTVS#2774]
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
An error occurred opening this interactive window.

[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
An error occurred opening this interactive window.

Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 3.0.17114.1

System.TypeLoadException: Could not load type 'Microsoft.VisualStudio.InteractiveWindow.Shell.IVsInteractiveWindowFactory2' from assembly 'Microsoft.VisualStudio.VsInteractiveWindow, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at Microsoft.PythonTools.Repl.InteractiveWindowProvider.CreateInteractiveWindowInternal(IInteractiveEvaluator evaluator, IContentType contentType, Boolean alwaysCreate, Int32 id, String title, Guid languageServiceGuid, String replId)
   at Microsoft.PythonTools.Repl.InteractiveWindowProvider.Create(String replId, Int32 curId)
   at Microsoft.PythonTools.Repl.InteractiveWindowProvider.OpenOrCreate(String replId)
   at Microsoft.PythonTools.InterpreterList.InterpreterListToolWindow.OpenInteractiveWindow_Executed(Object sender, ExecutedRoutedEventArgs e)
```

[^] Hide details  [Close]

[Expanded Information]
```
Build: 3.0.17114.1

System.TypeLoadException: Could not load type 'Microsoft.VisualStudio.InteractiveWindow.Shell.IVsInteractiveWindowFactory2' from assembly 'Microsoft.VisualStudio.VsInteractiveWindow, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at Microsoft.PythonTools.Repl.InteractiveWindowProvider.CreateInteractiveWindowInternal(IInteractiveEvaluator evaluator, IContentType contentType, Boolean alwaysCreate, Int32 id, String title, Guid languageServiceGuid, String replId)
   at Microsoft.PythonTools.Repl.InteractiveWindowProvider.Create(String replId, Int32 curId)
   at Microsoft.PythonTools.Repl.InteractiveWindowProvider.OpenOrCreate(String replId)
   at Microsoft.PythonTools.InterpreterList.InterpreterListToolWindow.OpenInteractiveWindow_Executed(Object sender, ExecutedRoutedEventArgs e)
```

**Comment by huguesv** [comment]
Unfortunately, this an issue that a lot of people have hit. Some have been able to resolve it by uninstalling VS and reinstalling.  Some ended up reinstalling Windows, but that's probably avoidable by doing some extra manual cleanup after uninstalling and before reinstalling.

There is more information in these threads:

https://github.com/Microsoft/PTVS/issues/2714
https://github.com/Microsoft/PTVS/issues/2641
https://github.com/Microsoft/PTVS/issues/2534

I'll close this one as duplicate, please post in one of the above if you need further assistance.
