### ISSUE TITLE
NullReferenceException after adding search path

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2781]
Create new project
Change the global interpreter to Python 3.6
Paste this code:
```
# tcp://my_secret@127.0.0.1:5713 tcp://my_secret@13.64.250.140
import ptvsd
print('enable_attach')
ptvsd.enable_attach(secret='my_secret', address=('127.0.0.1', 5714))
print('wait_for_attach')
ptvsd.wait_for_attach()


import random

def get_a_name():
    name = raw_input('Hello! What is your name?\n')
    return name

guesses_made = 0
number = random.randint(1, 20)
name = get_a_name()
print 'Well, {0}, I am thinking of a number between 1 and 20.'.format(name)

while guesses_made < 6:
    guess = int(raw_input('Take a guess: '))
    guesses_made += 1
    if guess < number:
        print 'Your guess is too low.'
    if guess > number:
        print 'Your guess is too high.'
    if guess == number:
        break
if guess == number:
    print 'Good job, {0}! You guessed my number in {1} guesses!'.format(name, guesses_made)
else:
    print 'Nope. The number I was thinking of was {0}'.format(number)

```

Add search path (path to your exp hive extension): `%localappdata%\Microsoft\VisualStudio\15.0_909856d1Exp\Extensions\Microsoft Corporation\Python\3.0`

Result:
```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
System.NullReferenceException: Object reference not set to an instance of an object.

   at Microsoft.PythonTools.Interpreter.Default.CPythonInterpreter.LoadModuleFromDirectory(String searchPath, String moduleName) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Interpreter\Default\CPythonInterpreter.cs:line 205

   at Microsoft.PythonTools.Interpreter.Default.CPythonInterpreter.ImportModule(String name) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Interpreter\Default\CPythonInterpreter.cs:line 103

   at Microsoft.PythonTools.Analysis.ModuleTable.TryImport(String name, ModuleReference& res) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\ModuleTable.cs:line 119

   at Microsoft.PythonTools.Analysis.Analyzer.DDG.TryImportModule(String modName, Boolean forceAbsolute, ModuleReference& moduleRef) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Analyzer\DDG.cs:line 307

   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(ImportStatement node) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Analyzer\DDG.cs:line 427

   at Microsoft.PythonTools.Parsing.Ast.ImportStatement.Walk(PythonWalker walker) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Parsing\Ast\ImportStatement.cs:line 63

   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(SuiteStatement node) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Analyzer\DDG.cs:line 515

   at Microsoft.PythonTools.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Parsing\Ast\SuiteStatement.cs:line 34

   at Microsoft.PythonTools.Parsing.Ast.PythonAst.Walk(PythonWalker walker) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Parsing\Ast\PythonAst.cs:line 69

   at Microsoft.PythonTools.Analysis.AnalysisUnit.AnalyzeWorker(DDG ddg, CancellationToken cancel) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\AnalysisUnit.cs:line 165

   at Microsoft.PythonTools.Analysis.AnalysisUnit.Analyze(DDG ddg, CancellationToken cancel) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\AnalysisUnit.cs:line 148

   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Analyze(Deque`1 queue, CancellationToken cancel, Action`1 reportQueueSize, Int32 reportQueueInterval) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Analyzer\DDG.cs:line 75

   at Microsoft.PythonTools.Analysis.PythonAnalyzer.AnalyzeQueuedEntries(CancellationToken cancel) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\PythonAnalyzer.cs:line 979

   at Microsoft.PythonTools.Intellisense.AnalysisQueue.GroupAnalysis.Analyze(CancellationToken cancel) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analyzer\Intellisense\AnalysisQueue.cs:line 248

   at Microsoft.PythonTools.Intellisense.AnalysisQueue.Worker(Object threadStarted) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analyzer\Intellisense\AnalysisQueue.cs:line 200



   at Microsoft.PythonTools.Intellisense.OutOfProcProjectAnalyzer.<SendUnhandledException>d__24.MoveNext() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analyzer\Intellisense\OutOfProcProjectAnalyzer.cs:line 222

   at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.PythonTools.Intellisense.OutOfProcProjectAnalyzer.SendUnhandledException(Exception ex)

   at Microsoft.PythonTools.Intellisense.OutOfProcProjectAnalyzer.ReportUnhandledException(Exception ex) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analyzer\Intellisense\OutOfProcProjectAnalyzer.cs:line 214

   at Microsoft.PythonTools.Intellisense.AnalysisQueue.Worker(Object threadStarted) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analyzer\Intellisense\AnalysisQueue.cs:line 206

   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Threading.ThreadHelper.ThreadStart(Object obj)


---------------------------
Abort   Retry   Ignore   
---------------------------

```

**Comment by huguesv** [comment]
`_searchPathDb` is `null` in `LoadModuleFromDirectory`:
```
            EnsureSearchPathDB();
            if (package.IsNativeExtension || package.IsCompiled) {
                _searchPathDb.LoadExtensionModule(package);
            } else {
                _searchPathDb.AddModule(package.FullName, AstPythonModule.FromFile(
                    this,
                    package.SourceFile,
                    _factory.GetLanguageVersion(),
                    package.FullName
                ));
            }

            var mod = _searchPathDb.GetModule(package.FullName);
```

due to this event handler setting it to `null` from a worker thread:
```
        private void PythonAnalyzer_SearchPathsChanged(object sender, EventArgs e) {
            _searchPaths = _state.GetSearchPaths();
            _searchPathDb = null;
            _zipPackageCache = null;

            BeginUpdateSearchPathPackages();
        }
```

**Comment by zooba** [comment]
We should probably set a flag in the event handler and then reset the DB in `EnsureSearchPathDB()`, so that it's never cleared out from the worker thread.

**Comment by zooba** [comment]
Already fixed as part of another change.
