### ISSUE TITLE
NullReferenceException in editor tooltip handling

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2782]
Create new python application
Replace the contents of the .py file with this:
```
import ptvsd
ptvsd.enable_attach(secret='my_secret', address=('127.0.0.1', 5713))
```

Put the mouse cursor between the 2 closing parentheses after 5713

ExpressionForDataTipAsync returns null task.

```
   at Microsoft.VisualStudioTools.Infrastructure.TaskExtensions.WaitAndUnwrapExceptions[T](Task`1 task, Dispatcher dispatcher) in C:\Projects\GitHub\huguesv\PTVS\Common\Product\SharedProject\TaskExtensions.cs:line 74
   at Microsoft.PythonTools.Language.TextViewFilter.GetDataTipText(TextSpan[] pSpan, String& pbstrText) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Navigation\TextViewFilter.cs:line 125
   at Microsoft.VisualStudio.Editor.Implementation.ShimQuickInfoSource.TryGetQuickInfoFromFilter(IQuickInfoSession session, TextSpan[] dataBufferTextSpan, String& tipText)
   at Microsoft.VisualStudio.Editor.Implementation.ShimQuickInfoSource.AugmentQuickInfoSession(IQuickInfoSession session, IList`1 qiContent, ITrackingSpan& applicableToSpan)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.QuickInfoSession.Recalculate()
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.QuickInfoSession.Start()
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.QuickInfoBroker.TriggerQuickInfo(ITextView textView, ITrackingPoint triggerPoint, Boolean trackMouse)
   at Microsoft.PythonTools.Intellisense.IntellisenseController.<TextViewMouseHover>d__18.MoveNext() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\IntellisenseController.cs:line 135
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
```

**Comment by huguesv** [comment]
![image](https://user-images.githubusercontent.com/1696845/28078783-d7bc2258-661a-11e7-908b-b3ccd057b388.png)
