### ISSUE TITLE
Test Explorer - Debug Test no longer works

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2784]
Using latest from master, running in exp hive

Create new python application
Add new item, unit test
Put a breakpoint on assert
Open test explorer, select test and debug test
Result:
```
[7/11/2017 1:52:51 PM Error] Failed to execute tests because the process has already exited.
[7/11/2017 1:52:53 PM Error] Error occurred connecting to debuggee.
[7/11/2017 1:52:53 PM Error] System.Runtime.InteropServices.COMException (0x80004005): Operation not supported. Unknown error: 0x80004005.
   at EnvDTE90.Debugger3.GetProcesses(Transport pTransport, String TransportQualifier)
   at Microsoft.PythonTools.Infrastructure.VisualStudioProxy.AttachToProcess(ProcessOutput processOutput, Guid portSupplier, String transportQualifierUri) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\VSCommon\Infrastructure\VisualStudioApp.cs:line 150
   at Microsoft.PythonTools.TestAdapter.TestExecutor.TestRunner.Run() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\TestAdapter.Executor\TestExecutor.cs:line 550
[7/11/2017 1:52:54 PM Informational] ========== Run test finished: 0 run (0:00:10.5298388) ==========
```

I went back to previous commits, and this broke in 221a674 (Always load Python debugger code as ptvsd package in all scenarios)

**Comment by ghpqans** [comment]
Don't know why this is closed. I'm currently facing that issue again after i updated visual studio two days ago.
May there be some persistant data which looses it's validy after a vs update?
