### ISSUE TITLE
Assert while editing

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2791]
I got this assert after hitting ENTER about 3 times at the end of my script.

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------




   at Microsoft.PythonTools.Intellisense.BufferParser.<ParseBuffers>d__37.MoveNext() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\BufferParser.cs:line 391

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass4_0.<OutputAsyncCausalityEvents>b__0()

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke()

   at System.Runtime.CompilerServices.TaskAwaiter.<>c__DisplayClass11_0.<OutputWaitEtwEvents>b__0()

   at System.Ru......

<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------
```

![image](https://user-images.githubusercontent.com/1696845/28133308-691af2ae-66f4-11e7-978a-76039cc84e33.png)

See locals and immediate window for the 2 values that were expected to match. 

![image](https://user-images.githubusercontent.com/1696845/28133350-921bf2fc-66f4-11e7-8092-9686df89ad4a.png)

**Comment by zooba** [comment]
I suspect this is a race-condition and we shouldn't be asserting here (or we should be checking whether we've raced). But we'd need to dig in deeper to be sure...

**Comment by huguesv** [comment]
I haven't seen this in a while. I'll reopen if it happens again.
