### ISSUE TITLE
Assert in ExpressionEvaluator.set_Scope

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2801]
Create new python application
Add virtual env based on 3.5 64-bit
Wait for analysis to complete
pip install tensorflow==1.2.1 (currently the latest) using environments window
At about 60% analysis progress, I start getting a lot of these assertions

```
Assertion Failed
   at Microsoft.PythonTools.Analysis.Analyzer.ExpressionEvaluator.set_Scope(InterpreterScope value) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Analyzer\ExpressionEvaluator.cs:line 146
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.set_Scope(InterpreterScope value) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Analyzer\DDG.cs:line 101
   at Microsoft.PythonTools.Analysis.Analyzer.FunctionAnalysisUnit.AnalyzeWorker(DDG ddg, CancellationToken cancel) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Analyzer\FunctionAnalysisUnit.cs:line 83
   at Microsoft.PythonTools.Analysis.AnalysisUnit.Analyze(DDG ddg, CancellationToken cancel) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\AnalysisUnit.cs:line 148
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Analyze(Deque`1 queue, CancellationToken cancel, Action`1 reportQueueSize, Int32 reportQueueInterval) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Analyzer\DDG.cs:line 75
   at Microsoft.PythonTools.Analysis.PythonAnalyzer.AnalyzeQueuedEntries(CancellationToken cancel) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\PythonAnalyzer.cs:line 979
   at Microsoft.PythonTools.Analysis.PyLibAnalyzer.Analyze() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analyzer\PyLibAnalyzer.cs:line 1358
   at Microsoft.PythonTools.Analysis.PyLibAnalyzer.<RunWorker>d__34.MoveNext() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analyzer\PyLibAnalyzer.cs:line 203
   ...
   at Microsoft.PythonTools.Analysis.PyLibAnalyzer.<Scrape>d__60.MoveNext() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analyzer\PyLibAnalyzer.cs:line 1152
   ...
```

**Comment by zooba** [comment]
They clearly have some sort of code construct in tensorflow that we can't analyze.

If you want to dig in, try and find that video I did on using the analysis memory testing tool and do the same thing here to narrow down the minimal set of files needed to cause the assertion.

**Comment by huguesv** [comment]
Minimum repro: paste this code in a new python application.
```
class SequenceQueueingStateSaver(object):
  def _store_index_maps(self, sequences, context, states):
    """Prepares the internal dictionaries _name_to_index and _index_to_name.

    These dictionaries are used to keep track of indices into the barrier.

    Args:
      sequences: `OrderedDict` of string, `Tensor` pairs.
      context: `OrderedDict` of string, `Tensor` pairs.
      states: `OrderedDict` of string, `Tensor` pairs.
    """
    assert isinstance(sequences, dict)
    assert isinstance(context, dict)
    assert isinstance(states, dict)
    self._name_to_index = dict(
        (name, ix)
        for (ix, name) in enumerate([
            "__length", "__total_length", "__next_key", "__sequence",
            "__sequence_count"
        ] + ["__sequence__%s" % k for k in sequences.keys()] + [
            "__context__%s" % k for k in context.keys()
        ] + ["__state__%s" % k for k in states.keys()]))
    self._index_to_name = [
        name
        for (name, _) in sorted(
            self._name_to_index.items(), key=lambda n_ix: n_ix[1])
    ]
```

**Comment by huguesv** [comment]
Ok, most minimal now :)
```
def my_func(my_param):
    assert isinstance(my_param, dict)
    my_val = [
        name
        for (name, _) in sorted(
            {}, key=lambda n_ix: n_ix[1])
    ]
```

**Comment by zooba** [comment]
I don't think we set up a list comprehension scope, but we should for the lambda, so I'm not surprised to have scope handling issues between the IsInstanceScope and the lambda scope.

**Comment by zooba** [comment]
Even shorter:
```python
if isinstance(p, dict):
    v = [i for i in (lambda x: x)()]
```

The problem is because of the lambda scope being nested within the comprehension scope when it should be in the outer scope:

```python
if isinstance(p, dict):
    def _unnamed(x): return x
    v = [i for i in _unnamed()]
```

**Comment by zooba** [comment]
Actually, scratch that second part. It's fine to define the lambda in the comprehension scope as long as we put the node scope in the module scope rather than the isinstance scope.
