### ISSUE TITLE
Stop Debugging asserts while debugging unit tests

### ISSUE THREAD

**Issue by int19h** [Microsoft/PTVS#2842]
```py
import unittest

class Test_test1(unittest.TestCase):
    def test_A(self):
        self.fail("Not implemented")

if __name__ == '__main__':
    unittest.main()
```
Set breakpoint on `fail`. Run the test w/debugging from Test Explorer. Once stopped on breakpoint, do "Stop Debugging".

There are three possible outcomes that I'm seeing more or less at random:

1. Debugging stops, unit test run is completed (this is the expected result).

2. Debugging stops, unit test run is stuck in running state as indicated by Test Explorer progress bar. There's a python.exe process in the background; when killed, Test Explorer will indicate completion in a few seconds.

3. Assertion failure as follows:

```
Failed to terminate debugger event thread

   at Microsoft.PythonTools.Debugger.DebugConnection.WaitForWorkerThreads() in C:\git\PTVS\Python\Product\Debugger\Debugger\DebugConnection.cs:line 313

   at Microsoft.PythonTools.Debugger.DebugConnection.Dispose() in C:\git\PTVS\Python\Product\Debugger\Debugger\DebugConnection.cs:line 297

   at Microsoft.PythonTools.Debugger.PythonProcess.Dispose(Boolean disposing) in C:\git\PTVS\Python\Product\Debugger\Debugger\PythonProcess.cs:line 208

   at Microsoft.PythonTools.Debugger.PythonProcess.Dispose() in C:\git\PTVS\Python\Product\Debugger\Debugger\PythonProcess.cs:line 167

   at Microsoft.PythonTools.Debugger.DebugEngine.AD7Engine.Microsoft.VisualStudio.Debugger.Interop.IDebugEngine2.ContinueFromSynchronousEvent(IDebugEvent2 eventObject) in C:\git\PTVS\Python\Product\Debugger\Debugger\DebugEngine\AD7Engine.cs:line 508

   at Microsoft.VisualStudio.Shell.Interop.IVsUIDataSource.Invoke(String verb, Object pvaIn, Object& pvaOut)

   at Microsoft.Internal.VisualStudio.PlatformUI.DataSource.Invoke(String verb, Object pvaIn, Object& pvaOut)

   at Microsoft.VisualStudio.PlatformUI.VsCommand.Execute(Object parameter)

   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)

   at System.Windows.Controls.Primitives.ButtonBase.OnClick()

   at System.Windows.Controls.Button.OnClick()

   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)

   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)

   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)

   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)

   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)

   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)

   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)

   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)

   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)

   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)

   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)

   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)

   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)

   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)

   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)

   at System.Windows.Input.InputManager.ProcessStagingArea()

   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)

   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)

   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)

   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)

   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
```
followed by another one:
```
Error while handling debugger event 'legacyRequestHandlers'.
System.OperationCanceledException: The operation was canceled.

   at Microsoft.PythonTools.Debugger.PythonProcess.<SendDebugRequestAsync>d__109`1.MoveNext() in C:\git\PTVS\Python\Product\Debugger\Debugger\PythonProcess.cs:line 1114

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

   at Microsoft.PythonTools.Infrastructure.TaskExtensions.WaitAndUnwrapExceptions[T](Task`1 task) in C:\git\PTVS\Python\Product\Common\Infrastructure\TaskExtensions.cs:line 75

   at Microsoft.PythonTools.Debugger.PythonProcess.OnLegacyRequestHandlers(Object sender, RequestHandlersEvent e) in C:\git\PTVS\Python\Product\Debugger\Debugger\PythonProcess.cs:line 564

   at Microsoft.PythonTools.Debugger.DebugConnection.HandleEvent(EventReceivedEventArgs e) in C:\git\PTVS\Python\Product\Debugger\Debugger\DebugConnection.cs:line 268

   at Microsoft.PythonTools.Debugger.DebugConnection.EventHandlingThread() in C:\git\PTVS\Python\Product\Debugger\Debugger\DebugConnection.cs:line 202



   at Microsoft.PythonTools.Debugger.DebugConnection.EventHandlingThread() in C:\git\PTVS\Python\Product\Debugger\Debugger\DebugConnection.cs:line 204

   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Threading.ThreadHelper.ThreadStart()
```
followed by the same symptoms as the previous outcome (i.e. Test Explorer stuck in running state).

**Comment by int19h** [comment]
It's a deadlock during debugger shutdown. On the main thread, we do this to wait for the event thread to complete:
```
 	mscorlib.dll!System.Threading.Thread.Join(int millisecondsTimeout) Line 694	C#
>	Microsoft.PythonTools.Debugger.dll!Microsoft.PythonTools.Debugger.DebugConnection.WaitForWorkerThreads() Line 313	C#
 	Microsoft.PythonTools.Debugger.dll!Microsoft.PythonTools.Debugger.DebugConnection.Dispose() Line 298	C#
 	Microsoft.PythonTools.Debugger.dll!Microsoft.PythonTools.Debugger.PythonProcess.Dispose(bool disposing) Line 210	C#
 	Microsoft.PythonTools.Debugger.dll!Microsoft.PythonTools.Debugger.PythonProcess.Dispose() Line 167	C#
 	Microsoft.PythonTools.Debugger.dll!Microsoft.PythonTools.Debugger.DebugEngine.AD7Engine.Microsoft.VisualStudio.Debugger.Interop.IDebugEngine2.ContinueFromSynchronousEvent(Microsoft.VisualStudio.Debugger.Interop.IDebugEvent2 eventObject) Line 508	C#
```
while the event thread was in the middle of processing an exception handler request, and is trying to send the response:
```
 	mscorlib.dll!System.Threading.Monitor.Enter(object obj, ref bool lockTaken) Line 62	C#
>	Microsoft.PythonTools.Debugger.dll!Microsoft.PythonTools.Debugger.PythonProcess.SendDebugRequestAsync<Microsoft.PythonTools.Ipc.Json.Response>(Microsoft.PythonTools.Ipc.Json.Request<Microsoft.PythonTools.Ipc.Json.Response> request, System.Threading.CancellationToken cancellationToken) Line 1119	C#
 	Microsoft.PythonTools.Debugger.dll!Microsoft.PythonTools.Debugger.PythonProcess.OnLegacyRequestHandlers(object sender, Microsoft.PythonTools.Debugger.LegacyDebuggerProtocol.RequestHandlersEvent e) Line 574	C#
 	Microsoft.PythonTools.Debugger.dll!Microsoft.PythonTools.Debugger.DebugConnection.HandleEvent(Microsoft.PythonTools.Ipc.Json.EventReceivedEventArgs e) Line 269	C#
 	Microsoft.PythonTools.Debugger.dll!Microsoft.PythonTools.Debugger.DebugConnection.EventHandlingThread() Line 202	C#
```
but can't, because it's waiting on this lock in `SendDebugRequestAsync`:
```cs
            lock (_connectionLock) {
                connection = _connection;
            }
```
The problem is that on the main thread, `PythonProcess.Dispose` invokes `DebugConnection.Dispose` while holding `_connectionLock`:
```cs
                lock (_connectionLock) {
                    if (_connection != null) {
                        _connection.ProcessingMessagesEnded -= OnProcessingMessagesEnded;
                        _connection.LegacyAsyncBreak -= OnLegacyAsyncBreak;
                        _connection.LegacyBreakpointFailed -= OnLegacyBreakpointFailed;
                        _connection.LegacyBreakpointHit -= OnLegacyBreakpointHit;
                        _connection.LegacyBreakpointSet -= OnLegacyBreakpointSet;
                        _connection.LegacyDebuggerOutput -= OnLegacyDebuggerOutput;
                        _connection.LegacyDetach -= OnLegacyDetach;
                        _connection.LegacyEnumChildren -= OnLegacyEnumChildren;
                        _connection.LegacyException -= OnLegacyException;
                        _connection.LegacyExecutionException -= OnLegacyExecutionException;
                        _connection.LegacyExecutionResult -= OnLegacyExecutionResult;
                        _connection.LegacyLast -= OnLegacyLast;
                        _connection.LegacyModuleLoad -= OnLegacyModuleLoad;
                        _connection.LegacyProcessLoad -= OnLegacyProcessLoad;
                        _connection.LegacyRequestHandlers -= OnLegacyRequestHandlers;
                        _connection.LegacyStepDone -= OnLegacyStepDone;
                        _connection.LegacyThreadCreate -= OnLegacyThreadCreate;
                        _connection.LegacyThreadExit -= OnLegacyThreadExit;
                        _connection.LegacyThreadFrameList -= OnLegacyThreadFrameList;
                        _connection.LegacyModulesChanged -= OnLegacyModulesChanged;
                        _connection.Dispose();
                        _connection = null;
                    }
                    // Avoiding ?. syntax because FxCop doesn't understand it
                    if (_process != null) {
                        _process.Dispose();
                    }
                }
```
Hence, deadlock.

@huguesv, do you recall if there's any specific reason why the lock is held for disposing (both connection and process)? Normally it's just used to access `_connection` and its event handlers, so it feels like it should suffice to lock around that, copy the current value of `_connection` to a local, and then dispose that once the lock is released - and ditto for `_process`. But it looks like it was written the way it is now from the get go, so perhaps I'm missing some other use of that lock?

**Comment by huguesv** [comment]
@int19h your suggestion sounds good.
