### ISSUE TITLE
Microsoft.PythonTools.Repl.PythonInteractiveEvaluator+CommandProcessorThread+DisconnectedException

### ISSUE THREAD

**Issue by MichaelGoulding** [Microsoft/PTVS#2845]
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 3.0.17160.3

Microsoft.PythonTools.Repl.PythonInteractiveEvaluator+CommandProcessorThread+DisconnectedException: The interactive window has become disconnected from the Python process. Please reset the window.
   at Microsoft.PythonTools.Repl.PythonInteractiveEvaluator.CommandProcessorThread.ThrowIfDisconnected()
   at Microsoft.PythonTools.Repl.PythonInteractiveEvaluator.CommandProcessorThread.StreamLock..ctor(CommandProcessorThread evaluator, Boolean throwIfDisconnected)
   at Microsoft.PythonTools.Repl.PythonInteractiveEvaluator.CommandProcessorThread.SetThreadAndFrameCommand(Int64 thread, Int32 frame, FrameKind frameKind)
   at Microsoft.PythonTools.Repl.PythonDebugProcessReplEvaluator.SwitchThread(PythonThread thread, Boolean verbose)
   at Microsoft.PythonTools.Repl.PythonDebugReplEvaluator.ChangeActiveThread(Int64 id, Boolean verbose)
   at Microsoft.PythonTools.Repl.PythonDebugReplEvaluator.<>c__DisplayClass14_1.<OnEnterBreakMode>b__1(Task t)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
```

**Comment by MichaelGoulding** [comment]
I was docking that window while debugging....

**Comment by huguesv** [comment]
Thanks, this specific issue shouldn't be a problem in the upcoming 15.3 release, as the Debug REPL protocol code was rewritten, and the code in this call stack doesn't exist anymore.
I'll try it out to make sure there's not an equivalent issue in the new code.

**Comment by huguesv** [comment]
Looks like it will be fine. It's no longer going to the debugged process when switching thread/frame.

**Comment by MichaelGoulding** [comment]
Thanks!


-------- Original message --------
