### ISSUE TITLE
interactive window not working (and sending to interactive window crashes VS2017)

### ISSUE THREAD

**Issue by gdoura** [Microsoft/PTVS#2905]
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
An error occurred opening this interactive window.

Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Fermer]

[Expanded Information]
```
Build: 3.0.17114.1

System.TypeLoadException: Could not load type 'Microsoft.VisualStudio.InteractiveWindow.Shell.IVsInteractiveWindowFactory2' from assembly 'Microsoft.VisualStudio.VsInteractiveWindow, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at Microsoft.PythonTools.Repl.InteractiveWindowProvider.CreateInteractiveWindowInternal(IInteractiveEvaluator evaluator, IContentType contentType, Boolean alwaysCreate, Int32 id, String title, Guid languageServiceGuid, String replId)
   at Microsoft.PythonTools.Repl.InteractiveWindowProvider.Create(String replId, Int32 curId)
   at Microsoft.PythonTools.Repl.InteractiveWindowProvider.OpenOrCreate(String replId)
   at Microsoft.PythonTools.InterpreterList.InterpreterListToolWindow.OpenInteractiveWindow_Executed(Object sender, ExecutedRoutedEventArgs e)
```

**Comment by gdoura** [comment]
solution from 
Funkrusha
i had the same problem too, in my case it's the componentcache in
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions
i also had the preview installed before...

the solution:

remove the cached folder in C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions (search for Microsoft.VisualStudio.VsInteractiveWindow.dll in the extensions dir named above

restart visual studio and then vs rebuild the component cache.

maybe clean the MEF cache in %localappdata%\Microsoft\VisualStudio\15.0_<your_id>\ComponentModelCache before
This was referenced on 28 Jun
 Closed
Python Windows Application can't be started #2740
 Closed
Error when attempting to "Open interactive window" in VS 2017 #2774
 @fklier
fklier commented on 10 Jul
Funkrusha's steps worked for me without needing to uninstall/reinstall anything (thanks!)

After removing the folder containing Microsoft.VisualStudio.VsInteractiveWindow.dll from the IDE\Extensions folder Visual Studio crashed on the next start. The following start rebuilt the cache and the interactive windows were opening and working normally.
