### ISSUE TITLE
crashes analyzing winpython 3.4.3.3 64-bit

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#291]
When first analysis ended, the refresh button was still there so I clicked it without much investigation, but after second analysis ended, there are still a lot of packages reported as not analyzed.  Here's my analysislog.txt with today's data:
```
2015-06-01T10:14:56 DONE_STDLIB "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio\2.2\Microsoft.PythonTools.Analyzer.exe" /id {9a7a9026-48c1-4688-9d5d-e5699d47d074} /version 3.5 /python "C:\Program Files\Python 3.5\python.exe" /outdir "C:\Users\huvalo\AppData\Local\Python Tools\CompletionDB\14.0\9a7a9026-48c1-4688-9d5d-e5699d47d074\3.5" /basedb "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio\2.2\CompletionDB" /log "C:\Users\huvalo\AppData\Local\Python Tools\CompletionDB\14.0\9a7a9026-48c1-4688-9d5d-e5699d47d074\3.5\AnalysisLog.txt" /glog "C:\Users\huvalo\AppData\Local\Python Tools\CompletionDB\14.0\AnalysisLog.txt" /wait ""
2015-06-01T10:29:04 START_STDLIB "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio\2.2\Microsoft.PythonTools.Analyzer.exe" /id {2af0f10d-7135-4994-9156-5d01c9c11b7e} /version 3.5 /python C:\Users\huvalo\AppData\Local\Programs\Python\Python35-32\python.exe /outdir "C:\Users\huvalo\AppData\Local\Python Tools\CompletionDB\14.0\2af0f10d-7135-4994-9156-5d01c9c11b7e\3.5" /basedb "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio\2.2\CompletionDB" /log "C:\Users\huvalo\AppData\Local\Python Tools\CompletionDB\14.0\2af0f10d-7135-4994-9156-5d01c9c11b7e\3.5\AnalysisLog.txt" /glog "C:\Users\huvalo\AppData\Local\Python Tools\CompletionDB\14.0\AnalysisLog.txt" /wait ""
2015-06-01T10:35:30 DONE_STDLIB "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio\2.2\Microsoft.PythonTools.Analyzer.exe" /id {2af0f10d-7135-4994-9156-5d01c9c11b7e} /version 3.5 /python C:\Users\huvalo\AppData\Local\Programs\Python\Python35-32\python.exe /outdir "C:\Users\huvalo\AppData\Local\Python Tools\CompletionDB\14.0\2af0f10d-7135-4994-9156-5d01c9c11b7e\3.5" /basedb "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio\2.2\CompletionDB" /log "C:\Users\huvalo\AppData\Local\Python Tools\CompletionDB\14.0\2af0f10d-7135-4994-9156-5d01c9c11b7e\3.5\AnalysisLog.txt" /glog "C:\Users\huvalo\AppData\Local\Python Tools\CompletionDB\14.0\AnalysisLog.txt" /wait ""
2015-06-01T11:04:51 START_STDLIB "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio\2.2\Microsoft.PythonTools.Analyzer.exe" /id {10ef0e1d-520b-4b97-b5be-d1760fa375e2} /version 3.4 /python C:\WinPython\WinPython-64bit-3.4.3.3\python-3.4.3.amd64\python.exe /outdir "C:\Users\huvalo\AppData\Local\Python Tools\CompletionDB\14.0\10ef0e1d-520b-4b97-b5be-d1760fa375e2\3.4" /basedb "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio\2.2\CompletionDB" /log "C:\Users\huvalo\AppData\Local\Python Tools\CompletionDB\14.0\10ef0e1d-520b-4b97-b5be-d1760fa375e2\3.4\AnalysisLog.txt" /glog "C:\Users\huvalo\AppData\Local\Python Tools\CompletionDB\14.0\AnalysisLog.txt" /wait ""
2015-06-01T11:27:24 FAIL_STDLIB
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.PythonTools.Analysis.AnalysisSetDetails.AnalysisHashSet.Clone()
   at Microsoft.PythonTools.Analysis.AnalysisSetDetails.AnalysisHashSet.Union(IEnumerable`1 items, Boolean& wasChanged, Boolean canMutate)
   at Microsoft.PythonTools.Analysis.Analyzer.DependentKeyValue.CopyFrom(DependentKeyValue dependentKeyValue, Boolean enqueue)
   at Microsoft.PythonTools.Analysis.Values.DictionaryInfo.DictionaryUpdate(Node node, AnalysisUnit unit, IAnalysisSet[] args, NameExpression[] keywordArgNames)
   at Microsoft.PythonTools.Analysis.Values.SpecializedCallable.Call(Node node, AnalysisUnit unit, IAnalysisSet[] args, NameExpression[] keywordArgNames)
   at Microsoft.PythonTools.Analysis.Analyzer.ExpressionEvaluator.EvaluateCall(ExpressionEvaluator ee, Node node)
   at Microsoft.PythonTools.Analysis.Analyzer.ExpressionEvaluator.EvaluateWorker(Node node)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(ExpressionStatement node)
   at Microsoft.PythonTools.Parsing.Ast.ExpressionStatement.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(SuiteStatement node)
   at Microsoft.PythonTools.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(IfStatement node)
   at Microsoft.PythonTools.Parsing.Ast.IfStatement.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(SuiteStatement node)
   at Microsoft.PythonTools.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(IfStatement node)
   at Microsoft.PythonTools.Parsing.Ast.IfStatement.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(SuiteStatement node)
   at Microsoft.PythonTools.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(IfStatement node)
   at Microsoft.PythonTools.Parsing.Ast.IfStatement.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(SuiteStatement node)
   at Microsoft.PythonTools.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(IfStatement node)
   at Microsoft.PythonTools.Parsing.Ast.IfStatement.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(SuiteStatement node)
   at Microsoft.PythonTools.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(IfStatement node)
   at Microsoft.PythonTools.Parsing.Ast.IfStatement.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(SuiteStatement node)
   at Microsoft.PythonTools.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Analysis.Analyzer.FunctionAnalysisUnit.AnalyzeWorker(DDG ddg, CancellationToken cancel)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Analyze(Deque`1 queue, CancellationToken cancel, Action`1 reportQueueSize, Int32 reportQueueInterval)
   at Microsoft.PythonTools.Analysis.PythonAnalyzer.AnalyzeQueuedEntries(CancellationToken cancel)
   at Microsoft.PythonTools.Analysis.PyLibAnalyzer.Analyze()
   at Microsoft.PythonTools.Analysis.PyLibAnalyzer.<RunWorker>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Analysis.PyLibAnalyzer.<Run>d__30.MoveNext() "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio\2.2\Microsoft.PythonTools.Analyzer.exe" /id {10ef0e1d-520b-4b97-b5be-d1760fa375e2} /version 3.4 /python C:\WinPython\WinPython-64bit-3.4.3.3\python-3.4.3.amd64\python.exe /outdir "C:\Users\huvalo\AppData\Local\Python Tools\CompletionDB\14.0\10ef0e1d-520b-4b97-b5be-d1760fa375e2\3.4" /basedb "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio\2.2\CompletionDB" /log "C:\Users\huvalo\AppData\Local\Python Tools\CompletionDB\14.0\10ef0e1d-520b-4b97-b5be-d1760fa375e2\3.4\AnalysisLog.txt" /glog "C:\Users\huvalo\AppData\Local\Python Tools\CompletionDB\14.0\AnalysisLog.txt" /wait ""
2015-06-01T11:53:11 START_STDLIB "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio\2.2\Microsoft.PythonTools.Analyzer.exe" /id {10ef0e1d-520b-4b97-b5be-d1760fa375e2} /version 3.4 /python C:\WinPython\WinPython-64bit-3.4.3.3\python-3.4.3.amd64\python.exe /outdir "C:\Users\huvalo\AppData\Local\Python Tools\CompletionDB\14.0\10ef0e1d-520b-4b97-b5be-d1760fa375e2\3.4" /basedb "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio\2.2\CompletionDB" /log "C:\Users\huvalo\AppData\Local\Python Tools\CompletionDB\14.0\10ef0e1d-520b-4b97-b5be-d1760fa375e2\3.4\AnalysisLog.txt" /glog "C:\Users\huvalo\AppData\Local\Python Tools\CompletionDB\14.0\AnalysisLog.txt" /wait ""
2015-06-01T12:24:26 FAIL_STDLIB
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.PythonTools.Analysis.AnalysisSetDetails.AnalysisHashSet.Clone()
   at Microsoft.PythonTools.Analysis.AnalysisSetDetails.AnalysisHashSet.Union(IEnumerable`1 items, Boolean& wasChanged, Boolean canMutate)
   at Microsoft.PythonTools.Analysis.Analyzer.DependentKeyValue.CopyFrom(DependentKeyValue dependentKeyValue, Boolean enqueue)
   at Microsoft.PythonTools.Analysis.Values.DictionaryInfo.DictionaryUpdate(Node node, AnalysisUnit unit, IAnalysisSet[] args, NameExpression[] keywordArgNames)
   at Microsoft.PythonTools.Analysis.Values.SpecializedCallable.Call(Node node, AnalysisUnit unit, IAnalysisSet[] args, NameExpression[] keywordArgNames)
   at Microsoft.PythonTools.Analysis.Analyzer.ExpressionEvaluator.EvaluateCall(ExpressionEvaluator ee, Node node)
   at Microsoft.PythonTools.Analysis.Analyzer.ExpressionEvaluator.EvaluateWorker(Node node)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(ExpressionStatement node)
   at Microsoft.PythonTools.Parsing.Ast.ExpressionStatement.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(SuiteStatement node)
   at Microsoft.PythonTools.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(IfStatement node)
   at Microsoft.PythonTools.Parsing.Ast.IfStatement.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(SuiteStatement node)
   at Microsoft.PythonTools.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(IfStatement node)
   at Microsoft.PythonTools.Parsing.Ast.IfStatement.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(SuiteStatement node)
   at Microsoft.PythonTools.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(IfStatement node)
   at Microsoft.PythonTools.Parsing.Ast.IfStatement.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(SuiteStatement node)
   at Microsoft.PythonTools.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(IfStatement node)
   at Microsoft.PythonTools.Parsing.Ast.IfStatement.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(SuiteStatement node)
   at Microsoft.PythonTools.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(IfStatement node)
   at Microsoft.PythonTools.Parsing.Ast.IfStatement.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(SuiteStatement node)
   at Microsoft.PythonTools.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Analysis.Analyzer.FunctionAnalysisUnit.AnalyzeWorker(DDG ddg, CancellationToken cancel)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Analyze(Deque`1 queue, CancellationToken cancel, Action`1 reportQueueSize, Int32 reportQueueInterval)
   at Microsoft.PythonTools.Analysis.PythonAnalyzer.AnalyzeQueuedEntries(CancellationToken cancel)
   at Microsoft.PythonTools.Analysis.PyLibAnalyzer.Analyze()
   at Microsoft.PythonTools.Analysis.PyLibAnalyzer.<RunWorker>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Analysis.PyLibAnalyzer.<Run>d__30.MoveNext() "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio\2.2\Microsoft.PythonTools.Analyzer.exe" /id {10ef0e1d-520b-4b97-b5be-d1760fa375e2} /version 3.4 /python C:\WinPython\WinPython-64bit-3.4.3.3\python-3.4.3.amd64\python.exe /outdir "C:\Users\huvalo\AppData\Local\Python Tools\CompletionDB\14.0\10ef0e1d-520b-4b97-b5be-d1760fa375e2\3.4" /basedb "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio\2.2\CompletionDB" /log "C:\Users\huvalo\AppData\Local\Python Tools\CompletionDB\14.0\10ef0e1d-520b-4b97-b5be-d1760fa375e2\3.4\AnalysisLog.txt" /glog "C:\Users\huvalo\AppData\Local\Python Tools\CompletionDB\14.0\AnalysisLog.txt" /wait ""

```

**Comment by huguesv** [comment]
This is on Dev-2015-05-28, I'll try the latest rolling build.

**Comment by huguesv** [comment]
Repros with CL1480360

Diagnostics info:
https://gist.github.com/huguesv/0ff07cca4642050a8c3d#file-diagnostic-info-2015-06-01t134534
