### ISSUE TITLE
Crash in PythonAnalysisClassifier

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2921]
This randomly occurs when loading my project, using latest from master.

```
An unhandled exception is about to terminate the process:
Unable to sort because the IComparer.Compare() method returns inconsistent results. Either a value does not compare equal to itself, or one value repeatedly compared to another value yields different results. IComparer: 'System.Array+FunctorComparer`1[Microsoft.PythonTools.Intellisense.AnalysisProtocol+AnalysisClassification]'.
System.ArgumentException: Unable to sort because the IComparer.Compare() method returns inconsistent results. Either a value does not compare equal to itself, or one value repeatedly compared to another value yields different results. IComparer: 'System.Array+FunctorComparer`1[Microsoft.PythonTools.Intellisense.AnalysisProtocol+AnalysisClassification]'.
   at System.Collections.Generic.IntrospectiveSortUtilities.ThrowOrIgnoreBadComparer(Object comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Comparison`1 comparison)
   at Microsoft.PythonTools.PythonAnalysisClassifier.<OnNewAnalysis>d__6.MoveNext() in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\PythonAnalysisClassifier.cs:line 85
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
   at Microsoft.VisualStudioTools.CommonPackage.<>c.<.ctor>b__8_0(Object sender, UnhandledExceptionEventArgs e) in C:\Projects\huguesv\PTVS\Common\Product\SharedProject\CommonPackage.cs:line 59
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by zooba** [comment]
The code causing "Unable to sort because the IComparer.Compare() method returns inconsistent results. Either a value does not compare equal to itself, or one value repeatedly compared to another value yields different results" is this:

```c#
Array.Sort(
    classifications.Data.classifications,
    (x, y) => x.start - y.start
);
```

Presumably this means we have multiple classifications for the same word.

**Comment by zooba** [comment]
This is also affecting 15.3 and we're being asked for a servicing fix.
