### ISSUE TITLE
Assert, then unexpected error when using New Window

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2924]
Open a Python file that has some code in it
From main menu, Window -> New Window
You'll get an assert because the text buffer was already initialized (from BufferParser.InitBuffer)
Close the new window
Move the cursor around in the original 'window' to trigger a tooltip, you'll get an activity log error
If you try to use IntelliSense, you'll get the unexpected error dialog instead

```
System.ArgumentException: Failed to get classifier from buffer
at Microsoft.PythonTools.Intellisense.ReverseExpressionParser..ctor(ITextSnapshot snapshot, ITextBuffer buffer, ITrackingSpan span) in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\ReverseExpressionParser.cs:line 53
at Microsoft.PythonTools.Language.TextViewFilter.GetDataTipText(TextSpan[] pSpan, String& pbstrText) in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Navigation\TextViewFilter.cs:line 119
at Microsoft.VisualStudio.Editor.Implementation.ShimQuickInfoSource.TryGetQuickInfoFromFilter(IQuickInfoSession session, TextSpan[] dataBufferTextSpan, String& tipText)
at Microsoft.VisualStudio.Editor.Implementation.ShimQuickInfoSource.AugmentQuickInfoSession(IQuickInfoSession session, IList`1 qiContent, ITrackingSpan& applicableToSpan)
at Microsoft.VisualStudio.Language.Intellisense.Implementation.QuickInfoSession.Recalculate() at Microsoft.VisualStudio.Language.Intellisense.Implementation.QuickInfoSession.Start()
at Microsoft.VisualStudio.Language.Intellisense.Implementation.DefaultQuickInfoController.OnTextView_MouseHover(Object sender, MouseHoverEventArgs e)
at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.RaiseHoverEvents()
```

`IntellisenseController.DisconnectSubjectBuffer` is called when the view is closed, and it does a `PythonTextBufferInfo.TryDispose(subjectBuffer)` which removes the `PythonTextBufferInfo` property, and `ReverseExpressionParser` expects it to be there later on.

I've had the assert and the TryDispose calls commented out while I've been working on Peek Definition, which is also a new window on a shared text buffer. Not sure what the right fix is.

**Comment by zooba** [comment]
Any idea how you're getting a hover event after closing the view?

Maybe we need to just let the buffer info object get GC'd on its own. It is supposed to only end up in reference cycles with the buffer itself, so perhaps we don't need to explicitly dispose it.

Since you've already got it disabled, keep an eye on memory usage and see if we seem to be leaking.

**Comment by huguesv** [comment]
The hover event is on the first view, not the one that is closing. It's because I'm moving the cursor around in the first view after I've closed the second view.

**Comment by zooba** [comment]
This has exposed a more fundamental issue in how buffer parsers work.
* We have one PythonTextBufferInfo, and hence one AnalysisEntry per ITextBuffer
* We have multiple BufferParsers, each with one or more PythonTextBufferInfos (for distinct buffers)
* Each PythonTextBufferInfo assumes it belongs to only one BufferParser, but this may not be true
