### ISSUE TITLE
Failing to get search paths from virtual environment

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#2926]
Nearly every log we ever see has errors like this:

```
2017-06-13T08:45:01 FAIL_STDLIB
System.InvalidOperationException: Cannot obtain search paths ---> System.InvalidOperationException: Cannot obtain list of paths
The system cannot find the file specified
   at Microsoft.PythonTools.Interpreter.PythonTypeDatabase.<GetUncachedDatabaseSearchPathsAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.PythonTools.Analysis.PyLibAnalyzer.<Prepare>d__46.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.PythonTools.Analysis.PyLibAnalyzer.<Prepare>d__46.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Analysis.PyLibAnalyzer.<RunWorker>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Analysis.PyLibAnalyzer.<Run>d__33.MoveNext() "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\Microsoft.PythonTools.Analyzer.exe" /id MSBuild|backend|path_to.pyproj /version 3.6 /python C:\project\env\Scripts\python.exe /outdir C:\project\env\.ptvs\ /basedb "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\CompletionDB" /log C:\project\env\.ptvs\AnalysisLog.txt /glog "C:\Users\Username\AppData\Local\Python Tools\CompletionDB\15.0-1\AnalysisLog.txt" /wait ""
```

It's not clear why we are failing here, but presumably we're starting the DB analysis too soon and the env is not fully created.

**Comment by zooba** [comment]
To be clear, eventually it ends up succeeding, but we should avoid failing the first few times.
