### ISSUE TITLE
XAML has no Intellisense

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#2943]
Analysis of XAML files broke. Need to fix it

**Comment by zooba** [comment]
Keeping this open - analysis and references are now fixed, but the XAML editor does not display Intellisense.

Once we have an integrated build with this fix, we need to give it to their team (I have the contact) to help us figure out why their editor doesn't like our projects any more.

**Comment by zooba** [comment]
Assigning to myself as I'm working with the XAML team on this. I don't yet have any actual work to do myself.

**Comment by huguesv** [comment]
Is this also the reason that the XAML designer doesn't work at all? It just says "Invalid Markup" even though it's valid.

**Comment by huguesv** [comment]
Keeping on the short list for 15.6. - if we have a fix, we'll take it.

**Comment by zooba** [comment]
The fix probably has to come from the XAML designer team, and I doubt it’ll make 15.6. I’d just push it out and we’ll ping them again.

**Comment by jmartens** [comment]
It seems this can be leveraged, at least in my case, by re-adding the PresentationFrameWork reference. after adding a valid PresentationFrame reference the UI is displayed immediately and IntelliSense seems to work as well.

This changes the following in my original Visual Studio Python project:

```
    <Reference Include="PresentationFramework, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35">
      <Name>PresentationFramework</Name>
      <Private>False</Private>
    </Reference>
```
to
```
    <Reference Include="PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35">
      <Name>PresentationFramework</Name>
      <AssemblyName>PresentationFramework.dll</AssemblyName>
      <HintPath>C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\PresentationFramework.dll</HintPath>
    </Reference>
```

I also checked what I need for my project (and for a minimal default project) to work and it requires at least valid PresentationCore, PresentationFrameWork and WindowsBase references. But for a default project the only reference I need to explicitly add is PresentationFramework.

See the PR #3738 I just raised.

**Comment by zooba** [comment]
Thanks! I tried this myself (just now, at your suggestion), and while it resolves the errors shown in the XAML editor, I'm not getting any completions when I type `<` (or Ctrl+Space, etc.). Were you getting those? (It might be because I'm testing from the experimental hive rather than a proper install - getting one now that I can test.)

Also, what version of Visual Studio are you testing on?

**Comment by jmartens** [comment]
I am not sure if code completion is working, most likely not, but I personally  hardly miss it in XAML. It does complain about syntax errors though.I am using Visual Studio 2017 Community and Enterprise edition. On Feb 13, 2018 20:38, Steve Dower <notifications@github.com> wrote:Thanks! I tried this myself (just now, at your suggestion), and while it resolves the errors shown in the XAML editor, I'm not getting any completions when I type < (or Ctrl+Space, etc.). Were you getting those? (It might be because I'm testing from the experimental hive rather than a proper install - getting one now that I can test.)
Also, what version of Visual Studio are you testing on?

**Comment by huguesv** [comment]
I'm also not getting completions on an installed build. It's still much better than before though :)

I was able to use the toolbox and designer to add controls. I did run into an error while trying to add an event handler when double-clicking the event handler in the properties window.
```
System.NullReferenceException
Object reference not set to an instance of an object.
   at Microsoft.PythonTools.Project.PythonNonCodeFileNode.XamlCallback.GetInsertionPoint(String className)
   at Microsoft.PythonTools.XamlDesignerSupport.WpfEventBindingProvider.CreateMethod(EventDescription eventDescription, String methodName, String initialStatements)
   at Microsoft.VisualStudio.DesignTools.XamlDesignerHost.Code.DesignerContextCodeContext.Microsoft.VisualStudio.DesignTools.DesignerContract.IHostCodeContext.CreateMethod(IHostCodeEvent codeEvent, String methodName, String initialStatements)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.RemoteHostCodeContext.<>c__DisplayClass13_0.<Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.IRemoteHostCodeContext.CreateMethod>b__0()
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.ThreadMarshaler.<>c__DisplayClass49_0`1.<MarshalIn>b__0()
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.STAMarshaler.Call.InvokeWorker()

System.NullReferenceException
Object reference not set to an instance of an object.

Server stack trace: 
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.STAMarshaler.WaitForCompletion(NestedCallContext nestedCallContext, BlockingCall call, WaitHandle timeoutSignal)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.STAMarshaler.MarshalInSynchronous(Action action, Int32 targetApartmentId, CancellationToken cancelToken, CallModality callModality, String methodName, String filePath, Int32 lineNumber)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.STAMarshaler.MarshalIn(Action action, Int32 targetApartmentId, CancellationToken cancelToken, CallSynchronizationMode syncMode, CallModality callModality, String methodName, String filePath, Int32 lineNumber)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.ThreadMarshaler.MarshalIn(IRemoteObject targetObject, Action action, CallSynchronizationMode syncMode, CallModality callModality, ApartmentState apartmentState, String memberName, String filePath, Int32 lineNumber)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.ThreadMarshaler.MarshalIn[TResult](IRemoteObject targetObject, Func`1 func, CallModality callModality, ApartmentState apartmentState, String memberName, String filePath, Int32 lineNumber)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.RemoteHostCodeContext.Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.IRemoteHostCodeContext.CreateMethod(String eventName, RemoteHostParameter[] parameters, String returnType, String methodName, String initialStatements)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.IRemoteHostCodeContext.CreateMethod(String eventName, RemoteHostParameter[] parameters, String returnType, String methodName, String initialStatements)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.LocalHostCodeContext.<>c__DisplayClass14_0.<Microsoft.VisualStudio.DesignTools.DesignerContract.IHostCodeContext.CreateMethod>b__0(IRemoteHostCodeContext cxt)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.ThreadMarshaler.<>c__DisplayClass33_0`2.<MarshalOut>b__0()
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.STAMarshaler.Call.InvokeWorker()

System.NullReferenceException
Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.STAMarshaler.WaitForCompletion(NestedCallContext nestedCallContext, BlockingCall call, WaitHandle timeoutSignal)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.STAMarshaler.MarshalOutSynchronous(Action action, Int32 targetApartmentId, WaitHandle aborted, WaitHandle timeoutSignal, CancellationToken cancelToken, String methodName, String filePath, Int32 lineNumber)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.STAMarshaler.MarshalOut(Action action, Int32 targetApartmentId, WaitHandle aborted, CancellationToken cancelToken, CallSynchronizationMode syncMode, WaitHandle timeoutSignal, String methodName, String filePath, Int32 lineNumber)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.ThreadMarshaler.MarshalOut[TValue](RemoteHandle`1 targetObject, Action action, CallSynchronizationMode syncMode, ApartmentState apartmentState, String methodName, String filePath, Int32 lineNumber)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.ThreadMarshaler.MarshalOut[TResult,TValue](RemoteHandle`1 targetObject, Func`2 func, CallSynchronizationMode syncMode, ApartmentState apartmentState, String methodName, String filePath, Int32 lineNumber)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.LocalHostCodeContext.Microsoft.VisualStudio.DesignTools.DesignerContract.IHostCodeContext.CreateMethod(IHostCodeEvent codeEvent, String methodName, String initialStatements)
   at Microsoft.VisualStudio.DesignTools.Designer.UI.PropertyInspector.CodeContext.CreateEventHandler(ISourceItemContext item, String typeName, IEvent eventKey, String methodName)
   at Microsoft.VisualStudio.DesignTools.Designer.UI.PropertyInspector.EventHandlerProvider.CreateEventHandler(IEvent eventKey, String methodName)
   at Microsoft.VisualStudio.DesignTools.Designer.UI.PropertyInspector.EventHandlerModel.SetMethodName(String newName)
   at Microsoft.VisualStudio.DesignTools.Designer.UI.PropertyInspector.EventHandlerModel.GenerateAndCommit()
   at Microsoft.VisualStudio.DesignTools.Designer.UI.PropertyInspector.EventHandlerModel.<get_GenerateAndCommitCommand>b__14_1(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.DesignerProcess.RunApplication()
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.DesignerProcess.<>c__DisplayClass3_0.<Main>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

**Comment by zooba** [comment]
Awesome! Stack traces can be fixed :)

@jmartens's PR may not be a 100% fix, but it's definitely goodness, so we should take it.

**Comment by huguesv** [comment]
@zooba has the XAML team been pinged about this recently?

Another report at https://developercommunity.visualstudio.com/content/problem/237335/no-intellisense-in-vs-1570-preview-4-ironpython-wp.html

**Comment by huguesv** [comment]
To get IntelliSense working in the XAML, the project system needs to return mscorlib as a reference. WPF C# does that implicitly even though it doesn't appear in References.

Workaround is for the user to add the reference to mscorlib via Add Reference dialog.

**Comment by huguesv** [comment]
Also reported at https://developercommunity.visualstudio.com/content/problem/283766/wpf-ironpython-markup-error.html

**Comment by zooba** [comment]
Finally closed! 🎉
