### ISSUE TITLE
Unexpected error after closing split view

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2949]
This is with the latest PR https://github.com/Microsoft/PTVS/pull/2945

Open a file with some code in it.
Window->Split
Window->Remove split

Move the mouse around, and you'll get assert/unexpected error.

```
Build: 3.0.1000.00

System.ArgumentException: Failed to get classifier from buffer
   at Microsoft.PythonTools.Intellisense.ReverseExpressionParser..ctor(ITextSnapshot snapshot, ITextBuffer buffer, ITrackingSpan span) in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\ReverseExpressionParser.cs:line 53
   at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.GetApplicableExpression(AnalysisEntry entry, SnapshotPoint point) in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\ProjectAnalyzer.cs:line 2447
   at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.<GetQuickInfoAsync>d__165.MoveNext() in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\ProjectAnalyzer.cs:line 2339
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.WaitForRequest[T](Task`1 request, String requestName, T defaultValue, Int32 timeoutScale) in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\ProjectAnalyzer.cs:line 128
   at Microsoft.PythonTools.Intellisense.IntellisenseController.<>c__DisplayClass18_0.<TextViewMouseHoverWorker>b__0() in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\IntellisenseController.cs:line 127
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.PythonTools.Intellisense.IntellisenseController.<TextViewMouseHoverWorker>d__18.MoveNext() in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\IntellisenseController.cs:line 127
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext() in C:\Projects\huguesv\PTVS\Python\Product\VSCommon\Infrastructure\VSTaskExtensions.cs:line 179
```

**Comment by zooba** [comment]
The problem is that when we split, the `BufferParser` gets given the same buffer again. We don't add it, but we don't refcount it either, so when we close the split it gets removed and shut down.

**Comment by zooba** [comment]
We also disconnect buffers twice when the text view closes, which happens when you close the split (two views, one buffer).
