### ISSUE TITLE
Unexpected error NullReferenceException after creating project

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2954]
This is on latest from master.
I created a new project and got this unhandled exception.
I tried a few more times but it didn't happen again.

[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 3.0.1000.00

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.<TransferFromOldAnalyzer>d__76.MoveNext() in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\ProjectAnalyzer.cs:line 734
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.PythonTools.Project.PythonProjectNode.<ReanalyzeProject>d__138.MoveNext() in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Project\PythonProjectNode.cs:line 1378
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext() in C:\Projects\huguesv\PTVS\Python\Product\VSCommon\Infrastructure\VSTaskExtensions.cs:line 179
```

**Comment by huguesv** [comment]
Okay, it did happen again, and it's `buffers` that's `null`.
```
                if (oldBuffers.TryGetValue(e.Path, out ITextBuffer[] buffers)) {
                    foreach (var b in buffers) {
                        PythonTextBufferInfo.MarkForReplacement(b);
                        e.GetOrCreateBufferParser(_services).AddBuffer(b);
                    }
                }
```
