### ISSUE TITLE
Unable to run a python app

### ISSUE THREAD

**Issue by NowPower** [Microsoft/PTVS#2961]
When I try to run a python file I get the following REPLY:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\Python\Core\ptvsd_launcher.py", line 34, in <module>
    import ptvsd.debugger as vspd
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\Python\Core\ptvsd\debugger.py", line 49, in <module>
    import ptvsd.repl as _vspr
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\Python\Core\ptvsd\repl\__init__.py", line 44, in <module>
    import random
  File "C:\Users\User\Desktop\Γιάννης\python\random.py", line 23
    for i in range(3):
                     ^
SyntaxError: invalid syntax

Internal error detected. Please copy the above traceback and report at
https://go.microsoft.com/fwlink/?LinkId=293415

Press Enter to close. . .

(I was able to fix the SyntaxError but not the other stuff)
Any help would be appreciated.

**Comment by zooba** [comment]
The problem here is that you've named your file `random.py`, which is the same name as a module in the standard library. This means that if any code tries to import `random`, it will actually get your program instead of the standard library module.

The easiest fix is to rename your file. We can also add code to our launcher that will avoid this problem, but ultimately when you accidentally shadow a standard library module you will probably break lots of code, and we can't protect against that.

**Comment by zooba** [comment]
@int19h in case you want to give the sys.path manipulation a go. Not urgent.
