### ISSUE TITLE
Failed to create entry for file (unobserved exception)

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2968]
I was browsing some code (adal for python) and got this.

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
An exception in a task was not observed. See ActivityLog.xml for more details.

System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Failed to create entry for file

   at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.<AnalyzeFileAsync>d__82.MoveNext() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\ProjectAnalyzer.cs:line 868

   --- End of inner exception stack trace ---

   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)

   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)

   at System.Threading.Tasks.Task`1.get_Result()

   at Microsoft.PythonTools.Navigation.PythonLibraryManager.<>c__DisplayClass3_0.<OnNewFile>b__0(Task`1 x) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Navigation\PythonLibraryManager.cs:line 66

   at System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()

   at System.Threading.Tasks.Task.Execute()

   --- End of inner exception stack trace ---

---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Failed to create entry for file

   at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.<AnalyzeFileAsync>d__82.MoveNext() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\ProjectAnalyzer.cs:line 868

   --- End of inner exception stack trace ---

   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)

   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)

   at System.Threading.Tasks.Task`1.get_Result()

   at Microsoft.PythonTools.Navigation.PythonLibraryManager.<>c__DisplayClass3_0.<OnNewFile>b__0(Task`1 x) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Navigation\PythonLibraryManager.cs:line 66

   at System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()

   at System.Threading.Tasks.Task.Execute()

---> (Inner Exception #0) System.InvalidOperationException: Failed to create entry for file

   at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.<AnalyzeFileAsync>d__82.MoveNext() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\ProjectAnalyzer.cs:line 868<---

<---



   at Microsoft.PythonTools.PythonToolsPackage.<>c.<.ctor>b__3_0(Object sender, UnobservedTaskExceptionEventArgs e) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonToolsPackage.cs:line 202

   at System.Threading.Tasks.TaskScheduler.PublishUnobservedTaskException(Object sender, UnobservedTaskExceptionEventArgs ueea)

   at System.Threading.Tasks.TaskExceptionHolder.Finalize()


---------------------------
Abort   Retry   Ignore   
---------------------------
```

So no one handled this:
```
            if (response == null || response.fileId == -1) {
                Interlocked.Decrement(ref _parsePending);
                // TODO: Get SendRequestAsync to return more useful information
                throw new InvalidOperationException("Failed to create entry for file");
            }
```

**Comment by zooba** [comment]
I think I already have a fix for the most common case.

**Comment by zooba** [comment]
Switching this to an enhancement. We shouldn't fail here any more with the fix I just merged, but it would still be nice to simplify this code.
