### ISSUE TITLE
Failed to get classifier from buffer (QuickInfo)

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2971]
I'm on the latest from master.

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Unhandled exception in Microsoft.PythonTools.Intellisense.IntellisenseController.TextViewMouseHover (C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\IntellisenseController.cs:104)

System.ArgumentException: Failed to get classifier from buffer

   at Microsoft.PythonTools.Intellisense.ReverseExpressionParser..ctor(ITextSnapshot snapshot, ITextBuffer buffer, ITrackingSpan span) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\ReverseExpressionParser.cs:line 53

   at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.GetApplicableExpression(AnalysisEntry entry, SnapshotPoint point) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\ProjectAnalyzer.cs:line 2453

   at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.<GetQuickInfoAsync>d__165.MoveNext() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\ProjectAnalyzer.cs:line 2345

--- End of stack trace from......

<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by zooba** [comment]
Again? :(

At this point, we probably just have to defend against the exception and not show a tooltip.

**Comment by zooba** [comment]
In fact, this can only happen now when we don't have a known Python buffer, so may as well just bail out.
