### ISSUE TITLE
Buffer must have a project entry before parsing error

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2992]
This happened shortly after adding an environment to my project.  I'm on the latest from master.

[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 3.0.1000.00

System.InvalidOperationException: buffer must have a project entry before parsing
   at Microsoft.PythonTools.Intellisense.BufferParser.AddBuffer(ITextBuffer textBuffer) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\BufferParser.cs:line 106
   at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.<TransferFromOldAnalyzer>d__76.MoveNext() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\ProjectAnalyzer.cs:line 752
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.PythonTools.Project.PythonProjectNode.<ReanalyzeProject>d__139.MoveNext() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Project\PythonProjectNode.cs:line 1382
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\VSCommon\Infrastructure\VSTaskExtensions.cs:line 179
```

**Comment by zooba** [comment]
There's a fix for this in #2991 - guess I ran into it too

**Comment by huguesv** [comment]
Is it the same as this one (from IntellisenseController):

[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 3.0.1000.00

System.InvalidOperationException: buffer must have a project entry before parsing
   at Microsoft.PythonTools.Intellisense.BufferParser.AddBuffer(ITextBuffer textBuffer) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\BufferParser.cs:line 106
   at Microsoft.PythonTools.Intellisense.IntellisenseController.<ConnectSubjectBufferAsync>d__22.MoveNext() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\IntellisenseController.cs:line 197
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\VSCommon\Infrastructure\VSTaskExtensions.cs:line 179
```

**Comment by huguesv** [comment]
That happened when I did go to definition on a standard library import, without any project open.

**Comment by zooba** [comment]
No - the direct caller (here ConnectSubjectBufferAsync; above, TransferFromOldAnalyzer) is responsible for setting the project entry on the buffer info before adding it to the parser.

**Comment by huguesv** [comment]
ok, I can file separately

**Comment by zooba** [comment]
May as well keep it here now
