### ISSUE TITLE
AttachWithOutputRedirection test asserting from incorrect thread

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#301]
```
Description: The process was terminated due to an unhandled exception.
Exception Info: Microsoft.VisualStudio.TestTools.UnitTesting.AssertFailedException
Stack:
   at Microsoft.VisualStudio.TestTools.UnitTesting.Assert.HandleFailure(System.String, System.String)
   at Microsoft.VisualStudio.TestTools.UnitTesting.Assert.AreEqual[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.__Canon, System.__Canon, System.String, System.Object[])
   at DebuggerTests.DebuggerTests+<>c__DisplayClass96_0.<AttachWithOutputRedirection>b__0(System.Object, Microsoft.PythonTools.Debugger.OutputEventArgs)
   at Microsoft.PythonTools.Debugger.PythonProcess.HandleDebuggerOutput(System.IO.Stream)
   at Microsoft.PythonTools.Debugger.PythonProcess.DebugEventThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by zooba** [comment]
Also, the assert is failing because it expected "stdout" and got "stderr".
