### ISSUE TITLE
Error scraping builtins

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#3023]
Experimental NoDatabaseFactory

I get this assert when I open a Python 2 project.

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Error scraping builtins.

Traceback (most recent call last):

  File "C:\USERS\HUVALO\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_8A7CED95EXP\EXTENSIONS\MICROSOFT CORPORATION\PYTHON\3.0\scrape_module.py", line 927, in <module>

    add_builtin_objects(state)

  File "C:\USERS\HUVALO\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_8A7CED95EXP\EXTENSIONS\MICROSOFT CORPORATION\PYTHON\3.0\scrape_module.py", line 822, in add_builtin_objects

    KNOWN_RESTYPES.update({

NameError: global name 'KNOWN_RESTYPES' is not defined





   at Microsoft.PythonTools.Interpreter.Ast.AstScrapedPythonModule.Imported(IModuleContext context) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Interpreter\Ast\AstScrapedPythonModule.cs:line 141

   at Microsoft.PythonTools.Interpreter.Ast.AstPythonInterpreter.ImportModule(String name) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Interpreter\Ast\AstPythonInterpreter.cs:line 171

   at Microsoft.PythonTools.Analysis.ModuleTable.<>c__DisplayClass7_0.<TryImportAsync>b__0() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\ModuleTable.cs:line 84

   at System.Threading.Tasks.Task`1.InnerInvoke()

   at System.Threading.Tasks.Task.Execute()

   at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)

   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)

   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()

   at System.Threading.ThreadPoolWorkQueue.Dispatch()

   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()


---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by zooba** [comment]
Glad I put that assertion in - makes it much easier to diagnose :)
