### ISSUE TITLE
GetAnalyzer() called on closed project assert

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#3024]
Got this while closing a project. It did not repro a second time.

I had NoDatabaseFactory enabled, not sure if that's relevant.

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
GetAnalyzer() called on closed project    at Microsoft.PythonTools.Project.PythonProjectNode.GetAnalyzer() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Project\PythonProjectNode.cs:line 1111

   at Microsoft.PythonTools.Project.PythonProjectNode.VsPythonProject.get_Analyzer() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Project\PythonProjectNode.cs:line 2756

   at Microsoft.PythonTools.TestAdapter.TestContainerDiscoverer.ProjectInfo.<UpdateTestCasesAsync>d__13.MoveNext() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\TestAdapter\TestContainerDiscoverer.cs:line 234

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.PythonTools.TestAdapter.TestContainerDiscoverer.ProjectInfo.UpdateTestCasesAsync(String path, Boolean notify)

   at Microsoft.PythonTools.TestAdapter.TestContainerDiscoverer.ProjectInfo.<UpdateTestCasesAsync>d__12.MoveNext() in C:\Projects\GitHub\huguesv\P......

<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by zooba** [comment]
Seems like a simple race. We can probably check in the `UpdateTestCasesAsync` function whether the project has been closed.
