### ISSUE TITLE
wfastcgi handler parameter mismatch

### ISSUE THREAD

**Issue by int19h** [Microsoft/PTVS#3033]
The setup is a new Bottle app from our template, and an app service set up according to [the docs](https://docs.microsoft.com/en-us/visualstudio/python/managing-python-on-azure-app-service), using Python 3.6 32-bit. Bottle is installed on the server via Kudu. 

This setup produces the following error message when the site is opened:
```
The page cannot be displayed because an internal server error has occurred.
```

This is the error that I'm getting in wfastcgi.log:
```
StdErr: 
2017-09-14 06:55:10.333137: Error occurred:

Traceback (most recent call last):
  File "D:\home\python362x86\wfastcgi.py", line 847, in main
    result = handler(record.params, response.start)
TypeError: wsgi_app() takes 0 positional arguments but 2 were given
```

This is the relevant code from the app (unmodified from the template):
```py
def wsgi_app():
    """Returns the application to make available through wfastcgi. This is used
    when the site is published to Microsoft Azure."""
    return bottle.default_app()
```

This is web.config, also taken directly from the docs, with only the Python path modified:
```xml
<configuration>
  <appSettings>
    <add key="WSGI_HANDLER" value="app.wsgi_app"/>
    <add key="PYTHONPATH" value="D:\home\site\wwwroot"/>
    <add key="WSGI_LOG" value="D:\home\LogFiles\wfastcgi.log"/>
  </appSettings>
  <system.webServer>
    <handlers>
      <add name="PythonHandler" path="*" verb="*" modules="FastCgiModule" scriptProcessor="D:\home\python362x86\python.exe|D:\home\python362x86\wfastcgi.py" resourceType="Unspecified" requireAccess="Script"/>
    </handlers>
  </system.webServer>
</configuration>
```

And this is the line in wfastcgi.py that triggers the error:
```py
                result = handler(record.params, response.start)
```

The error does look legit given the code above, so our template must be wrong.

**Comment by int19h** [comment]
So the fix was:
```xml
    <add key="WSGI_HANDLER" value="app.wsgi_app()"/>
```
i.e. add `()`. This is probably worth pointing out somewhere in the docs.

Also, is it the intent that it's different for different template (it looks like my original web.config would work for Flask template as is, for example)? Should we change the Bottle template to conform?

**Comment by int19h** [comment]
Also, one correction - I didn't actually copy web.config from the docs. What I did was Add New Item on the project, and then selecting "Azure web.config (FastCGI)" from the list.

**Comment by huguesv** [comment]
@kraigb is working on updating the documentation (there's a discussion on Teams Python channel).

They weren't designed to be all the same, because it didn't matter that much before. We were storing the string in the project itself and auto generating the web.config, so the user didn't really care unless they started moving/renaming things that affected the handler name.

In the case of Django, it's `DjangoWebProject1.wsgi.application` ie it doesn't match the others either.

In addition to documentation, maybe we should add more obvious comments to the project template to indicate exactly what they need to use for the `WSGI_HANDLER` value.

**Comment by kraigb** [comment]
Yes, I'm working on updating the docs so that details for each of the templates are clearly spelled out. There are some short-term updates to https://docs.microsoft.com/en-us/visualstudio/python/publishing-to-azure that describe the web.config for Bottle to address exactly the scenario you describe here.

**Comment by kraigb** [comment]
@int19h Please review the docs on https://docs.microsoft.com/en-us/visualstudio/python/publishing-to-azure, which are updated now for exact details on Bottle, Flask, and Django.

**Comment by int19h** [comment]
Looks good to me. @huguesv, could you take a look as well?

**Comment by huguesv** [comment]
@kraigb this does not match the example project name you give in the paragraph above it, and App should be lowercase:
<add key="WSGI_HANDLER" value="FlaskAzurePublishExample.App"/>

replace with:
<add key="WSGI_HANDLER" value="FlaskExample.app"/>

Everything else looks great

**Comment by kraigb** [comment]
OK, I'll make those tweaks.

**Comment by kraigb** [comment]
The changes are in. Should be able to close now.

**Comment by fax0013** [comment]
Error occurred:

Traceback (most recent call last):
  File "c:\ae\venv\lib\site-packages\wfastcgi.py", line 847, in main
    result = handler(record.params, response.start)
TypeError: module() argument 1 must be str, not dict


StdOut: 

StdErr: 

any help on this error while deploying flask on IIS
