### ISSUE TITLE
Frequent IDE crashes when editing python files

### ISSUE THREAD

**Issue by zjturner** [Microsoft/PTVS#3038]
This happens at random times and on random files.  Can you advise how to collect a useful crash dump?  Unfortunately Visual Studio's crash recovery system kicks in and automatically restarts the IDE for me so I can't attach a debugger.

On the other hand, because of that, maybe you already have my crash dumps somewhere?  If I can provide you with some sort of ID by which you can look up my crashes, that might also help me produce a better bug report.

Thanks!

**Comment by huguesv** [comment]
The simplest thing to check first would be Event Viewer. There may be an Error entry under Windows Logs/Application, with a useful call stack.

**Comment by zjturner** [comment]
Yep, unfortunately the call stack is pretty generic.

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.Collections.Generic.IntrospectiveSortUtilities.ThrowOrIgnoreBadComparer(System.Object)
   at System.Collections.Generic.ArraySortHelper`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Sort(System.__Canon[], Int32, Int32, System.Collections.Generic.IComparer`1<System.__Canon>)
   at System.Array.Sort[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.__Canon[], Int32, Int32, System.Collections.Generic.IComparer`1<System.__Canon>)
   at System.Array.Sort[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.__Canon[], System.Collections.Generic.IComparer`1<System.__Canon>)
   at System.Array.Sort[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.__Canon[], System.Comparison`1<System.__Canon>)
   at Microsoft.PythonTools.PythonAnalysisClassifier+<OnNewAnalysis>d__6.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

But this triggered my memory.  One time I did manage to get a debugger attached (don't remember how) and it reproduced under the debugger.  There, I was able to see that it thought a comparison function was in use somewhere that was inconsistent (e.g. returned different results on same inputs, or something to that effect).

**Comment by huguesv** [comment]
We have fixed a sorting issue very recently, and it was backported to the latest 5.3 update. 
https://github.com/Microsoft/PTVS/issues/2921

**Comment by zjturner** [comment]
That would do it.  I haven't downloaded the latest update yet.  I'll go ahead and close this, and re-open it if I encounter it again using the latest update.  Thanks!
