### ISSUE TITLE
Error while editing

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#305]
VS 2015 RC
PTVS 2.2 CL1480636 (debug)

Python 2.7
I installed boto, then I typed
```
import boto
boto.
```
However when I typed `import boto` and hit enter, I got something from the completion list that wasn't boto, so I had to undo that and type `boto` again.

Activity log:
```
An exception in a task was not observed: System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. --->
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. Parameter name: column must be greater than or equal to 1
 at Microsoft.PythonTools.Parsing.SourceLocation.ValidateLocation(Int32 index, Int32 line, Int32 column)
 at Microsoft.PythonTools.Parsing.SourceLocation..ctor(Int32 index, Int32 line, Int32 column)
 at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.TranslateIndex(Int32 index, ITextSnapshot fromSnapshot, ModuleAnalysis toAnalysisSnapshot)
 at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.GetMissingImports(IServiceProvider serviceProvider, ITextSnapshot snapshot, ITrackingSpan span)
 at Microsoft.PythonTools.Intellisense.PythonAnalysisExtensions.GetMissingImports(ITextSnapshot snapshot, IServiceProvider serviceProvider, ITrackingSpan span)
 at Microsoft.PythonTools.Intellisense.PythonSuggestedActionsSource.<>c__DisplayClass12_0.<HasSuggestedActionsAsync>b__0()
 at System.Threading.Tasks.Task`1.InnerInvoke()
 at System.Threading.Tasks.Task.Execute()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
 at Microsoft.PythonTools.Intellisense.PythonSuggestedActionsSource.<HasSuggestedActionsAsync>d__12.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbBroker.<>c__DisplayClass0.<<HasSuggestedActionsAsync>b__3>d__0.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbBroker.<HasSuggestedActionsAsync>d__2.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbController.<RefreshSessionAsync>d__1.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbController.<FullRefreshSessionAsync>d__1.MoveNext()
 --- End of inner exception stack trace
 --- ---> (Inner Exception #0) System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. Parameter name: column must be greater than or equal to 1
 at Microsoft.PythonTools.Parsing.SourceLocation.ValidateLocation(Int32 index, Int32 line, Int32 column)
 at Microsoft.PythonTools.Parsing.SourceLocation..ctor(Int32 index, Int32 line, Int32 column)
 at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.TranslateIndex(Int32 index, ITextSnapshot fromSnapshot, ModuleAnalysis toAnalysisSnapshot)
 at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.GetMissingImports(IServiceProvider serviceProvider, ITextSnapshot snapshot, ITrackingSpan span)
 at Microsoft.PythonTools.Intellisense.PythonAnalysisExtensions.GetMissingImports(ITextSnapshot snapshot, IServiceProvider serviceProvider, ITrackingSpan span)
 at Microsoft.PythonTools.Intellisense.PythonSuggestedActionsSource.<>c__DisplayClass12_0.<HasSuggestedActionsAsync>b__0()
 at System.Threading.Tasks.Task`1.InnerInvoke()
 at System.Threading.Tasks.Task.Execute()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
 at Microsoft.PythonTools.Intellisense.PythonSuggestedActionsSource.<HasSuggestedActionsAsync>d__12.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbBroker.<>c__DisplayClass0.<<HasSuggestedActionsAsync>b__3>d__0.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbBroker.<HasSuggestedActionsAsync>d__2.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbController.<RefreshSessionAsync>d__1.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbController.<FullRefreshSessionAsync>d__1.MoveNext()<---    UnobservedTaskException 2015/06/02 18:24:37.308 
599 ERROR System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. Parameter name: column must be greater than or equal to 1
 at Microsoft.PythonTools.Parsing.SourceLocation.ValidateLocation(Int32 index, Int32 line, Int32 column)
 at Microsoft.PythonTools.Parsing.SourceLocation..ctor(Int32 index, Int32 line, Int32 column)
 at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.TranslateIndex(Int32 index, ITextSnapshot fromSnapshot, ModuleAnalysis toAnalysisSnapshot)
 at Microsoft.PythonTools.Intellisense.NormalCompletionAnalysis.GetCompletions(IGlyphService glyphService)
 at Microsoft.PythonTools.Intellisense.CompletionSource.AugmentCompletionSession(ICompletionSession session, IList`1 completionSets)
 at Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionSession.Start()
 at Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionBroker.TriggerCompletion(ITextView textView)
 at Microsoft.PythonTools.Intellisense.IntellisenseController.TriggerCompletionSession(Boolean completeWord, Boolean commitByDefault)
 at Microsoft.PythonTools.Intellisense.IntellisenseController.HandleChar(Char ch)
 at Microsoft.PythonTools.Intellisense.IntellisenseController.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
 at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
 at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
 at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.SendCommand(Guid cmdGroup, UInt32 cmdID, Object inParam)
 at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.TextInput(TextCompositionEventArgs args)
 at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c__DisplayClass0.<DispatchTextInputEvents>b__1(KeyProcessor p, TextCompositionEventArgs args)
 at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c__DisplayClass26`1.<Dispatch>b__27()
 at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call) 
```

**Comment by huguesv** [comment]
FYI: Still getting similar exceptions with build CL1481388 (which is supposed to include the commit above).  Happens when I hit '.'.  I haven't seen it triggered by the lightbulb, which is what this morning's call stack showed.
```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. Parameter name: column must be greater than or equal to 1 at Microsoft.PythonTools.Parsing.SourceLocation.ValidateLocation(Int32 index, Int32 line, Int32 column) at Microsoft.PythonTools.Parsing.SourceLocation..ctor(Int32 index, Int32 line, Int32 column) 
at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.TranslateIndex(Int32 index, ITextSnapshot fromSnapshot, ModuleAnalysis toAnalysisSnapshot) 
at Microsoft.PythonTools.Intellisense.NormalCompletionAnalysis.GetCompletions(IGlyphService glyphService) at Microsoft.PythonTools.Intellisense.CompletionSource.AugmentCompletionSession(ICompletionSession session, IList`1 completionSets) 
at Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionSession.Start() 
at Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionBroker.TriggerCompletion(ITextView textView) 
at Microsoft.PythonTools.Intellisense.IntellisenseController.TriggerCompletionSession(Boolean completeWord, Boolean commitByDefault) 
at Microsoft.PythonTools.Intellisense.IntellisenseController.HandleChar(Char ch) 
at Microsoft.PythonTools.Intellisense.IntellisenseController.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) 
at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) 
at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) 
at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.SendCommand(Guid cmdGroup, UInt32 cmdID, Object inParam) 
at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.TextInput(TextCompositionEventArgs args) 
at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c__DisplayClass0.<DispatchTextInputEvents>b__1(KeyProcessor p, TextCompositionEventArgs args) 
at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c__DisplayClass26`1.<Dispatch>b__27() at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)
```

**Comment by huguesv** [comment]
I think this is fixed.  I can't repro on CL1482026_VS2015RC.  I'll reopen if I ever see it again.
