### ISSUE TITLE
Frequently getting Abort/Retry/Fail dialogs

### ISSUE THREAD

**Issue by MichaelGoulding** [Microsoft/PTVS#3063]
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Hash code changed when merging AnalysisValues

   at Microsoft.PythonTools.Analysis.AnalysisSetDetails.AnalysisHashSet.AddOne(Bucket[] buckets, AnalysisValue key, Int32 hc) in E:\A\_work\2\s\Python\Product\Analysis\AnalysisHashSet.cs:line 366

   at Microsoft.PythonTools.Analysis.AnalysisSetDetails.AnalysisHashSet.Add(Bucket[] buckets, AnalysisValue key) in E:\A\_work\2\s\Python\Product\Analysis\AnalysisHashSet.cs:line 323

   at Microsoft.PythonTools.Analysis.AnalysisSetDetails.AnalysisHashSet.AddOne(AnalysisValue key) in E:\A\_work\2\s\Python\Product\Analysis\AnalysisHashSet.cs:line 255

   at Microsoft.PythonTools.Analysis.AnalysisSetDetails.AnalysisHashSet.Add(AnalysisValue item, Boolean& wasChanged, Boolean canMutate) in E:\A\_work\2\s\Python\Product\Analysis\AnalysisHashSet.cs:line 133

   at Microsoft.PythonTools.Analysis.Analyzer.TypedDependencyInfo.AddType(AnalysisValue ns) in E:\A\_work\2\s\Python\Product\Analysis\Analyzer\DependencyInfo.cs:line 144

   at Microsoft.PythonTools.Analysis.TypedDef`1.AddTypes(IVersioned projectEntry, IAnalysisSet newTypes, Boolean enqueue, IProjectEntry declaringScope) in E:\A\_work\2\s\Python\Product\Analysis\VariableDef.cs:line 300

   at Microsoft.PythonTools.Analysis.Analyzer.FunctionScope.UpdateParameters(FunctionAnalysisUnit unit, ArgumentSet others, Boolean enqueue, FunctionScope scopeWithDefaultParameters) in E:\A\_work\2\s\Python\Product\Analysis\Analyzer\FunctionScope.cs:line 101

   at Microsoft.PythonTools.Analysis.Analyzer.CalledFunctionAnalysisUnit.UpdateParameters(ArgumentSet callArgs, Boolean enqueue) in E:\A\_work\2\s\Python\Product\Analysis\Analyzer\FunctionAnalysisUnit.cs:line 226

   at Microsoft.PythonTools.Analysis.Values.FunctionInfo.Call(Node node, AnalysisUnit unit, IAnalysisSet[] args, NameExpression[] keywordArgNames) in E:\A\_work\2\s\Python\Product\Analysis\Values\FunctionInfo.cs:line 135

   at Microsoft.PythonTools.Analysis.Values.BoundMethodInfo.Call(Node node, AnalysisUnit unit, IAnalysisSet[] args, NameExpression[] keywordArgNames) in E:\A\_work\2\s\Python\Product\Analysis\Values\BoundMethodInfo.cs:line 40

   at Microsoft.PythonTools.Analysis.Analyzer.ExpressionEvaluator.EvaluateCall(ExpressionEvaluator ee, Node node) in E:\A\_work\2\s\Python\Product\Analysis\Analyzer\ExpressionEvaluator.cs:line 338

   at Microsoft.PythonTools.Analysis.Analyzer.ExpressionEvaluator.EvaluateWorker(Node node) in E:\A\_work\2\s\Python\Product\Analysis\Analyzer\ExpressionEvaluator.cs:line 170

   at Microsoft.PythonTools.Analysis.Analyzer.ExpressionEvaluator.Evaluate(Expression node) in E:\A\_work\2\s\Python\Product\Analysis\Analyzer\ExpressionEvaluator.cs:line 54

   at Microsoft.PythonTools.Analysis.Analyzer.ExpressionEvaluator.EvaluateParenthesis(ExpressionEvaluator ee, Node node) in E:\A\_work\2\s\Python\Product\Analysis\Analyzer\ExpressionEvaluator.cs:line 224

   at Microsoft.PythonTools.Analysis.Analyzer.ExpressionEvaluator.EvaluateWorker(Node node) in E:\A\_work\2\s\Python\Product\Analysis\Analyzer\ExpressionEvaluator.cs:line 170

   at Microsoft.PythonTools.Analysis.Analyzer.ExpressionEvaluator.Evaluate(Expression node) in E:\A\_work\2\s\Python\Product\Analysis\Analyzer\ExpressionEvaluator.cs:line 54

   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(IfStatement node) in E:\A\_work\2\s\Python\Product\Analysis\Analyzer\DDG.cs:line 374

   at Microsoft.PythonTools.Parsing.Ast.IfStatement.Walk(PythonWalker walker) in E:\A\_work\2\s\Python\Product\Analysis\Parsing\Ast\IfStatement.cs:line 49

   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(SuiteStatement node) in E:\A\_work\2\s\Python\Product\Analysis\Analyzer\DDG.cs:line 515

   at Microsoft.PythonTools.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker) in E:\A\_work\2\s\Python\Product\Analysis\Parsing\Ast\SuiteStatement.cs:line 34

   at Microsoft.PythonTools.Analysis.Analyzer.FunctionAnalysisUnit.AnalyzeWorker(DDG ddg, CancellationToken cancel) in E:\A\_work\2\s\Python\Product\Analysis\Analyzer\FunctionAnalysisUnit.cs:line 85

   at Microsoft.PythonTools.Analysis.AnalysisUnit.Analyze(DDG ddg, CancellationToken cancel) in E:\A\_work\2\s\Python\Product\Analysis\AnalysisUnit.cs:line 148

   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Analyze(Deque`1 queue, CancellationToken cancel, Action`1 reportQueueSize, Int32 reportQueueInterval) in E:\A\_work\2\s\Python\Product\Analysis\Analyzer\DDG.cs:line 75

   at Microsoft.PythonTools.Analysis.PythonAnalyzer.AnalyzeQueuedEntries(CancellationToken cancel) in E:\A\_work\2\s\Python\Product\Analysis\PythonAnalyzer.cs:line 1010

   at Microsoft.PythonTools.Intellisense.AnalysisQueue.GroupAnalysis.Analyze(CancellationToken cancel) in E:\A\_work\2\s\Python\Product\Analyzer\Intellisense\AnalysisQueue.cs:line 256

   at Microsoft.PythonTools.Intellisense.AnalysisQueue.Worker(Object threadStarted) in E:\A\_work\2\s\Python\Product\Analyzer\Intellisense\AnalysisQueue.cs:line 202

   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Threading.ThreadHelper.ThreadStart(Object obj)

---------------------------
Abort   Retry   Ignore   
---------------------------

**Comment by zooba** [comment]
Did you build this yourself? Or did we release a debug build by accident... can you attach your Tools/Python/Diagnostic Info output?

This error pops up occasionally for some particular code constructs. However, it's only valuable if we can debug the live code when it is raised. If you can share the Python code that is causing this, that'd be great. Otherwise we can't fix anything based solely on this report.

**Comment by zooba** [comment]
Confirmed this is the issue we know about already, and that the debug build was never publicly released.
