### ISSUE TITLE
An unexpected error occured

### ISSUE THREAD

**Issue by westfielddave** [Microsoft/PTVS#3064]
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 3.0.17240.1

System.ArgumentNullException: Value cannot be null.
Parameter name: obj
   at Microsoft.Internal.VisualStudio.PlatformUI.Utilities.GetObjectData(IVsUIObject obj)
   at Microsoft.VisualStudio.PlatformUI.StatusBarService.GetImageListFromMonikers(IEnumerable`1 monikerList)
   at Microsoft.VisualStudio.PlatformUI.StatusBarService.GetBuiltInAnimation(StatusBarAnimationIndex statusBarAnimationIndex)
   at Microsoft.VisualStudio.PlatformUI.StatusBarService.StartAnimation(Object animationInfoKey, Boolean isBuiltInAnimation)
   at Microsoft.VisualStudio.PlatformUI.StatusBarService.Animation(Int32 fOnOff, Object& pvIcon)
   at Microsoft.PythonTools.Project.PythonProjectNode.<ReanalyzeProject>d__138.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
```

**Comment by zooba** [comment]
I suspect there's an underlying issue here, since this is outside of our direct control, but it is something we can safely detect and suppress.

**Comment by huguesv** [comment]
Filed a bug for the shell team so they can investigate.
https://devdiv.visualstudio.com/DevDiv/_queries?id=504329

Submitting a PR to suppress the exception.
