### ISSUE TITLE
System.ArgumentNullException: Value cannot be null.

### ISSUE THREAD

**Issue by westfielddave** [Microsoft/PTVS#3101]
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[V] Show details  [Close]

[Expanded Information]
```
Build: 3.0.17240.1

System.ArgumentNullException: Value cannot be null.
Parameter name: obj
   at Microsoft.Internal.VisualStudio.PlatformUI.Utilities.GetObjectData(IVsUIObject obj)
   at Microsoft.VisualStudio.PlatformUI.StatusBarService.GetImageListFromMonikers(IEnumerable`1 monikerList)
   at Microsoft.VisualStudio.PlatformUI.StatusBarService.GetBuiltInAnimation(StatusBarAnimationIndex statusBarAnimationIndex)
   at Microsoft.VisualStudio.PlatformUI.StatusBarService.StartAnimation(Object animationInfoKey, Boolean isBuiltInAnimation)
   at Microsoft.VisualStudio.PlatformUI.StatusBarService.Animation(Int32 fOnOff, Object& pvIcon)
   at Microsoft.PythonTools.Project.PythonProjectNode.<ReanalyzeProject>d__138.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
```

**Comment by zooba** [comment]
Thanks. This is the same as #3064, so we'll track the issue there.
