### ISSUE TITLE
Editor randomly gives NullReferenceException

### ISSUE THREAD

**Issue by mehrdadn** [Microsoft/PTVS#3110]
I get errors like the following every so often when in a project.
I'm not sure how exactly to reproduce it.
I'm running Visual Studio 15.3.2 with its Python support being version 3.0.17208.1.

	System.NullReferenceException: Object reference not set to an instance of an object.
	   at Microsoft.VisualStudioTools.Infrastructure.TaskExtensions.WaitAndUnwrapExceptions[T](Task`1 task, Dispatcher dispatcher)
	   at Microsoft.PythonTools.Language.TextViewFilter.GetDataTipText(TextSpan[] pSpan, String& pbstrText)
	   at Microsoft.VisualStudio.Editor.Implementation.ShimQuickInfoSource.TryGetQuickInfoFromFilter(IQuickInfoSession session, TextSpan[] dataBufferTextSpan, String& tipText)
	   at Microsoft.VisualStudio.Editor.Implementation.ShimQuickInfoSource.AugmentQuickInfoSession(IQuickInfoSession session, IList`1 qiContent, ITrackingSpan& applicableToSpan)
	   at Microsoft.VisualStudio.Language.Intellisense.Implementation.QuickInfoSession.Recalculate()
	   at Microsoft.VisualStudio.Language.Intellisense.Implementation.QuickInfoSession.Start()
	   at Microsoft.VisualStudio.Language.Intellisense.Implementation.DefaultQuickInfoController.OnTextView_MouseHover(Object sender, MouseHoverEventArgs e)
	   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.RaiseHoverEvents()
	--- End of stack trace from previous location where exception was thrown ---
	   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by zooba** [comment]
Thanks for the report! We've fixed this issue already and you'll see it when 15.4 becomes available (or you can get it now from https://visualstudio.com/vs/preview )

**Comment by mehrdadn** [comment]
Oh I see, thanks! Would you have an estimate on when it might become available?

**Comment by zooba** [comment]
I have an exact date, but I can't give it out... won't be long :)

**Comment by mehrdadn** [comment]
Haha aw okay thanks!
