### ISSUE TITLE
Visual Studio failed to load cursor from the stream?

### ISSUE THREAD

**Issue by mehrdadn** [Microsoft/PTVS#3112]
I sometimes get the following error in Visual Studio 15.3.2 (Python support version 3.0.17208.1).
I've only seen it occur when debugging Python.
Unfortunately this is as much of the stack trace as I could see when debugging with another instance of Visual Studio -- I'm not sure if there was more to it.

	at System.Windows.Input.Cursor.LoadFromStream(Stream cursorStream)
	at System.Windows.Input.Cursor..ctor(Stream cursorStream, Boolean scaleWithDpi)
	at System.Windows.Input.Cursor..ctor(Stream cursorStream)
	at System.Windows.Controls.GridViewColumnHeader.GetCursor(Int32 cursorID)
	at System.Windows.Controls.GridViewColumnHeader.get_SplitCursor()
	at System.Windows.Controls.GridViewColumnHeader.HookupGripperEvents()
	at System.Windows.Controls.GridViewColumnHeader.OnApplyTemplate()
	at System.Windows.FrameworkElement.ApplyTemplate()
	at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
	at System.Windows.UIElement.Measure(Size availableSize)
	at System.Windows.Controls.GridViewHeaderRowPresenter.MeasureOverride(Size constraint)
	at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
	at System.Windows.UIElement.Measure(Size availableSize)
	at MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element, Size constraint)
	at System.Windows.Controls.ScrollContentPresenter.MeasureOverride(Size constraint)
	at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
	at System.Windows.UIElement.Measure(Size availableSize)
	at System.Windows.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV)
	at System.Windows.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged)
	at System.Windows.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV)
	at System.Windows.Controls.Grid.MeasureOverride(Size constraint)
	at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
	at System.Windows.UIElement.Measure(Size availableSize)
	at System.Windows.Controls.ScrollViewer.MeasureOverride(Size constraint)
	at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
	at System.Windows.UIElement.Measure(Size availableSize)
	at System.Windows.Controls.DockPanel.MeasureOverride(Size constraint)
	at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
	at System.Windows.UIElement.Measure(Size availableSize)
	at System.Windows.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV)
	at System.Windows.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged)
	at System.Windows.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV)
	at System.Windows.Controls.Grid.MeasureOverride(Size constraint)
	at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
	at System.Windows.UIElement.Measure(Size availableSize)
	at System.Windows.Controls.ScrollViewer.MeasureOverride(Size constraint)
	at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
	at System.Windows.UIElement.Measure(Size availableSize)
	at System.Windows.Controls.Border.MeasureOverride(Size constraint)
	at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
	at System.Windows.UIElement.Measure(Size availableSize)
	at System.Windows.Controls.Control.MeasureOverride(Size constraint)
	at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
	at System.Windows.UIElement.Measure(Size availableSize)
	at System.Windows.Controls.Grid.MeasureOverride(Size constraint)
	at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
	at System.Windows.UIElement.Measure(Size availableSize)
	at MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element, Size constraint)
	at System.Windows.Controls.ContentPresenter.MeasureOverride(Size constraint)
	at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
	at System.Windows.UIElement.Measure(Size availableSize)
	at System.Windows.Controls.Border.MeasureOverride(Size constraint)
	at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
	at System.Windows.UIElement.Measure(Size availableSize)
	at System.Windows.Controls.Control.MeasureOverride(Size constraint)
	at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
	at System.Windows.UIElement.Measure(Size availableSize)
	at MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element, Size constraint)
	at System.Windows.Controls.ContentPresenter.MeasureOverride(Size constraint)
	at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
	at System.Windows.UIElement.Measure(Size availableSize)
	at System.Windows.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV)
	at System.Windows.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged)
	at System.Windows.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV)
	at System.Windows.Controls.Grid.MeasureOverride(Size constraint)
	at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
	at System.Windows.UIElement.Measure(Size availableSize)
	at MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element, Size constraint)
	at System.Windows.Controls.ContentPresenter.MeasureOverride(Size constraint)
	at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
	at System.Windows.UIElement.Measure(Size availableSize)
	at System.Windows.ContextLayoutManager.UpdateLayout()
	at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
	at System.Windows.Media.MediaContext.InvokeOnRenderCallback.DoWork()
	at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
	at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
	at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
	at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	at System.Windows.Threading.DispatcherOperation.InvokeImpl()
	at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
	at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
	at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
	at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
	at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
	at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
	at System.Windows.Threading.DispatcherOperation.Invoke()
	at System.Windows.Threading.Dispatcher.ProcessQueue()
	at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
	at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
	at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

**Comment by huguesv** [comment]
Hi, could you clarify what the symptom is? Are you seeing a message box appear? What happens after that?

**Comment by mehrdadn** [comment]
I just get the standard crash error dialog in Windows (Close vs. Debug). If I press Close, it pops up an identical box a second time (I'm not sure why). If I press Debug then I can open it with another instance of Visual Studio in which case I see the error you see above when I click View Details. There wasn't really anything else to add unfortunately, that's all I see.

**Comment by zooba** [comment]
@mehrdadn - looking at the range of issues you're running into, I think it might be worth your time checking for a graphics driver update and running a Repair of Visual Studio.

None of these issues are caused by bugs in our Python support, and they're also unlikely to be bugs that occur in a good install - invalid file streams typically only occur because the file is corrupt, and they are not "expected" in any other sense.

If you are sending error reports to Microsoft or using the Help/Report a Problem feature, the correct teams already have enough information to investigate, and if you do the latter then they can also provide suggestions that may help you out. But since these are outside the scope of what we are responsible for, there's no useful assistance we can provide.
