### ISSUE TITLE
Visual Studio "out of memory" when drawing group box?

### ISSUE THREAD

**Issue by mehrdadn** [Microsoft/PTVS#3117]
I randomly got this error when on the "Debug" tab in a Python project's properties page (Visual Studio 15.3.2, Python support version 3.0.17208.1).
I'm not sure if it's actually Python-related or not.
These are the only exception details I can see (which I observed by debugging with another instance of Visual Studio).

Despite the error message, I'm not running out of _memory_ (I have 5 GB free) but I can see **the GDI handle count is at 10,000**. I'm not sure why.

	at System.Drawing.Graphics.FromHdcInternal(IntPtr hdc)
	at System.Drawing.Font.GetHeight()
	at System.Drawing.Font.get_Height()
	at System.Windows.Forms.GroupBoxRenderer.DrawThemedGroupBoxWithText(Graphics g, Rectangle bounds, String groupBoxText, Font font, Color textColor, TextFormatFlags flags, GroupBoxState state)
	at System.Windows.Forms.GroupBoxRenderer.DrawGroupBox(Graphics g, Rectangle bounds, String groupBoxText, Font font, TextFormatFlags flags, GroupBoxState state)
	at System.Windows.Forms.GroupBox.OnPaint(PaintEventArgs e)
	at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
	at System.Windows.Forms.Control.WmPaint(Message& m)
	at System.Windows.Forms.Control.WndProc(Message& m)
	at System.Windows.Forms.GroupBox.WndProc(Message& m)
	at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
	at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
	at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by mehrdadn** [comment]
Same error with another stack trace:

	at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
	at System.Windows.Media.MediaContext.NotifySyncModeStatus(Int32 enabledResult)
	at System.Windows.Media.MediaContext.NotifyChannelMessage()
	at System.Windows.Media.MediaContextNotificationWindow.MessageFilter(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
	at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
	at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

**Comment by zooba** [comment]
Yeah, unfortunately this is a well known issue that has been around for a long time (it bites me all the time). I believe it's a conflict between WPF and some graphics drivers, but I don't recall all the details right now.

The relevant team already knows about it, and it is not caused by Python support.
