### ISSUE TITLE
CompletionTests occasional failures

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#3136]
You'll sometimes see a `TimeoutException: Failed to see entry finish analyzing` when running some of the CompletionTests.

It's because there's an exception thrown on a background thread.

```
Specified argument was out of the range of valid values.
Parameter name: currentPosition
   at Microsoft.VisualStudio.Text.Tracking.TrackPositionBackwardInTime(PointTrackingMode trackingMode, Int32 currentPosition, ITextVersion currentVersion, ITextVersion targetVersion)
   at Microsoft.PythonTools.Intellisense.LocationTracker.TranslateBack(Int32 position) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\LocationTracker.cs:line 104
   at Microsoft.PythonTools.PythonAnalysisClassifier.GetClassificationSpans(SnapshotSpan span) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\PythonAnalysisClassifier.cs:line 140
   at Microsoft.VisualStudioTools.MockVsTests.MockClassifierAggregatorService.AggregatedClassifier.Subclassification_Changed(Object sender, ClassificationChangedEventArgs e) in C:\Projects\GitHub\huguesv\PTVS\Common\Tests\MockVsTests\MockClassifierAggregatorService.cs:line 57
   at Microsoft.PythonTools.PythonAnalysisClassifier.OnNewClassifications(ITextSnapshot snapshot) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\PythonAnalysisClassifier.cs:line 94
   at Microsoft.PythonTools.PythonAnalysisClassifier.<OnNewAnalysisAsync>d__5.MoveNext() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\PythonAnalysisClassifier.cs:line 88
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\VSCommon\Infrastructure\VSTaskExtensions.cs:line 179
```

**Comment by zooba** [comment]
🙌 You found the problem!
