### ISSUE TITLE
Error scraping builtins

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#3170]
I'm getting this assert sometimes when running UI tests.
```
Error scraping builtins
"C:\Projects\GitHub\huguesv\PTVS\Python\TestResults\Deploy_huvalo 2017-10-17 16_02_29\Out\Temp\venv\Scripts\python.exe" -B -E "C:\USERS\HUVALO\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_D3C430C9EXP\EXTENSIONS\MICROSOFT CORPORATION\PYTHON\3.0\scrape_module.py"
Fatal Python error: Py_Initialize: can't initialize sys standard streams
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python36-32\\lib\locale.py", line 16, in <module>
    import re
  File "C:\Program Files (x86)\Python36-32\\lib\re.py", line 122, in <module>
    import enum
  File "C:\Program Files (x86)\Python36-32\\lib\enum.py", line 2, in <module>
    from types import MappingProxyType, DynamicClassAttribute
  File "C:\Program Files (x86)\Python36-32\\lib\types.py", line 22
    async def _c(): pass
            ^
SyntaxError: invalid syntax

   at Microsoft.PythonTools.Interpreter.Ast.AstScrapedPythonModule.Imported(IModuleContext context) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Interpreter\Ast\AstScrapedPythonModule.cs:line 164
   at Microsoft.PythonTools.Interpreter.Ast.AstPythonInterpreter.ImportModule(String name) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Interpreter\Ast\AstPythonInterpreter.cs:line 178
   at Microsoft.PythonTools.Analysis.ModuleTable.<>c__DisplayClass7_0.<TryImportAsync>b__0() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\ModuleTable.cs:line 84
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by zooba** [comment]
This looks like an issue with the virtual environment - can you find it and verify that it actually works? It shouldn't be complaining about `async def` like that if it's really Python 3.6.

**Comment by huguesv** [comment]
It's probably due to my broken virtualenv tests then. I'll reopen if that happens with a good environment.
