### ISSUE TITLE
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

### ISSUE THREAD

**Issue by denfromufa** [Microsoft/PTVS#3176]
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[V] Show details  [Close]

[Expanded Information]
```
Build: 3.0.17240.1

Microsoft.PythonTools.MissingInterpreterException: The environment "Global|VisualStudio|3.5.3-64" appears to be incorrectly configured or missing. You may need to install it or re-create a virtual environment.
   at Microsoft.PythonTools.Project.PythonProjectNode.GetInterpreterFactoryOrThrow()
   at Microsoft.PythonTools.Project.PythonProjectNode.GetLaunchConfigurationOrThrow()
   at Microsoft.PythonTools.Project.DefaultLauncherProvider.CreateLauncher(IPythonProject project)
   at Microsoft.PythonTools.PythonToolsPackage.<>c__DisplayClass8_0.<GetLauncher>b__2()
   at Microsoft.VisualStudioTools.UIThread.Invoke[T](Func`1 func)
   at Microsoft.PythonTools.PythonToolsPackage.GetLauncher(IServiceProvider serviceProvider, IPythonProject project)
   at Microsoft.PythonTools.PythonToolsPackage.LaunchFile(IServiceProvider provider, String filename, Boolean debug, Boolean saveDirtyFiles)
   at Microsoft.PythonTools.Language.EditFilter.ExecWorker(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.PythonTools.Language.EditFilter.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
```

**Comment by zooba** [comment]
This appears to be a custom environment - have you moved or removed it? Can you check the configuration?

Either way, we should be handling the error here and displaying a better message.

**Comment by huguesv** [comment]
I was able to repro by making the ExecutablePath point to a file that doesn't exist.
Start Debugging (F5) handles it properly by showing a standard error message box, but right-click Start with Debugging doesn't (assert + unexpected error).
I'll change it to match the F5 behavior.
