### ISSUE TITLE
GetTypeFromValue() doesn't handle AstPythonBoundMethod type

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#3211]
Just got that assert:
`Debug.Fail("Unhandled type() value: " + value.GetType().FullName);`

**Comment by huguesv** [comment]
```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Unhandled type() value: Microsoft.PythonTools.Interpreter.Ast.AstPythonBoundMethod



   at Microsoft.PythonTools.Interpreter.Ast.NameLookupContext.GetTypeFromValue(IMember value) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Interpreter\Ast\NameLookupContext.cs:line 412

   at Microsoft.PythonTools.Interpreter.Ast.NameLookupContext.GetValueFromCallable(CallExpression expr, LookupOptions options) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Interpreter\Ast\NameLookupContext.cs:line 325

   at Microsoft.PythonTools.Interpreter.Ast.NameLookupContext.GetValueFromExpression(Expression expr, LookupOptions options) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Interpreter\Ast\NameLookupContext.cs:line 175

   at Microsoft.PythonTools.Interpreter.Ast.NameLookupContext.GetValueFromExpression(Expression expr) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Interpreter\Ast\NameLookupContext.cs:line 163

   at Microsoft.PythonTools.Interpreter.Ast.AstAnalysisWalker.W......

<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by zooba** [comment]
That might be the shortest time from report to PR ever :)
