### ISSUE TITLE
'Mismatched line number' assert while editing

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#3243]
Important to follow these exact steps:
- Create new project, python application
- Place cursor at the beginning of document and paste the code below
- Place cursor at the beginning of document
- Wait about 10 secs and press enter
- If it doesn't repro, try pressing backspace, if that doesn't do it, then start all over

Note: Sometimes I hear the assert dialog sound, but don't see the dialog, which means I can't dismiss it. VS is frozen, which is extra annoying.

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Mismatched line number



   at Microsoft.PythonTools.TrackingTokenInfo.ToSnapshotSpan(ITextSnapshot snapshot) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\TokenCache.cs:line 150

   at Microsoft.PythonTools.PythonClassifier.ClassifyToken(SnapshotSpan span, TrackingTokenInfo token) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\PythonClassifier.cs:line 140

   at Microsoft.PythonTools.PythonClassifier.<>c__DisplayClass6_0.<GetClassificationSpans>b__0(TrackingTokenInfo kv) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\PythonClassifier.cs:line 72

   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()

   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()

   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)

   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

   at Microsoft.PythonTools.PythonClassifier.GetClassificationSpans(SnapshotSpan span) in C:\Projects\Gi......

<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------
```

```
import os

try: raise os.error()   # does not break
except: pass

try: raise os.error()   # does not break
except Exception: pass

try: raise os.error()   # does not break
except os.error: pass

os_error = os.error
try: raise os.error()   # does not break
except os_error: pass

def a():
    raise os.error()

try: a()    # does not break
except: pass

try: a()    # does not break
except Exception: pass

try: a()    # does not break
except os.error: pass

try: a()    # does not break
except os_error: pass

def b(var):
    try: a()
    except var: pass

b(Exception)    # does not break
b(os.error)     # does not break

exc = os.error()

try: raise exc      # does not break
except: pass

try: raise exc      # does not break
except Exception: pass

try: raise exc      # does not break
except os.error: pass

try: b(ValueError)  # does not break
except: pass

try: b(os.error)    # does not break
except ValueError: pass

b(ValueError)       # breaks at line 17

```

**Comment by zooba** [comment]
Sometimes asserts pop up in the background and you have to Alt+Tab to get to them.

**Comment by zooba** [comment]
Ah, no, you're right. It just asserted for me and there's no dialog... strange

**Comment by zooba** [comment]
Looks like it is just an incorrect assertion in the presence of certain race conditions - in this case, because the previous snapshot did not include the line at all, we couldn't map the line number to the right place. It doesn't matter, because the mapping is "accurate", so it's probably best to just remove the assertion (after all, the mapping is here to handle the race condition that the assertion is detecting).
