### ISSUE TITLE
opening file with .cfg extension (buildbot config file)

### ISSUE THREAD

**Issue by bruceoberg** [Microsoft/PTVS#3288]
throws this error:

[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 3.0.17297.4

System.InvalidOperationException: Failed to create entry for file
   at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.<AnalyzeFileAsync>d__82.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Intellisense.IntellisenseController.<ConnectSubjectBufferAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
```

**Comment by bruceoberg** [comment]
i tried to attach the (text) cfg file, but github wont let me

**Comment by zooba** [comment]
That's okay, we know about this issue and have already fixed it. It shouldn't occur in normal circumstances, as VS won't associate a ".cfg" file with the Python editor. But with the fix, if it does, we won't double-check and fail (like we did here).

**Comment by bruceoberg** [comment]
thank you @zooba. can you tell me approximately when this fix will be released? weeks? months? again, thanks for your help.

**Comment by zooba** [comment]
We're generally doing releases every 2-3 months right now. This will be in 15.6, and the next release is 15.5.

**Comment by bruceoberg** [comment]
thank you steve… when is 15.5 scheduled to release? or should i say, when did 15.4 release?

**Comment by zooba** [comment]
@bruceoberg I can't say anything about the future schedule, I'm afraid - releasing that information is above my pay grade :)

You can see the release history of 15.5 in [the release notes](https://www.visualstudio.com/en-us/news/releasenotes/vs2017-preview-relnotes), which may give you a sense of how close it is.
