### ISSUE TITLE
Unable to print in VS 2017 Community

### ISSUE THREAD

**Issue by CovertKoala** [Microsoft/PTVS#3290]
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 3.0.17297.4

System.Printing.PrintQueueException: PrintTicket provider failed to convert PrintTicket to DEVMODE. Win32 error: -2147221164
   at MS.Internal.Printing.Configuration.PTProvider.ConvertPrintTicketToDevMode(MemoryStream printTicket, BaseDevModeType baseType, PrintTicketScope scope)
   at System.Printing.Interop.PrintTicketConverter.InternalConvertPrintTicketToDevMode(PTProviderBase provider, PrintTicket printTicket, BaseDevModeType baseType, PrintTicketScope scope)
   at System.Printing.Interop.PrintTicketConverter.ConvertPrintTicketToDevMode(PrintTicket printTicket, BaseDevModeType baseType, PrintTicketScope scope)
   at System.Printing.Interop.PrintTicketConverter.ConvertPrintTicketToDevMode(PrintTicket printTicket, BaseDevModeType baseType)
   at MS.Internal.Printing.Win32PrintDialog.PrintDlgExMarshaler.AllocateAndInitializeDevMode(String printerName, PrintTicket printTicket)
   at MS.Internal.Printing.Win32PrintDialog.PrintDlgExMarshaler.AllocateUnmanagedPrintDlgExStruct()
   at MS.Internal.Printing.Win32PrintDialog.PrintDlgExMarshaler.SyncToStruct()
   at MS.Internal.Printing.Win32PrintDialog.ShowDialog()
   at System.Windows.Controls.PrintDialog.ShowDialog()
   at Microsoft.VisualStudio.Editor.Implementation.EditorPrintDialog.ShowDialog()
   at Microsoft.VisualStudio.Editor.Implementation.PrintingClient.TryPrint(IWpfTextView view, Boolean showDialog, String moniker)
   at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.VisualStudio.Editor.Implementation.Undo.UndoManagerCommandFilter.Microsoft.VisualStudio.OLE.Interop.IOleCommandTarget.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.VisualStudio.Editor.Implementation.IntellisenseCommandFilter.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.VisualStudio.Editor.Implementation.BraceCompletionCommandFilter.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.VisualStudio.Editor.Implementation.CommandFilterWrapper.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.VisualStudio.Editor.Implementation.CommandFilterWrap

**Comment by zooba** [comment]
Interesting that we picked up this error - it doesn't actually come from any of the Python-related code. I assume you were printing Python code.

If you try to print non-Python code, such as a plain text file, do you see a similar error (it won't be the same dialog)? If so, what would be best is to then use Help/Send Feedback/Report a Problem and also include the message posted above. That will provide enough information to make sure it gets to the right team.

If this only occurs for Python files, please let us know and we'll see what we can find.

**Comment by CovertKoala** [comment]
Mr Dower,

Due to a need (desire) for the great way VS prints code (for a project due today), I ended up doing a complete uninstall/reinstall of VS with slightly different setup (I installed python 3.6.3 first, then VS without the default 3.6.2).  The problem was fixed with the reinstall, so I unfortunately won’t be able to reproduce the error.

Very respectfully,
Capt Teal “Koala” Peterson, USMC
Student, Computer Science
Naval Post Graduate School
Cell: 408-608-8058

**Comment by zooba** [comment]
Okay, thanks for checking!
