### ISSUE TITLE
SocketException when installing package with elevation

### ISSUE THREAD

**Issue by JeffJQ** [Microsoft/PTVS#3301]
[Window Title]
Visual Studio - Python support

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 3.0.17297.4

System.Net.Sockets.SocketException (0x80004005): Only one usage of each socket address (protocol/network address/port) is normally permitted
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.TcpListener.Start(Int32 backlog)
   at Microsoft.PythonTools.Infrastructure.ProcessOutput.RunElevated(String filename, IEnumerable`1 arguments, String workingDirectory, IEnumerable`1 env, Redirector redirector, Boolean quoteArgs, Boolean elevate, Encoding outputEncoding, Encoding errorEncoding)
   at Microsoft.PythonTools.Infrastructure.ProcessOutput.Run(String filename, IEnumerable`1 arguments, String workingDirectory, IEnumerable`1 env, Boolean visible, Redirector redirector, Boolean quoteArgs, Boolean elevate, Encoding outputEncoding, Encoding errorEncoding)
   at Microsoft.PythonTools.Interpreter.PipPackageManager.<InstallAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.PythonTools.Interpreter.PipPackageManager.<InstallAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.EnvironmentsList.PipExtensionProvider.<InstallPackage>d__38.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.EnvironmentsList.PipExtension.<UpgradePackage_Executed>d__12.MoveNext()
```

**Comment by huguesv** [comment]
Some details on that error here: https://blogs.msdn.microsoft.com/dgorti/2005/09/18/only-one-usage-of-each-socket-address-protocolnetwork-addressport-is-normally-permitted/

We do 10 retries, and after that we rethrow the exception and nobody catches it.

**Comment by zooba** [comment]
So we should handle the exception properly, but we probably also need to pick a different port. There should be no conflict unless we're racing between two processes.
