### ISSUE TITLE
Intellisense stops after adding PySpark to the search paths

### ISSUE THREAD

**Issue by mmaitre314** [microsoft/PTVS#3314]
I am trying to use Apache Spark (PySpark) in Visual Studio 2017 and I am hitting some issues with auto-completion. Are there PTVS logs I could look at to understand what is failing?

I start by adding the dependency on Py4J and things look fine:

<img width="676" alt="pyspark1" src="https://user-images.githubusercontent.com/8584604/32618880-d277ba2e-c52d-11e7-8eb5-967d61635589.png">

The I add the dependency on PySpark, restart VS, and auto-completion does not work anymore:

<img width="669" alt="pyspark0" src="https://user-images.githubusercontent.com/8584604/32618943-fd953826-c52d-11e7-9f11-823fc50a3e43.png">

The REPL remains fine. It's not ideal to code though.

<img width="444" alt="pyspark2" src="https://user-images.githubusercontent.com/8584604/32618992-31313efa-c52e-11e7-868c-fd2b0b925f99.png">

**Comment by zooba** [comment]
If you look in the log generated from Tools, Python, Diagnostic Info, it may display error messages coming from the analyzer (if they occurred in the session when you get the log). Or you can attach the log here if you'd like us to take a look.

**Comment by zooba** [comment]
Also, just so you're aware, our handling of regular search paths is slightly more reliable than zip files. If you can extract those files you may see an improvement.

**Comment by huguesv** [comment]
I tried this with my own simple zip file and it worked ok with database IntelliSense. It doesn't work with new style IntelliSense though. I've closed and reopened the file and also the project, and it never recognizes the module that I'm importing as a module. @zooba do you want a separate bug for that?

**Comment by zooba** [comment]
@huguesv I think we have one, but if you can't find it, sure. That's not the cause of this issue though - something more central is failing here.

**Comment by mmaitre314** [comment]
Probably something obvious, but where can I find those logs?

**Comment by huguesv** [comment]
They live under `%localappdata%\Python Tools\CompletionDB` but it's easiest/best if you just generate the one diagnostics file from tools/options.

![image](https://user-images.githubusercontent.com/1696845/32634244-85ad5910-c55f-11e7-86b7-fcbf282bf822.png)

**Comment by mmaitre314** [comment]
Here are the logs:
[Diagnostic Info 2017-11-09T163223.txt](https://github.com/Microsoft/PTVS/files/1459648/Diagnostic.Info.2017-11-09T163223.txt)

Some lines that look suspicious:

```
2017-11-08T00:32:33: [ERROR] poplib.POP3.POP3: Unknown has no name
2017-11-08T00:32:33: [ERROR] traceback.format_exception: Unknown has no name
2017-11-08T00:32:33: [ERROR] traceback.TracebackException.TracebackException: Unknown has no name
2017-11-08T00:32:33: [ERROR] traceback._some_str: Unknown has no name
2017-11-08T00:32:33: [ERROR] traceback.StackSummary.StackSummary: Unknown has no name
2017-11-08T00:32:33: [ERROR] http.client.parse_headers: Unknown has no name
...
```

```
2017-11-08T08:31:52: [ERROR] Analysis failed
System.InvalidOperationException: Cannot obtain search paths ---> System.InvalidOperationException: Cannot obtain list of paths
The system cannot find the file specified
   at Microsoft.PythonTools.Interpreter.PythonTypeDatabase.<GetUncachedDatabaseSearchPathsAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.PythonTools.Analysis.PyLibAnalyzer.<Prepare>d__46.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.PythonTools.Analysis.PyLibAnalyzer.<Prepare>d__46.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Analysis.PyLibAnalyzer.<RunWorker>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Analysis.PyLibAnalyzer.<Run>d__33.MoveNext()
```

**Comment by huguesv** [comment]
So it's having trouble running the get_search_paths.py script
https://github.com/Microsoft/PTVS/blob/master/Python/Product/Analysis/get_search_paths.py
https://github.com/Microsoft/PTVS/blob/98d8f9e2b392ae0507a785f3b3c697c83c29a01a/Python/Product/Analysis/Interpreter/PythonTypeDatabase.cs#L743

where presumably the process outputs the "The system cannot find the file specified" error.

**Comment by zooba** [comment]
That error pops up occasionally, but doesn't seem to be consistent. It's a Windows error rather than a Python one, so I suspect something like an AV scanner is to blame, but we don't have enough diagnostics. It isn't the cause of this issue, anyway (if for no other reason than the project with the problem isn't using that Python environment).

We probably need to set up our own repro. I bet there's an assertion from the analyzer that we aren't seeing, but as soon as we run with a debug build it will be obvious. The step from screenshot 1 to screenshot 2 is the only part of this that worries me.

**Comment by huguesv** [comment]
Yep, assertion when I add pyspark.zip to the search path:
```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
System.NullReferenceException: Object reference not set to an instance of an object.

   at Microsoft.PythonTools.Interpreter.Ast.NameLookupContext.GetValueFromCallable(CallExpression expr, LookupOptions options) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Interpreter\Ast\NameLookupContext.cs:line 340

   at Microsoft.PythonTools.Interpreter.Ast.NameLookupContext.GetValueFromExpression(Expression expr, LookupOptions options) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Interpreter\Ast\NameLookupContext.cs:line 180

   at Microsoft.PythonTools.Interpreter.Ast.NameLookupContext.GetValueFromExpression(Expression expr) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Interpreter\Ast\NameLookupContext.cs:line 168

   at Microsoft.PythonTools.Interpreter.Ast.AstAnalysisFunctionWalker.Walk(ReturnStatement node) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Interpreter\Ast\AstAnalysisFunctionWalker.cs:line 128

   at Microsoft.PythonTools.Parsing.Ast.ReturnStatement.Walk(PythonWalker walker) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Parsing\Ast\ReturnStatement.cs:line 32

   at Microsoft.PythonTools.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Parsing\Ast\SuiteStatement.cs:line 37

   at Microsoft.PythonTools.Parsing.Ast.FunctionDefinition.Walk(PythonWalker walker) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Parsing\Ast\FunctionDefinition.cs:line 252

   at Microsoft.PythonTools.Interpreter.Ast.AstAnalysisFunctionWalker.Walk() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Interpreter\Ast\AstAnalysisFunctionWalker.cs:line 101

   at Microsoft.PythonTools.Interpreter.Ast.AstAnalysisWalker.PostWalk(PythonAst node) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Interpreter\Ast\AstAnalysisWalker.cs:line 86

   at Microsoft.PythonTools.Parsing.Ast.PythonAst.Walk(PythonWalker walker) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Parsing\Ast\PythonAst.cs:line 71

   at Microsoft.PythonTools.Interpreter.Ast.AstPythonModule..ctor(String moduleName, IPythonInterpreter interpreter, PythonAst ast, String filePath) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Interpreter\Ast\AstPythonModule.cs:line 113

   at Microsoft.PythonTools.Interpreter.Ast.AstPythonModule.FromStream(IPythonInterpreter interpreter, Stream sourceFile, String fileName, PythonLanguageVersion langVersion, String moduleFullName) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Interpreter\Ast\AstPythonModule.cs:line 78

   at Microsoft.PythonTools.Interpreter.Ast.AstPythonModule.FromStream(IPythonInterpreter interpreter, Stream sourceFile, String fileName, PythonLanguageVersion langVersion) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Interpreter\Ast\AstPythonModule.cs:line 64

   at Microsoft.PythonTools.Interpreter.Default.CPythonInterpreter.LoadModuleFromZipFile(String zipFile, String moduleName) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Interpreter\Default\CPythonInterpreter.cs:line 308

   at Microsoft.PythonTools.Interpreter.Default.CPythonInterpreter.ImportModule(String name) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Interpreter\Default\CPythonInterpreter.cs:line 110

   at Microsoft.PythonTools.Interpreter.Ast.AstNestedPythonModule.GetModule() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Interpreter\Ast\AstNestedPythonModule.cs:line 57

   at Microsoft.PythonTools.Interpreter.Ast.AstNestedPythonModule.Imported(IModuleContext context) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Interpreter\Ast\AstNestedPythonModule.cs:line 82

   at Microsoft.PythonTools.Interpreter.Ast.AstAnalysisWalker.Walk(FromImportStatement node) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Interpreter\Ast\AstAnalysisWalker.cs:line 182

   at Microsoft.PythonTools.Parsing.Ast.FromImportStatement.Walk(PythonWalker walker) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Parsing\Ast\FromImportStatement.cs:line 79

   at Microsoft.PythonTools.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Parsing\Ast\SuiteStatement.cs:line 37

   at Microsoft.PythonTools.Parsing.Ast.PythonAst.Walk(PythonWalker walker) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Parsing\Ast\PythonAst.cs:line 69

   at Microsoft.PythonTools.Interpreter.Ast.AstPythonModule..ctor(String moduleName, IPythonInterpreter interpreter, PythonAst ast, String filePath) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Interpreter\Ast\AstPythonModule.cs:line 113

   at Microsoft.PythonTools.Interpreter.Ast.AstPythonModule.FromStream(IPythonInterpreter interpreter, Stream sourceFile, String fileName, PythonLanguageVersion langVersion, String moduleFullName) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Interpreter\Ast\AstPythonModule.cs:line 78

   at Microsoft.PythonTools.Interpreter.Ast.AstPythonModule.FromStream(IPythonInterpreter interpreter, Stream sourceFile, String fileName, PythonLanguageVersion langVersion) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Interpreter\Ast\AstPythonModule.cs:line 64

   at Microsoft.PythonTools.Interpreter.Default.CPythonInterpreter.LoadModuleFromZipFile(String zipFile, String moduleName) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Interpreter\Default\CPythonInterpreter.cs:line 308

   at Microsoft.PythonTools.Interpreter.Default.CPythonInterpreter.ImportModule(String name) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Interpreter\Default\CPythonInterpreter.cs:line 110

   at Microsoft.PythonTools.Analysis.ModuleTable.TryImport(String name, ModuleReference& res) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\ModuleTable.cs:line 119

   at Microsoft.PythonTools.Analysis.Analyzer.DDG.TryImportModule(String modName, Boolean forceAbsolute, ModuleReference& moduleRef) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Analyzer\DDG.cs:line 302

   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(FromImportStatement node) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Analyzer\DDG.cs:line 253

   at Microsoft.PythonTools.Parsing.Ast.FromImportStatement.Walk(PythonWalker walker) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Parsing\Ast\FromImportStatement.cs:line 79

   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(SuiteStatement node) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Analyzer\DDG.cs:line 515

   at Microsoft.PythonTools.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Parsing\Ast\SuiteStatement.cs:line 34

   at Microsoft.PythonTools.Parsing.Ast.PythonAst.Walk(PythonWalker walker) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Parsing\Ast\PythonAst.cs:line 69

   at Microsoft.PythonTools.Analysis.AnalysisUnit.AnalyzeWorker(DDG ddg, CancellationToken cancel) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\AnalysisUnit.cs:line 165

   at Microsoft.PythonTools.Analysis.AnalysisUnit.Analyze(DDG ddg, CancellationToken cancel) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\AnalysisUnit.cs:line 148

   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Analyze(Deque`1 queue, CancellationToken cancel, Action`1 reportQueueSize, Int32 reportQueueInterval) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Analyzer\DDG.cs:line 75

   at Microsoft.PythonTools.Analysis.PythonAnalyzer.AnalyzeQueuedEntries(CancellationToken cancel) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\PythonAnalyzer.cs:line 1052

   at Microsoft.PythonTools.Intellisense.AnalysisQueue.GroupAnalysis.Analyze(CancellationToken cancel) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analyzer\Intellisense\AnalysisQueue.cs:line 268

   at Microsoft.PythonTools.Intellisense.AnalysisQueue.Worker(Object threadStarted) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analyzer\Intellisense\AnalysisQueue.cs:line 210



   at Microsoft.PythonTools.Intellisense.OutOfProcProjectAnalyzer.<SendUnhandledException>d__25.MoveNext() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analyzer\Intellisense\OutOfProcProjectAnalyzer.cs:line 221

   at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.PythonTools.Intellisense.OutOfProcProjectAnalyzer.SendUnhandledException(Exception ex)

   at Microsoft.PythonTools.Intellisense.OutOfProcProjectAnalyzer.ReportUnhandledException(Exception ex) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analyzer\Intellisense\OutOfProcProjectAnalyzer.cs:line 213

   at Microsoft.PythonTools.Intellisense.AnalysisQueue.Worker(Object threadStarted) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analyzer\Intellisense\AnalysisQueue.cs:line 216

   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Threading.ThreadHelper.ThreadStart(Object obj)


---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by huguesv** [comment]
Project file and zip files all ready to go in our share under `bugs\3314`, just need to add pyspark.zip to search path to see the assert.

**Comment by zooba** [comment]
Ah, yeah, that'll be this condition:
```
if (fn.Overloads.Count > 0 && fn.Overloads[0].ReturnType.Count > 0)
```

No null checks (we don't initialize those lists/arrays if they're empty), and there's a TODO there anyway to do better overload selection.

Doing something like this should be sufficient (with adaptation to be correct - this is simplified here).
```
if (fn.Overloads?[0]?.ReturnType == null) {
    Log("NoOverloads");
    return _unknownType;
}
```

Probably also worth checking with the NoDB experiment turned off, but I think they're the same code path here regardless.

**Comment by huguesv** [comment]
It was with NoDB turned off. Not seeing the assert with NoDB.

**Comment by huguesv** [comment]
Made low priority since it didn't appear to be a problem with NoDB.
