### ISSUE TITLE
System.InvalidOperationException: Failed to create entry for file

### ISSUE THREAD

**Issue by lvmgeo** [Microsoft/PTVS#3326]
Opening Python file with extension not beein *.py

Visual Studio 2017 (15.4.3)

[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Expanded Information]
```
Build: 3.0.17310.2

System.InvalidOperationException: Failed to create entry for file
   at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.<AnalyzeFileAsync>d__82.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Intellisense.IntellisenseController.<ConnectSubjectBufferAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
```

**Comment by zooba** [comment]
Thanks for the report! I recently fixed this in our main branch, so it'll be coming soon (15.6 Preview 1 - sorry, I can't give you a date for it).
