### ISSUE TITLE
python-sklearn-classifier-cookiecutter throws InvalidProjectFileException when creating a project

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/PTVS#3337]
```
Microsoft.Build.Exceptions.InvalidProjectFileException
  HResult=0x80131500
  Message=The imported project "C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\Python Tools\Microsoft.PythonTools.targets" was not found. Also, tried to find "Microsoft\VisualStudio\v15.0\Python Tools\Microsoft.PythonTools.targets" in the fallback search path(s) for $(MSBuildExtensionsPath32) - "C:\Program Files (x86)\MSBuild" . These search paths are defined in "C:\Users\kanadig\AppData\Local\Microsoft\VisualStudio\15.0_97830777Exp\devenv.exe.config". Confirm that the path in the <Import> declaration is correct, and that the file exists on disk in one of the search paths.  C:\Users\kanadig\Documents\Visual Studio 2017\Projects\PyClassifier\PyClassifier.pyproj
  Source=Microsoft.Build
  StackTrace:
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Evaluation.Evaluator`4.ThrowForImportedProjectWithSearchPathsNotFound(ProjectImportPathMatch searchPathMatch, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, ProjectRootElement root, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCache projectRootElementCache, BuildEventContext buildEventContext, ProjectInstance projectInstanceIfAnyForDebuggerOnly, SdkResolution sdkResolution)
   at Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName)
   at Microsoft.VisualStudioTools.Project.Utilities.InitializeMsBuildProject(ProjectCollection buildEngine, String fullProjectPath) in G:\GIT\PTVS\Common\Product\SharedProject\Utilities.cs:line 488
   at Microsoft.VisualStudioTools.Project.Utilities.ReinitializeMsBuildProject(ProjectCollection buildEngine, String fullProjectPath, Project exitingBuildProject) in G:\GIT\PTVS\Common\Product\SharedProject\Utilities.cs:line 513
   at Microsoft.VisualStudioTools.Project.ProjectFactory.ProjectTypeGuids(String file) in G:\GIT\PTVS\Common\Product\SharedProject\ProjectFactory.cs:line 176
   at Microsoft.PythonTools.Project.PythonProjectFactory.ProjectTypeGuids(String file) in G:\GIT\PTVS\Python\Product\PythonTools\PythonTools\Project\PythonProjectFactory.cs:line 98
   at Microsoft.VisualStudioTools.Project.ProjectFactory.CreateProject(String fileName, String location, String name, UInt32 flags, Guid& projectGuid, IntPtr& project, Int32& canceled) in G:\GIT\PTVS\Common\Product\SharedProject\ProjectFactory.cs:line 132
   at Microsoft.VisualStudioTools.Project.FlavoredProjectFactoryBase.Microsoft.VisualStudio.Shell.Interop.IVsProjectFactory.CreateProject(String fileName, String location, String name, UInt32 flags, Guid& projectGuid, IntPtr& project, Int32& canceled) in G:\GIT\PTVS\Common\Product\SharedProject\FlavoredProjectFactoryBase.cs:line 62
```

**Comment by zooba** [comment]
@karthiknadig This is only when you haven't installed properly. Look at the TestTargets folder in BuildTasks (and if you want to add instructions to the wiki to look there, go ahead)

**Comment by karthiknadig** [comment]
@zooba You are correct. That fixed the issue.

**Comment by huguesv** [comment]
I've updated the wiki to mention TestTargets.
