### ISSUE TITLE
An unexpected error occurred.

### ISSUE THREAD

**Issue by kchawla-pi** [Microsoft/PTVS#3355]
Actions:
Set a breakpoint in a python program. 
Run program in debug mode.
Activate interactive debugger on execution pause.
In it, type:
 `from pathlib import Path`
Terminal prompt appears.
Error occurs. unexpected error dialogue box.

Error report contents follows:

[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[V] Show details  [Close]

[Expanded Information]
```
Build: 3.0.17297.4

System.InvalidOperationException: Failed to create entry for file
   at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.<AnalyzeFileAsync>d__82.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Intellisense.IntellisenseController.<ConnectSubjectBufferAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
```

**Comment by zooba** [comment]
Thanks for the report! This has already been fixed for our next release, which is currently available in Visual Studio Preview.
