### ISSUE TITLE
InteliSense hangs when scraping the 'vpython' module

### ISSUE THREAD

**Issue by dgordon42** [Microsoft/PTVS#3378]
I'm using VS 2017 Community on Windows 10, 64-bit version 1709.
I installed 'vpython' using 'pip' in VS for Python3.6.
VS reported a successfull installation, but when I tried to refresh the InteliSense Database, it hangs while "Scraping vpython".
Below is the pasted error message:
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 3.0.17310.2

System.InvalidOperationException: Failed to create entry for file
   at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.<AnalyzeFileAsync>d__82.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Intellisense.IntellisenseController.<ConnectSubjectBufferAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
```

Many Thanks,
Dave.

**Comment by zooba** [comment]
So there are two issues here. The first (very slow analysis of vpython) is likely the same as #2051, and will be fixed in the same way (by removing the completion DB completely in the next version).

The second issue is known and already fixed for our next version. I'll close this as a duplicate.

Thanks for the report!
