### ISSUE TITLE
InvalidOperationException appears at random time when debugging C++ code

### ISSUE THREAD

**Issue by alexeyvo** [microsoft/PTVS#3392]
When I debug C++ project(no python code) sometimes weird dialog appears:

```
Build: 3.0.17310.2

System.InvalidOperationException: Failed to create entry for file
   at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.<AnalyzeFileAsync>d__82.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Intellisense.IntellisenseController.<ConnectSubjectBufferAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
```

I just close it and continue debugging.

Here is my VS info:
```
Microsoft Visual Studio Professional 2017 
Version 15.4.4
VisualStudio.15.Release/15.4.4+27004.2009
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Professional

Visual Basic 2017   00370-20004-69286-AA692
Microsoft Visual Basic 2017

Visual C# 2017   00370-20004-69286-AA692
Microsoft Visual C# 2017

Visual C++ 2017   00370-20004-69286-AA692
Microsoft Visual C++ 2017

ASP.NET and Web Tools 2017   15.0.30925.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   1.0
Provides languages services for ASP.NET Core Razor.

JavaScript Language Service   2.0
JavaScript Language Service

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   4.4.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Python   3.0.17310.2
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - IronPython support   3.0.17310.2
Provides templates and integration for IronPython-based projects.

Python - Profiling support   3.0.17310.2
Profiling support for Python projects.

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Visual Assist   
For more information about Visual Assist, see the Whole Tomato Software website at http://www.WholeTomato.com. Copyright (c) 1997-2017 Whole Tomato Software, Inc.

Visual C++ for Linux Development   1.0.8
Visual C++ for Linux Development

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio tools for CMake   1.0
Visual Studio tools for CMake
```

**Comment by huguesv** [comment]
Thanks. I think those are fixed, but it's strange that you are seeing it with C++ code. Maybe you had a Python project in the same solution, or Python files open in the editor?

**Comment by alexeyvo** [comment]
My solution contains only 2 c++ projects, there are no opened python files when I got this dialog. I use python tools for different solution(contains single python project) but last time I opened it was week ago, so It's really weird that I get some error related to python.

**Comment by zooba** [comment]
This might also happen for an interactive window, but if we're being loaded without any Python files being opened that is a very serious bug that is going to be very hard to investigate.

Is it possible that you had a Python interactive window open while debugging and it is coming back even when you start debugging a different project?

**Comment by zooba** [comment]
Great, thanks! This is really weird, so we’ll take a look at any ways this may be triggered indirectly.

**Comment by huguesv** [comment]
I've been trying to repro this. I spent a bit of time debugging boost unit tests.

While some PTVS code executes in that scenario due to our test container discoverer, I haven't seen anything that caused ConnectSubjectBufferAsync to execute yet.

**Comment by alexeyvo** [comment]
It looks like this issue appears only when I step into system/stl headers(vector, etc)

**Comment by huguesv** [comment]
I added some STL vector usage to my boost test and stepped into it without triggering our `IntellisenseController`. The code in `ConnectSubjectBufferAsync` has had a few changes since your build and I'm not sure I'd get an error even if it got invoked. Anyway, I put a breakpoint and I'm not seeing it getting called.

**Comment by alexeyvo** [comment]
Thanks for checking, I'll let you know If I get more details on this.
