### ISSUE TITLE
ObjectDisposedException in TaskProvider.WorkerWorker

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#3420]
Seen in Output of ClassifierTests.ModuleClassification (when it failed, which doesn't always happen)

```
testhost.x86.exe Error: 0 : System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'The event has been disposed.'.
   at System.Threading.ManualResetEventSlim.ThrowIfDisposed()
   at System.Threading.ManualResetEventSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.ManualResetEventSlim.Wait(Int32 millisecondsTimeout)
   at Microsoft.PythonTools.Intellisense.TaskProvider.WorkerWorker() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\TaskProvider.cs:line 552
   at Microsoft.PythonTools.Intellisense.TaskProvider.Worker(Object param) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\TaskProvider.cs:line 517

```

**Comment by zooba** [comment]
Probably just want to handle the exception here and cancel the loop - there isn't any reason to continue.

**Comment by zooba** [comment]
This is already handled - the trace message is coming from the handler. Nothing to see here :)
