### ISSUE TITLE
Unhandled Argument Exception when deleting collapsed IronPython method from file

### ISSUE THREAD

**Issue by ipyguy** [Microsoft/PTVS#348]
Using VS2013 Pro w/ PTVS 2.2 RC.  IronPython 2.7.5.  
I've found that if I delete a method that is collapsed, the IDE fires off an 'Unhanlded Argument exception' from mscorlib.  If I expand the method before deleting it, there is no issue.  I'm not sure if this is related to issue #62: https://github.com/Microsoft/PTVS/issues/62, but since collapsing to function headers is not much different than collapsing to regions, I figured I'd reference it here.

FYI on a side note, I've been using this release daily since it came out and this is the only exception I've seen so far -nice work.

**Comment by ipyguy** [comment]
System events:
Time: 2015-06-09T09:05:39
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
Stack:
   at System.ThrowHelper.ThrowArgumentException(System.ExceptionResource)
   at System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Insert(System.__Canon, System.__Canon, Boolean)
   at Microsoft.VisualStudio.Text.Editor.Implementation.TextContentLayer.UpdateTextVisuals()
   at Microsoft.VisualStudio.Text.Editor.Implementation.TextContentLayer.ArrangeOverride(System.Windows.Size)
   at System.Windows.FrameworkElement.ArrangeCore(System.Windows.Rect)
   at System.Windows.UIElement.Arrange(System.Windows.Rect)
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(System.Object)
   at System.Windows.Media.MediaContext+InvokeOnRenderCallback.DoWork()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(System.Object)
   at System.Windows.Media.MediaContext.RenderMessageHandler(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

**Comment by zooba** [comment]
This could be the same as #62, though we haven't seen it on VS 2013 before. It's also an ArgumentException coming from a dictionary, while the other was from a span, so it may be unrelated.

@crwilcox - can you confirm and fix/close?

**Comment by crwilcox** [comment]
@ipyguy.  I can't seem to repro this in our current builds at all.

```python
def func(f):
    pass
    pass
    pass
```

If I collapse that and delete it seems to work fine.

We have a dev build out from last Friday: https://github.com/Microsoft/PTVS/releases/tag/dev-2015-06-05

Do you want to see if the problem repros for you?  It may be slightly more complicated than just collapsing.  If it isn't though we can close this as no repro/fixed.

Thanks!

**Comment by ipyguy** [comment]
I was not able to reproduce the issue with the build you suggested.
Thanks.
