### ISSUE TITLE
Argument exception on hover

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#3511]
Reported at https://developercommunity.visualstudio.com/content/problem/161340/python-intellisense-doesnt-work-at-all.html

```
System.ArgumentException: Failed to get classifier from buffer
at Microsoft.PythonTools.Intellisense.ReverseExpressionParser..ctor(ITextSnapshot snapshot, ITextBuffer buffer, ITrackingSpan span)
at Microsoft.PythonTools.Language.TextViewFilter.GetDataTipText(TextSpan[] pSpan, String& pbstrText)
at Microsoft.VisualStudio.Editor.Implementation.ShimQuickInfoSource.TryGetQuickInfoFromFilter(IQuickInfoSession session, TextSpan[] dataBufferTextSpan, String& tipText)
at Microsoft.VisualStudio.Editor.Implementation.ShimQuickInfoSource.AugmentQuickInfoSession(IQuickInfoSession session, IList`1 qiContent, ITrackingSpan& applicableToSpan)
at Microsoft.VisualStudio.Language.Intellisense.Implementation.QuickInfoSession.Recalculate()
at Microsoft.VisualStudio.Language.Intellisense.Implementation.QuickInfoSession.Start()
at Microsoft.VisualStudio.Language.Intellisense.Implementation.DefaultQuickInfoController.OnTextView_MouseHover(Object sender, MouseHoverEventArgs e)
at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.RaiseHoverEvents()
--- End of stack trace from previous location where exception was thrown---
at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject) 
```

We should handle the error here and just not provide a tooltip. If there is no classifier, we clearly haven't started running properly yet and so the tooltip isn't going to be interesting anyway.

**Comment by huguesv** [comment]
This doesn't affect the code in 15.6, which no longer uses `ReverseExpressionParser` for `GetDataTipText`, which appears to behave properly now when we can't get the buffer info.

It might be worth fixing for 15.5. I was able to repro by opening a python project and a file in the editor, changing the active interpreter in solution explorer and then mouse over the code.
