### ISSUE TITLE
System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by MTVS2** [Microsoft/PTVS#3515]
I got this popup in the middle of debugging a Python 3.0.17109.1 script on VS2017prev v15.2 (26419.1-Preview) with .NET v4.7.02556. Didn't seem to affect my debugging since I was just editing. Hope it can help somebody.

[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 3.0.17109.1

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: length
   at Microsoft.VisualStudio.Text.Span..ctor(Int32 start, Int32 length)
   at Microsoft.PythonTools.Intellisense.LocationTracker.TranslateForward(Span from)
   at Microsoft.PythonTools.Intellisense.LocationTracker.TranslateForward(Int32 position)
   at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.<ConvertOutliningTags>d__160.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.PythonTools.OutliningTaggerProvider.OutliningTagger.<>c__DisplayClass14_1.<UpdateTagsAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.OutliningTaggerProvider.OutliningTagger.<UpdateTagsAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudioTools.UIThread.<InvokeTaskHelper>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
```

**Comment by huguesv** [comment]
Thanks! I just looked at the code and it looks like it's been fixed for 15.6 preview already.
