### ISSUE TITLE
Assertion failed when using snippets

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/PTVS#3538]
Trying to use the `if` snippet cause this assertion.
```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Buffer content mismatch



   at Microsoft.PythonTools.Intellisense.BufferParser.ValidateBufferContents(IEnumerable`1 snapshots, FileUpdateResponse response) in G:\GIT\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\BufferParser.cs:line 268

   at Microsoft.PythonTools.Intellisense.BufferParser.<ParseBuffersAsync>d__41.MoveNext() in G:\GIT\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\BufferParser.cs:line 309

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass4_0.<OutputAsyn......

<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by huguesv** [comment]
@zooba FYI I have the latest, including https://github.com/Microsoft/PTVS/pull/3571 and I just saw the Buffer content mismatch assert when I used the `if` snippet here.

![image](https://user-images.githubusercontent.com/1696845/35166886-3725e8a8-fd08-11e7-86d8-43618cc4913e.png)

**Comment by zooba** [comment]
@huguesv Do you have connection logs for Analyzer and ProjectAnalyzer? I'll try to repro anyway, but that would save some time.

**Comment by zooba** [comment]
For my own future reference, here are the relevant lines from the logs:

```
{"command":"fileUpdate","arguments":{"documentUri":"file:///.../PythonApplication31.py","updates":[{"kind":1,"version":3,"content":"import os\r\nimport sys\r\nimport package1\r\n\r\nv = sys.version\r\nprint(v)\r\n\r\ndef main():\r\n    if\r\n    pass\r\n\r\nif __name__ == \"__main__\":\r\n    sys.exit(int(main() or 0))\r\n\r\nprint(os.altsep)\r\n\r\n\r\n"}]},"type":"request","seq":24}
{"request_seq":24,"success":true,"command":"fileUpdate","body":{"version":3,"newCode":"import os\r\nimport sys\r\nimport package1\r\n\r\nv = sys.version\r\nprint(v)\r\n\r\ndef main():\r\n    if\r\n    pass\r\n\r\nif __name__ == \"__main__\":\r\n    sys.exit(int(main() or 0))\r\n\r\nprint(os.altsep)\r\n\r\n\r\n"},"type":"response","seq":31}
{"event":"fileParsed","body":{"documentUri":"file:///.../PythonApplication31.py","version":3},"type":"event","seq":32}

{"command":"fileUpdate","arguments":{"documentUri":"file:///.../PythonApplication31.py","updates":[{"kind":2,"version":4,"changes":[{"newText":"if","startLine":9,"startColumn":5,"endLine":9,"endColumn":7,"_startIndex":88,"_endIndex":90}]},{"kind":2,"version":5,"changes":[{"newText":"","startLine":9,"startColumn":5,"endLine":9,"endColumn":7,"_startIndex":88,"_endIndex":90}]},{"kind":2,"version":6,"changes":[{"newText":"if True:\r\n    ","startLine":9,"startColumn":5,"endLine":9,"endColumn":5,"_startIndex":88,"_endIndex":88}]}]},"type":"request","seq":26}
{"request_seq":26,"success":true,"command":"fileUpdate","body":{"version":6,"newCode":"import os\r\nimport sys\r\nimport package1\r\n\r\nv = sys.version\r\nprint(v)\r\n\r\ndef main():\r\n    if True:\r\n    \r\n    pass\r\n\r\nif __name__ == \"__main__\":\r\n    sys.exit(int(main() or 0))\r\n\r\nprint(os.altsep)\r\n\r\n\r\n"},"type":"response","seq":37}
{"event":"fileParsed","body":{"documentUri":"file:///.../PythonApplication31.py","version":5},"type":"event","seq":38}
{"event":"fileParsed","body":{"documentUri":"file:///.../PythonApplication31.py","version":6},"type":"event","seq":40}
{"event":"fileParsed","body":{"documentUri":"file:///.../PythonApplication31.py","version":6},"type":"event","seq":43}

{"command":"fileUpdate","arguments":{"documentUri":"file:///.../PythonApplication31.py","updates":[{"kind":2,"version":7,"changes":[{"newText":"    pass","startLine":10,"startColumn":1,"endLine":10,"endColumn":1,"_startIndex":98,"_endIndex":98}]}]},"type":"request","seq":29}
{"request_seq":29,"success":true,"command":"fileUpdate","body":{"version":7,"newCode":"import os\r\nimport sys\r\nimport package1\r\n\r\nv = sys.version\r\nprint(v)\r\n\r\ndef main():\r\n    if True:\r\n    pass    \r\n    pass\r\n\r\nif __name__ == \"__main__\":\r\n    sys.exit(int(main() or 0))\r\n\r\nprint(os.altsep)\r\n\r\n\r\n"},"type":"response","seq":49}
{"event":"fileParsed","body":{"documentUri":"file:///.../PythonApplication31.py","version":7},"type":"event","seq":50}
```

**Comment by zooba** [comment]
The problem appears to be very much on the VS side of things - the index values being used are "correct" for what was seen, so my current suspicion is that virtual whitespace is being a problem.

**Comment by zooba** [comment]
It was actually because our logic for merging adjacent changes together was incorrect. Rather than fixing it, I've just removed it. In practice, VS creates separate snapshots nearly all the time (snippets are one of the few examples where we put multiple changes in the one edit), so it isn't a great loss.
