### ISSUE TITLE
Virtual environments don't appear in Python Environments

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#354]
Steps:

1. New Python Application
2. Add Python 2.7 to project
3. Create virtual environment based on Python 2.7
4. Look in Python Environments window

Should be there.

**Comment by zooba** [comment]
Haven't been able to repro this - leaving it open for now in case we see it again.

**Comment by zooba** [comment]
Saw this again - might have been when virtual environments are created too early (as part of the wizard).

**Comment by zooba** [comment]
Might be due to this error:

```
Failed to import factory providers: System.Reflection.ReflectionTypeLoadException:
Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
 at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
 at System.Reflection.RuntimeModule.GetTypes()
 at System.Reflection.Assembly.GetTypes()
 at System.ComponentModel.Composition.Hosting.AssemblyCatalog.get_InnerCatalog()
 at System.ComponentModel.Composition.Hosting.AssemblyCatalog.GetExports(ImportDefinition definition)
 at System.ComponentModel.Composition.Hosting.CatalogExportProvider.InternalGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
 at System.ComponentModel.Composition.Hosting.CatalogExportProvider.InnerCatalogExportProvider.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
 at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
 at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExports(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
 at System.ComponentModel.Composition.Hosting.CatalogExportProvider.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
 at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
 at System.ComponentModel.Composition.Hosting.ExportProvider.GetExports(ImportDefinition definition, AtomicComposition atomicComposition)
 at System.ComponentModel.Composition.Hosting.AggregateExportProvider.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
 at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
 at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExports(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
 at System.ComponentModel.Composition.Hosting.CompositionContainer.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
 at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
 at System.ComponentModel.Composition.Hosting.ExportProvider.GetExports(ImportDefinition definition, AtomicComposition atomicComposition)
 at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportsCore(Type type, Type metadataViewType, String contractName, ImportCardinality cardinality)
 at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportsCore[T](String contractName)
 at System.ComponentModel.Composition.Hosting.ExportProvider.GetExports[T](String contractName)
 at System.ComponentModel.Composition.Hosting.ExportProvider.GetExports[T]()
 at Microsoft.PythonTools.Interpreter.InterpreterOptionsService.LoadProviders(SettingsStore store, IServiceProvider serviceProvider) in C:\Source\PTVS\Python\Product\VSInterpreters\InterpreterOptionsService.cs:line 326
 
 System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Windows.Design.Host, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. File name: 'Microsoft.Windows.Design.Host, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' 
 at System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.VsInteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. File name: 'Microsoft.VisualStudio.VsInteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' 
 at System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. File name: 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' 
 at System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. File name: 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' 
 at System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. File name: 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' 
 at System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. File name: 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' 
 at System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. File name: 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' 
 at System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. File name: 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' 
 at System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. File name: 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' 
 at System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. File name: 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' 
 at System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. File name: 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' 
 at System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. File name: 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' 
 at System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. File name: 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' 
 at System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. File name: 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' 
 at System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. File name: 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' 
 at System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. File name: 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' 
 at System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. File name: 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' 
 at System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. File name: 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' 
 at System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. File name: 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' 
 at System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. File name: 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' 
 at System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. File name: 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' 
 at System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. File name: 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' 
 at System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. File name: 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' 
 at System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. File name: 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' 
 at System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. File name: 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' 
 at System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. File name: 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' 
 at System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Windows.Design.Host, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. File name: 'Microsoft.Windows.Design.Host, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' 
 at System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. File name: 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' 
 at System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. File name: 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' 
 at System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. File name: 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' 
 at System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. File name: 'Microsoft.VisualStudio.InteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
```

I'd start by double-checking the full names to make sure they are correct (though this was from 2015 RC and they may have changed since then). Possibly we'll have to move one of the providers from PythonTools into VSInterpreters.

**Comment by int19h** [comment]
This is a consequence of building against VS 2015 RC, but running against later builds. `ISuggestedAction` (and possibly others, but that's the one that popped out first) has a bunch of new members added to it post-RC, such as `HasActionSets`. We implement those in `PythonSuggestedImportAction`, but because it's an implicit implementation, if built against VS version that doesn't have them in the interface, the corresponding class members don't get the proper `.override` in IL, and as a result the class doesn't actually implement the interface, screwing up MEF exports from PythonTools assembly.

**Comment by zooba** [comment]
@crwilcox this is the bug you were seeing today. It'll be fixed with a rolling build, or with the next dev build (which probably won't run against RC).

**Comment by kunom** [comment]
Same issue here (`Could not load file or assembly "Microsoft.Windows.Design.Host [...]"`). Maybe you should produce a new build, now that VS 2015 is out.

**Comment by zooba** [comment]
We did produce a new build. Can you open a new issue and post the info from Tools, Python Tools, Diagnostic Info as a [gist](https://gist.github.com)?

**Comment by kunom** [comment]
Done: #830.
