### ISSUE TITLE
Always check `__stdout__` before using

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#3569]
Hard to be sure, but [this issue](https://developercommunity.visualstudio.com/content/problem/175588/adjusting-console-output.html) seems like it could be fixed by verifying `__stdout__` is not None before using it.

**Comment by huguesv** [comment]
I reproduced it using our Python 3.6 64-bit, by checking Windows application in project settings. Sorry for the pseudo-loc build.
```
Hello World
!vAzEJ!The thread 'MainThread' (0xc2c) has exited with code 0 (0x0). ýÛöÑé!
AttributeError: 'NoneType' object has no attribute 'write'
Error in sys.excepthook:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\ptvsd\debugger.py", line 2411, in _excepthook
    do_wait()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\ptvsd\debugger.py", line 2543, in do_wait
    sys.__stdout__.write('Press any key to continue . . . ')
AttributeError: 'NoneType' object has no attribute 'write'

Original exception was:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\ptvsd_launcher.py", line 96, in <module>
    vspd.debug(filename, port_num, debug_id, debug_options, run_as)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\ptvsd\debugger.py", line 2702, in debug
    do_wait()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\ptvsd\debugger.py", line 2543, in do_wait
    sys.__stdout__.write('Press any key to continue . . . ')
AttributeError: 'NoneType' object has no attribute 'write'
!y9Wtz!The program '[4708] pythonw.exe' has exited with code 1 (0x1). ýÛöÑé!
```

**Comment by rarahim75** [comment]
I'm running:
MS VS Community 2017 15.9.6
Python 3.7.2 (64bit)

I was trying to direct my python output to the Output window instead of the console window and someone suggested to check Windows Application in the project properties. After doing that, trying to execute a simple print statement like below..

```
n = 10
print(n)
```

.. kept failing with the following error..

```
  Message='NoneType' object has no attribute 'write'
  Source=C:\Users\rarahim\source\repos\PythonApplication1\PythonApplication1\PythonApplication1.py
  StackTrace:
  File "C:\Users\rarahim\source\repos\PythonApplication1\PythonApplication1\PythonApplication1.py", line 2, in <module>
    print(n)
```

This seems to be a know issue with VS Code and python extension. Is it the same issue here? is there any workaround because i really prefer not to have the console window popping up every time running python code.

Thanks.
