### ISSUE TITLE
Unexpected error analysis/debug interactive

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#3573]
In design mode, I closed my output window which brought my debug interactive window to the front, and produced this error. I was able to repro that a second time.

[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 3.0.18018.1

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.PythonTools.Intellisense.AnalysisEntryService.TryGetAnalyzer(ITextBuffer textBuffer, ProjectAnalyzer& analyzer, String& filename)
   at Microsoft.PythonTools.Intellisense.IntellisenseController.<AnalyzeBufferAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Intellisense.IntellisenseController.<ConnectSubjectBufferAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
```

**Comment by zooba** [comment]
I repro'd as well, here's my stack trace with line numbers:

```
Unhandled exception in Microsoft.PythonTools.Intellisense.IntellisenseController.ConnectSubjectBuffer (C:\Projects\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\IntellisenseController.cs:158)
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.PythonTools.Intellisense.AnalysisEntryService.TryGetAnalyzer(ITextBuffer textBuffer, ProjectAnalyzer& analyzer, String& filename) in C:\Projects\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\AnalysisEntryService.cs:line 243
   at Microsoft.PythonTools.Intellisense.IntellisenseController.<AnalyzeBufferAsync>d__22.MoveNext() in C:\Projects\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\IntellisenseController.cs:line 167
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

Line looks like this, and `DocumentUri` is `null`:
```
filename = evaluator.DocumentUri.IsFile ? evaluator.DocumentUri.LocalPath : null;
```
