### ISSUE TITLE
Python project can not be run or debug anymore

### ISSUE THREAD

**Issue by wuhongyewhy** [Microsoft/PTVS#3686]
I write a python project, all things goes well. And I made some setting changes in tools->options related to python language formatting. Later, all python project can not be run or debug. Even a blank project! I'm not sure whether the problem occurs immedgetly after settings change.

Append： reinstall "python development" and "data science and analytical applications" can not solve the problem.

[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 3.0.17320.1

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.PythonTools.Project.PythonProjectNode.GetLaunchConfigurationOrThrow()
   at Microsoft.PythonTools.Project.DefaultLauncherProvider.CreateLauncher(IPythonProject project)
   at Microsoft.PythonTools.PythonToolsPackage.<>c__DisplayClass8_0.<GetLauncher>b__2()
   at Microsoft.VisualStudioTools.UIThread.Invoke[T](Func`1 func)
   at Microsoft.PythonTools.PythonToolsPackage.GetLauncher(IServiceProvider serviceProvider, IPythonProject project)
   at Microsoft.PythonTools.PythonToolsPackage.LaunchFile(IServiceProvider provider, String filename, Boolean debug, Boolean saveDirtyFiles)
   at Microsoft.PythonTools.Language.EditFilter.ExecWorker(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.PythonTools.Language.EditFilter.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
```

**Comment by wuhongyewhy** [comment]
I have solved it by reinstalling entire visual studio.
