### ISSUE TITLE
Python Django cannot run anymore

### ISSUE THREAD

**Issue by Auvite** [Microsoft/PTVS#3687]
Trying to debug before update worked django project and now vs cannot run it.
Gives following traceback.

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions\Microsoft\Python\Core\ptvsd_launcher.py", line 34, in <module>
    import ptvsd.debugger as vspd
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions\Microsoft\Python\Core\ptvsd\debugger.py", line 29, in <module>
    import ctypes
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\Lib\ctypes\__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: DLL load failed: The specified procedure could not be found.

Internal error detected. Please copy the above traceback and report at
https://go.microsoft.com/fwlink/?LinkId=293415

Press Enter to close. . .
```

**Comment by Auvite** [comment]
Okay so the vs disappeared the virtual environment for some reason. I added new virtual environment and got it back to situation as it was. 

Now i have another problem. 
The project runs fine with cmd->manage.py runserver
But with vs debugger i get just errors i don't understand why.<-This was the reason that i updated visual studio.
Django version 2
Python 3.6


The traceback log
```
Traceback (most recent call last):
  File "C:\Users\<user>\source\repos\customer\blank\blank\views.py", line 12, in <module>
    from blank.tokens import account_activation_token
  File "C:\Users\<user>\source\repos\customer\blank\blank\tokens.py", line 1, in <module>
    from django.contrib.auth.tokens import PasswordResetTokenGenerator
  File "C:\Users\<user>\source\repos\customer\blank\customer_env\lib\site-packages\django\contrib\auth\tokens.py", line 8, in <module>
    class PasswordResetTokenGenerator:
  File "C:\Users\<user>\source\repos\customer\blank\customer_env\lib\site-packages\django\contrib\auth\tokens.py", line 14, in PasswordResetTokenGenerator
    secret = settings.SECRET_KEY
  File "C:\Users\<user>\source\repos\customer\blank\customer_env\lib\site-packages\django\conf\__init__.py", line 56, in __getattr__
    self._setup(name)
  File "C:\Users\<user>\source\repos\customer\blank\customer_env\lib\site-packages\django\conf\__init__.py", line 41, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting SECRET_KEY, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
Press any key to continue . . .
```

Any ideas?

**Comment by zooba** [comment]
Hi @Auvite 

Did you create this as a Django project using our template? Or did you import an existing project? If you imported this, then we aren't trying to run it using `runserver` and you're likely to see this error.

When importing an existing project, there is a dropdown on the last page that will let you set it as a Django project. Unfortunately, the modifications to change this later are complicated, so it's best to do it at the start.

Alternatively, you could try setting `manage.py` as the startup file and adding `runserver` as the debug arguments. That should give you much the same behavior (though with the properly created project we would also open your default browser for you).

**Comment by huguesv** [comment]
I hope you figured it out, if not, feel free to ask follow up questions.
