### ISSUE TITLE
NullReferenceException in GetQuickInfoAsync

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#3696]
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 15.6.18033.2

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.<GetQuickInfoAsync>d__179.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.WaitForRequest[T](Task`1 request, String requestName, T defaultValue, Int32 timeoutScale)
   at Microsoft.PythonTools.Intellisense.IntellisenseController.<>c__DisplayClass18_0.<TextViewMouseHoverWorker>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Intellisense.IntellisenseController.<TextViewMouseHoverWorker>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
```

**Comment by huguesv** [comment]
I saw this one twice and @AlexanderSher saw it a couple of times too.

**Comment by huguesv** [comment]
Could it be `analysis.Entry.DocumentUri` because `analysis.Entry` is `null`?
```
        internal async Task<QuickInfo> GetQuickInfoAsync(AnalysisEntry entry, ITextView view, SnapshotPoint point) {
            Debug.Assert(entry.Analyzer == this);

            var analysis = await GetExpressionAtPointAsync(point, ExpressionAtPointPurpose.Hover, TimeSpan.FromMilliseconds(200.0)).ConfigureAwait(false);

            if (analysis != null) {
                var location = analysis.Location;
                var req = new AP.QuickInfoRequest() {
                    expr = analysis.Text,
                    column = location.Column,
                    line = location.Line,
                    documentUri = analysis.Entry.DocumentUri
                };

                var quickInfo = await SendRequestAsync(req).ConfigureAwait(false);

                if (!string.IsNullOrEmpty(quickInfo?.text)) {
                    return new QuickInfo(quickInfo.text, analysis.Span);
                }
            }

            return null;
        }
```

**Comment by huguesv** [comment]
It comes from PythonTextBufferInfo.AnalysisEntry which has one return `null`, so we have to expect that.
```
        public AnalysisEntry AnalysisEntry {
            get {
                var entry = Volatile.Read(ref _analysisEntry);
                if (entry != null && (entry.Analyzer == null || !entry.Analyzer.IsActive)) {
                    // Analyzer has closed, so clear it out from our info.
                    TraceWithStack("AnalyzerExpired", entry.Analyzer);
                    var previous = TrySetAnalysisEntry(null, entry);
                    if (previous != entry) {
                        // The entry has already been updated, so return the new one
                        return previous;
                    }
                    InvokeSinks(new PythonTextBufferInfoEventArgs(PythonTextBufferInfoEvents.AnalyzerExpired));
                    return null;
                }
                return entry;
            }
        }
```
