### ISSUE TITLE
REPL indent is not calculated correctly

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#3722]
(Reported at https://developercommunity.visualstudio.com/content/problem/191564/python-interactive-hangs-on-import.html)

Saw this exception causing problems in an interactive window. This likely means that the spaces returned from our smart indent provider did not take into account the current prompt length (which is subtracted from our return value and then passed as `virtualSpaces`).

```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: virtualSpaces
   at Microsoft.VisualStudio.Text.VirtualSnapshotPoint..ctor(SnapshotPoint position, Int32 virtualSpaces)
   at Microsoft.VisualStudio.InteractiveWindow.InteractiveWindow.UIThreadOnly.IndentCurrentLine(SnapshotPoint caretPosition)
   at Microsoft.VisualStudio.InteractiveWindow.InteractiveWindow.UIThreadOnly.CaretPositionChanged(Object sender, CaretPositionChangedEventArgs e)
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by huguesv** [comment]
With the fix above, it's no longer indenting (well it indents - 4). I have default prompts.
![image](https://user-images.githubusercontent.com/1696845/36113981-77d6e616-0fe3-11e8-9331-63e6e9a140d6.png)

**Comment by zooba** [comment]
This is also the cause of the indent being wrong when you have differing length prompts (e.g. set `sys.ps2 = '. '` and count the spaces inserted when you go to the second line).

As for the issues with the attempted fix, I'd guess we're seeing some sort of race condition when mapping the new line back to the projection buffer and that is failing. Hard to tell whether it's throwing or giving us the wrong line and so we're subtracting too many spaces, but given the original error I'd guess we're miscalculating to exactly zero somehow or the errors would be more obvious.
