### ISSUE TITLE
Visual Studio Startup Error Message

### ISSUE THREAD

**Issue by WayneKiely** [Microsoft/PTVS#3746]
MS Visual Studio started giving this message at startup a couple of days ago.  Upgrading to Build: 3.0.17320.1 out today made no change.  

[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

Build: 3.0.17320.1

System.ArgumentException: Path was invalid
Parameter name: root ---> System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString, UriKind uriKind)
   at Microsoft.PythonTools.Infrastructure.PathUtils.MakeUri(String path, Boolean isDirectory, UriKind kind, String throwParameterName)
   --- End of inner exception stack trace ---
   at Microsoft.PythonTools.Infrastructure.PathUtils.MakeUri(String path, Boolean isDirectory, UriKind kind, String throwParameterName)
   at Microsoft.PythonTools.Infrastructure.PathUtils.GetAbsoluteDirectoryPath(String root, String relativePath)
   at Microsoft.PythonTools.Repl.PythonCommonInteractiveEvaluator.GetScriptsPath(IServiceProvider provider, String displayName, InterpreterConfiguration config, Boolean onlyIfExists)
```

**Comment by zooba** [comment]
This is fixed in our upcoming release. Thanks for reporting it!
