### ISSUE TITLE
Error in ParseFullyQualifiedTestName

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#3748]
Create new python application
Add new item, unit test
Open test explorer
Run tests

Note: Sometimes running the tests again works ok.

Found while testing on 15.6

```
[2/15/2018 9:53:18 AM Informational] ------ Run test started ------
[2/15/2018 9:53:19 AM Error] System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.PythonTools.TestAdapter.TestReader.ParseFullyQualifiedTestName(String fullyQualifiedName, String& modulePath, String& className, String& methodName)
   at Microsoft.PythonTools.TestAdapter.TestExecutor.TestRunner.<GetTestCases>d__35.MoveNext()
   at Microsoft.PythonTools.TestAdapter.TestExecutor.TestRunner.GetArguments(String testList)
   at Microsoft.PythonTools.TestAdapter.TestExecutor.TestRunner.Run()
[2/15/2018 9:53:20 AM Informational] ========== Run test finished: 0 run (0:00:01.287934) ==========

```

![image](https://user-images.githubusercontent.com/1696845/36273270-d3dd7522-1238-11e8-978f-22c2bae63e59.png)

**Comment by huguesv** [comment]
We discover the test with a fully qualified name that is delimited with ":", and when test explorer calls us back to execute, the qualified name is now delimited with ".".

Is there any way we can be at fault here? It seems like this functionality broke without us making any change.

At discovery, when we report the test:
![image](https://user-images.githubusercontent.com/1696845/36283941-eb5b2790-125a-11e8-9efe-23c7ebde117f.png)

When we get called to execute:
![image](https://user-images.githubusercontent.com/1696845/36283965-f8e88254-125a-11e8-994f-f60436b73656.png)

**Comment by huguesv** [comment]
Internal bug 568443

**Comment by huguesv** [comment]
Fixed in VS.
