### ISSUE TITLE
Cannot start profiling with WinPython

### ISSUE THREAD

**Issue by int19h** [Microsoft/PTVS#377]
WinPython 3.4.3.3 64-bit. When starting a new session, the following is seen in the console window:
```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio - Profiling\2.2\proflaun.py", line 35, in <module>
    vspyprof.profile(__file__, globals(), locals(), profdll)
  File "C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio - Profiling\2.2\vspyprof.py", line 42, in profile
    pyprofdll = ctypes.PyDLL(profdll)
  File "C:\WinPython-64bit-3.4.3.3\python-3.4.3.amd64\lib\ctypes\__init__.py", line 351, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application
Press any key to continue . . .
```

**Comment by int19h** [comment]
This is because I had the environment wrongly registered as 32-bit.
