### ISSUE TITLE
AssertionError 0 < 0 <= 0 in Jupyter REPL

### ISSUE THREAD

**Issue by zooba** [microsoft/PTVS#3817]
You sometimes see this error when resetting:

```
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "D:\Anaconda3_510_x64\lib\site-packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "D:\Anaconda3_510_x64\lib\site-packages\ipykernel\kernelbase.py", line 434, in complete_request
    matches = self.do_complete(code, cursor_pos)
  File "D:\Anaconda3_510_x64\lib\site-packages\ipykernel\ipkernel.py", line 262, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "D:\Anaconda3_510_x64\lib\site-packages\ipykernel\ipkernel.py", line 287, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "D:\Anaconda3_510_x64\lib\site-packages\IPython\core\completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "D:\Anaconda3_510_x64\lib\site-packages\IPython\core\completer.py", line 1791, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "D:\Anaconda3_510_x64\lib\site-packages\IPython\core\completer.py", line 1828, in _completions
    cursor_line, cursor_column = position_to_cursor(full_text, offset)
  File "D:\Anaconda3_510_x64\lib\site-packages\IPython\core\completer.py", line 871, in position_to_cursor
    assert 0 < offset <= len(text) , "0 < %s <= %s" % (offset , len(text))
AssertionError: 0 < 0 <= 0
```

It has been reported at https://github.com/ipython/ipython/issues/11029, so hopefully a newer version of `ipython` can fix it. Until then, there's nothing we can really do from our side.

**Comment by zooba** [comment]
This is also the cause of the serious slowness while typing.
