### ISSUE TITLE
Attaching existing virtual environment

### ISSUE THREAD

**Issue by jinngynn** [Microsoft/PTVS#3830]
i have set up a virtual environment; it works from a command line.
then, in VS17, i tried attaching the solution to this environment:
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 15.6.18045.1

System.ArgumentException: Parameter "include" cannot have zero length.
   at Microsoft.Build.Shared.ErrorUtilities.VerifyThrowArgumentLength(String parameter, String parameterName)
   at Microsoft.Build.Construction.ProjectRootElement.AddItem(String itemType, String include, IEnumerable`1 metadata)
   at Microsoft.Build.Evaluation.Project.AddItem(String itemType, String unevaluatedInclude, IEnumerable`1 metadata)
   at Microsoft.PythonTools.Project.PythonProjectNode.AddInterpreterReference(InterpreterConfiguration config)
   at Microsoft.PythonTools.Project.PythonProjectNode.<CreateOrAddVirtualEnvironment>d__191.MoveNext()
```

**Comment by zooba** [comment]
Thanks! We'll take a look at this one.
