### ISSUE TITLE
NullReferenceException in GeneratorInfo while analyzing a simple module

### ISSUE THREAD

**Issue by lostmsu** [Microsoft/PTVS#3918]
Here's what I am trying to do:
```csharp
var container = InterpreterCatalog.CreateContainer(
    typeof(IInterpreterOptionsService).Assembly.Location,
    typeof(IInterpreterRegistryService).Assembly.Location,
    GetType().Assembly.Location);
var interpreterRegistry = container.GetExport<IInterpreterRegistryService>().Value;
var interpreterFactory = interpreterRegistry.Interpreters.First(interpreter => interpreter.GetLanguageVersion() == PythonLanguageVersion.V36);
var analyzer = PythonAnalyzer.Create(interpreterFactory);
IPythonProjectEntry module = analyzer.AddModule(moduleName, fileName);
var errorSink = new CollectingErrorSink();
using (var reader = new StringReader(source))
using (var p = module.BeginParse()) {
    Parser parser = Parser.CreateParser(reader, analyzer.LanguageVersion,
        new ParserOptions { BindReferences = true, ErrorSink = errorSink });
    p.Tree = parser.ParseFile();
    p.Complete();
}
foreach (ErrorResult error in errorSink.Errors) {
    Console.Error.WriteLine(error.ToString());
}
module.Analyze(CancellationToken.None);
```

The source is
```python
import itertools

def iter_primes():
     # an iterator of all numbers between 2 and +infinity
     numbers = itertools.count(2)

     # generate primes forever
     while True:
         # get the first number from the iterator (always a prime)
         prime = numbers.next()
         yield prime

         # this code iteratively builds up a chain of
         # filters...slightly tricky, but ponder it a bit
         numbers = itertools.ifilter(prime.__rmod__, numbers)

for p in iter_primes():
    if p > 1000:
        break
    print(p)
```

Result StackTrace:	
```
at Microsoft.PythonTools.Analysis.Values.GeneratorInfo..ctor(PythonAnalyzer projectState, IPythonProjectEntry entry)
   at Microsoft.PythonTools.Analysis.Analyzer.FunctionScope..ctor(FunctionInfo function, Node node, InterpreterScope declScope, IPythonProjectEntry declModule)
   at Microsoft.PythonTools.Analysis.Analyzer.FunctionAnalysisUnit..ctor(FunctionInfo function, AnalysisUnit declUnit, InterpreterScope declScope, IPythonProjectEntry declEntry)
   at Microsoft.PythonTools.Analysis.Values.FunctionInfo..ctor(FunctionDefinition node, AnalysisUnit declUnit, InterpreterScope declScope)
   at Microsoft.PythonTools.Analysis.Analyzer.OverviewWalker.AddFunction(FunctionDefinition node, AnalysisUnit outerUnit, InterpreterScope prevScope)
   at Microsoft.PythonTools.Analysis.Analyzer.OverviewWalker.Walk(FunctionDefinition node)
   at Microsoft.PythonTools.Parsing.Ast.FunctionDefinition.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Analysis.Analyzer.OverviewWalker.Walk(SuiteStatement node)
   at Microsoft.PythonTools.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Parsing.Ast.PythonAst.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Analysis.ProjectEntry.Parse(Boolean enqueueOnly, CancellationToken cancel)
   at Microsoft.PythonTools.Analysis.ProjectEntry.Analyze(CancellationToken cancel, Boolean enqueueOnly)
   at Microsoft.PythonTools.Analysis.ProjectEntry.Analyze(CancellationToken cancel)

Test method yielding threw exception: 
System.NullReferenceException: Object reference not set to an instance of an object.
```

Module name and file name are yielding and yielding.py respectivey.

The same issue also occurs if I try to create InterpreterFactory like this: `InterpreterFactoryCreator.CreateAnalysisInterpreterFactory(PythonLanguageVersion.V36.ToVersion())` bypassing `IInterpreterRegistryService`

Might be missing something in initialization steps really.
This started happening after upgrade to VS 15.6, still happens in VS 15.6.3

**Comment by zooba** [comment]
You need to also call and wait for `analyzer.ReloadModulesAsync()` before you can start analyzing, or you can call `PythonAnalyzer.CreateAsync()` instead of regular `.Create()`.

I'll add a more specific error message for this case - there is documentation on that function (but we don't ship the .xml files, so you wouldn't see that unless you're building from source).
