### ISSUE TITLE
Assert in AnalysisDictionary.AddWorker

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#3940]
It happened while trying to reproduce https://github.com/Microsoft/PTVS/issues/3829

Using code from PR https://github.com/Microsoft/PTVS/pull/3844

```
   at Microsoft.PythonTools.Analysis.AnalysisDictionary`2.AddWorker(Bucket[] buckets, TKey key, TValue value, Int32 hc, Boolean throwIfExists) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\AnalysisDictionary.cs:line 199
   at Microsoft.PythonTools.Analysis.AnalysisDictionary`2.Add(Bucket[] buckets, TKey key, TValue value, Boolean throwIfExists) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\AnalysisDictionary.cs:line 189
   at Microsoft.PythonTools.Analysis.AnalysisDictionary`2.AddOne(TKey key, TValue value, Boolean throwIfExists) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\AnalysisDictionary.cs:line 112
   at Microsoft.PythonTools.Analysis.AnalysisDictionary`2.set_Item(TKey key, TValue value) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\AnalysisDictionary.cs:line 549
   at Microsoft.PythonTools.Analysis.Analyzer.InterpreterScope.AddVariable(String name, VariableDef variable) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Analyzer\InterpreterScope.cs:line 268
   at Microsoft.PythonTools.Analysis.Analyzer.InterpreterScope.CreateVariable(Node node, AnalysisUnit unit, String name, Boolean addRef) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Analyzer\InterpreterScope.cs:line 244
   at Microsoft.PythonTools.Analysis.Analyzer.ModuleScope.SetModuleVariable(String name, IAnalysisSet value) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Analyzer\ModuleScope.cs:line 33
   at Microsoft.PythonTools.Analysis.Values.ModuleInfo.EnsureModuleVariables(PythonAnalyzer state) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Values\ModuleInfo.cs:line 71
   at Microsoft.PythonTools.Analysis.ProjectEntry.Parse(Boolean enqueueOnly, CancellationToken cancel) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\ProjectEntry.cs:line 228
   at Microsoft.PythonTools.Analysis.ProjectEntry.Analyze(CancellationToken cancel, Boolean enqueueOnly) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\ProjectEntry.cs:line 175
   at Microsoft.PythonTools.Intellisense.AnalysisQueue.Worker(Object threadStarted) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Intellisense\AnalysisQueue.cs:line 233
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
```

followed by

```
addIndex was not found while scanning buckets. This normally indicates a race condition - AnalysisDictionary does not support simultaneous mutations.

   at Microsoft.PythonTools.Analysis.AnalysisDictionary`2.AddWorker(Bucket[] buckets, TKey key, TValue value, Int32 hc, Boolean throwIfExists) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\AnalysisDictionary.cs:line 230
   at Microsoft.PythonTools.Analysis.AnalysisDictionary`2.Add(Bucket[] buckets, TKey key, TValue value, Boolean throwIfExists) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\AnalysisDictionary.cs:line 189
   at Microsoft.PythonTools.Analysis.AnalysisDictionary`2.AddOne(TKey key, TValue value, Boolean throwIfExists) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\AnalysisDictionary.cs:line 112
   at Microsoft.PythonTools.Analysis.AnalysisDictionary`2.set_Item(TKey key, TValue value) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\AnalysisDictionary.cs:line 549
   at Microsoft.PythonTools.Analysis.Analyzer.InterpreterScope.AddVariable(String name, VariableDef variable) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Analyzer\InterpreterScope.cs:line 268
   at Microsoft.PythonTools.Analysis.Analyzer.InterpreterScope.CreateVariable(Node node, AnalysisUnit unit, String name, Boolean addRef) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Analyzer\InterpreterScope.cs:line 244
   at Microsoft.PythonTools.Analysis.Analyzer.ModuleScope.SetModuleVariable(String name, IAnalysisSet value) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Analyzer\ModuleScope.cs:line 33
   at Microsoft.PythonTools.Analysis.Values.ModuleInfo.EnsureModuleVariables(PythonAnalyzer state) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Values\ModuleInfo.cs:line 71
   at Microsoft.PythonTools.Analysis.ProjectEntry.Parse(Boolean enqueueOnly, CancellationToken cancel) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\ProjectEntry.cs:line 228
   at Microsoft.PythonTools.Analysis.ProjectEntry.Analyze(CancellationToken cancel, Boolean enqueueOnly) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\ProjectEntry.cs:line 175
   at Microsoft.PythonTools.Intellisense.AnalysisQueue.Worker(Object threadStarted) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Intellisense\AnalysisQueue.cs:line 233
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
```

and
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.

   at Microsoft.PythonTools.Analysis.AnalysisDictionary`2.AddWorker(Bucket[] buckets, TKey key, TValue value, Int32 hc, Boolean throwIfExists) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\AnalysisDictionary.cs:line 236
   at Microsoft.PythonTools.Analysis.AnalysisDictionary`2.Add(Bucket[] buckets, TKey key, TValue value, Boolean throwIfExists) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\AnalysisDictionary.cs:line 189
   at Microsoft.PythonTools.Analysis.AnalysisDictionary`2.AddOne(TKey key, TValue value, Boolean throwIfExists) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\AnalysisDictionary.cs:line 112
   at Microsoft.PythonTools.Analysis.AnalysisDictionary`2.set_Item(TKey key, TValue value) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\AnalysisDictionary.cs:line 549
   at Microsoft.PythonTools.Analysis.Analyzer.InterpreterScope.AddVariable(String name, VariableDef variable) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Analyzer\InterpreterScope.cs:line 268
   at Microsoft.PythonTools.Analysis.Analyzer.InterpreterScope.CreateVariable(Node node, AnalysisUnit unit, String name, Boolean addRef) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Analyzer\InterpreterScope.cs:line 244
   at Microsoft.PythonTools.Analysis.Analyzer.ModuleScope.SetModuleVariable(String name, IAnalysisSet value) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Analyzer\ModuleScope.cs:line 33
   at Microsoft.PythonTools.Analysis.Values.ModuleInfo.EnsureModuleVariables(PythonAnalyzer state) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Values\ModuleInfo.cs:line 71
   at Microsoft.PythonTools.Analysis.ProjectEntry.Parse(Boolean enqueueOnly, CancellationToken cancel) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\ProjectEntry.cs:line 228
   at Microsoft.PythonTools.Analysis.ProjectEntry.Analyze(CancellationToken cancel, Boolean enqueueOnly) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\ProjectEntry.cs:line 175
   at Microsoft.PythonTools.Intellisense.AnalysisQueue.Worker(Object threadStarted) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Intellisense\AnalysisQueue.cs:line 233


   at Microsoft.PythonTools.Analysis.LanguageServer.Server.Analysis_UnhandledException(Object sender, UnhandledExceptionEventArgs e) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\LanguageServer\Server.cs:line 69
   at Microsoft.PythonTools.Intellisense.AnalysisQueue.Worker(Object threadStarted) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Intellisense\AnalysisQueue.cs:line 238
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
```

No colorization for the class after hitting ignore.

![image](https://user-images.githubusercontent.com/1696845/37787335-f0160e5e-2dbb-11e8-98e7-cb0d54dd57a2.png)

**Comment by AlexanderSher** [comment]
Not repro anymore. Maybe because of the disabled live linting or because of the fixes in #4087
