### ISSUE TITLE
Error when closing Python Project

### ISSUE THREAD

**Issue by SvenLauterbach** [Microsoft/PTVS#3984]
Hi, 

when closing a Python Project via File->Close Solution I receive a dialog with this information:

[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 15.6.18072.2

System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Concurrent.ConcurrentDictionary`2.TryRemove(TKey key, TValue& value)
   at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.<UnloadFileAsync>d__139.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
```

I couldn't reproduce it a second time, but maybe you can work with the information above.

**Comment by zooba** [comment]
Thanks! This is the same as #3826, which we have fixed for our next release.
