### ISSUE TITLE
Remote attach with source reference crashes VS

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/PTVS#4033]
![image](https://user-images.githubusercontent.com/3840081/38583634-816ef44a-3cc8-11e8-916d-d2b72646ee68.png)

Repro steps:
on a remote machine:
1. Create a py file with following content `one.py`:
```py
import time


for x in range(10000):
    time.sleep(1)
    print(x)
```
2. start ptvsd for remote debugging:
```
python3 -m ptvsd --server --port 8765 --file one.py
```

On a machine with VS:
1. Go to Debug > Attach to process ...
2. Select Connection type : python remote, Connection target: tcp://<remote name>:8765
3. Hit pause after attaching

**Comment by huguesv** [comment]
Source reference is a feature added post 4.0.0a6, so it is not an issue for 15.7

**Comment by karthiknadig** [comment]
Still seeing this issue:
![image](https://user-images.githubusercontent.com/3840081/42394392-d2dd0242-810e-11e8-8c98-746af0b8e547.png)


```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
^ScriptDocument0 one.py is not a valid URI.

Unhandled exception in Microsoft.PythonTools.Editor.PythonTextBufferInfo.GetOrCreateDocumentUri (C:\GIT\PTVS\Python\Product\PythonTools\PythonTools\Editor\PythonTextBufferInfo.cs:196)

System.UriFormatException: Invalid URI: The format of the URI could not be determined.

   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)

   at System.Uri..ctor(String uriString)

   at Microsoft.PythonTools.Editor.PythonTextBufferInfo.GetOrCreateDocumentUri() in C:\GIT\PTVS\Python\Product\PythonTools\PythonTools\Editor\PythonTextBufferInfo.cs:line 194



   at Microsoft.PythonTools.Editor.PythonTextBufferInfo.GetOrCreateDocumentUri() in C:\GIT\PTVS\Python\Product\PythonTools\PythonTools\Editor\PythonTextBufferInfo.cs:line 196

   at System.Lazy`1.CreateValue()

   at System.Lazy`1.LazyInitValue()

   at System.Lazy`1.get_Value()

   at Microsoft.PythonTools.Editor.PythonTextBufferInfo.get_DocumentUri() in C:\GIT\PTVS\Python\Product\PythonTools\PythonTools\Editor\PythonTextBufferInfo.cs:line 211

   at Microsoft.PythonTools.Intellisense.IntellisenseController.<ConnectSubjectBufferAsync>d__25.MoveNext() in C:\GIT\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\IntellisenseController.cs:line 230

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.PythonTools.Intellisense.IntellisenseController.ConnectSubjectBufferAsync(PythonTextBufferInfo buffer)

   at Microsoft.PythonTools.Intellisense.IntellisenseController.<ConnectSubjectBuffer>d__23.MoveNext() in C:\GIT\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\IntellisenseController.cs:line 183

   at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.PythonTools.Intellisense.IntellisenseController.ConnectSubjectBuffer(ITextBuffer subjectBuffer)

   at Microsoft.PythonTools.Intellisense.IntellisenseControllerProvider.TryCreateIntellisenseController(ITextView textView, IList`1 subjectBuffers) in C:\GIT\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\IntellisenseControllerProvider.cs:line 61

   at Microsoft.VisualStudio.Language.Intellisense.Implementation.IntellisenseManagerConnectionListener.<>c__DisplayClass8_1.<SubjectBuffersConnected>b__1(IIntellisenseControllerProvider provider)

   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InstantiateExtension[TExtension,TMetadata,TExtensionInstance](Object errorSource, Lazy`2 provider, Func`2 getter)

   at Microsoft.VisualStudio.Language.Intellisense.Implementation.IntellisenseManagerConnectionListener.SubjectBuffersConnected(ITextView textView, ConnectionReason reason, IReadOnlyCollection`1 subjectBuffers)

   at Microsoft.VisualStudio.Text.Editor.Implementation.ConnectionManager.NonWpfListener.SubjectBuffersConnected(IWpfTextView textView, ConnectionReason reason, Collection`1 subjectBuffers)

   at Microsoft.VisualStudio.Text.Editor.Implementation.ConnectionManager.<>c__DisplayClass7_3.<.ctor>b__3()

   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)

   at Microsoft.VisualStudio.Text.Editor.Implementation.ConnectionManager..ctor(IWpfTextView textView, ICollection`1 wpfTextViewConnectionListeners, ICollection`1 nonWpfTextViewConnectionListeners, GuardedOperations guardedOperations)

   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.Initialize()

   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextEditorFactoryService.InitializeTextView(IWpfTextView view)

   at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.Init_InitializeWpfTextView()

   at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.Init_OnActivation()

   at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.SetInfo()

   at Microsoft.VisualStudio.Editor.Implementation.CompoundTextViewWindow.SetInfo()

   at Microsoft.VisualStudio.PlatformUI.StatusBarService.OnElementValueChanged(UInt32 elementid, Object varValueOld, Object varValueNew)

   at Microsoft.Internal.VisualStudio.Shell.Interop.IVsTrackSelectionExPrivate.Register()

   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.ConnectSelectionContext()

   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.Activate()

   at Microsoft.VisualStudio.Platform.WindowManagement.WindowManagerService.viewManager_ActiveViewChanged(Object sender, ActiveViewChangedEventArgs e)

   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)

   at Microsoft.VisualStudio.PlatformUI.ExtensionMethods.RaiseEvent[TEventArgs](EventHandler`1 eventHandler, Object source, TEventArgs args)

   at Microsoft.VisualStudio.PlatformUI.Shell.ViewManager.SetActiveView(View view, ActivationType type)

   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.ShowInternal(ShowFlags showFlags)

   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.<Show>b__505_0()

   at Microsoft.VisualStudio.ErrorHandler.CallWithCOMConvention(Func`1 method, Boolean reportError, Boolean setShellErrorInfo)

   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.Show()

   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.MarshalingWindowFrame.<Microsoft.VisualStudio.Shell.Interop.IVsWindowFrame.Show>b__12_0()

   at Microsoft.VisualStudio.Shell.ThreadHelper.Invoke[TResult](Func`1 method)

   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.MarshalingWindowFrame.Microsoft.VisualStudio.Shell.Interop.IVsWindowFrame.Show()


```
