### ISSUE TITLE
"An unexpected error occurred" when trying to install a python package

### ISSUE THREAD

**Issue by MMeketon** [Microsoft/PTVS#4047]
I opened up VS (15.7.18083.1).  Opened up an existing solution that had a Python project.  Went to install a package and pulled down the "Packages (Conda)" option.  Then the "unexpected error" occurred and told me to create an issue with the below.  Note that I had not typed in the name of the package I wanted to install.

[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 15.7.18083.1

System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Cannot access child value on Newtonsoft.Json.Linq.JValue.
   at Newtonsoft.Json.Linq.JToken.get_Item(Object key)
   at Newtonsoft.Json.Linq.JToken.Value[T](Object key)
   at Microsoft.PythonTools.Interpreter.CondaPackageManager.<>c.<CacheInstalledPackagesAsync>b__58_0(JToken j)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.PythonTools.Interpreter.CondaPackageManager.<CacheInstalledPackagesAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Interpreter.CondaPackageManager.<GetInstalledPackagesAsync>d__63.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Project.InterpretersNode.<RefreshPackagesAsync>d__25.MoveNext()
   --- End of inner exception stack trace ---
   at System.AggregateException.Handle(Func`2 predicate)
   at Microsoft.PythonTools.Infrastructure.TaskExtensions.<>c__7`1.<SilenceException>b__7_0(Task t)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
---> (Inner Exception #0) System.InvalidOperationException: Cannot access child value on Newtonsoft.Json.Linq.JValue.
   at Newtonsoft.Json.Linq.JToken.get_Item(Object key)
   at Newtonsoft.Json.Linq.JToken.Value[T](Object key)
   at Microsoft.PythonTools.Interpreter.CondaPackageManager.<>c.<CacheInstalledPackagesAsync>b__58_0(JToken j)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.PythonTools.Interpreter.CondaPackageManager.<CacheInstalledPackagesAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Interpreter.CondaPackageManager.<GetInstalledPackagesAsync>d__63.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Project.Interpr

**Comment by huguesv** [comment]
Thanks for the report!

**Comment by huguesv** [comment]
Hi @MMeketon would it be possible to provide us your package list results by running this command? That's the json we're having trouble to parse, and I'm not clear on what could be triggering the error.

You can email it to ptvshelp at microsoft.com if you prefer.

`conda list --json`

or

`conda list -p "c:\path\to\conda\env" --json`
(if it's not the root conda env)

conda.exe is in your root conda env's scripts subfolder

Thanks!

**Comment by huguesv** [comment]
Oh, might as well include the results of `conda -V` too.

**Comment by huguesv** [comment]
Anaconda 4.2.0 installs conda 4.2.9, which has a different json format. Workaround is to update conda. We'll need to handle this more gracefully.

I installed Anaconda 4.2.0 and was able to reproduce the exact error. The problem is that the json format is different on that old version. Thanks for your help!

Old format:
```
 [
  "_license-1.1-py35_1",
  "_nb_ext_conf-0.3.0-py35_0",
  "alabaster-0.7.9-py35_0",
  "anaconda-4.2.0-np111py35_0",
  "anaconda-clean-1.0.0-py35_0",
  "anaconda-client-1.5.1-py35_0",
  "anaconda-navigator-1.3.1-py35_0",
  "argcomplete-1.0.0-py35_1",
  "astroid-1.4.7-py35_0",
  "astropy-1.2.1-np111py35_0",
  "babel-2.3.4-py35_0",
  "backports-1.0-py35_0",
  "beautifulsoup4-4.5.1-py35_0",
  "bitarray-0.8.1-py35_1",
  "blaze-0.10.1-py35_0",
```
New format:
 ```
[
  {
    "base_url": null,
    "build_number": 0,
    "build_string": "py27h9111531_0",
    "channel": "defaults",
    "dist_name": "_ipyw_jlab_nb_ext_conf-0.1.0-py27h9111531_0",
    "name": "_ipyw_jlab_nb_ext_conf",
    "platform": null,
    "version": "0.1.0",
    "with_features_depends": null
  },
  {
    "base_url": null,
    "build_number": 0,
    "build_string": "py27h2cab13d_0",
    "channel": "defaults",
    "dist_name": "alabaster-0.7.10-py27h2cab13d_0",
    "name": "alabaster",
    "platform": null,
    "version": "0.7.10",
    "with_features_depends": null
  },
```
