### ISSUE TITLE
Updating custom environment fails

### ISSUE THREAD

**Issue by CBrauer** [Microsoft/PTVS#4059]
I got the following error when I tried to update an environment (Python Environments window):
_

[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred
_
[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 15.6.18072.2

System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Concurrent.ConcurrentDictionary`2.TryRemove(TKey key, TValue& value)
   at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.<UnloadFileAsync>d__139.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
```

**Comment by zooba** [comment]
I don't recall the last time this was reported, but we've definitely fixed it for the next release. Thanks for letting us know!
