### ISSUE TITLE
devenv.exe An unexpected error occured

### ISSUE THREAD

**Issue by OldDon** [Microsoft/PTVS#4121]
Hi there,

I am new to this, very new. So, please forgive me for any unintended stepping on norms.

I was simply working with VS Python and adding a function. I got no further than typing 'def ' and the system through this error.

I hope that this is useful.

Many thanks.

[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 15.6.18072.2

System.ArgumentException: Start and End must be well ordered
   at Microsoft.PythonTools.SourceSpan.ValidateLocations(SourceLocation start, SourceLocation end)
   at Microsoft.PythonTools.Intellisense.LocationTracker.Translate(SourceSpan span, Int32 fromVersion, Int32 toVersion)
   at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.ConvertNavigations(Navigation[] navigations, LocationTracker translator, Int32 fromVersion, ITextSnapshot snapshot)
   at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.ConvertNavigations(Navigation[] navigations, LocationTracker translator, Int32 fromVersion, ITextSnapshot snapshot)
   at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.<GetNavigationsAsync>d__169.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudioTools.UIThread.<>c__DisplayClass18_0`1.<<InvokeTask>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Navigation.DropDownBarClient.<RefreshNavigationsFromAnalysisEntry>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Navigation.DropDownBarClient.<Microsoft-PythonTools-Editor-IPythonTextBufferInfoEventSink-PythonTextBufferEventAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
```

**Comment by huguesv** [comment]
Thanks! We've already fixed it to prevent the crash in the upcoming 15.7 release.
