### ISSUE TITLE
AF 'Accessing Mro before SetBases has been called'

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/PTVS#4126]
Haven't reproed in VS yet, but reproes in VSC consistently.

- Clone https://github.com/davidhalter/parso
- Open folder

```
Loading files from f:\Parso
FailFast: Accessing Mro before SetBases has been called

   at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
   at Microsoft.PythonTools.Interpreter.Ast.AstPythonType.get_Mro() in F:\PTVS\Python\Product\Analysis\Interpreter\Ast\AstPythonType.cs:line 91
   at Microsoft.PythonTools.Interpreter.Ast.AstPythonType.GetMember(IModuleContext context, String name) in F:\PTVS\Python\Product\Analysis\Interpreter\Ast\AstPythonType.cs:line 199
   at Microsoft.PythonTools.Interpreter.Ast.NameLookupContext.GetValueFromMember(MemberExpression expr, LookupOptions options) in F:\PTVS\Python\Product\Analysis\Interpreter\Ast\NameLookupContext.cs:line 224
   at Microsoft.PythonTools.Interpreter.Ast.NameLookupContext.GetValueFromExpression(Expression expr, LookupOptions options) in F:\PTVS\Python\Product\Analysis\Interpreter\Ast\NameLookupContext.cs:line 184
   at Microsoft.PythonTools.Interpreter.Ast.NameLookupContext.GetValueFromExpression(Expression expr) in F:\PTVS\Python\Product\Analysis\Interpreter\Ast\NameLookupContext.cs:line 172
   at Microsoft.PythonTools.Interpreter.Ast.AstAnalysisWalker.Walk(AssignmentStatement node) in F:\PTVS\Python\Product\Analysis\Interpreter\Ast\AstAnalysisWalker.cs:line 122
   at Microsoft.PythonTools.Parsing.Ast.AssignmentStatement.Walk(PythonWalker walker) in F:\PTVS\Python\Product\Analysis\Parsing\Ast\AssignmentStatement.cs:line 41
   at Microsoft.PythonTools.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker) in F:\PTVS\Python\Product\Analysis\Parsing\Ast\SuiteStatement.cs:line 37
   at Microsoft.PythonTools.Parsing.Ast.ClassDefinition.Walk(PythonWalker walker) in F:\PTVS\Python\Product\Analysis\Parsing\Ast\ClassDefinition.cs:line 171
   at Microsoft.PythonTools.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker) in F:\PTVS\Python\Product\Analysis\Parsing\Ast\SuiteStatement.cs:line 37
   at Microsoft.PythonTools.Parsing.Ast.PythonAst.Walk(PythonWalker walker) in F:\PTVS\Python\Product\Analysis\Parsing\Ast\PythonAst.cs:line 83
   at Microsoft.PythonTools.Interpreter.Ast.AstPythonModule..ctor(String moduleName, IPythonInterpreter interpreter, PythonAst ast, String filePath) in F:\PTVS\Python\Product\Analysis\Interpreter\Ast\AstPythonModule.cs:line 116
   at Microsoft.PythonTools.Interpreter.Ast.AstPythonModule.FromStream(IPythonInterpreter interpreter, Stream sourceFile, String fileName, PythonLanguageVersion langVersion, String moduleFullName) in F:\PTVS\Python\Product\Analysis\Interpreter\Ast\AstPythonModule.cs:line 81
   at Microsoft.PythonTools.Interpreter.Ast.AstPythonModule.FromFile(IPythonInterpreter interpreter, String sourceFile, PythonLanguageVersion langVersion, String moduleFullName) in F:\PTVS\Python\Product\Analysis\Interpreter\Ast\AstPythonModule.cs:line 50
   at Microsoft.PythonTools.Interpreter.Ast.AstPythonInterpreter.<ImportFromSearchPathsAsyncWorker>d__34.MoveNext() in F:\PTVS\Python\Product\Analysis\Interpreter\Ast\AstPythonInterpreter.cs:line 398
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.PythonTools.Interpreter.Ast.AstPythonInterpreter.ImportFromSearchPathsAsyncWorker(String name)
   at Microsoft.PythonTools.Interpreter.Ast.AstPythonInterpreter.<ImportFromSearchPathsAsync>d__33.MoveNext() in F:\PTVS\Python\Product\Analysis\Interpreter\Ast\AstPythonInterpreter.cs:line 338
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.PythonTools.Interpreter.Ast.AstPythonInterpreter.ImportFromSearchPathsAsync(String name)
   at Microsoft.PythonTools.Interpreter.Ast.AstPythonInterpreter.ImportModuleOrRetry(String name, Boolean& retry) in F:\PTVS\Python\Product\Analysis\Interpreter\Ast\AstPythonInterpreter.cs:line 267
   at Microsoft.PythonTools.Interpreter.Ast.AstPythonInterpreter.ImportModule(String name) in F:\PTVS\Python\Product\Analysis\Interpreter\Ast\AstPythonInterpreter.cs:line 203
   at Microsoft.PythonTools.Interpreter.Ast.AstNestedPythonModule.GetModule() in F:\PTVS\Python\Product\Analysis\Interpreter\Ast\AstNestedPythonModule.cs:line 57
   at Microsoft.PythonTools.Interpreter.Ast.AstNestedPythonModule.GetMember(IModuleContext context, String name) in F:\PTVS\Python\Product\Analysis\Interpreter\Ast\AstNestedPythonModule.cs:line 73
   at Microsoft.PythonTools.Interpreter.Ast.NameLookupContext.GetValueFromMember(MemberExpression expr, LookupOptions options) in F:\PTVS\Python\Product\Analysis\Interpreter\Ast\NameLookupContext.cs:line 224
   at Microsoft.PythonTools.Interpreter.Ast.NameLookupContext.GetValueFromExpression(Expression expr, LookupOptions options) in F:\PTVS\Python\Product\Analysis\Interpreter\Ast\NameLookupContext.cs:line 184
   at Microsoft.PythonTools.Interpreter.Ast.NameLookupContext.GetValueFromExpression(Expression expr) in F:\PTVS\Python\Product\Analysis\Interpreter\Ast\NameLookupContext.cs:line 172
   at Microsoft.PythonTools.Interpreter.Ast.AstAnalysisWalker.Walk(AssignmentStatement node) in F:\PTVS\Python\Product\Analysis\Interpreter\Ast\AstAnalysisWalker.cs:line 122
   at Microsoft.PythonTools.Parsing.Ast.AssignmentStatement.Walk(PythonWalker walker) in F:\PTVS\Python\Product\Analysis\Parsing\Ast\AssignmentStatement.cs:line 41
   at Microsoft.PythonTools.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker) in F:\PTVS\Python\Product\Analysis\Parsing\Ast\SuiteStatement.cs:line 37
   at Microsoft.PythonTools.Parsing.Ast.PythonAst.Walk(PythonWalker walker) in F:\PTVS\Python\Product\Analysis\Parsing\Ast\PythonAst.cs:line 83
   at Microsoft.PythonTools.Interpreter.Ast.AstScrapedPythonModule.Imported(IModuleContext context) in F:\PTVS\Python\Product\Analysis\Interpreter\Ast\AstScrapedPythonModule.cs:line 230
   at Microsoft.PythonTools.Interpreter.Ast.AstNestedPythonModule.Imported(IModuleContext context) in F:\PTVS\Python\Product\Analysis\Interpreter\Ast\AstNestedPythonModule.cs:line 82
   at Microsoft.PythonTools.Interpreter.Ast.AstAnalysisWalker.Walk(FromImportStatement node) in F:\PTVS\Python\Product\Analysis\Interpreter\Ast\AstAnalysisWalker.cs:line 210
   at Microsoft.PythonTools.Parsing.Ast.FromImportStatement.Walk(PythonWalker walker) in F:\PTVS\Python\Product\Analysis\Parsing\Ast\FromImportStatement.cs:line 61
   at Microsoft.PythonTools.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker) in F:\PTVS\Python\Product\Analysis\Parsing\Ast\SuiteStatement.cs:line 37
   at Microsoft.PythonTools.Parsing.Ast.PythonAst.Walk(PythonWalker walker) in F:\PTVS\Python\Product\Analysis\Parsing\Ast\PythonAst.cs:line 83
   at Microsoft.PythonTools.Interpreter.Ast.AstPythonModule..ctor(String moduleName, IPythonInterpreter interpreter, PythonAst ast, String filePath) in F:\PTVS\Python\Product\Analysis\Interpreter\Ast\AstPythonModule.cs:line 116
   at Microsoft.PythonTools.Interpreter.Ast.AstPythonModule.FromStream(IPythonInterpreter interpreter, Stream sourceFile, String fileName, PythonLanguageVersion langVersion, String moduleFullName) in F:\PTVS\Python\Product\Analysis\Interpreter\Ast\AstPythonModule.cs:line 81
   at Microsoft.PythonTools.Interpreter.Ast.AstPythonModule.FromFile(IPythonInterpreter interpreter, String sourceFile, PythonLanguageVersion langVersion, String moduleFullName) in F:\PTVS\Python\Product\Analysis\Interpreter\Ast\AstPythonModule.cs:line 50
   at Microsoft.PythonTools.Interpreter.Ast.AstPythonInterpreter.<ImportFromSearchPathsAsyncWorker>d__34.MoveNext() in F:\PTVS\Python\Product\Analysis\Interpreter\Ast\AstPythonInterpreter.cs:line 398
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.PythonTools.Interpreter.Ast.AstPythonInterpreter.ImportFromSearchPathsAsyncWorker(String name)
   at Microsoft.PythonTools.Interpreter.Ast.AstPythonInterpreter.<ImportFromSearchPathsAsync>d__33.MoveNext() in F:\PTVS\Python\Product\Analysis\Interpreter\Ast\AstPythonInterpreter.cs:line 338
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.PythonTools.Interpreter.Ast.AstPythonInterpreter.ImportFromSearchPathsAsync(String name)
   at Microsoft.PythonTools.Interpreter.Ast.AstPythonInterpreter.ImportModuleOrRetry(String name, Boolean& retry) in F:\PTVS\Python\Product\Analysis\Interpreter\Ast\AstPythonInterpreter.cs:line 267
   at Microsoft.PythonTools.Interpreter.Ast.AstPythonInterpreter.ImportModule(String name) in F:\PTVS\Python\Product\Analysis\Interpreter\Ast\AstPythonInterpreter.cs:line 203
   at Microsoft.PythonTools.Analysis.ModuleTable.TryImport(String name, ModuleReference& res) in F:\PTVS\Python\Product\Analysis\ModuleTable.cs:line 127
   at Microsoft.PythonTools.Analysis.PythonAnalyzer.GetEntriesThatImportModule(String moduleName, Boolean includeUnresolved) in F:\PTVS\Python\Product\Analysis\PythonAnalyzer.cs:line 286
   at Microsoft.PythonTools.Analysis.LanguageServer.Server.<AddFileAsync>b__60_1(String a) in F:\PTVS\Python\Product\Analysis\LanguageServer\Server.cs:line 463
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.PythonTools.Analysis.LanguageServer.Server.AddFileAsync(Uri documentUri, Uri fromSearchPath, IAnalysisCookie cookie) in F:\PTVS\Python\Product\Analysis\LanguageServer\Server.cs:line 463
   at Microsoft.PythonTools.Analysis.LanguageServer.Server.LoadFileAsync(Uri documentUri) in F:\PTVS\Python\Product\Analysis\LanguageServer\Server.cs:line 369
   at Microsoft.PythonTools.Analysis.LanguageServer.Server.<LoadFromDirectoryAsync>d__66.MoveNext() in F:\PTVS\Python\Product\Analysis\LanguageServer\Server.cs:line 649
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.PythonTools.Analysis.LanguageServer.Server.LoadFromDirectoryAsync(String rootDir)
   at Microsoft.PythonTools.Analysis.LanguageServer.Server.<LoadFromDirectoryAsync>d__66.MoveNext() in F:\PTVS\Python\Product\Analysis\LanguageServer\Server.cs:line 665
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.PythonTools.Analysis.LanguageServer.Server.LoadFromDirectoryAsync(String rootDir)
   at Microsoft.PythonTools.Analysis.LanguageServer.Server.OnAnalyzerCreated(InitializeParams params) in F:\PTVS\Python\Product\Analysis\LanguageServer\Server.cs:line 176
   at Microsoft.PythonTools.Analysis.LanguageServer.Server.<CreateAnalyzerAndNotify>d__25.MoveNext() in F:\PTVS\Python\Product\Analysis\LanguageServer\Server.cs:line 145
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(TResult result)
   at Microsoft.PythonTools.Analysis.LanguageServer.Server.<CreateAnalyzer>d__34.MoveNext() in F:\PTVS\Python\Product\Analysis\LanguageServer\Server.cs:line 334
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(TResult result)
   at Microsoft.PythonTools.Analysis.PythonAnalyzer.<CreateAsync>d__24.MoveNext() in F:\PTVS\Python\Product\Analysis\PythonAnalyzer.cs:line 86
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(Task`1 completedTask)
   at Microsoft.PythonTools.Analysis.PythonAnalyzer.<ReloadModulesAsync>d__29.MoveNext() in F:\PTVS\Python\Product\Analysis\PythonAnalyzer.cs:line 192
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(Task`1 completedTask)
   at Microsoft.PythonTools.Analysis.PythonAnalyzer.<LoadKnownTypesAsync>d__28.MoveNext() in F:\PTVS\Python\Product\Analysis\PythonAnalyzer.cs:line 160
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(TResult result)
   at Microsoft.PythonTools.Analysis.ModuleTable.<TryImportAsync>d__9.MoveNext() in F:\PTVS\Python\Product\Analysis\ModuleTable.cs:line 111
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

```

**Comment by zooba** [comment]
This is probably an invalid assertion inside AstAnalysisWalker. It was intended for full analysis, but in the single-pass mode it is unlikely to ever be true (though apparently in most cases it is, so worth checking out still, but my guess is this module is one of the rare one that also reads back from a value).

**Comment by MikhailArkhipov** [comment]
Yeah, if I add (supposedly missing)

```
            if (!_scraped) {
                Imported(context);
            }

```
to `AstScrapedPythonModule.GetMember` (while `GetMemberNames` has the check), this reproes pretty much anywhere. Such as on (io.py)
```
class IOBase(_io._IOBase, metaclass=abc.ABCMeta):
    __doc__ = _io._IOBase.__doc__
```
Technically it is possible to set bases in the `ClassDefinition.Walk`
