### ISSUE TITLE
LinkedFileTests.TestLinkedWithProjectHome should check for relative path in file

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#414]
```
Assert.Fail failed.
Expected <<Content Include="C:\\Users\\...\\AppData\\Local\\Temp\\tmpA75F\.tmp">\s*<Link>tmpA75F\.tmp</Link>\s*</Content>>.

Actual <<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <ProjectTypeGuid>888888a0-9f3d-457c-b088-3a5042f75d52</ProjectTypeGuid>
    <Name>TempFile</Name>
    <ProjectGuid>{74a35683-94e2-4ae5-8fcd-7a73439f19ee}</ProjectGuid>
    <SchemaVersion>2.0</SchemaVersion>
    <ProjectHome>..\..\..\..\..\Drop\TestResults\2015-06-12 22_29_42\Out\Temp\wetqwkss.lkw\LinkedFiles1\</ProjectHome>
    <WorkingDirectory>.</WorkingDirectory>
    <VisualStudioVersion Condition="'$(VisualStudioVersion)' == ''">11.0</VisualStudioVersion>
    <PtvsTargetsFile>$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\Python Tools\Microsoft.PythonTools.targets</PtvsTargetsFile>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\FileNotInProject1.py" />
    <Compile Include="..\FileNotInProject2.py" />
  </ItemGroup>
  <Import Project="$(PtvsTargetsFile)" Condition="Exists($(PtvsTargetsFile))" />
  <Import Project="$(MSBuildToolsPath)\Microsoft.Common.targets" Condition="!Exists($(PtvsTargetsFile))" />
</Project>>. 
   at TestUtilities.AssertUtil.AreEqual(Regex expected, String actual, String message) in C:\Source\Common\Tests\Utilities\AssertUtil.cs:line 322
   at VisualStudioToolsUITests.LinkedFileTests.TestLinkedWithProjectHome() in C:\Source\Common\Tests\SharedProjectTests\LinkedFileTests.cs:line 726
```

**Comment by zooba** [comment]
Looks like it also failed to add the linked file...

**Comment by huguesv** [comment]
Test still fails with the same error.
