### ISSUE TITLE
Crash when search paths change

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#4147]
Seeing this call stack in some crash reports:

```
System.ObjectDisposedException: Cannot access a disposed object.
   at System.Threading.TimerQueueTimer.Change(UInt32 dueTime, UInt32 period)
   at System.Threading.Timer.Change(Int32 dueTime, Int32 period)
   at Microsoft.PythonTools.SearchPathManager.Microsoft.VisualStudio.Shell.Interop.IVsFileChangeEvents.DirectoryChanged(String pszDirectory)
   at Microsoft.VisualStudio.Services.FileChange.ChangeNotificationBuffer.BufferingSink.<>c__DisplayClass12_0.<SendDirectoryNotifications>b__0()
```

**Comment by zooba** [comment]
Internal bug 607729
