### ISSUE TITLE
Crash running Sklearn demo

### ISSUE THREAD

**Issue by CBrauer** [Microsoft/PTVS#4166]
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 15.6.18072.2

Microsoft.PythonTools.Debugger.NoStartupFileException: The project cannot be launched because the startup file 'C:\Users\Charles\AppData\Local\Temp\~vs1969.py' was not found.
   at Microsoft.PythonTools.Debugger.DebugLaunchHelper.RequireStartupFile(LaunchConfiguration config)
   at Microsoft.PythonTools.Project.DefaultPythonLauncher.Launch(LaunchConfiguration config, Boolean debug)
   at Microsoft.PythonTools.Project.DefaultPythonLauncher.LaunchFile(String file, Boolean debug)
   at Microsoft.PythonTools.PythonToolsPackage.LaunchFile(IServiceProvider provider, String filename, Boolean debug, Boolean saveDirtyFiles)
   at Microsoft.PythonTools.Language.EditFilter.ExecWorker(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.PythonTools.Language.EditFilter.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
```

**Comment by huguesv** [comment]
To repro:
File->New->Python->Empty Module
F5
Accept when prompted to save (this will delete the tmp file as it creates the real file)
We then try to launch the tmp file that no longer exists

**Comment by CBrauer** [comment]
It would have been nice to have these instructions when the crash occurred.

No it’s too late.  I have moved on
