### ISSUE TITLE
Refactor Extract method crash

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#4171]
15.8p2

Using the async package pr, but that's probably not relevant.

![image](https://user-images.githubusercontent.com/1696845/39655877-0f069bb4-4fb1-11e8-9757-827e9aa68caf.png)

Repro a second time:
![image](https://user-images.githubusercontent.com/1696845/39655934-67d7536e-4fb1-11e8-80ab-d775f392857e.png)

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Unhandled exception in Microsoft.PythonTools.Language.EditFilter.Exec (C:\Users\huvalo\ptvs\Python\Product\PythonTools\PythonTools\Navigation\EditFilter.cs:630)

System.ObjectDisposedException: Cannot access a disposed object.

Object name: 'FormattedLine'.

   at Microsoft.VisualStudio.Text.Formatting.Implementation.FormattedLine.ThrowIfInvalid()

   at Microsoft.VisualStudio.Text.Formatting.Implementation.FormattedLine.get_VisibilityState()

   at Microsoft.VisualStudio.Text.Editor.Implementation.TextViewLineCollection.Microsoft.VisualStudio.Text.Editor.IWpfTextViewLineCollection.get_FirstVisibleLine()

   at Microsoft.VisualStudio.Text.OverviewMargin.Implementation.OverviewElement.EnsureViewport()

   at Microsoft.VisualStudio.Text.OverviewMargin.Implementation.OverviewElement.OnTextViewOptionsChanged(Object sender, EditorOptionChangedEventArgs e)

   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)

   at Microsoft.VisualStudio.Text.EditorOptions.Implementation.EditorOptions.RaiseChangedEve......

<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by AlexanderSher** [comment]
Another stack trace:
```cs
   at Microsoft.PythonTools.Intellisense.LocationTracker.ValidateSnapshotLines(ITextSnapshot snapshot) in D:\GitHub\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\LocationTracker.cs:line 298
   at Microsoft.PythonTools.Intellisense.LocationTracker.Translate(SourceSpan span, Int32 fromVersion, ITextSnapshot toSnapshot) in D:\GitHub\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\LocationTracker.cs:line 355
   at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.ApplyChanges(ChangeInfo[] changes, ITextBuffer textBuffer, LocationTracker translator, Int32 atVersion) in D:\GitHub\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\ProjectAnalyzer.cs:line 2527
   at Microsoft.PythonTools.Intellisense.PreviewChangesService.CreateDiffView(ChangeInfo[] changes, PythonTextBufferInfo buffer, Int32 atVersion) in D:\GitHub\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\PreviewChangesService.cs:line 69
   at Microsoft.PythonTools.Intellisense.ExtractMethodSuggestedActionSourceProvider.ExtractMethodSuggestedActionSource.SuggestedAction.<GetPreviewAsync>d__17.MoveNext() in D:\GitHub\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\ExtractMethodSuggestedActionSourceProvider.cs:line 175
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass4_0.<OutputAsyncCausalityEvents>b__0()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke()
   at System.Runtime.CompilerServices.TaskAwaiter.<>c__DisplayClass11_0.<OutputWaitEtwEvents>b__0()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke()
   at System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation.<>c__DisplayClass6_0.<GetActionLogDelegate>b__0()
   at System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation.<>c.<.cctor>b__8_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
```
