### ISSUE TITLE
Add Import tests not seeing tags on VS 2013

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#418]
All the tests are failing for the same reason:

```
Assert.Fail failed. failed to find session Microsoft.VisualStudio.Language.Intellisense.ISmartTagSession
   at TestUtilities.UI.EditorWindow.WaitForSession[T](Boolean assertIfNoSession) in c:\RollBuild\Common\Tests\Utilities.UI\UI\EditorWindow.cs:line 228
   at TestUtilities.UI.EditorWindow.StartSmartTagSession() in c:\RollBuild\Common\Tests\Utilities.UI\UI\EditorWindow.cs:line 201
   at PythonToolsUITests.AddImportTests.AddSmartTagTest(EditorWindow doc, Int32 line, Int32 column, String[] expectedActions, Int32 invokeAction, String expectedText) in c:\RollBuild\Python\Tests\Core.UI\AddImportTests.cs:line 287
```

**Comment by zooba** [comment]
Good news: smart tags still work, so this is a test failure.
