### ISSUE TITLE
ErrorListTaskListTests not seeing any items on VS 2013

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#419]
Similar error in all related tests on VS 2013
```
Assert.AreEqual failed. Expected:<7>. Actual:<0>. 
   at TestUtilities.UI.VisualStudioApp.WaitForTaskListItems(Type taskListService, Int32 expectedCount, Boolean exactMatch) in c:\RollBuild\Common\Tests\Utilities.UI\UI\VisualStudioApp.cs:line 987
   at PythonToolsUITests.ErrorListTaskListTests.TaskListTest(VisualStudioApp app, Type taskListService, IList`1 expectedItems, Int32[] navigateTo) in c:\RollBuild\Python\Tests\Core.UI\ErrorListTaskListTests.cs:line 88
   at PythonToolsUITests.ErrorListTaskListTests.ErrorList() in c:\RollBuild\Python\Tests\Core.UI\ErrorListTaskListTests.cs:line 135
 ```

**Comment by zooba** [comment]
Error list still has items, so this is a test failure only.

**Comment by int19h** [comment]
The repro for this is very inconsistent. Most of the time these pass. I suspect that this is simply due to the nature of the test, which has to deal with async refresh of the Task List that doesn't have any good way to detect when it's done, and so just spins & sleeps. Short of increasing the spin count, I don't see what else can we do here when running without mocks.

**Comment by zooba** [comment]
We should be using code markers here probably, but even those may not help us.
