### ISSUE TITLE
Package management broken on pip v10

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#4194]
I created a new python application
I created a 2.7 32bit based virtualenv
Right-click Install Package, requests
After that failed I tried to upgrade pip twice
In the screenshot, you can see pip twice in the list of packages, that was there before I tried to upgrade it.

```

----- Installing 'requests==2.18.4' -----
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'main'
----- Failed to install 'requests==2.18.4' -----

----- Installing 'pip' -----
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'main'
----- Failed to install 'pip' -----

----- Installing 'pip' -----
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'main'
----- Failed to install 'pip' -----

```

![image](https://user-images.githubusercontent.com/1696845/39846548-17274ce0-53b1-11e8-97cb-aecddf1a30fc.png)

**Comment by huguesv** [comment]
Seems okay on pip 9, but broken after updating to pip 10.

**Comment by huguesv** [comment]
We do things like this:
```
-c "import pip; pip.main()" list --format=json
```

The problem is that in pip 10:
`pip.main()` is now `pip._internal.main()`

**Comment by huguesv** [comment]
Change was done in https://github.com/pypa/pip/commit/95bcf8c5f6394298035a7332c441868f3b0169f4#diff-fb27453163710cf8e94b3d498fe07044
