### ISSUE TITLE
Failed to use the module "socket" to connect to Web

### ISSUE THREAD

**Issue by Xiang-Ao** [Microsoft/PTVS#4196]
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions\Microsoft\Python\Core\ptvsd_launcher.py", line 77, in <module>
    import ptvsd.debugger as vspd
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions\Microsoft\Python\Core\ptvsd\debugger.py", line 34, in <module>
    import socket
  File "C:\Users\AoXiang\source\repos\PythonApplication3\PythonApplication3\socket.py", line 2, in <module>
    s = socket.socket()
TypeError: 'module' object is not callable

**Comment by huguesv** [comment]
This is due to your project file named `socket.py` which conflicts with the name of the standard library module. Renaming your project file should fix the issue.
