### ISSUE TITLE
PROTOCOL_TLS error when I install packages

### ISSUE THREAD

**Issue by jenokizm** [Microsoft/PTVS#4203]
VS2017 lastet version with python tools. im use ironpython2 wpf project.
command:

> ipy -X:Frames -m pip install ecdsa

output:

> Unhandled exception:
> Traceback (most recent call last):
>   File "C:\Program Files (x86)\IronPython 2.7\Lib\runpy.py", line 182, in run_mo
> dule
>   File "C:\Program Files (x86)\IronPython 2.7\Lib\runpy.py", line 111, in _get_m
> odule_details
>   File "C:\Program Files (x86)\IronPython 2.7\lib\site-packages\pip\__init__.py"
> , line 21, in <module>
>   File "C:\Program Files (x86)\IronPython 2.7\lib\site-packages\pip\_vendor\requ
> ests\__init__.py", line 62, in <module>
>   File "C:\Program Files (x86)\IronPython 2.7\lib\site-packages\pip\_vendor\requ
> ests\packages\__init__.py", line 27, in <module>
>   File "C:\Program Files (x86)\IronPython 2.7\lib\site-packages\pip\_vendor\requ
> ests\packages\urllib3\__init__.py", line 8, in <module>
>   File "C:\Program Files (x86)\IronPython 2.7\lib\site-packages\pip\_vendor\requ
> ests\packages\urllib3\connectionpool.py", line 33, in <module>
>   File "C:\Program Files (x86)\IronPython 2.7\lib\site-packages\pip\_vendor\requ
> ests\packages\urllib3\packages\__init__.py", line 3, in <module>
>   File "C:\Program Files (x86)\IronPython 2.7\lib\site-packages\pip\_vendor\requ
> ests\packages\urllib3\packages\ssl_match_hostname\__init__.py", line 3, in <modu
> le>
>   File "C:\Program Files (x86)\IronPython 2.7\Lib\ssl.py", line 133, in <module>
> 
> NameError: global name 'PROTOCOL_TLS' is not defined

**Comment by jenokizm** [comment]
I just updated ironpython2 to the last 2.7.8 and now when I install the package, I get a new error:

> Unhandled exception:
> Traceback (most recent call last):
>   File "C:\Program Files (x86)\IronPython 2.7\Lib\runpy.py", line 182, in run_mo
> dule
>   File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\_vendor\pypa
> rsing.py", line 1261, in setParseAction
>   File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\_vendor\pypa
> rsing.py", line 1043, in _trim_arity
>   File "C:\Program Files (x86)\IronPython 2.7\Lib\runpy.py", line 111, in _get_m
> odule_details
>   File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\__init__.py"
> , line 26, in <module>
>   File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\utils\__init
> __.py", line 27, in <module>
>   File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\_vendor\pkg_
> resources\__init__.py", line 74, in <module>
>   File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\_vendor\pack
> aging\requirements.py", line 9, in <module>
>   File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\_vendor\pypa
> rsing.py", line 4715, in <module>
>
> IndexError: index out of range: -1

**Comment by jenokizm** [comment]
delete pip then rerun **ipy -m ensurepip** helped me. Now the packages are installed.
