### ISSUE TITLE
Crash while editing in interactive window

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#4218]
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 15.8.18131.2

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionSession.get_CompletionSets()
   at Microsoft.PythonTools.Intellisense.IntellisenseController.HandleChar(Char ch)
   at Microsoft.PythonTools.Intellisense.IntellisenseController.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.PythonTools.Language.EditFilter.ExecWorker(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.PythonTools.Language.EditFilter.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

![image](https://user-images.githubusercontent.com/1696845/40023896-626b4566-5781-11e8-99b9-03ed7418e684.png)

**Comment by huguesv** [comment]
When `Dismiss()` is called, it sets `_completionSets` to `null`, so you can't call `CompletionSets` after that without crashing.

We can work around that by checking `IsDismissed` first, I'm testing a fix that does that.

I filed internal bug 616189 to the editor team, as they should have better handling of that scenario.
