### ISSUE TITLE
Unhandled exception in PythonProjectNode.RemoveInterpreter

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#422]
From a test:

```
devenv.exe Error: 0 : Unhandled exception in Microsoft.PythonTools.Project.PythonProjectNode.RemoveInterpreter (c:\RollBuild\Python\Product\PythonTools\PythonTools\Project\PythonProjectNode.cs:2166)
System.IO.IOException: The directory is not empty.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Microsoft.PythonTools.Project.PythonProjectNode.<>c__DisplayClassb1.<RemoveInterpreter>b__af()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudioTools.VsTaskExtensions.<HandleAllExceptions>d__1`1.MoveNext()
```

**Comment by zooba** [comment]
Not actually a crash. HandleAllExceptions is now displaying an extra message box here when it originally wasn't. We should handle common exceptions here.
