### ISSUE TITLE
Crash in multi line string

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#4236]
Type
```
print('''

.\''')
```

and press CTRL+SPACE after `\`

Result:
```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
An unhandled exception is about to terminate the process:

Specified argument was out of the range of valid values.

Parameter name: span

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.

Parameter name: span

   at Microsoft.VisualStudio.Text.Implementation.TrackingSpan..ctor(ITextVersion version, Span span, SpanTrackingMode trackingMode)

   at Microsoft.VisualStudio.Text.Implementation.TextVersion.CreateTrackingSpan(Span span, SpanTrackingMode trackingMode, TrackingFidelityMode trackingFidelity)

   at Microsoft.VisualStudio.Text.Implementation.BaseSnapshot.CreateTrackingSpan(Span span, SpanTrackingMode trackingMode)

   at Microsoft.PythonTools.Extensions.GetApplicableSpan(ITextSnapshot snapshot, Int32 position, Boolean completeWord) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Extensions.cs:line 170

   at Microsoft.PythonTools.Extensions.GetApplicableSpan(ITextSnapshot snapshot, ITrackingPoint point, Boolean completeWord) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Extensions.cs:line 129

   at Microsoft.PythonTools.Extensions.GetApplicableSpan(IIntellisenseSession session, ITextBuffer buffer) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Extensions.cs:line 116

   at Microsoft.PythonTools.Intellisense.CompletionSource.AugmentCompletionSession(ICompletionSession session, IList`1 completionSets) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\CompletionSource.cs:line 70

   at Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionSession.Start()

   at Microsoft.PythonTools.Intellisense.IntellisenseController.<TriggerCompletionSession>d__43.MoveNext() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\IntellisenseController.cs:line 967

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()

   at Microsoft.PythonTools.Infrastructure.TaskExtensions.<DoNotWaitImpl>d__1.MoveNext() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Common\Infrastructure\TaskExtensions.cs:line 35

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.DispatcherOperation.InvokeImpl()

   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)

   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Windows.Threading.DispatcherOperation.Invoke()

   at System.Windows.Threading.Dispatcher.ProcessQueue()

   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)

   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

   at Microsoft.VisualStudioTools.CommonPackage.<>c.<.ctor>b__9_0(Object sender, UnhandledExceptionEventArgs e) in C:\Projects\GitHub\huguesv\PTVS\Common\Product\SharedProject\CommonPackage.cs:line 67

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.DispatcherOperation.InvokeImpl()

   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)

   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Windows.Threading.DispatcherOperation.Invoke()

   at System.Windows.Threading.Dispatcher.ProcessQueue()

   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)

   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)


---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by MikhailArkhipov** [comment]
Prob not P0 since this is not a very common scenario.

**Comment by AlexanderSher** [comment]
Bug is in `Microsoft.PythonTools.Extensions.GetApplicableSpan`, which doesn't handle multiline strings properly. So this is probably not the only repro for this issue.
