### ISSUE TITLE
Debug unit test no longer works with native code debugging enabled

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#4323]
Python 3.6 64-bit
Create new python app
Add new item, unit test
Add breakpoint to the test
in project properties, enable native code debugging
open test explorer, debug test

Result is this assert, and the breakpoint doesn't get hit.

If you try to debug the unit test with F5 with the test as startup file, there is no assert and breakpoint is hit.

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
IDebuggeeReference-derived type PyThreadState does not have a (DkmProcess, ulong) constructor.



   at Microsoft.PythonTools.Debugger.Concord.Proxies.DataProxy.FactoryBuilder`1.<>c.<.cctor>b__2_0(DkmProcess process, UInt64 address, Boolean polymorphic) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Debugger.Concord\Proxies\DataProxy.cs:line 73

   at Microsoft.PythonTools.Debugger.Concord.Proxies.DataProxy.Create[TProxy](DkmProcess process, UInt64 address, Boolean polymorphic) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Debugger.Concord\Proxies\DataProxy.cs:line 98

   at Microsoft.PythonTools.Debugger.Concord.Proxies.PointerProxy`1.TryRead() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Debugger.Concord\Proxies\PointerProxy.cs:line 122

   at Microsoft.PythonTools.Debugger.Concord.Proxies.Structs.PyInterpreterState.<GetThreadStates>d__15.MoveNext() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Debugger.Concord\Proxies\Structs\PyInterpreterState.cs:line 83

   at Microsoft.PythonTools.Debugger.Concord.TraceManagerLocalHelper..ctor(DkmProcess process, Kind kind) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Debugger.Concord\TraceManagerLocalHelper.cs:line 287

   at Microsoft.PythonTools.Debugger.Concord.LocalComponent.Microsoft.VisualStudio.Debugger.ComponentInterfaces.IDkmRuntimeInstanceLoadNotification.OnRuntimeInstanceLoad(DkmRuntimeInstance runtimeInstance, DkmEventDescriptor eventDescriptor) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Debugger.Concord\LocalComponent.cs:line 293

   at Microsoft.VisualStudio.Debugger.EntryPoint.IDkmRuntimeInstanceLoadNotification_OnRuntimeInstanceLoad(IntPtr pvClassInfo, IntPtr RuntimeInstance, IntPtr EventDescriptor)

   at Microsoft.VisualStudio.Debugger.NativeDkmCustomMessage.ProcA035DEDBF7F91EB78B75DE7CDEB4644C(IntPtr pThis, IntPtr& ReplyMessage)

   at Microsoft.VisualStudio.Debugger.DkmCustomMessage.SendLower()

   at Microsoft.PythonTools.Debugger.Concord.ComponentBase.MessageBase`1.SendLower(DkmProcess process) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Debugger.Concord\ComponentBase.cs:line 69

   at Microsoft.PythonTools.Debugger.Concord.LocalComponent.CreatePythonRuntimeInstance(DkmProcess process) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Debugger.Concord\LocalComponent.cs:line 67

   at Microsoft.PythonTools.Debugger.Concord.LocalComponent.OnHelperDllInitialized(DkmNativeModuleInstance moduleInstance) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Debugger.Concord\LocalComponent.cs:line 141

   at Microsoft.PythonTools.Debugger.Concord.LocalComponent.NativeModuleInstanceLoadedNotification.<>c__DisplayClass4_1.<Handle>b__1(DkmThread thread, UInt64 frameBase, UInt64 vFrame, UInt64 retAddr) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Debugger.Concord\LocalComponent.cs:line 234

   at Microsoft.PythonTools.Debugger.Concord.LocalComponent.HandleBreakpointRequest.Handle(DkmProcess process) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Debugger.Concord\LocalComponent.cs:line 654

   at Microsoft.PythonTools.Debugger.Concord.ComponentBase.MessageBase`1.Microsoft.PythonTools.Debugger.Concord.ComponentBase.IMessage.Handle(DkmProcess process) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Debugger.Concord\ComponentBase.cs:line 82

   at Microsoft.PythonTools.Debugger.Concord.ComponentBase.Handle(DkmCustomMessage customMessage) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Debugger.Concord\ComponentBase.cs:line 171

   at Microsoft.PythonTools.Debugger.Concord.ComponentBase.Microsoft.VisualStudio.Debugger.ComponentInterfaces.IDkmCustomMessageCallbackReceiver.SendHigher(DkmCustomMessage customMessage) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Debugger.Concord\ComponentBase.cs:line 164

   at Microsoft.VisualStudio.Debugger.EntryPoint.IDkmCustomMessageCallbackReceiver_SendHigher(IntPtr pvClassInfo, IntPtr CustomMessage, IntPtr& ReplyMessage)


---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by huguesv** [comment]
The assert is a regression in 15.8 (PythonLanguageVersion parameter was added to PyThreadState constructor when support for Python 3.7 was added).
Using 15.7, I am not able to stop at a breakpoint using debug unit test, so that's an older regression.

**Comment by huguesv** [comment]
I just verified that on 15.6, debug unit test worked as expected (it stops at breakpoints) with native code debugging enabled.

**Comment by huguesv** [comment]
Also affects DebugPurePythonProject test in CI test run. For some reason test passes on my local machine.
```
Test method DebuggerUITestsRunner.MixedModeDebugProjectUITests3x_32.DebugPurePythonProject threw exception: 

TestRunnerInterop.TestFailedException: AssertFailedException: Assert.Fail failed. IDebuggeeReference-derived type PyThreadState does not have a (DkmProcess, ulong) constructor.
```

**Comment by ghpqans** [comment]
After every update i'm faced with this issue again. Then sometimes it works again until the next update.
