### ISSUE TITLE
python debugger starting issue

### ISSUE THREAD

**Issue by chhenning** [Microsoft/PTVS#4395]
I foolishly updated to the new python debugger in Visual Studio 2017 (15.7.4) and now I cannot debug anymore. I get this error:
```
pydev debugger: starting

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\wrapper.py", line 796, in done
    fut.result()
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\futures.py", line 40, in result
    reraise(self._exc_info)
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\reraise3.py", line 8, in reraise
    raise exc_info[1].with_traceback(exc_info[2])
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\futures.py", line 149, in callback
    x = next(it)
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\wrapper.py", line 1004, in on_launch
    args.get('options', options))
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\wrapper.py", line 959, in _parse_debug_options
    options[key] = DEBUG_OPTIONS_PARSER[key](value)
KeyError: 'DEBUG_STDLIB'
```

How can revert to my old compiler?

**Comment by chhenning** [comment]
In Tools\Options\Python\Experimental turn off `Use experimental debugger`.

**Comment by huguesv** [comment]
If you want to continue using the experimental debugger, you can toggle the "Enable debugging of the Python standard library" in Tools/Options/Python/Debugging. That's what is causing the error.

**Comment by whitneyland** [comment]
This still appears to be a problem in version 15.7.4, as well as the previous build.  @huguesv I've tried your suggestions but no joy.

pydev debugger: starting

Traceback (most recent call last):
  File "D:\Programs\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\wrapper.py", line 796, in done
    fut.result()
  File "D:\Programs\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\futures.py", line 40, in result
    reraise(self._exc_info)
  File "D:\Programs\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\reraise3.py", line 8, in reraise
    raise exc_info[1].with_traceback(exc_info[2])
  File "D:\Programs\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\futures.py", line 149, in callback
    x = next(it)
  File "D:\Programs\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\wrapper.py", line 1004, in on_launch
    args.get('options', options))
  File "D:\Programs\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\wrapper.py", line 959, in _parse_debug_options
    options[key] = DEBUG_OPTIONS_PARSER[key](value)
KeyError: 'DEBUG_STDLIB'

**Comment by huguesv** [comment]
@whitneyland if you install the latest ptvsd into your python environment, using `pip install ptvsd --pre`, it will use that one instead of the one in `D:\Programs\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd` folder.

The latest one on PyPI has the fix for `DEBUG_STDLIB` error.

We're not updating the bundled ptvsd in 15.7.x servicing releases, so it's pretty old by now.
