### ISSUE TITLE
Crash debugging multithreaded project

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#441]
Received this crash while debugging a multithreaded project using a thread pool. The dictionary in question (`_pendingExecutes`) is empty at this point.

```
An unhandled exception is about to terminate the process:
The given key was not present in the dictionary.
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.PythonTools.Debugger.PythonProcess.HandleExecutionException(Stream stream) in C:\Source\PTVS\Python\Product\Debugger\Debugger\PythonProcess.cs:line 673
   at Microsoft.PythonTools.Debugger.PythonProcess.DebugEventThread() in C:\Source\PTVS\Python\Product\Debugger\Debugger\PythonProcess.cs:line 454
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by zooba** [comment]
Also received this assertion trying the same thing again (specifically, hovering over a variable running off the main thread):
```
Received REPL execution result with unknown execution ID 1
   at Microsoft.PythonTools.Debugger.PythonProcess.HandleExecutionResult(Stream stream) in C:\Projects\Work\Python\PTVS\Python\Product\Debugger\Debugger\PythonProcess.cs:line 689
   at Microsoft.PythonTools.Debugger.PythonProcess.DebugEventThread() in C:\Projects\Work\Python\PTVS\Python\Product\Debugger\Debugger\PythonProcess.cs:line 453
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

Also, I'm running against Python 3.5b2 64-bit.

**Comment by zooba** [comment]
I cut the thread pool down to a single thread. Stepping is very slow, but seems to be working now. Not sure how related all of these are.

**Comment by zooba** [comment]
Still very slow against Python 3.4 32-bit, but no more crashing.
