### ISSUE TITLE
An unexpected error occurred

### ISSUE THREAD

**Issue by ShivaDurai** [Microsoft/PTVS#4458]
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 15.7.18131.1

Microsoft.PythonTools.Debugger.NoStartupFileException: The project cannot be launched because the startup file 'C:\Users\sdurai004c\AppData\Local\Temp\~vsECAB.py' was not found.
   at Microsoft.PythonTools.Debugger.DebugLaunchHelper.RequireStartupFile(LaunchConfiguration config)
   at Microsoft.PythonTools.Project.DefaultPythonLauncher.Launch(LaunchConfiguration config, Boolean debug)
   at Microsoft.PythonTools.Project.DefaultPythonLauncher.LaunchFile(String file, Boolean debug)
   at Microsoft.PythonTools.PythonToolsPackage.LaunchFile(IServiceProvider provider, String filename, Boolean debug, Boolean saveDirtyFiles)
   at Microsoft.PythonTools.Language.EditFilter.ExecWorker(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.PythonTools.Language.EditFilter.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by huguesv** [comment]
Thanks! This has already been fixed for 15.8.
