### ISSUE TITLE
ExtractMethodTests are unreliable

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#4489]
Random failures that look like this. Sometimes it passes after running it a second time. Happens both locally and on test machine.
```
TestCleanup method PythonToolsTests.ExtractMethodTests.TestCleanup threw exception. System.AggregateException: System.AggregateException: One or more errors occurred. ---> Microsoft.VisualStudio.TestTools.UnitTesting.AssertFailedException: Assert.Fail failed. Unhandled exception in InitializeAsync (C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\ProjectAnalyzer.cs:241)
System.InvalidOperationException: Failed to parse packet: Unexpected character encountered while parsing value: S. Path '', line 0, position 0.
   at Microsoft.PythonTools.Ipc.Json.Connection.<WriteError>d__43.MoveNext() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Ipc.Json\Connection.cs:line 599
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.PythonTools.Ipc.Json.Connection.<ProcessMessages>d__33.MoveNext() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Ipc.Json\Connection.cs:line 292
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\VSCommon\Infrastructure\VSTaskExtensions.cs:line 179.
```

**Comment by zooba** [comment]
This typically means the analyzer is printing an error message. We should be capturing it somewhere, so maybe check the logs on your local machine?

**Comment by huguesv** [comment]
Here's an example:
```
Assert.Fail failed. Unhandled exception in InitializeAsync (E:\A\_work\27\s\Python\Product\PythonTools\PythonTools\Intellisense\ProjectAnalyzer.cs:241)

System.InvalidOperationException: Malformed header, expected 'name: value'

at System.Threading.SemaphoreSlim.CheckDispose() at System.Threading.SemaphoreSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)

at System.Threading.SemaphoreSlim.Wait(TimeSpan timeout)

at Microsoft.PythonTools.Analysis.PythonAnalyzer.Dispose(Boolean disposing) in E:\A\_work\27\s\Python\Product\Analysis\PythonAnalyzer.cs:line 1015

at Microsoft.PythonTools.Analysis.PythonAnalyzer.Dispose() in E:\A\_work\27\s\Python\Product\Analysis\PythonAnalyzer.cs:line 1003

at Microsoft.PythonTools.Analysis.LanguageServer.Server.Dispose() in E:\A\_work\27\s\Python\Product\Analysis\LanguageServer\Server.cs:line 111

at Microsoft.PythonTools.Intellisense.OutOfProcProjectAnalyzer.Dispose() in E:\A\_work\27\s\Python\Product\Analyzer\Intellisense\OutOfProcProjectAnalyzer.cs:line 1714

at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.ThreadConnectionWorker(Object o) in E:\A\_work\27\s\Python\Product\PythonTools\PythonTools\Intellisense\ProjectAnalyzer.cs:line 771

Content-Length: 168



{"event":"analyzerWarning","body":{"message":"Received new analysis for file:///E:/A/_work/r1/a/PTVS-Github-CI-Dev15/temp/g2sevwcn.q2h/fob.py"},"type":"event","seq":19}Content-Length: 177



{"event":"analyzerWarning","body":{"message":"Analysis complete for file:///E:/A/_work/r1/a/PTVS-Github-CI-Dev15/temp/g2sevwcn.q2h/fob.py at version 0"},"type":"event","seq":20}Content-Length: 163



{"event":"fileAnalysisComplete","body":{"documentUri":"file:///E:/A/_work/r1/a/PTVS-Github-CI-Dev15/temp/g2sevwcn.q2h/fob.py","version":0},"type":"event","seq":21}

at Microsoft.PythonTools.Ipc.Json.Connection.<WriteError>d__43.MoveNext() in E:\A\_work\27\s\Python\Product\Ipc.Json\Connection.cs:line 599

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.GetResult()

at Microsoft.PythonTools.Ipc.Json.Connection.<ProcessMessages>d__33.MoveNext() in E:\A\_work\27\s\Python\Product\Ipc.Json\Connection.cs:line 292

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.GetResult()

at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext() in E:\A\_work\27\s\Python\Product\VsCommon\Infrastructure\VSTaskExtensions.cs:line 179```
