### ISSUE TITLE
Asserts on go to definition

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#4497]
I kept on going to definition on `os` and closing and reopening os.py:
```
import os
```

And ended up with asserts.
```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
System.IndexOutOfRangeException: Index was outside the bounds of the array.

   at Microsoft.PythonTools.Analysis.Deque`1.Append(T x) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Deque.cs:line 42

   at Microsoft.PythonTools.Analysis.AnalysisUnit.Enqueue() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\AnalysisUnit.cs:line 130

   at Microsoft.PythonTools.Analysis.Analyzer.OverviewWalker.AddFunction(FunctionDefinition node, AnalysisUnit outerUnit, InterpreterScope prevScope) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Analyzer\OverviewWalker.cs:line 184

   at Microsoft.PythonTools.Analysis.Analyzer.OverviewWalker.AddFunction(FunctionDefinition node, AnalysisUnit outerUnit) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Analyzer\OverviewWalker.cs:line 160

   at Microsoft.PythonTools.Analysis.Analyzer.OverviewWalker.Walk(FunctionDefinition node) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Analyzer\OverviewWalker.cs:line 98

   at Microsoft.PythonTools.Parsing.Ast.FunctionDefinition.Walk(PythonWalker walker) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Parsing\Ast\FunctionDefinition.cs:line 238

   at Microsoft.PythonTools.Analysis.Analyzer.OverviewWalker.Walk(SuiteStatement node) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Analyzer\OverviewWalker.cs:line 545

   at Microsoft.PythonTools.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Parsing\Ast\SuiteStatement.cs:line 34

   at Microsoft.PythonTools.Parsing.Ast.ClassDefinition.Walk(PythonWalker walker) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Parsing\Ast\ClassDefinition.cs:line 171

   at Microsoft.PythonTools.Analysis.Analyzer.OverviewWalker.Walk(SuiteStatement node) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Analyzer\OverviewWalker.cs:line 545

   at Microsoft.PythonTools.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Parsing\Ast\SuiteStatement.cs:line 34

   at Microsoft.PythonTools.Parsing.Ast.PythonAst.Walk(PythonWalker walker) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Parsing\Ast\PythonAst.cs:line 92

   at Microsoft.PythonTools.Analysis.ProjectEntry.Parse(Boolean enqueueOnly, CancellationToken cancel) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\ProjectEntry.cs:line 243

   at Microsoft.PythonTools.Analysis.ProjectEntry.Analyze(CancellationToken cancel, Boolean enqueueOnly) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\ProjectEntry.cs:line 174

   at Microsoft.PythonTools.Intellisense.AnalysisQueue.Worker(Object threadStarted) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Intellisense\AnalysisQueue.cs:line 231



   at Microsoft.PythonTools.Analysis.LanguageServer.Server.Analysis_UnhandledException(Object sender, UnhandledExceptionEventArgs e) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\LanguageServer\Server.cs:line 103

   at Microsoft.PythonTools.Intellisense.AnalysisQueue.Worker(Object threadStarted) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Intellisense\AnalysisQueue.cs:line 236

   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Threading.ThreadHelper.ThreadStart(Object obj)


---------------------------
Abort   Retry   Ignore   
---------------------------

```

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Failed to analyze file:///c:/program files/python36/lib/os.py



   at Microsoft.PythonTools.Intellisense.IntellisenseController.<ConnectSubjectBufferAsync>d__25.MoveNext() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\IntellisenseController.cs:line 244

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()

   at System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation.<>c.<.cctor>b__8_0(Object state)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.DispatcherOperation.InvokeImpl()

   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)

   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Windows.Threading.DispatcherOperation.Invoke()

   at System.Windows.Threading.Dispatcher.ProcessQueue()

   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)

   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)


---------------------------
Abort   Retry   Ignore   
---------------------------

```

**Comment by zooba** [comment]
This looks like a race condition, which means we're querying the analysis without using a ForEval unit.

Unfortunately, the thread that crashed is the one that's supposed to be in there, so it doesn't help us track anything down.

That assertion is expected under the circumstances. Not sure there's anything specific we can do here.

**Comment by zooba** [comment]
I think I can add more debug asserts to make sure we notice any of these cases while working on it.
