### ISSUE TITLE
VisualStudio_PY_Debugger cannot load ctypes DLLs

### ISSUE THREAD

**Issue by rbed23** [Microsoft/PTVS#4510]
From VSC Debugger Console:

```
PS H:\technology> cd 'h:\technology'; ${env:PYTHONIOENCODING}='UTF-8'; ${env:PYTHONUNBUFFERED}='1'; & 'python' 'c:\Users\Ryan\.vscode\extensions\ms-python.python-2018.6.0\pythonFiles\PythonTools\visualstudio_py_launcher.py' 'h:\technology' '54181' '34806ad9-833a-4524-8cd6-18ca4aa74f14' 'RedirectOutput,RedirectOutput' 'h:\technology\actors.py'

Traceback (most recent call last):
  File "c:\Users\Ryan\.vscode\extensions\ms-python.python-2018.6.0\pythonFiles\PythonTools\visualstudio_py_launcher.py", line 31, in <module>
    import visualstudio_py_debugger as vspd
  File "c:\Users\Ryan\.vscode\extensions\ms-python.python-2018.6.0\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 30, in <module>
    import ctypes
  File "C:\Python27\lib\ctypes\__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: DLL load failed: The specified procedure could not be found.

Actors.py file:
#!/usr/bin/env python
from thespian.actors import *

class Hello(Actor):
    def receiveMessage(self, message, sender):
        self.send(sender, 'Hello World!')

hello = ActorSystem().createActor(Hello)
print (ActorSystem().ask(hello, 'hi', 1))
ActorSystem().tell(hello, ActorExitRequest())
```

**Comment by zooba** [comment]
I think you meant to post this at the [vscode-python](https://github.com/microsoft/vscode-python) repo. Hopefully @DonJayamanne or @brettcannon can help out, though.

**Comment by brettcannon** [comment]
@rbed23 if this is through VS Code then please file over where zooba pointed you at, although this looks more like an issue with your Python installation.
