### ISSUE TITLE
Unhandled NullReferenceException in interactive window

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#4513]
From diagnostics attached to https://developercommunity.visualstudio.com/content/problem/229987/python-reset-interactive-window.html

Probably on shutdown? That's what happened in RTVS.
See https://github.com/dotnet/interactive-window/issues/32
See https://github.com/Microsoft/RTVS/issues/2637

```
Time: 2018-06-25T09:43:19
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Microsoft.VisualStudio.InteractiveWindow.InteractiveWindow.UIThread[[Microsoft.VisualStudio.Text.Span, Microsoft.VisualStudio.Text.Data, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](System.Func`2<UIThreadOnly,Microsoft.VisualStudio.Text.Span>)
   at Microsoft.VisualStudio.InteractiveWindow.InteractiveWindow.Microsoft.VisualStudio.InteractiveWindow.IInteractiveWindow.WriteError(System.String)
   at Microsoft.PythonTools.Repl.PythonCommonInteractiveEvaluator.AppendTextWithEscapes(Microsoft.VisualStudio.InteractiveWindow.IInteractiveWindow, System.String, Boolean, Boolean)
   at Microsoft.PythonTools.Repl.PythonCommonInteractiveEvaluator.WriteError(System.String, Boolean)
   at Microsoft.PythonTools.Repl.PythonInteractiveEvaluator+CommandProcessorThread.StdErrReceived(System.Object, System.Diagnostics.DataReceivedEventArgs)
   at System.Diagnostics.Process.ErrorReadNotifyUser(System.String)
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue()
   at System.Diagnostics.AsyncStreamReader.GetLinesFromStringBuilder()
   at System.Diagnostics.AsyncStreamReader.ReadBuffer(System.IAsyncResult)
   at System.IO.Stream+ReadWriteTask.InvokeAsyncCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.IO.Stream+ReadWriteTask.System.Threading.Tasks.ITaskCompletionAction.Invoke(System.Threading.Tasks.Task)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task.FinishStageTwo()
   at System.Threading.Tasks.Task.Finish(Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by zooba** [comment]
I don't see any feasible workaround other than handling the exception.
