### ISSUE TITLE
Assert while/after creating a virtual env

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#4526]
```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------


   at Microsoft.PythonTools.Analysis.Deque`1.AssertContext() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Deque.cs:line 39
   at Microsoft.PythonTools.Analysis.Deque`1.Append(T x) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Deque.cs:line 50
   at Microsoft.PythonTools.Analysis.AnalysisUnit.Enqueue() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\AnalysisUnit.cs:line 130
   at Microsoft.PythonTools.Analysis.DependentData`1.EnqueueDependents(IVersioned assigner, IProjectEntry declaringScope) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\VariableDef.cs:line 75
   at Microsoft.PythonTools.Analysis.Values.ModuleInfo.EnsureModuleVariables(PythonAnalyzer state) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Values\ModuleInfo.cs:line 79
   at Microsoft.PythonTools.Analysis.PythonAnalyzer.<ReloadModulesAsync>d__66.MoveNext() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\PythonAnalyzer.cs:line 188
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.PythonTools.Analysis.PythonAnalyzer.ReloadModulesAsync()
   at Microsoft.PythonTools.Analysis.LanguageServer.Server.ReloadModulesQueueItem.<Analyze>b__5_0() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\LanguageServer\Server.cs:line 55
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
 
---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by zooba** [comment]
The previous await does `ConfigureAwait(false)`, but we need to end up back on the analysis thread here. (Note that the earlier `ConfigureAwait(false)` is fine because the `.Release()` operation is free threaded and then we return.)
