### ISSUE TITLE
NullReferenceException in CreateOrAddVirtualEnvironment

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#454]
Can't tell exactly where it is, though presumably it's after the await.

Wild guess says we're cleaning up and `_interpreters` is null.

```
First-chance exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.PythonTools.Project.PythonProjectNode.<CreateOrAddVirtualEnvironment>d__148.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Project.AddVirtualEnvironmentOperation.<Run>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Project.AddVirtualEnvironmentView.<Create>d__105.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
```

**Comment by zooba** [comment]
This affects `WebProjectInstallOnNew`, which apparently still passed despite the crash.
