### ISSUE TITLE
Exception log in VSCode python extension

### ISSUE THREAD

**Issue by shengyfu** [Microsoft/PTVS#4576]
[Info  - 9:42:57 PM] Reloading modules...

Unhandled Exception: System.InvalidOperationException: currently processing another request
   at Microsoft.PythonTools.Analysis.LanguageServer.ServerBase.RequestLock..ctor(ServerBase owner, Int32 millisecondsTimeout)
   at Microsoft.PythonTools.Analysis.LanguageServer.Server.ReloadModulesAsync(CancellationToken token)
   at Microsoft.PythonTools.Analysis.Infrastructure.TaskExtensions.ReThrowTaskException(Object state)
   at Microsoft.PythonTools.Analysis.Infrastructure.TaskExtensions.DoNotWait(Task task)
   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.<DidChangeConfiguration>b__26_0()
   at Microsoft.Python.LanguageServer.PathsWatcher.<TimerProc>b__7_0(Object _)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.<>c.<.cctor>b__5_0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
[Info  - 9:43:00 PM] Connection to server got closed. Server will restart.
[Info  - 9:43:01 PM] Created Microsoft.PythonTools.Interpreter.Ast.AstPythonInterpreter instance from Microsoft.PythonTools.Interpreter.Ast.AstPythonInterpreterFactory
Initializing for C:\ProgramData\Anaconda3\python.exe
Loading files from c:\repos\intellisense-samples

**Comment by zooba** [comment]
Same as #4563
