### ISSUE TITLE
Exception in Python extension for VS Code

### ISSUE THREAD

**Issue by md2perpe** [Microsoft/PTVS#4620]
I'm using the [Python extension](https://marketplace.visualstudio.com/items?itemName=ms-python.python) v. 2018.7.1 in VS Code. Often when I type something the VS IntelliCode console opens and shows the following exception:
```
[Error - 11:55:01] Exception in Pythia: System.AggregateException: One or more errors occurred. (Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index) ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.SZArrayHelper.get_Item[T](Int32 index)
   at Microsoft.PythonTools.Analysis.Pythia.AssignmentWalker.PostWalk(FromImportStatement node)
   at Microsoft.PythonTools.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Parsing.Ast.TryStatement.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Parsing.Ast.PythonAst.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Analysis.Pythia.PythiaService.GetRecommendationsAsync(CompletionItem[] completionList, PythonAst ast, SourceLocation location, Int32 recommendataionLimit)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.PythonTools.Analysis.Pythia.LanguageServerExtension.PostProcessCompletion(Object sender, CompletionEventArgs e)
---> (Inner Exception #0) System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.SZArrayHelper.get_Item[T](Int32 index)
   at Microsoft.PythonTools.Analysis.Pythia.AssignmentWalker.PostWalk(FromImportStatement node)
   at Microsoft.PythonTools.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Parsing.Ast.TryStatement.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Parsing.Ast.PythonAst.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Analysis.Pythia.PythiaService.GetRecommendationsAsync(CompletionItem[] completionList, PythonAst ast, SourceLocation location, Int32 recommendataionLimit)<---
```

I assume that this project is used in that extension and that the error comes from this code.

**Comment by MikhailArkhipov** [comment]
Could you provide code sample if possible?

**Comment by MikhailArkhipov** [comment]
@vivlimmsft - FYI

**Comment by shengyfu** [comment]
@md2perpe, how do I repro the issue? Sample code would be great.

**Comment by dc-avasilev** [comment]
file-tree:
.
..
|
pymodule
      |
      __init__.py
      somefile.py
      ....
...
services
       |
       directory1
       directory2
       ...
       directoryN
                  |
                   tests
                         |
                         subfolder
                                   |
                                    test_ololo.py - inside this file try wright: from pymodule.(ctrl+space)

i see error in that moment

**Comment by dc-avasilev** [comment]
if disabled visualstudioexptteam.vscodeintellicode extension, this exception is disappear

**Comment by GenkunAbe** [comment]
I have the same problem. No matter what code I type, an annoying error will pop up.

This error appears after I install Visual Studio IntelliCode.

![issue](https://user-images.githubusercontent.com/11963004/44136640-13fba49e-a0a0-11e8-9639-eaf3245d7aa9.gif)

**Comment by md2perpe** [comment]
Thank you, @GenkunAbe. That is exactly what happened to me all the time when I created this issue. But now it hasn't happened for several days.

**Comment by MikhailArkhipov** [comment]
Closing now. Please open VS Code issues in https://github.com/Microsoft/vscode-python
