### ISSUE TITLE
Publish to App Service Linux

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#4760]
I was able to make it the option appear in the publish dialog by returning “Web” and “CPS” for our project capabilities.

We’re MPFProj based, not CPS based, so that’s pretty wrong but it allowed me to get further.

I was able to publish, and it crashed post publish, it’s probably _hierarchy.GetUnconfiguredProject() that returns null, because we’re not really CPS.
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.Web.Azure.Publish.AppCapabilities.AppServicePublishProfileVisual.<LinuxAppServicePostPublishAsync>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Web.Azure.Publish.AppCapabilities.AppServicePublishProfileVisual.<PostPublishAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ApplicationCapabilities.Publish.ViewModel.ProfileSelectorViewModel.<RunPublishTaskAsync>d__127.MoveNext()
```

**Comment by huguesv** [comment]
https://docs.microsoft.com/en-us/azure/app-service/containers/quickstart-python
https://docs.microsoft.com/en-us/azure/app-service/containers/how-to-configure-python#custom-startup-command

https://github.com/Azure-Samples/python-docs-hello-world

**Comment by huguesv** [comment]
The web tools team change is now available.

I manually edited my project file to add the 2 properties PublishLinuxFxVersion, PublishLinuxAppCommandLine

When I published, it did not work because the stack was not set:
![image](https://user-images.githubusercontent.com/1696845/58662228-8a878a80-82de-11e9-93ba-1aff485d7f45.png)

Using the portal, I set it to Python and then the site worked.
![image](https://user-images.githubusercontent.com/1696845/58662282-ae4ad080-82de-11e9-8216-86b863698c38.png)

**Comment by huguesv** [comment]
The UI for App Service Linux in the publish dialog stopped working, so I'm blocked until that gets fixed.

**Comment by huguesv** [comment]
The bug mentioned above is now fixed in latest builds.
