### ISSUE TITLE
Crash while edit multiple lines.

### ISSUE THREAD

**Issue by HarshCoastOS** [Microsoft/PTVS#4762]
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 15.8.18241.1

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.PythonTools.Intellisense.CompletionSessionExtensions.SetTriggerCharacter(IIntellisenseSession session, Char triggerChar)
   at Microsoft.PythonTools.Intellisense.IntellisenseController.<TriggerCompletionSession>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.PythonTools.Infrastructure.TaskExtensions.ReThrowTaskException(Object state)
   at Microsoft.PythonTools.Infrastructure.TaskExtensions.DoNotWait(Task task)
   at Microsoft.PythonTools.Intellisense.IntellisenseController.HandleChar(Char ch)
   at Microsoft.PythonTools.Intellisense.IntellisenseController.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.PythonTools.Language.EditFilter.ExecWorker(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.PythonTools.Language.EditFilter.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by huguesv** [comment]
`session` is `null` here:
```
        internal async Task TriggerCompletionSession(bool completeWord, char triggerChar, bool? commitByDefault = null) {
            var caretPoint = _textView.TextBuffer.CurrentSnapshot.CreateTrackingPoint(_textView.Caret.Position.BufferPosition, PointTrackingMode.Positive);
            var session = _services.CompletionBroker.CreateCompletionSession(_textView, caretPoint, true);
            session.SetTriggerCharacter(triggerChar);
            if (completeWord) {
                session.SetCompleteWordMode();
            }
```
We probably should make `ShouldTriggerIdentifierCompletionSession` return `false` when there's multiple carets.
```
                            if (ShouldTriggerIdentifierCompletionSession(out commitByDefault)) {
                                TriggerCompletionSession(false, ch, commitByDefault).DoNotWait();
                            }
```
