### ISSUE TITLE
Python loads 6 binaries during UWP solution load with designer view on top

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#4777]
internal bug 660073

 seems to be from MEF during VsTextViewCreated. Python loads the following 6 binaries

Microsoft.PythonTools.Analyzer.exe
Microsoft.PythonTools.dll
Microsoft.PythonTools.Analysis.dll
Microsoft.PythonTools.Analyzer.exe
Microsoft.PythonTools.Common.dll
Microsoft.PythonTools.VSInterpreters.dll
Microsoft.PythonTools.VSCommon.dll
Microsoft.PythonTools.Ipc.Json.dll

**Comment by huguesv** [comment]
After loading the Uwp project, but before opening any .xaml file, the following binaries were loaded:
Microsoft.PythonTools.dll
Microsoft.PythonTools.Common.dll
Microsoft.PythonTools.Profiling.dll

When you open a .xaml file from the Uwp project, you get several asserts:
```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
No UIThread service but shell is not shutting down



   at Microsoft.VisualStudioTools.UIThreadExtensions.GetUIThread(IServiceProvider serviceProvider) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\VSCommon\Infrastructure\UIThreadBase.cs:line 156

   at Microsoft.PythonTools.Editor.PythonTextBufferInfoExtensions.<FindAnalyzerAsync>d__5.MoveNext() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Editor\PythonTextBufferInfo.cs:line 753

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.PythonTools.Editor.PythonTextBufferInfoExtensions.FindAnalyzerAsync(IServiceProvider site, PythonTextBufferInfo buffer)

   at Microsoft.PythonTools.Editor.PythonTextBufferInfoExtensions.<FindAnalyzerAsync>d__4.MoveNext() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Editor\PythonTextBufferInfo.cs:line 717

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](T......

<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------


---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
No UIThread service but shell is not shutting down



   at Microsoft.VisualStudioTools.UIThreadExtensions.GetUIThread(IServiceProvider serviceProvider) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\VSCommon\Infrastructure\UIThreadBase.cs:line 156

   at Microsoft.VisualStudioTools.UIThreadExtensions.MustBeCalledFromUIThread(IServiceProvider serviceProvider, String message) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\VSCommon\Infrastructure\UIThreadBase.cs:line 167

   at Microsoft.PythonTools.Editor.PythonTextBufferInfoExtensions.<FindAnalyzerAsync>d__4.MoveNext() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Editor\PythonTextBufferInfo.cs:line 721

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.PythonTools.Editor.PythonTextBufferInfoExtensions.FindAnalyzerAsync(IServiceProvider site, ITextView view)

   at Microsoft.PythonTools.Intellisense.XamlTextViewCreationListener.<AnalyzeXamlFile......

<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------


---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
No UIThread service but shell is not shutting down



   at Microsoft.VisualStudioTools.UIThreadExtensions.GetUIThread(IServiceProvider serviceProvider) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\VSCommon\Infrastructure\UIThreadBase.cs:line 156

   at Microsoft.VisualStudioTools.UIThreadExtensions.MustBeCalledFromUIThread(IServiceProvider serviceProvider, String message) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\VSCommon\Infrastructure\UIThreadBase.cs:line 167

   at Microsoft.PythonTools.Editor.PythonTextBufferInfoExtensions.<FindAnalyzerAsync>d__4.MoveNext() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Editor\PythonTextBufferInfo.cs:line 721

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.PythonTools.Editor.PythonTextBufferInfoExtensions.FindAnalyzerAsync(IServiceProvider site, ITextView view)

   at Microsoft.PythonTools.Intellisense.XamlTextViewCreationListener.<AnalyzeXamlFileAsync>d__3.MoveNext() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\XamlTextViewCreationListener.cs:line 82

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.PythonTools.Intellisense.XamlTextViewCreationListener.AnalyzeXamlFileAsync(ITextView textView, PythonTextBufferInfo bufferInfo)

   at Microsoft.PythonTools.Intellisense.XamlTextViewCreationListener.<VsTextViewCreated>d__2.MoveNext() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\XamlTextViewCreationListener.cs:line 63

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass4_0.<OutputAsyncCausalityEvents>b__0()

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke()

   at System.Runtime.CompilerServices.TaskAwaiter.<>c__DisplayClass11_0.<OutputWaitEtwEvents>b__0()

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke()

   at System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation.<>c__DisplayClass6_0.<GetActionLogDelegate>b__0()

   at System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation.<>c.<.cctor>b__8_0(Object state)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.DispatcherOperation.InvokeImpl()

   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)

   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Windows.Threading.DispatcherOperation.Invoke()

   at System.Windows.Threading.Dispatcher.ProcessQueue()

   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)

   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)


---------------------------
Abort   Retry   Ignore   
---------------------------

```
