### ISSUE TITLE
Python Environments packages, many errors after most recent update

### ISSUE THREAD

**Issue by MGDMedia** [Microsoft/PTVS#4828]
It seems i'm getting a lot of odd glitches all the sudden with my virual evniroment packages.  
1. It lists duplicates of many packages.
2. It is listing some of my packages that are in the same project.
3. Pip fails to update or uninstall packages with this error:

```
----- Uninstalling 'ijson' -----
Traceback (most recent call last):
  File "C:\Users\jmarshall\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\jmarshall\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\jmarshall\source\repos\MediaDesignGroup\ETL\ETLApp\ETLAppEnv_3_7\lib\site-packages\pip\__main__.py", line 16, in <module>
    from pip._internal import main as _main  # noqa
  File "C:\Users\jmarshall\source\repos\MediaDesignGroup\ETL\ETLApp\ETLAppEnv_3_7\lib\site-packages\pip\_internal\__init__.py", line 20, in <module>
    from pip._vendor.urllib3.exceptions import DependencyWarning
  File "C:\Users\jmarshall\source\repos\MediaDesignGroup\ETL\ETLApp\ETLAppEnv_3_7\lib\site-packages\pip\_vendor\urllib3\__init__.py", line 8, in <module>
    from .connectionpool import (
  File "C:\Users\jmarshall\source\repos\MediaDesignGroup\ETL\ETLApp\ETLAppEnv_3_7\lib\site-packages\pip\_vendor\urllib3\connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "C:\Users\jmarshall\source\repos\MediaDesignGroup\ETL\ETLApp\ETLAppEnv_3_7\lib\site-packages\pip\_vendor\urllib3\exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import (
ModuleNotFoundError: No module named 'pip._vendor.urllib3.packages'
----- Error while uninstalling 'ijson' -----
'ijson' may not have been uninstalled completely.
```

**Comment by huguesv** [comment]
Thanks for the report.

Could it be that the version of pip you are now using is different from before you had these issues?

Can you please provide the exact Python version for this environment and run a `pip list` from command line (so we see the pip version)? Thank you!

**Comment by huguesv** [comment]
Please reopen with additional details if you still experience this. Thanks.
