### ISSUE TITLE
Internal Error Detected in VS2013

### ISSUE THREAD

**Issue by wygonski** [Microsoft/PTVS#4834]
Requesting help -- I consistently get this error when launching a debugger session:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio\2.2\visualstudio_py_launcher.py", line 25, in <module>
    import visualstudio_py_debugger as vspd
  File "C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio\2.2\visualstudio_py_debugger.py", line 24, in <module>
    import ctypes
  File "C:\Python27\Lib\ctypes\__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: DLL load failed: %1 is not a valid Win32 application.

Internal error detected. Please copy the above traceback and report at
http://go.microsoft.com/fwlink/?LinkId=293415

**Comment by huguesv** [comment]
This could be due to a broken virtual environment. When that's the case, the solution is to delete and recreate it. If you're using the global Python 2.7, then maybe that installation is broken and needs to be repaired.
