### ISSUE TITLE
Autocomplete problems with "*.html" files in "Django Web Project" template

### ISSUE THREAD

**Issue by RaymonGulati1** [Microsoft/PTVS#4837]
**Description:** 
Autocompleting a URL reference in a "*.html" file causes an "Object reference not set to an instance of the object" error.  

**Expected behavior:** 
The Django analyzer should be able to auto complete URL patterns by looking through the urls.py files and mapping each URL keyword to a URL path. 

**Steps to reproduce:** 
	1. Go to "DjangoWebProject/app/templates/layout.html"
	2. Modify the "<li><a href="{% url ' %}">About</a></li>" to "<li><a href="{% url '
	3. Place your curser at end of line (right of ') and try to autocomplete by pressing control + space. This will cause the error. 

**Call stack:** 
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.PythonTools.Django
  StackTrace:
   at Microsoft.PythonTools.Django.TemplateParsing.DjangoBlocks.DjangoUrlBlock.GetCompletions(IDjangoCompletionContext context, Int32 position) in C:\Users\Administrator\Source\Repos\PTVS\Python\Product\Django\TemplateParsing\DjangoBlocks\DjangoUrlBlock.cs:line 110
   at Microsoft.PythonTools.Django.Intellisense.DjangoCompletionSourceBase.GetCompletionSet(CompletionOptions options, VsProjectAnalyzer analyzer, TemplateTokenKind kind, String templateText, Int32 templateStart, SnapshotPoint triggerPoint, ITrackingSpan& applicableSpan) in C:\Users\Administrator\Source\Repos\PTVS\Python\Product\Django\Intellisense\DjangoCompletionSourceBase.cs:line 65
   at Microsoft.PythonTools.Django.Intellisense.DjangoCompletionSource.AugmentCompletionSession(ICompletionSession session, IList`1 completionSets) in C:\Users\Administrator\Source\Repos\PTVS\Python\Product\Django\Intellisense\DjangoCompletionSource.cs:line 68
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionSession.Start()
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionBroker.TriggerCompletion(ITextView textView)
   at Microsoft.Web.Editor.Completion.CompletionController.TriggerCompletion()
   at Microsoft.Web.Editor.Completion.CompletionController.ShowCompletion(Boolean autoShownCompletion)
   at Microsoft.Web.Editor.Completion.CompletionController.OnShowMemberList(Boolean filterList)
   at Microsoft.Web.Editor.Completion.CompletionController.OnCompleteWord()
   at Microsoft.Web.Editor.Completion.CompletionCommandHandler.Invoke(Guid group, Int32 id, Object inputArg, Object& outputArg)
   at Microsoft.Web.Editor.Controller.Controller.Invoke(Guid group, Int32 id, Object inputArg, Object& outputArg)
   at Microsoft.Web.Editor.Controller.ViewController.Invoke(Guid group, Int32 id, Object inputArg, Object& outputArg)
   at Microsoft.Html.Editor.Commands.HtmlMainController.Invoke(Guid group, Int32 id, Object inputArg, Object& outputArg)
   at Microsoft.VisualStudio.Html.Interop.CommandTargetToOleShim.Exec(Guid& guidCommandGroup, UInt32 commandID, UInt32 commandExecOpt, IntPtr variantIn, IntPtr variantOut)

**Comment by RaymonGulati1** [comment]
Followup issue: 
"Go to definition" in "path" function is not supported, but it should be. 
![image](https://user-images.githubusercontent.com/3315992/48452765-6068e380-e765-11e8-9d6a-1d2ad267d5f7.png)
