### ISSUE TITLE
Internal error detected VS2017

### ISSUE THREAD

**Issue by akreho1** [Microsoft/PTVS#4886]
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\Python\Core\ptvsd_launcher.py", line 34, in <module>
    import ptvsd.debugger as vspd
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\Python\Core\ptvsd\debugger.py", line 34, in <module>
    import socket
  File "C:\Users\acer\source\repos\socket\socket\socket.py", line 3, in <module>
    sock = socket.socket()
TypeError: 'module' object is not callable

I was trying to establish socket client for WIFI communication usin ESP32. But it keeps showing me this message and since I am new to Python, I do not know what the issue is. I was using the code listed below:
`import socket               
 
sock = socket.socket()
 
host = "192.168.1.78" #ESP32 IP in local network
port = 80             #ESP32 Server Port    
 
sock.connect((host, port))
 
message = "Hello World"
sock.send(message)
 
data = ""       
 
while len(data) < len(message):
    data += sock.recv(1)
 
print(data)
 
sock.close()
`
Thank you very much in advance

**Comment by huguesv** [comment]
This is due to your project file named socket.py which conflicts with the name of the standard library module. The debugger does `import socket` and is getting your module definition. Renaming your project file should fix the issue.

**Comment by akreho1** [comment]
Thank you very much huguesv. That was the only issue. You saved me a lot of time :)
