### ISSUE TITLE
gevent 'BlockingSwitchOutError' exception after updating

### ISSUE THREAD

**Issue by mkimberling** [Microsoft/PTVS#4922]
After updating VisualStudio to 15.9.4 yesterday, I'm experiencing an unhandled exception from `gevent` when I perform operations in my application:
```
 Traceback (most recent call last):
   File "c:\program files (x86)\microsoft visual studio\2017\professional\common7\ide\extensions\microsoft\python\core\Packages\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_frame.py", line 649, in trace_dispatch
     self.do_wait_suspend(thread, frame, event, arg)
   File "c:\program files (x86)\microsoft visual studio\2017\professional\common7\ide\extensions\microsoft\python\core\Packages\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_frame.py", line 134, in do_wait_suspend
     self._args[0].do_wait_suspend(*args, **kwargs)
   File "c:\program files (x86)\microsoft visual studio\2017\professional\common7\ide\extensions\microsoft\python\core\Packages\ptvsd\_vendored\pydevd\pydevd.py", line 821, in do_wait_suspend
     time.sleep(0.01)
   File "Q:\t8\tools\lang\python2.7\lib\site-packages\gevent\hub.py", line 159, in sleep
     hub.wait(t)
   File "src\gevent\_hub_primitives.py", line 46, in gevent.__hub_primitives.WaitOperationsGreenlet.wait
   File "src\gevent\_hub_primitives.py", line 55, in gevent.__hub_primitives.WaitOperationsGreenlet.wait
   File "src\gevent\_waiter.py", line 151, in gevent.__waiter.Waiter.get
   File "src\gevent\_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
   File "src\gevent\_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
   File "src\gevent\_greenlet_primitives.py", line 62, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
   File "src\gevent\_greenlet_primitives.py", line 65, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch_out
   File "src\gevent\_greenlet_primitives.py", line 66, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch_out
 BlockingSwitchOutError: Impossible to call blocking function in the event loop callback
```

Updating gevent & greenlet to the latest version doesn't address the issue.

**Comment by mkimberling** [comment]
I do not get this when the "Use legacy debugger" checkbox in Options:Python:Debugging is checked.

**Comment by huguesv** [comment]
Can you try updating to the latest ptvsd? There's been updates to it since it was bundled with 15.9.

You can do that by "pip install ptvsd" in your python environment. VS knows to use the one in the environment if found.

**Comment by mkimberling** [comment]
I tried that out just now and still get the same error after disabling the legacy debugger.

**Comment by huguesv** [comment]
Thanks! I'll move this to ptvsd issue tracker.

**Comment by huguesv** [comment]
Issue moved to [Microsoft/ptvsd #1073](https://github.com/Microsoft/ptvsd/issues/1073) via [**ZenHub**](https://www.zenhub.com/)
