### ISSUE TITLE
Failed to create conda environment

### ISSUE THREAD

**Issue by zhouwangyang** [Microsoft/PTVS#4949]
VS Version: 28426.108.d16.0stg
Python Tool Version: 16.0.18354.1

make sure use the default installed python miniconda.
![image](https://user-images.githubusercontent.com/39871640/50535671-3dfd1f00-0b87-11e9-94cb-8ddd73c1dc28.png)
repro step:
1.create a python application
2. right-click on "python environment" to select "add environment"
3.select "Conda environment" and select "python 3.7" package names
![image](https://user-images.githubusercontent.com/39871640/50535702-96342100-0b87-11e9-817a-c8beec3bd916.png)
4.click "create"
excepted: create environment successfully
actually: failed to create conda enviroment

**Comment by huguesv** [comment]
```
----- Creating 'env' -----
Solving environment: ...working... done
==> WARNING: A newer version of conda exists. <==
  current version: 4.5.11
  latest version: 4.5.12
Please update conda by running
    $ conda update -n base -c defaults conda
## Package Plan ##
  environment location: C:\Users\huvalo\.conda\envs\env
  added / updated specs: 
    - python=3.7
The following packages will be downloaded:
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
    Traceback (most recent call last):
      File "C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\PREVIEW\COMMON7\IDE\EXTENSIONS\MICROSOFT\PYTHON\MINICONDA\Miniconda3-x64\lib\site-packages\conda\exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\PREVIEW\COMMON7\IDE\EXTENSIONS\MICROSOFT\PYTHON\MINICONDA\Miniconda3-x64\lib\site-packages\conda\cli\main.py", line 78, in _main
        exit_code = do_call(args, p)
      File "C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\PREVIEW\COMMON7\IDE\EXTENSIONS\MICROSOFT\PYTHON\MINICONDA\Miniconda3-x64\lib\site-packages\conda\cli\conda_argparse.py", line 77, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\PREVIEW\COMMON7\IDE\EXTENSIONS\MICROSOFT\PYTHON\MINICONDA\Miniconda3-x64\lib\site-packages\conda\cli\main_create.py", line 11, in execute
        install(args, parser, 'create')
      File "C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\PREVIEW\COMMON7\IDE\EXTENSIONS\MICROSOFT\PYTHON\MINICONDA\Miniconda3-x64\lib\site-packages\conda\cli\install.py", line 253, in install
        handle_txn(unlink_link_transaction, prefix, args, newenv)
      File "C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\PREVIEW\COMMON7\IDE\EXTENSIONS\MICROSOFT\PYTHON\MINICONDA\Miniconda3-x64\lib\site-packages\conda\cli\install.py", line 269, in handle_txn
        unlink_link_transaction.print_transaction_summary()
      File "C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\PREVIEW\COMMON7\IDE\EXTENSIONS\MICROSOFT\PYTHON\MINICONDA\Miniconda3-x64\lib\site-packages\conda\core\link.py", line 735, in print_transaction_summary
        specs_to_remove=stp.remove_specs, specs_to_add=stp.update_specs)
      File "C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\PREVIEW\COMMON7\IDE\EXTENSIONS\MICROSOFT\PYTHON\MINICONDA\Miniconda3-x64\lib\site-packages\conda\plan.py", line 97, in display_actions
        info = index[dist]
    KeyError: Dist(channel='<unknown>', dist_name='ca-certificates-2018.03.07-0', name='ca-certificates', version='2018.03.07', build_string='0', build_number=0, base_url='file:///C:/PROGRAM%20FILES%20%28X86%29/MICROSOFT%20VISUAL%20STUDIO/2019/PREVIEW/COMMON7/IDE/EXTENSIONS/MICROSOFT/PYTHON/MINICONDA/Miniconda3-x64/pkgs', platform=None)
`$ C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\PREVIEW\COMMON7\IDE\EXTENSIONS\MICROSOFT\PYTHON\MINICONDA\Miniconda3-x64\Scripts\conda create -n env -y python=3.7`
  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\PREVIEW\COMMON7\ID
                          E\EXTENSIONS\MICROSOFT\PYTHON\MINICONDA\Miniconda3-x64
                 HOMEPATH=\Users\huvalo
                     PATH=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\Sys
                          tem32\WindowsPowerShell\v1.0\;C:\Users\huvalo\AppData\Local\Microsoft\
                          WindowsApps;
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\Windows
                          PowerShell\v1.0\Modules
         PYTHONUNBUFFERED=1
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
     active environment : None
       user config file : C:\Users\huvalo\.condarc
 populated config files : C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\PREVIEW\COMMON7\IDE\EXTENSIONS\MICROSOFT\PYTHON\MINICONDA\Miniconda3-x64\condarc
          conda version : 4.5.11
    conda-build version : not installed
         python version : 3.7.0.final.0
       base environment : C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\PREVIEW\COMMON7\IDE\EXTENSIONS\MICROSOFT\PYTHON\MINICONDA\Miniconda3-x64  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\PREVIEW\COMMON7\IDE\EXTENSIONS\MICROSOFT\PYTHON\MINICONDA\Miniconda3-x64\pkgs
                          C:\Users\huvalo\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\huvalo\.conda\envs
                          C:\Users\huvalo\AppData\Local\conda\conda\envs
                          C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\PREVIEW\COMMON7\IDE\EXTENSIONS\MICROSOFT\PYTHON\MINICONDA\Miniconda3-x64\envs
               platform : win-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.7.0 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False
An unexpected error has occurred. Conda has prepared the above report.
Upload successful.
----- Failed to create 'env' -----

Failed to create environment.

```

**Comment by huguesv** [comment]
I was able to create one successfully on my PTVS dev machine. Not sure what is going on. Maybe related to the conda preview process being canceled when you press OK without waiting for the preview to finish.

**Comment by huguesv** [comment]
Also not sure if it's only failing when selecting Python 3.7 package, haven't tried any other on that machine.

**Comment by huguesv** [comment]
After upgrading conda it's able to successfully create the environment.

Upgrade:
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\IDE\Extensions\Microsoft\Python\Miniconda\Miniconda3-x64\Scripts>conda update -n base -c defaults conda
Solving environment: done

## Package Plan ##

  environment location: C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\IDE\Extensions\Microsoft\Python\Miniconda\Miniconda3-x64

  added / updated specs:
    - conda


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.5.12               |           py37_0         1.1 MB
    openssl-1.1.1a             |       he774522_0         5.7 MB
    cryptography-2.4.2         |   py37h7a1dbc1_0         550 KB
    certifi-2018.11.29         |           py37_0         146 KB
    ------------------------------------------------------------
                                           Total:         7.5 MB

The following packages will be UPDATED:

    certifi:        2018.8.24-py37_1     --> 2018.11.29-py37_0
    conda:          4.5.11-py37_0        --> 4.5.12-py37_0
    cryptography:   2.3.1-py37h74b6da3_0 --> 2.4.2-py37h7a1dbc1_0
    openssl:        1.0.2p-hfa6e2cd_0    --> 1.1.1a-he774522_0
    vc:             14-h0510ff6_3        --> 14.1-h0510ff6_4
    vs2015_runtime: 14.0.25123-3         --> 14.15.26706-h3a45250_0

Proceed ([y]/n)? y


Downloading and Extracting Packages
conda-4.5.12         | 1.1 MB    | ############################################################################ | 100%
openssl-1.1.1a       | 5.7 MB    | ############################################################################ | 100%
cryptography-2.4.2   | 550 KB    | ############################################################################ | 100%
certifi-2018.11.29   | 146 KB    | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\IDE\Extensions\Microsoft\Python\Miniconda\Miniconda3-x64\Scripts>
```

Create:
```
----- Creating 'condaenv7' -----
Solving environment: ...working... done
## Package Plan ##
  environment location: C:\Users\huvalo\.conda\envs\condaenv7
  added / updated specs: 
    - requests
The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    six-1.12.0                 |           py37_0          22 KB
    requests-2.21.0            |           py37_0          85 KB
    pip-18.1                   |           py37_0         1.8 MB
    setuptools-40.6.3          |           py37_0         631 KB
    pycparser-2.19             |           py37_0         173 KB
    python-3.7.2               |       h8c8aaf0_0        17.7 MB
    idna-2.8                   |           py37_0         101 KB
    urllib3-1.24.1             |           py37_0         150 KB
    wheel-0.32.3               |           py37_0          53 KB
    ------------------------------------------------------------
                                           Total:        20.7 MB
The following NEW packages will be INSTALLED:
    asn1crypto:      0.24.0-py37_0         
    ca-certificates: 2018.03.07-0          
    certifi:         2018.11.29-py37_0     
    cffi:            1.11.5-py37h74b6da3_1 
    chardet:         3.0.4-py37_1          
    cryptography:    2.4.2-py37h7a1dbc1_0  
    idna:            2.8-py37_0            
    openssl:         1.1.1a-he774522_0     
    pip:             18.1-py37_0           
    pycparser:       2.19-py37_0           
    pyopenssl:       18.0.0-py37_0         
    pysocks:         1.6.8-py37_0          
    python:          3.7.2-h8c8aaf0_0      
    requests:        2.21.0-py37_0         
    setuptools:      40.6.3-py37_0         
    six:             1.12.0-py37_0         
    sqlite:          3.26.0-he774522_0     
    urllib3:         1.24.1-py37_0         
    vc:              14.1-h0510ff6_4       
    vs2015_runtime:  14.15.26706-h3a45250_0
    wheel:           0.32.3-py37_0         
    win_inet_pton:   1.0.1-py37_1          
    wincertstore:    0.2-py37_0            
Downloading and Extracting Packages
```

**Comment by huguesv** [comment]
The problem appears to be that the subfolders for the extracted packages under the miniconda3-x64\pkgs folder need to be there in addition to the .tar.bz2 package files.

Right now we only put down the .tar.bz2 files.

On PTVS dev machine, this works because the miniconda3-x64 folder is under user permission, and so the .tar.bz2 files get extracted, but that doesn't work when miniconda3-x64 is under program files folder.

**Comment by huguesv** [comment]
Unfortunately, those folders consist of over 7000 files.
