### ISSUE TITLE
Unexpected error in Python debugger Debug Interactive

### ISSUE THREAD

**Issue by a-j-albert** [microsoft/PTVS#4957]
I had typed in 'webpage' and was waiting for the value to be displayed, when I received the error.  I see the value is actually there:

[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 15.9.18254.1

System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Microsoft.PythonTools.Repl.PythonDebugProcessReplEvaluator..ctor(IServiceProvider serviceProvider, PythonProcess process, IThreadIdMapper threadIdMapper)
   at Microsoft.PythonTools.Repl.PythonDebugReplEvaluator.<AttachProcessAsync>d__80.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Repl.PythonDebugReplEvaluator.<OnReadyForInputAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by huguesv** [comment]
Need to correctly handle the scenario where GetThreads returns no result.

**Comment by judej** [comment]
@RaymonGulati1, Please check if this is legacy. If it is, please close

**Comment by huguesv** [comment]
`PythonDebugProcessReplEvaluator` is legacy debugger. Please disable legacy debugger in tools/options to get around this.
