### ISSUE TITLE
pykinect Import problems

### ISSUE THREAD

**Issue by simoni-pietro** [microsoft/PTVS#5067]
hi im new to programin and woanted to do somthin this the kinect 
but i have a import problem i can't  out figure out.
 im using pycharm and imported pygame and pykinect 
CODE:
from pykinect import nui

with nui.Runtime() as Kinect:
    Kinect.skeleton_engine.enabled = true
    while true:
        frame = Kinect.skeleton_engine.get_next_frame()
        print frame

ERROR:
C:\Python27\python.exe "C:/Users/simon/PycharmProjects/untitled/venv/caoonesion ano.py"
Traceback (most recent call last):
  File "C:/Users/simon/PycharmProjects/untitled/venv/caoonesion ano.py", line 2, in <module>
    from pykinect import nui
  File "C:\Python27\lib\site-packages\pykinect\nui\__init__.py", line 22, in <module>
    from pykinect.nui.structs import (ImageDigitalZoom, ImageFrame, ImageResolution, 
  File "C:\Python27\lib\site-packages\pykinect\nui\structs.py", line 513, in <module>
    _NuiSkeletonCalculateBoneOrientations = _NUIDLL.NuiSkeletonCalculateBoneOrientations
  File "C:\Python27\lib\ctypes\__init__.py", line 379, in __getattr__
    func = self.__getitem__(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 384, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'NuiSkeletonCalculateBoneOrientations' not found

Process finished with exit code 1

**Comment by huguesv** [comment]
Have you installed the Kinect SDK? This I think: https://www.microsoft.com/en-us/download/details.aspx?id=40278

**Comment by simoni-pietro** [comment]
Now  I did, but there's another error:
Traceback (most recent call last):
  File "C:/Users/simon/PycharmProjects/untitled/venv/caoonesion ano.py", line 4, in <module>
    with nui.Runtime() as Kinect:
  File "C:\Python27\lib\site-packages\pykinect\nui\__init__.py", line 109, in __init__
    self._nui = _NuiCreateSensorByIndex(index)
  File "C:\Python27\lib\site-packages\pykinect\nui\_interop.py", line 257, in _NuiCreateSensorByIndex
    __NuiCreateSensorByIndex(index, ctypes.byref(inst))
  File "_ctypes/callproc.c", line 950, in GetResult
WindowsError: [Error -2097085051] Windows Error 0x83010585

Process finished with exit code 1

**Comment by judej** [comment]
@simoni-pietro, sorry, but we don't support pyKinect.

**Comment by GameDungeon** [comment]
As this is the only reference to this error I can find on the internet, I'll point out the solution for anyone else walking down my path. 

> WindowsError: [Error -2097085051] Windows Error 0x83010585

This error happens if you install the libusbk driver on the Kinect and then try to use it with pykinect. Uninstall the device and let windows redownload the proper driver.
