### ISSUE TITLE
VS2017 remote debugging of python 3.x

### ISSUE THREAD

**Issue by JensSkytteMikkelsen** [Microsoft/PTVS#5089]
I'm debugging a Python 3.x process on a Linux box. I got attached to the process via ptvsd. Got the process break in but when i try to set a breakpoint I get the following error. Something with type for a filename not being a string.
The question is how to get arround this? 
Content from Output window:
Loaded '__main__'
Traceback (most recent call last):
  File "/usr/local/python-3.7/lib/python3.7/site-packages/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 278, in _on_run
    self.process_net_command_json(self.global_debugger_holder.global_dbg, json_contents)
  File "/usr/local/python-3.7/lib/python3.7/site-packages/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command_json.py", line 48, in process_net_command_json
    cmd = on_request(py_db, request)
  File "/usr/local/python-3.7/lib/python3.7/site-packages/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command_json.py", line 155, in on_setbreakpoints_request
    filename = self.api.filename_to_server(filename)
  File "/usr/local/python-3.7/lib/python3.7/site-packages/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_api.py", line 202, in filename_to_server
    filename = self.filename_to_str(filename)
  File "/usr/local/python-3.7/lib/python3.7/site-packages/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_api.py", line 198, in filename_to_str
    raise AssertionError('Expected to have str on Python 3. Found: %s (%s)' % (filename, filename.__class__))
AssertionError: Expected to have str on Python 3. Found: None (<class 'NoneType'>)

**Comment by huguesv** [comment]
Could you please provide debug log for this? Instructions to enable logging are here: https://docs.microsoft.com/en-us/visualstudio/python/debugging-python-in-visual-studio?view=vs-2017#enable-debugger-logging

**Comment by jemicon** [comment]
After successfully setting the debug flag on I get the below log in the output window now at VS2017 on my dev PC. A of the same stuf as I got in console of the python process.

Traceback (most recent call last):
  File "/usr/local/python-3.7/lib/python3.7/site-packages/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 278, in _on_run
    self.process_net_command_json(self.global_debugger_holder.global_dbg, json_contents)
  File "/usr/local/python-3.7/lib/python3.7/site-packages/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command_json.py", line 48, in process_net_command_json
    cmd = on_request(py_db, request)
  File "/usr/local/python-3.7/lib/python3.7/site-packages/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command_json.py", line 155, in on_setbreakpoints_request
    filename = self.api.filename_to_server(filename)
  File "/usr/local/python-3.7/lib/python3.7/site-packages/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_api.py", line 202, in filename_to_server
    filename = self.filename_to_str(filename)
  File "/usr/local/python-3.7/lib/python3.7/site-packages/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_api.py", line 198, in filename_to_str
    raise AssertionError('Expected to have str on Python 3. Found: %s (%s)' % (filename, filename.__class__))
AssertionError: Expected to have str on Python 3. Found: None (<class 'NoneType'>)

**Comment by JensSkytteMikkelsen** [comment]
After successfully setting the debug flag on I get the below log in the output window now at VS2017 on my dev PC. A of the same stuf as I got in console of the python process.

Traceback (most recent call last):
 File "/usr/local/python-3.7/lib/python3.7/site-packages/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 278, in _on_run
 self.process_net_command_json(self.global_debugger_holder.global_dbg, json_contents)
 File "/usr/local/python-3.7/lib/python3.7/site-packages/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command_json.py", line 48, in process_net_command_json
 cmd = on_request(py_db, request)
 File "/usr/local/python-3.7/lib/python3.7/site-packages/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command_json.py", line 155, in on_setbreakpoints_request
 filename = self.api.filename_to_server(filename)
 File "/usr/local/python-3.7/lib/python3.7/site-packages/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_api.py", line 202, in filename_to_server
 filename = self.filename_to_str(filename)
 File "/usr/local/python-3.7/lib/python3.7/site-packages/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_api.py", line 198, in filename_to_str
 raise AssertionError('Expected to have str on Python 3. Found: %s (%s)' % (filename, filename.class))
 AssertionError: Expected to have str on Python 3. Found: None (<class 'NoneType'>)

**Comment by huguesv** [comment]
The log should show json messages like this:
![image](https://user-images.githubusercontent.com/1696845/53036559-d481ea00-342c-11e9-9a29-ee74ecfe7683.png)

This tells us what values are being sent to the debugger from Visual Studio.

**Comment by JensSkytteMikkelsen** [comment]
Yes but I'm not getting the breakpoint set in the target process (python.exe test.py).
I throws the exception on target Expected to have str on Python 3. Found: None (<class 'NoneType'>)

**Comment by huguesv** [comment]
A few things:
- Because we don't have path mappings functionality (yet), you will not be able to set breakpoints before you've attached. It's not clear whether that's what you are doing or not. Try clearing breakpoints before attaching.
- Setting a breakpoint after you've attached should work in most scenarios, but there are known corner cases regarding encoding and also the use of `compile()`.

After you've attached, any debug operation like F9 from VS should send a message to the debuggee, and show up in the Debug Adapter Host Log window.
