### ISSUE TITLE
NullReferenceException in Microsoft.PythonTools.Intellisense.CompletionAnalysis

### ISSUE THREAD

**Issue by huguesv** [microsoft/PTVS#5132]
Whenever I type a variable name in python, VS crashes before intellisense displays information.

```
Exception Info: System.NullReferenceException
   at Microsoft.PythonTools.Intellisense.CompletionAnalysis+<>c.<GetCompletions>b__12_0(Microsoft.PythonTools.Analysis.LanguageServer.CompletionItem)
   at System.Linq.Enumerable+<>c__DisplayClass7_0`3[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<CombineSelectors>b__0(System.__Canon)
   at System.Linq.Enumerable+WhereSelectArrayIterator`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Linq.Enumerable+WhereEnumerableIterator`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Linq.Buffer`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]..ctor(System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at System.Linq.OrderedEnumerable`1+<GetEnumerator>d__1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Linq.Enumerable.Any[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at Microsoft.VisualStudio.Language.Intellisense.BulkObservableCollection`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].AddRange(System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at Microsoft.PythonTools.Intellisense.FuzzyCompletionSet..ctor(System.String, System.String, Microsoft.VisualStudio.Text.ITrackingSpan, System.Collections.Generic.IEnumerable`1<Microsoft.PythonTools.Intellisense.DynamicallyVisibleCompletion>, Microsoft.PythonTools.Intellisense.CompletionOptions, System.Collections.Generic.IComparer`1<Microsoft.VisualStudio.Language.Intellisense.Completion>, Boolean)
   at Microsoft.PythonTools.Intellisense.CompletionAnalysis.GetCompletions(Microsoft.VisualStudio.Language.Intellisense.IGlyphService)
   at Microsoft.PythonTools.Intellisense.CompletionSource.AugmentCompletionSession(Microsoft.VisualStudio.Language.Intellisense.ICompletionSession, System.Collections.Generic.IList`1<Microsoft.VisualStudio.Language.Intellisense.CompletionSet>)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionSession.Start()
   at Microsoft.PythonTools.Intellisense.IntellisenseController+<TriggerCompletionSession>d__43.MoveNext()
   at Microsoft.PythonTools.Infrastructure.TaskExtensions.ReThrowTaskException(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

Also reported at https://developercommunity.visualstudio.com/content/problem/468023/an-unhandled-microsoft-net-framework-exception-occ-2.html

**Comment by huguesv** [comment]
same as https://github.com/microsoft/PTVS/issues/6076 which is now fixed for 16.6
