### ISSUE TITLE
An error occurs when creating Iron Python  WPF application at the first time

### ISSUE THREAD

**Issue by xiaofeng0123** [Microsoft/PTVS#5168]
VS Version: 28701.213.d16.0stg
Python Tool Version: 16.0.19066.1
Repro step:
1. Install Iron Python
2. Create Iron Python WPF application

Actual Result:
An error popup when creating Iron Python WPF application **at the first time**
![image](https://user-images.githubusercontent.com/41426540/54419762-363f2680-4743-11e9-905c-71d70991ed4d.png)

Expect Result:
No error popup

**Comment by huguesv** [comment]
When an activity log error message box appears, please include the relevant contents from the file. You can open it in Microsoft Edge and it will format it as a table. The error will usually be near the bottom, with a red background.

Did you have IronPython installed? If so, which exact version?
Which Visual Studio workload did you have installed?

**Comment by xiaofeng0123** [comment]
[ActivityLog.zip](https://github.com/Microsoft/PTVS/files/2976070/ActivityLog.zip)
Installed Iron Python version: 2.7.9
Installed workload is "Desktop development with C++" and "Python development"
Below screenshot is the error message in activity log. and the attachment is activity log file. 
![image](https://user-images.githubusercontent.com/41426540/54501872-b8f1fc80-4962-11e9-81fd-39ae51b86bb5.png)

**Comment by huguesv** [comment]
@xiaofeng0123

I installed today's dogfood build Preview 4.4 [28718.190.d16.0stg] with those 2 workloads + IronPython 2.7.9 and I'm not experiencing this issue.

The call stacks show it's an issue in Roslyn. It's better to file this one via Send Feedback -> Report a Problem

```
A MEF Component threw an exception at runtime: Microsoft.VisualStudio.Composition.CompositionFailedException: An exception was thrown while initializing part "Microsoft.VisualStudio.LanguageServices.Implementation.Options.LanguageSettingsPersister". ---> System.InvalidOperationException: Unexpected false at Roslyn.Utilities.Contract.ThrowIfFalse(Boolean condition, String message) at Microsoft.CodeAnalysis.Editor.Shared.Utilities.ForegroundThreadAffinitizedObject.AssertIsForeground() at Microsoft.CodeAnalysis.Editor.Shared.Utilities.ForegroundThreadAffinitizedObject..ctor(IThreadingContext threadingContext, Boolean assertIsForeground) at Microsoft.VisualStudio.LanguageServices.Implementation.Options.LanguageSettingsPersister..ctor(IThreadingContext threadingContext, IServiceProvider serviceProvider, IGlobalOptionService optionService) --- End of inner exception stack trace --- at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue() at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create() at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState) at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState) at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose() at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0()
```
```
Microsoft.VisualStudio.Composition.CompositionFailedException: An exception was thrown while initializing part "Microsoft.VisualStudio.LanguageServices.Implementation.Options.LanguageSettingsPersister". ---> System.InvalidOperationException: Unexpected false at Roslyn.Utilities.Contract.ThrowIfFalse(Boolean condition, String message) at Microsoft.CodeAnalysis.Editor.Shared.Utilities.ForegroundThreadAffinitizedObject.AssertIsForeground() at Microsoft.CodeAnalysis.Editor.Shared.Utilities.ForegroundThreadAffinitizedObject..ctor(IThreadingContext threadingContext, Boolean assertIsForeground) at Microsoft.VisualStudio.LanguageServices.Implementation.Options.LanguageSettingsPersister..ctor(IThreadingContext threadingContext, IServiceProvider serviceProvider, IGlobalOptionService optionService) --- End of stack trace from previous location where exception was thrown --- at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject) --- End of stack trace from previous location where exception was thrown --- at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject) --- End of inner exception stack trace --- at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue() at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create() at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState) at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState) at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose() at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0() at Microsoft.VisualStudio.Composition.DelegateServices.<>c__DisplayClass2_0`1.<As>b__0() at System.Lazy`1.CreateValue() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Lazy`1.get_Value() at Microsoft.CodeAnalysis.Options.GlobalOptionService.LoadOptionFromSerializerOrGetDefault(OptionKey optionKey) at Microsoft.CodeAnalysis.Options.GlobalOptionService.GetOption(OptionKey optionKey) at Microsoft.CodeAnalysis.Options.OptionServiceFactory.OptionService.GetOption(OptionKey optionKey) at Microsoft.CodeAnalysis.Options.WorkspaceOptionSet.GetOption(OptionKey optionKey) at Microsoft.CodeAnalysis.Options.OptionSet.GetOption[T](Option`1 option) at Microsoft.CodeAnalysis.Editor.Shared.Extensions.ITextBufferExtensions.GetFeatureOnOffOption(ITextBuffer buffer, Option`1 option) at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.CreateTaggerWorker[T](ITextView textViewOpt, ITextBuffer subjectBuffer) at Microsoft.CodeAnalysis.Editor.Tagging.AsynchronousViewTaggerProvider`1.CreateTagger[T](ITextView textView, ITextBuffer subjectBuffer) at Microsoft.CodeAnalysis.Editor.Tagging.AsynchronousViewTaggerProvider`1.Microsoft.VisualStudio.Text.Tagging.IViewTaggerProvider.CreateTagger[T](ITextView textView, ITextBuffer buffer) at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.InstantiateViewTagger(ITextView textView, Lazy`2 factory, ITextBuffer textBuffer, IList`1 newTaggers)
```

**Comment by xiaofeng0123** [comment]
I found this issue on Preview 4.3 [28701.213.d16.0stg]. And I verified on today's latest build Preview 4.4[28719.195.d16.0stg]. It is not repro. I will file it via Send Feedback -> Report a Problem if this issue occurs again in future testing

**Comment by huguesv** [comment]
Thanks!

**Comment by VipulPandey-arch** [comment]
@xiaofeng0123 
change the debugger from python 3.7 to iron python .if its not being shown then install iron python from cmd prompt.
