### ISSUE TITLE
InteliSense often doesn't work at all.

### ISSUE THREAD

**Issue by jmh-aira** [Microsoft/PTVS#5214]
Hi, I'm using visual studio 2019 pro, the released version this april 2nd...  Often when I open a project and enter a python file, no INtelliSense is working.  If I start typing 'imp', I expect things like Import to come up.  But a good chunk of the time nothing comes up.  Sometimes INtelliSense starts working after a few minutes, but other times I have to restart visual studio.

**Comment by huguesv** [comment]
Hi @jmh-aira 

A delay after initial load is expected especially for environments with large libraries installed, but it should eventually work.

Can you see the Microsoft.PythonTools.Analyzer.exe running in task manager, and if so, is there CPU usage while you are waiting for completions to start working?

Can you provide some info on the environment you are using (python version, packages installed) and the imports that you have in your project?

**Comment by wangxianliang** [comment]
The same phenomena here. After copying some codes from one file to current editing file, the INtelliSense is totally gone.

**Comment by huguesv** [comment]
We do not have a repro for this, so any additional information, like code we can use to reproduce, is appreciated.

**Comment by eugals** [comment]
@huguesv 
Here's a repro which fails every time in my latest official VS2019 CE: [PTVSFailTest.zip](https://github.com/microsoft/PTVS/files/3168986/PTVSFailTest.zip)

IntelliSense doesn't work in ALL python modules this project includes.
But if you exclude `app/viewset.py` from it, save and reopen VS, then bam, everything would work fine after that (if if significantly slower as compared to VS2017, but this is probably another issue).

So something in `viewset.py` must be breaking the engine. This module should contain some errors because I had just started working on it by copying&pasting random pieces of code from other django modules. But why would it break IntelliSense in all the other Python files and make typing some much slow everywhere?

**Comment by eugals** [comment]
I've updated to `16.0.4` today and can confirm that the issue is still reproduceable there.

**Comment by huguesv** [comment]
Thanks @eugals I can repro with your project's viewset.py. I'll try to narrow it down further.

**Comment by Trigve** [comment]
I've got also intelisense problem with VS 2017 (15.9.14).

If in package's __init__.py there is some import of local py module, intelisense doesn't work anymore:
```
...
from . import some_module
...
```

If the "import" line is deleted, then the intelisene will work again (after restart).

I'm using VS as part of project where python is embedded in C++ application.

**Comment by timothy4** [comment]
I also have an InteliSense problem with VB 2017, version 15.9.14. When I updated to that version I was forced to update my PTVSD version to 4.2.10. and that's when I first noticed the problem, but I'm not sure if there wasn't a problem before that.

**Comment by Pcb21** [comment]
Hi,

I have what is, at some level at least, the same issue. 
Visual Studio Professional 2019 16.4.3 - Python 16.4.19310.1

I load my solution containing 17 pyprojs. Each projects gets its own "Visual Studio - Python background analyser" process. After a while all but one of them settle down to use no CPU. The one remaining process runs "forever" with CPU %percentage looking like it is using 1 core. If I try to use intellisense by e.g. F12, then I get the "Python source analysis is not up-to-date message".  I can see from the /comment to the command line of the analyser that it is one particular .pyproj that is causing the problem, but F12 doesn't work in any project, even on ones that are not dependent on the problematic project.

How can I narrow down the code that is causing the analyser problems? This project contains ~100 or so .py files that I am not permitted to upload here. Is there any logging/ further diagnostics that I can enable that might pin it down? Thanks.

Here is a snippet from Tools -> Options -> Python -> Diagnostics -> Copy diagnostics to clipboard (if necessary I can attach whole file but will need to scrub some data :-/) - I didn't explicit cancel any diagnostics myself.


Analysis abnormalities (102):
[01/30/2020 16:40:11] AnalysisWarning: Reloading modules... 
[01/30/2020 16:40:11] AnalysisWarning: Reloading modules... 
[01/30/2020 16:40:11] AnalysisWarning: Reloading modules... 
[01/30/2020 16:40:11] AnalysisWarning: Reloading modules... 
[01/30/2020 16:40:11] AnalysisWarning: Reloading modules... 
[01/30/2020 16:40:11] AnalysisWarning: Reloading modules... 
[01/30/2020 16:40:11] AnalysisWarning: Reloading modules... 
[01/30/2020 16:40:11] AnalysisWarning: Reloading modules... 
[01/30/2020 16:40:11] AnalysisWarning: Reloading modules... 
[01/30/2020 16:40:11] AnalysisWarning: Reloading modules... 
[01/30/2020 16:40:11] AnalysisWarning: Reloading modules... 
[01/30/2020 16:40:11] AnalysisWarning: Reloading modules... 
[01/30/2020 16:40:11] AnalysisWarning: Reloading modules... 
[01/30/2020 16:40:11] AnalysisWarning: Reloading modules... 
[01/30/2020 16:40:11] AnalysisWarning: Reloading modules... 
[01/30/2020 16:40:12] AnalysisWarning: Reloading modules... 
[01/30/2020 16:40:12] AnalysisWarning: Reloading modules... 
[01/30/2020 16:40:12] AnalysisWarning: Reloading modules... 
[01/30/2020 16:40:13] AnalysisWarning: Reloading modules... 
[01/30/2020 16:40:13] AnalysisWarning: Reloading modules... 
[01/30/2020 16:40:20] AnalysisWarning: Reloading modules... 
[01/30/2020 16:40:21] AnalysisWarning: Reloading modules... 
[01/30/2020 16:40:23] AnalysisWarning: Reloading modules... 
[01/30/2020 16:40:23] AnalysisWarning: Reloading modules... 
[01/30/2020 16:40:23] AnalysisWarning: Reloading modules... 
[01/30/2020 16:40:23] AnalysisWarning: Reloading modules... 
[01/30/2020 16:40:24] AnalysisWarning: Reloading modules... 
[01/30/2020 16:40:24] AnalysisWarning: Reloading modules... 
[01/30/2020 16:40:26] AnalysisWarning: Reloading modules... 
[01/30/2020 16:40:26] AnalysisWarning: Reloading modules... 
[01/30/2020 16:40:28] AnalysisWarning: Reloading modules... 
[01/30/2020 16:40:28] AnalysisWarning: Reloading modules... 
[01/30/2020 16:40:30] AnalysisWarning: done.
[01/30/2020 16:40:30] AnalysisWarning: Reloading modules... 
[01/30/2020 16:40:30] AnalysisWarning: Reloading modules... 
[01/30/2020 16:40:30] AnalysisWarning: done.
[01/30/2020 16:40:31] AnalysisWarning: done.
[01/30/2020 16:40:32] AnalysisWarning: done.
[01/30/2020 16:40:35] AnalysisWarning: done.
[01/30/2020 16:40:35] AnalysisWarning: done.
[01/30/2020 16:40:36] AnalysisWarning: done.
[01/30/2020 16:40:36] AnalysisWarning: done.
[01/30/2020 16:40:36] AnalysisWarning: done.
[01/30/2020 16:40:36] AnalysisWarning: done.
[01/30/2020 16:40:37] AnalysisWarning: done.
[01/30/2020 16:40:43] AnalysisWarning: done.
[01/30/2020 16:40:45] AnalysisWarning: done.
[01/30/2020 16:40:45] AnalysisWarning: done.
[01/30/2020 16:40:47] AnalysisWarning: done.
[01/30/2020 16:40:48] AnalysisWarning: done.
[01/30/2020 16:40:48] AnalysisWarning: done.
[01/30/2020 16:40:49] AnalysisWarning: done.
[01/30/2020 16:40:50] AnalysisWarning: done.
[01/30/2020 16:40:50] AnalysisWarning: done.
[01/30/2020 16:40:50] AnalysisWarning: done.
[01/30/2020 16:40:53] AnalysisWarning: done.
[01/30/2020 16:40:53] AnalysisWarning: done.
[01/30/2020 16:40:55] AnalysisWarning: done.
[01/30/2020 16:40:57] AnalysisWarning: done.
[01/30/2020 16:40:57] AnalysisWarning: done.
[01/30/2020 16:40:57] AnalysisWarning: done.
[01/30/2020 16:40:59] AnalysisWarning: done.
[01/30/2020 16:40:59] AnalysisWarning: done.
[01/30/2020 16:41:00] AnalysisWarning: done.
[01/30/2020 16:41:06] AnalysisWarning: done.
[01/30/2020 16:41:09] AnalysisWarning: done.
[01/30/2020 16:41:12] AnalysisWarning: done.
[01/30/2020 16:41:12] AnalysisWarning: done.
[01/30/2020 16:41:53] AnalysisOperationCancelled: 
[01/30/2020 16:41:53] AnalysisOperationCancelled: 
[01/30/2020 16:41:56] AnalysisOperationCancelled: 
[01/30/2020 16:41:57] AnalysisOperationCancelled: 
[01/30/2020 16:42:00] AnalysisOperationCancelled: 
[01/30/2020 17:54:05] AnalysisWarning: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.PythonTools.Analysis.AnalysisSetDetails.AnalysisHashSet.SetEquals(IAnalysisSet other)
   at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.PythonTools.Analysis.ObjectComparer.Equals(IAnalysisSet set1, IAnalysisSet set2)
   at System.Collections.Generic.ObjectEqualityComparer`1.Equals(T x, T y)
   at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value)
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at Microsoft.PythonTools.Analysis.TypedDef`1.EstimateTypeCount(IAnalysisSet extraTypes)
   at Microsoft.PythonTools.Analysis.Analyzer.FunctionScope.UpdateParameters(FunctionAnalysisUnit unit, ArgumentSet others, Boolean enqueue, FunctionScope scopeWithDefaultParameters, Boolean usePlaceholders)
   at Microsoft.PythonTools.Analysis.Analyzer.FunctionAnalysisUnit.UpdateParameters(ArgumentSet callArgs, Boolean enqueue)
   at Microsoft.PythonTools.Analysis.Values.FunctionInfo.Call(Node node, AnalysisUnit unit, IAnalysisSet[] args, NameExpression[] keywordArgNames)
   at Microsoft.PythonTools.Analysis.Analyzer.ExpressionEvaluator.EvaluateCall(ExpressionEvaluator ee, Node node)
   at Microsoft.PythonTools.Analysis.Analyzer.ExpressionEvaluator.EvaluateWorker(Node node)
   at Microsoft.PythonTools.Analysis.Analyzer.ExpressionEvaluator.Evaluate(IList`1 nodes)
   at Microsoft.PythonTools.Analysis.Analyzer.ExpressionEvaluator.EvaluateCall(ExpressionEvaluator ee, Node node)
   at Microsoft.PythonTools.Analysis.Analyzer.ExpressionEvaluator.EvaluateWorker(Node node)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(ExpressionStatement node)
   at Microsoft.PythonTools.Parsing.Ast.ExpressionStatement.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(SuiteStatement node)
   at Microsoft.PythonTools.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Analysis.Analyzer.FunctionAnalysisUnit.AnalyzeWorker(DDG ddg, CancellationToken cancel)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Analyze(Deque`1 queue, CancellationToken cancel, Action`1 reportQueueSize, Int32 reportQueueInterval)
   at Microsoft.PythonTools.Analysis.PythonAnalyzer.AnalyzeQueuedEntries(CancellationToken cancel)
   at Microsoft.PythonTools.Intellisense.AnalysisQueue.GroupAnalysis.Analyze(CancellationToken cancel)
   at Microsoft.PythonTools.Intellisense.AnalysisQueue.<HandleAnalyzable>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Intellisense.AnalysisQueue.<ConsumerLoop>d__25.MoveNext()
[01/30/2020 17:56:05] AnalysisWarning: Reloading modules... 
[01/30/2020 17:58:57] AnalysisOperationCancelled: 
[01/30/2020 17:58:57] AnalysisOperationCancelled: 
[01/30/2020 17:58:59] AnalysisOperationCancelled: 
[01/30/2020 17:58:59] AnalysisOperationCancelled: 
[01/30/2020 17:59:00] AnalysisOperationCancelled: 
[01/30/2020 17:59:01] AnalysisOperationCancelled: 
[01/30/2020 17:59:02] AnalysisOperationCancelled: 
[01/30/2020 17:59:08] AnalysisOperationCancelled: 
[01/30/2020 18:00:34] AnalysisOperationCancelled: 
[01/30/2020 18:00:34] AnalysisOperationCancelled: 
[01/30/2020 18:33:50] AnalysisOperationCancelled: 
[01/30/2020 18:33:51] AnalysisOperationCancelled: 
[01/30/2020 18:33:54] AnalysisOperationCancelled: 
[01/30/2020 18:33:55] AnalysisOperationCancelled: 
[01/30/2020 18:33:55] AnalysisOperationCancelled: 
[01/30/2020 18:33:59] AnalysisOperationCancelled: 
[01/30/2020 18:33:59] AnalysisOperationCancelled: 
[01/30/2020 18:34:02] AnalysisOperationCancelled: 
[01/30/2020 18:34:07] AnalysisOperationCancelled: 
[01/30/2020 18:34:07] AnalysisOperationCancelled: 
[01/30/2020 18:34:13] AnalysisOperationCancelled: 
[01/30/2020 18:34:14] AnalysisOperationCancelled: 
[01/30/2020 18:34:18] AnalysisOperationCancelled: 
[01/30/2020 18:34:18] AnalysisOperationCancelled: 
[01/30/2020 18:34:18] AnalysisOperationCancelled: 
[01/30/2020 18:34:19] AnalysisOperationCancelled: 
[01/30/2020 18:34:20] AnalysisOperationCancelled: 

Analysis timing:
    GetExpressionAtPoint (count 20, slow count 20, 18 timeouts, max 1,731ms, mean 1,063.90ms)
    GetExpressionSpanAtPoint (count 12, slow count 12, 9 timeouts, max 1,015ms, mean 1,008.33ms)
    GetQuickInfo (count 12, slow count 12, 0 timeouts, max 500ms, mean 499.33ms)

**Comment by Pcb21** [comment]
Re my previous comment - if unload the problematic .pyproj, save the .sln, re-start Visual Studio then (after the initial warmup period) Intellisense *is* available to the other projects. 

Also the diagnostics for the new session do NOT show the HashSet exception shown in the previous session, so it feels like that exception could be a cause...?
