### ISSUE TITLE
NullReferenceException in SetupPackagesCache.GetPackages from Add environment dialog

### ISSUE THREAD

**Issue by miftahfauzy** [microsoft/PTVS#5235]
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[V] Show details  [Close]

[Expanded Information]
```
Build: 16.1.19081.2

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.PlatformUI.SetupPackagesCache.GetPackages(String& language, DateTime& installDate, DateTime& lastUpdatedDate, Uri& currentReleaseUri, String& currentProductDisplayVersion, String& currentProductDisplayName)
   at Microsoft.VisualStudio.PlatformUI.SetupPackagesCache.Refresh()
   at Microsoft.VisualStudio.PlatformUI.SetupPackagesCache.<>c.<.cctor>b__35_0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Microsoft.VisualStudio.PlatformUI.SetupCompositionService.GetSetupPackagesInfo(UInt32 numberofPackages, IVsSetupPackageInfo[] packageInfo, UInt32& pcActual)
   at Microsoft.PythonTools.Environments.AddInstalledEnvironmentView.GetPackages(IVsSetupCompositionService setupService)
   at Microsoft.PythonTools.Environments.AddInstalledEnvironmentView..ctor(IServiceProvider serviceProvider, ProjectView[] projects, ProjectView selectedProject)
   at Microsoft.PythonTools.Environments.AddEnvironmentDialog.<ShowDialogAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Environments.AddEnvironmentDialog.<ShowAddVirtualEnvironmentDialogAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by huguesv** [comment]
Thanks for the report!

I filed internal bug 847842 against VS/Setup team.

**Comment by RaymonGulati1** [comment]
Can you please provide steps to reproduce this issue?

**Comment by RaymonGulati1** [comment]
Closed because not a lot of people are currently affected by this bug. If this changes, please comment or reopen this issue and we will investigate again.
