### ISSUE TITLE
wfastcgi3.0.0 + django 2.1.8 + IIS, WSGI_HANDLER not set

### ISSUE THREAD

**Issue by wdifruscio** [microsoft/PTVS#5302]
I followed the instructions exactly on the microsoft docs, as well as some youtube videos.
Here is my error and my config

```
Error occurred while reading WSGI handler:

Traceback (most recent call last):
  File "c:\python\lib\site-packages\wfastcgi.py", line 791, in main
    env, handler = read_wsgi_handler(response.physical_path)
  File "c:\python\lib\site-packages\wfastcgi.py", line 633, in read_wsgi_handler
    handler = get_wsgi_handler(os.getenv("WSGI_HANDLER"))
  File "c:\python\lib\site-packages\wfastcgi.py", line 586, in get_wsgi_handler
    raise Exception('WSGI_HANDLER env var must be set')
Exception: WSGI_HANDLER env var must be set


StdOut: 

StdErr: 
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <remove name="project" />
      <add name="Python FastCGI" path="*" verb="*" modules="FastCgiModule" scriptProcessor="C:\python\python.exe|c:\python\lib\site-packages\wfastcgi.py" resourceType="Unspecified" requireAccess="Script" />
    </handlers>
    <httpErrors errorMode="Detailed" />
    <asp scriptErrorSentToBrowser="true" />
  </system.webServer>
  <system.web>
    <customErrors mode="Off" />
    <compilation debug="true" />
  </system.web>
  <appSettings>
      <add key="PYTHONPATH" value="c:\inetpub\wwwroot\STC\project" />
      <add key="WSGI_HANDLER" value="project.wsgi.application" />
      <add key="DJANGO_SETTINGS_MODULE" value="project.settings" />
  </appSettings>
</configuration>
```

**Comment by huguesv** [comment]
There's nothing that jumps out as being wrong, it's the first time I see a report of that particular error. There may be something about the IIS configuration that is not applying those keys as environment variables? I remember reading about some people have permissions not set correctly that affected usage of wfastcgi, but I'm searching online and not finding it anymore.

**Comment by wdifruscio** [comment]
I worked around this by manually setting the environment variables needed inside wfastcgi.py, unfortunately this means I will have to do this manually on several django projects. I have not found where my permissions might be wrong.

Thanks regardless!

**Comment by Bodra123** [comment]
@wdifruscio 
Hello!
I got the same problem. Do You know any solution?
What you changed in Your projects?

Thanks in advance!

**Comment by wdifruscio** [comment]
I was able to find a setting in the FASTCGI Module to add environment variables 🗡

**Comment by Bodra123** [comment]
I solved the issue with same solution.
Thank You!

**Comment by xxMrPHDxx** [comment]
May I know what should I set that variable into?

**Comment by wdifruscio** [comment]
your project will need a wsgi handler from what I know! I am not sure how django handles it behind the scenes - I hope you figured this out
