### ISSUE TITLE
ptvs unexpected error on current weekly. No clue what caused it.

### ISSUE THREAD

**Issue by csharpen** [Microsoft/PTVS#531]
Complete text of the "program":
import requests
def main():
    r = requests.get('https://www.google.com', auth=('user', 'pass'))
    print('Hello World')

main()

=============================================================

[Window Title]
Python Tools for Visual Studio

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
System.UnauthorizedAccessException: Access to the path 'C:\Users\dev\AppData\Local\Python Tools\CompletionDB\12.0\8d5863a2-902d-3e5a-98ad-54de74830a8f\2.7\site-packages_appinst' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.AddSearchableDirsToStack(SearchData localSearchData)
   at System.IO.FileSystemEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at Microsoft.PythonTools.EnvironmentsList.DBPackageView.<FromModuleList>d__5.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.PythonTools.EnvironmentsList.DBEnvironmentView.<RefreshPackagesAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.EnvironmentsList.DBEnvironmentView.<Provider_ModulesChanged>d__12.MoveNext()

**Comment by zooba** [comment]
Thanks.

This looks like we aren't handling filesystem errors in `PythonInterpreterFactoryWithDatabase.GetUpToDateModules`. Unfortunately, one error on any subdirectory will abort the entire enumeration currently, so to do this properly we need to handle the recursion ourselves. Otherwise a directory that's been deleted but kept alive by an existing handle (as I suspect happened here) will continue to break the IntelliSense page in the environments window.

(We probably just want a generic helper method for enumerating files that doesn't abort when it can't recurse into a subdirectory.)

**Comment by zooba** [comment]
This has been fixed
