### ISSUE TITLE
Trying to add new environment in a python project

### ISSUE THREAD

**Issue by AdiTCG** [microsoft/PTVS#5348]
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 16.0.19074.1

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.PlatformUI.SetupPackagesCache.GetPackages(String& language, DateTime& installDate, DateTime& lastUpdatedDate, Uri& currentReleaseUri, String& currentProductDisplayVersion, String& currentProductDisplayName)
   at Microsoft.VisualStudio.PlatformUI.SetupPackagesCache.Refresh()
   at Microsoft.VisualStudio.PlatformUI.SetupPackagesCache.<>c.<.cctor>b__35_0()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at Microsoft.VisualStudio.PlatformUI.SetupCompositionService.GetSetupPackagesInfo(UInt32 numberofPackages, IVsSetupPackageInfo[] packageInfo, UInt32& pcActual)
   at Microsoft.PythonTools.Environments.AddInstalledEnvironmentView.GetPackages(IVsSetupCompositionService setupService)
   at Microsoft.PythonTools.Environments.AddInstalledEnvironmentView..ctor(IServiceProvider serviceProvider, ProjectView[] projects, ProjectView selectedProject)
   at Microsoft.PythonTools.Environments.AddEnvironmentDialog.<ShowDialogAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by huguesv** [comment]
Thanks for the report. I believe that the setup team may fixed this already (it may be in 16.1).

@RaymonGulati1  a user had filed a developer community for this which I had passed along to setup team. You should try to find it (look for that call stack) to see the status.

**Comment by RaymonGulati1** [comment]
Due to the low number of users encountering this issue, the setup team has determined that this is a low priority issue. There is no ETA for a fix.

**Comment by RaymonGulati1** [comment]
I'm investigating this issue. Will report back soon.

**Comment by RaymonGulati1** [comment]
Can you please provide steps to reproduce this issue?

**Comment by huguesv** [comment]
Same as https://github.com/microsoft/PTVS/issues/5235
