### ISSUE TITLE
ironpython environment

### ISSUE THREAD

**Issue by ImALolNoob** [microsoft/PTVS#5357]
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 16.1.19129.1

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.PlatformUI.SetupPackagesCache.GetPackages(String& language, DateTime& installDate, DateTime& lastUpdatedDate, Uri& currentReleaseUri, String& currentProductDisplayVersion, String& currentProductDisplayName)
   at Microsoft.VisualStudio.PlatformUI.SetupPackagesCache.Refresh()
   at Microsoft.VisualStudio.PlatformUI.SetupPackagesCache.<>c.<.cctor>b__35_0()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at Microsoft.VisualStudio.PlatformUI.SetupCompositionService.GetSetupPackagesInfo(UInt32 numberofPackages, IVsSetupPackageInfo[] packageInfo, UInt32& pcActual)
   at Microsoft.PythonTools.Environments.AddInstalledEnvironmentView.GetPackages(IVsSetupCompositionService setupService)
   at Microsoft.PythonTools.Environments.AddInstalledEnvironmentView..ctor(IServiceProvider serviceProvider, ProjectView[] projects, ProjectView selectedProject)
   at Microsoft.PythonTools.Environments.AddEnvironmentDialog.<ShowDialogAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Environments.AddEnvironmentDialog.<ShowAddVirtualEnvironmentDialogAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Environments.AddEnvironmentDialog.<ShowAddEnvironmentDialogAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by RaymonGulati1** [comment]
Thanks for the report. I'm investigating this issue and will report back soon.

**Comment by RaymonGulati1** [comment]
Can you please provide steps to reproduce this issue?

**Comment by RaymonGulati1** [comment]
Related to #5348 #5235 #5365

**Comment by huguesv** [comment]
Same as https://github.com/microsoft/PTVS/issues/5235
