### ISSUE TITLE
default Polls test_about

### ISSUE THREAD

**Issue by danielgarner64** [microsoft/PTVS#5382]
test_about in the default Polls project fails with 301 error.
```
Traceback (most recent call last):
  File "C:\Users\bob\source\repos\pollsShown\app\tests.py", line 34, in test_about
    self.assertContains(response, 'About', 3, 200)
  File "C:\Users\bob\source\repos\pollsShown\env\lib\site-packages\django\test\testcases.py", line 446, in assertContains
    response, text, status_code, msg_prefix, html)
  File "C:\Users\bob\source\repos\pollsShown\env\lib\site-packages\django\test\testcases.py", line 418, in _assert_contains
    " (expected %d)" % (response.status_code, status_code)
AssertionError: 301 != 200 : Couldn't retrieve content: Response code was 301 (expected 200)
```

Fix is to remove trailing slash from the about url in pollsShown/urls.py
to
```
path('about', views.about, name='about'),
```

**Comment by huguesv** [comment]
We've removed the samples project templates from the product.
