### ISSUE TITLE
Pytest: Unexpected errors and no test discovered after project is moved on disk

### ISSUE THREAD

**Issue by huguesv** [microsoft/PTVS#5425]
**Describe the bug**
When a project with an existing .pytest_cache folder is moved to a different location on disk and opened in VS, tests are not discovered and a `KeyNotFoundException` error appears in the Tests output window.

**Steps to Reproduce**
1. Open a project and enable pytest. Confirm tests are discovered.
2. Close the project
3. Move the solution/project folder to a different location on disk
4. Load the solution/project from the new location

**Expected behavior**
Tests are discovered successfully

**Additional context and screenshots**
```
[7/11/2019 2:25:07.188 PM Error] System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key)
   at Microsoft.VisualStudio.TestWindow.Host.VsTestRunSession.<>c__DisplayClass17_0.<AddTestCases>b__0(TestCase test)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at Microsoft.VisualStudio.TestWindow.Host.TestRunSession.AddTestCases(IEnumerable`1 testCases)
   at Microsoft.VisualStudio.TestWindow.Host.TestPlatformProvider.<>c__DisplayClass41_0.<HandleDiscoveredTests>b__0()
   at Microsoft.VisualStudio.TestWindow.Extensibility.ILoggerExtensions.CallInternalWithLogging(ILogger2 log, Action action, Boolean shouldThrow)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

Not sure if we can detect that the cache is out of date, or maybe tell pytest not to use the cache? That may have too big of a perf hit?

The symptom and error message don't make it very obvious as to what the problem is.

**Comment by bschnurr** [comment]
I'll double check if VsCode uses the --cache-clear argument..  We could set it up so that it clears the cache on solution/workspace load and when we do a refresh, but not use it when its an incremental change.

**Comment by bschnurr** [comment]
adding the cache-clear doesn't fix the issue.. but improves it.  manually deleting __pycache__ as well does seem to fix it

**Comment by bschnurr** [comment]
pycache is saying the test file exists in the previous folder..

when we source paths from the test adapter we assume they are relative to the current project root.  In this case it is not.  

it could be returning full path strings or multiple ..\\..\\

We could detect this can print an error message saying to clear _pycache

**Comment by bschnurr** [comment]
We now have messaging showing the old path location of where the pycache thinks the files live and also show a hyperlink for more info on discovery configuration, where we can mention manually clearing the cache.
![image](https://user-images.githubusercontent.com/1946977/62884732-0d1fc380-bcec-11e9-9f99-b0c6d7ad72cf.png)
