### ISSUE TITLE
UnauthorizedAccessException from interpreter list window

### ISSUE THREAD

**Issue by antal0** [microsoft/PTVS#5429]
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Bezárás]

[Expanded Information]
```
Build: 16.1.19129.1

System.UnauthorizedAccessException: Access to the path is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.FileStream.FlushWrite(Boolean calledFromFinalizer)
   at System.IO.FileStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents)
   at Microsoft.PythonTools.InterpreterList.InterpreterListToolWindow.SetIPythonEnabled(EnvironmentView view, Boolean enable)
```

**Comment by RaymonGulati1** [comment]
@antal0, thank for you the report. 

Can you please provide some more information? How do you reproduce this? Any screenshots?

**Comment by judej** [comment]
closing, no response.
