### ISSUE TITLE
Pytest: assert when add existing item as link

### ISSUE THREAD

**Issue by huguesv** [microsoft/PTVS#5433]
Enable pytest for the project
Add existing item, "as link", a test file from a folder outside the project folder

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------




   at Microsoft.PythonTools.TestAdapter.Pytest.PyTestDiscoveryReader.ParseDiscovery(IList`1 results, ITestCaseDiscoverySink discoverySink, PythonProjectSettings settings, IMessageLogger logger) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\TestAdapter.Executor\Pytest\PytestDiscoveryReader.cs:line 30

   at Microsoft.PythonTools.TestAdapter.ProjectTestDiscover.DiscoverTestGroup(IGrouping`2 testGroup, IMessageLogger logger, ITestCaseDiscoverySink discoverySink) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\TestAdapter.Executor\TestDiscoverer.cs:line 67

   at Microsoft.PythonTools.TestAdapter.ProjectTestDiscover.DiscoverTests(IEnumerable`1 sources, IDiscoveryContext discoveryContext, IMessageLogger logger, ITestCaseDiscoverySink discoverySink) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\TestAdapter.Executor\TestDiscoverer.cs:line 54

   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Discovery.DiscovererEnumerator.DiscoverTestsFromSingleDiscoverer(LazyExtension`2 discoverer, Dictionary`2 discovererToSourcesMap, DiscoveryContext context, TestCaseDiscoverySink discoverySink, IMessageLogger logger, Double& totalAdaptersUsed, Double& totalTimeTakenByAdapters)

   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Discovery.DiscovererEnumerator.LoadTestsFromAnExtension(String extensionAssembly, IEnumerable`1 sources, IRunSettings settings, String testCaseFilter, IMessageLogger logger)

   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Discovery.DiscovererEnumerator.LoadTests(IDictionary`2 testExtensionSourceMap, IRunSettings settings, String testCaseFilter, IMessageLogger logger)

   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Discovery.DiscoveryManager.DiscoverTests(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler)

   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TestRequestHandler.<>c__DisplayClass30_1.<OnMessageReceived>b__1()

   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TestRequestHandler.<>c.<.ctor>b__18_1(Action action)

   at Microsoft.VisualStudio.TestPlatform.Utilities.JobQueue`1.SafeProcessJob(T job)

   at Microsoft.VisualStudio.TestPlatform.Utilities.JobQueue`1.BackgroundJobProcessor()

   at Microsoft.VisualStudio.TestPlatform.Utilities.JobQueue`1.<.ctor>b__12_0()

   at System.Threading.Tasks.Task.InnerInvoke()

   at System.Threading.Tasks.Task.Execute()

   at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)

   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)

   at System.Threading.Tasks.ThreadPoolTaskScheduler.LongRunningThreadWork(Object obj)

   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Threading.ThreadHelper.ThreadStart(Object obj)


---------------------------
Abort   Retry   Ignore   
---------------------------

```

**Comment by bschnurr** [comment]
currently the VsCode pytest Adapter doesn't handle the case of files outside the project folder, but I think we can handle this error better.

**Comment by huguesv** [comment]
Assert has been fixed. We now get warning and the file is skipped. Filed https://github.com/microsoft/PTVS/issues/5622 for that.
