### ISSUE TITLE
Pytest: Test is removed from Test explorer after file rename

### ISSUE THREAD

**Issue by huguesv** [microsoft/PTVS#5434]
Enable pytest for the project
Make sure to have at least 2 files with tests in them and that they appear in test explorer
Rename one of the test files

Result: The tests from the renamed file are removed from test explorer. You have to trigger discovery (make an edit and save the renamed file) to get them to show up in test explorer.

```
[7/15/2019 10:41:35.563 AM Informational] Store opened in 0.071 sec.
[7/15/2019 10:41:36.737 AM Informational] ---------- Discovery started ----------
[7/15/2019 10:41:37.504 AM Informational] cd C:\Projects\GitHub\temp\TestExplorerPytest\
[7/15/2019 10:41:37.505 AM Informational] set PYTHONPATH=C:\Projects\GitHub\temp\TestExplorerPytest\;c:\projects\github\temp\testexplorerpytest
[7/15/2019 10:41:37.505 AM Informational] "C:\Program Files\Python37\python.exe" "C:\USERS\HUVALO\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_D1270DCBEXP\EXTENSIONS\MICROSOFT CORPORATION\PYTHON\16.0.0\PythonFiles\testing_tools\run_adapter.py" discover pytest -- c:\projects\github\temp\testexplorerpytest\test_pt.py c:\projects\github\temp\testexplorerpytest\test_usermark.py
[7/15/2019 10:41:37.879 AM Informational] Discovered the following tests:
[7/15/2019 10:41:37.882 AM Informational] test_pt_pass Source:c:\projects\github\temp\testexplorerpytest\test_pt.py Line:1
[7/15/2019 10:41:37.889 AM Informational] test_pt_fail Source:c:\projects\github\temp\testexplorerpytest\test_pt.py Line:4
[7/15/2019 10:41:37.890 AM Informational] test_method_pass Source:c:\projects\github\temp\testexplorerpytest\test_pt.py Line:8
[7/15/2019 10:41:37.890 AM Informational] test_webtest Source:c:\projects\github\temp\testexplorerpytest\test_usermark.py Line:5
[7/15/2019 10:41:37.891 AM Informational] test_skip Source:c:\projects\github\temp\testexplorerpytest\test_usermark.py Line:9
[7/15/2019 10:41:37.891 AM Informational] test_skipif_skipped Source:c:\projects\github\temp\testexplorerpytest\test_usermark.py Line:13
[7/15/2019 10:41:37.892 AM Informational] test_skipif_not_skipped Source:c:\projects\github\temp\testexplorerpytest\test_usermark.py Line:17
[7/15/2019 10:41:37.954 AM Informational] ========== Discovery finished: 7 tests found (0:00:01.2142244) ==========
[7/15/2019 10:41:46.876 AM Informational] ---------- Discovery started ----------
[7/15/2019 10:41:46.965 AM Informational] ---------- Discovery started ----------
[7/15/2019 10:41:47.675 AM Informational] cd C:\Projects\GitHub\temp\TestExplorerPytest\
[7/15/2019 10:41:47.676 AM Informational] set PYTHONPATH=C:\Projects\GitHub\temp\TestExplorerPytest\;c:\projects\github\temp\testexplorerpytest
[7/15/2019 10:41:47.676 AM Informational] "C:\Program Files\Python37\python.exe" "C:\USERS\HUVALO\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_D1270DCBEXP\EXTENSIONS\MICROSOFT CORPORATION\PYTHON\16.0.0\PythonFiles\testing_tools\run_adapter.py" discover pytest -- c:\projects\github\temp\testexplorerpytest\test_pt.py c:\projects\github\temp\testexplorerpytest\test_usermar.py
[7/15/2019 10:41:47.709 AM Informational] cd C:\Projects\GitHub\temp\TestExplorerPytest\
[7/15/2019 10:41:47.709 AM Informational] set PYTHONPATH=C:\Projects\GitHub\temp\TestExplorerPytest\;c:\projects\github\temp\testexplorerpytest
[7/15/2019 10:41:47.709 AM Informational] "C:\Program Files\Python37\python.exe" "C:\USERS\HUVALO\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_D1270DCBEXP\EXTENSIONS\MICROSOFT CORPORATION\PYTHON\16.0.0\PythonFiles\testing_tools\run_adapter.py" discover pytest -- c:\projects\github\temp\testexplorerpytest\test_pt.py
[7/15/2019 10:41:48.069 AM Informational] Discovered the following tests:
[7/15/2019 10:41:48.072 AM Informational] test_pt_pass Source:c:\projects\github\temp\testexplorerpytest\test_pt.py Line:1
[7/15/2019 10:41:48.079 AM Informational] test_pt_fail Source:c:\projects\github\temp\testexplorerpytest\test_pt.py Line:4
[7/15/2019 10:41:48.080 AM Informational] test_method_pass Source:c:\projects\github\temp\testexplorerpytest\test_pt.py Line:8
[7/15/2019 10:41:48.080 AM Informational] test_webtest Source:c:\projects\github\temp\testexplorerpytest\test_usermar.py Line:5
[7/15/2019 10:41:48.081 AM Informational] test_skip Source:c:\projects\github\temp\testexplorerpytest\test_usermar.py Line:9
[7/15/2019 10:41:48.081 AM Informational] test_skipif_skipped Source:c:\projects\github\temp\testexplorerpytest\test_usermar.py Line:13
[7/15/2019 10:41:48.082 AM Informational] test_skipif_not_skipped Source:c:\projects\github\temp\testexplorerpytest\test_usermar.py Line:17
[7/15/2019 10:41:48.122 AM Informational] Discovered the following tests:
[7/15/2019 10:41:48.126 AM Informational] test_pt_pass Source:c:\projects\github\temp\testexplorerpytest\test_pt.py Line:1
[7/15/2019 10:41:48.137 AM Informational] test_pt_fail Source:c:\projects\github\temp\testexplorerpytest\test_pt.py Line:4
[7/15/2019 10:41:48.137 AM Informational] test_method_pass Source:c:\projects\github\temp\testexplorerpytest\test_pt.py Line:8
[7/15/2019 10:41:48.139 AM Error] System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key)
   at Microsoft.VisualStudio.TestWindow.Host.VsTestRunSession.<>c__DisplayClass17_0.<AddTestCases>b__0(TestCase test)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at Microsoft.VisualStudio.TestWindow.Host.TestRunSession.AddTestCases(IEnumerable`1 testCases)
   at Microsoft.VisualStudio.TestWindow.Host.TestPlatformProvider.<>c__DisplayClass40_0.<HandleDiscoveryComplete>b__0()
   at Microsoft.VisualStudio.TestWindow.Extensibility.ILoggerExtensions.CallInternalWithLogging(ILogger2 log, Action action, Boolean shouldThrow)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
[7/15/2019 10:41:48.142 AM Informational] ========== Discovery finished: 7 tests found (0:00:01.1744797) ==========
[7/15/2019 10:41:48.144 AM Error] System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Microsoft.VisualStudio.TestWindow.Controller.OperationData.Microsoft.VisualStudio.TestWindow.Controller.IOperationData.OperationSetFinished(Operation operation)
   at Microsoft.VisualStudio.TestWindow.Controller.Operation.<Execute>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Extensibility.ILoggerExtensions.<CallWithCatchAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
[7/15/2019 10:41:48.187 AM Informational] ========== Discovery finished: 10 tests found (0:00:01.3063473) ==========

```

**Comment by huguesv** [comment]
Can't repro this anymore.
