### ISSUE TITLE
E_INVALIDARG opening repl window

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#544]
In our VWD tests, the first exception below occurred. All later attempts to open an interactive window then failed with the second exception.

```
Test method PythonToolsUITests.BuildTasksUI25Tests.CustomCommandsReplWithResourceLabel threw exception: 
System.ArgumentException: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
    at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.ErrorHandler.ThrowOnFailure(Int32 hr, Int32[] expectedHRFailure)
   at Microsoft.VisualStudio.InteractiveWindow.Shell.VsInteractiveWindow.OnToolWindowCreated()
   at Microsoft.VisualStudio.InteractiveWindow.Shell.VsInteractiveWindow..ctor(IComponentModel model, Guid providerId, Int32 instanceId, String title, IInteractiveEvaluator evaluator, __VSCREATETOOLWIN creationFlags)
   at Microsoft.VisualStudio.InteractiveWindow.Shell.VsInteractiveWindowFactory.Create(Guid providerId, Int32 instanceId, String title, IInteractiveEvaluator evaluator, __VSCREATETOOLWIN creationFlags)
   at Microsoft.PythonTools.Repl.InteractiveWindowProvider.CreateReplWindowInternal(IInteractiveEvaluator evaluator, IContentType contentType, String[] roles, Int32 id, String title, Guid languageServiceGuid, String replId)
   at Microsoft.PythonTools.Repl.InteractiveWindowProvider.CreateReplWindow(IContentType contentType, String title, Guid languageServiceGuid, String replId)
   at Microsoft.PythonTools.Project.CustomCommand.<RunInRepl>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.PythonTools.Project.CustomCommand.<ExecuteWorker>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudioTools.UIThread.<InvokeTaskHelper>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PythonToolsUITests.BuildTasksUI27Tests.Execute(PythonProjectNode projectNode, String commandName) in C:\Source\Python\Tests\Core.UI\BuildTasksUITests.cs:line 54
   at PythonToolsUITests.BuildTasksUI27Tests.CustomCommandsReplWithResourceLabel() in C:\Source\Python\Tests\Core.UI\BuildTasksUITests.cs:line 143
```

```
System.InvalidOperationException: The DocumentSite on a WindowFrame may only be set once
    at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.set_DocumentSite(DocumentObjectSite value)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowManagerService.CreateContentPane(FrameMoniker frameMoniker, Boolean isDocument, String lpstrMkDoc, UInt32 eCreateWindowFlags, Object punkView, Object punkData, IServiceProvider pServiceProvider, IVsUIHierarchy pUIHierarchy, UInt32 vsid, Guid rguidCmdUI, ViewGroup parent, IVsWindowFrame& ppWindowFrame)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowManagerService.CreateContentPane(String pszName, Int32 fDockViewOn, Int32 fDocument, String lpstrMkDoc, UInt32 eCreateWindowFlags, UInt32 dwToolWinId, Object punkView, Object punkData, IServiceProvider pServiceProvider, IVsUIHierarchy pUIHierarchy, UInt32 vsid, Int32& pfDefaultPosition, Guid& rguidCmdUI, IVsWindowFrame& ppWindowFrame)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.ErrorHandler.ThrowOnFailure(Int32 hr, Int32[] expectedHRFailure)
   at Microsoft.VisualStudio.InteractiveWindow.Shell.VsInteractiveWindow..ctor(IComponentModel model, Guid providerId, Int32 instanceId, String title, IInteractiveEvaluator evaluator, __VSCREATETOOLWIN creationFlags)
   at Microsoft.VisualStudio.InteractiveWindow.Shell.VsInteractiveWindowFactory.Create(Guid providerId, Int32 instanceId, String title, IInteractiveEvaluator evaluator, __VSCREATETOOLWIN creationFlags)
   at Microsoft.PythonTools.Repl.InteractiveWindowProvider.CreateReplWindowInternal(IInteractiveEvaluator evaluator, IContentType contentType, String[] roles, Int32 id, String title, Guid languageServiceGuid, String replId)
   at Microsoft.PythonTools.Repl.InteractiveWindowProvider.CreateReplWindow(IContentType contentType, String title, Guid languageServiceGuid, String replId)
```

**Comment by zooba** [comment]
Due to https://github.com/dotnet/roslyn/issues/3839
