### ISSUE TITLE
Pytest discovery not working when python file named same as project exists

### ISSUE THREAD

**Issue by huguesv** [microsoft/PTVS#5461]
1. Create new python project
2. Make sure current environment has pytest installed
3. Add new item, unit test, "test_hello1.py"
4. In project properties, change test framework to pytest

Result: 

```
=================================== ERRORS ====================================
___________________ ERROR collecting pythonapplication62.py ___________________
ImportError while importing test module 'c:\users\huvalo\source\repos\pythonapplication62\pythonapplication62.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
ModuleNotFoundError: No module named 'pythonapplication62'
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!
=========================== 1 error in 0.10 seconds ===========================
Traceback (most recent call last):
  File "C:\USERS\HUVALO\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_D1270DCBEXP\EXTENSIONS\MICROSOFT CORPORATION\PYTHON\16.0.0\PythonFiles\testing_tools\run_adapter.py", line 16, in <module>
    main(tool, cmd, subargs, toolargs)
  File "C:\USERS\HUVALO\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_D1270DCBEXP\EXTENSIONS\MICROSOFT CORPORATION\PYTHON\16.0.0\PythonFiles\testing_tools\adapter\__main__.py", line 98, in main
    parents, result = run(toolargs, **subargs)
  File "C:\USERS\HUVALO\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_D1270DCBEXP\EXTENSIONS\MICROSOFT CORPORATION\PYTHON\16.0.0\PythonFiles\testing_tools\adapter\pytest\_discovery.py", line 34, in discover
    raise Exception('pytest discovery failed (exit code {})'.format(ec))
Exception: pytest discovery failed (exit code 2)
```

Deleting the file from the project (PythonApplicationX.py) works around the issue.

Even when the file is present, pytest from command line works correctly:
```
C:\Users\huvalo\source\repos\PythonApplication62>pytest
================================================= test session starts =================================================
platform win32 -- Python 3.7.3, pytest-5.0.1, py-1.8.0, pluggy-0.12.0
rootdir: C:\Users\huvalo\source\repos\PythonApplication62
collected 1 item

test_hello1.py F                                                                                                 [100%]

====================================================== FAILURES =======================================================
_______________________________________________ Test_test_hello1.test_A _______________________________________________

self = <test_hello1.Test_test_hello1 testMethod=test_A>

    def test_A(self):
>       self.fail("Not implemented")
E       AssertionError: Not implemented

test_hello1.py:5: AssertionError
============================================== 1 failed in 0.04 seconds ===============================================
```

**Comment by bschnurr** [comment]
fix with change https://github.com/microsoft/PTVS/commit/132d1373adddb64447db3e8c79875942d3d31750
