### ISSUE TITLE
Pytest execution failure - tests in subpackages

### ISSUE THREAD

**Issue by huguesv** [microsoft/PTVS#5525]
![image](https://user-images.githubusercontent.com/1696845/62336913-47d16280-b487-11e9-9b0f-5f4a7650da29.png)

Output:
```
[8/1/2019 6:06:04.914 PM Informational] Store opened in 0.004 sec.
[8/1/2019 6:06:08.829 PM Informational] ---------- Discovery started ----------
[8/1/2019 6:06:10.566 PM Informational] Starting pytest discovery for the PythonApplication84 project. This can take up to 60 seconds.
[8/1/2019 6:06:10.581 PM Informational] cd C:\Users\huvalo\source\repos\PythonApplication84\
[8/1/2019 6:06:10.605 PM Informational] set PYTHONPATH=C:\Users\huvalo\source\repos\PythonApplication84\
[8/1/2019 6:06:10.637 PM Informational] C:\Program Files\Python36\python.exe C:\USERS\HUVALO\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_D1270DCBEXP\EXTENSIONS\MICROSOFT CORPORATION\PYTHON\16.0.0\PythonFiles\testing_tools\run_adapter.py discover pytest -- --cache-clear c:\users\huvalo\source\repos\pythonapplication84\package1\packagea\test1.py c:\users\huvalo\source\repos\pythonapplication84\package1\packagea\test2.py c:\users\huvalo\source\repos\pythonapplication84\package1\packagea\__init__.py c:\users\huvalo\source\repos\pythonapplication84\package1\__init__.py
[8/1/2019 6:06:11.661 PM Error] Failed to parse: Unexpected character encountered while parsing value: =. Path '', line 0, position 0.
[8/1/2019 6:06:11.696 PM Error] ============================= test session starts =============================
platform win32 -- Python 3.6.8, pytest-5.0.1, py-1.8.0, pluggy-0.12.0
rootdir: C:\Users\huvalo\source\repos\PythonApplication84
collected 0 items / 3 errors
=================================== ERRORS ====================================
_________________ ERROR collecting package1/packagea/test1.py _________________
ImportError while importing test module 'c:\users\huvalo\source\repos\pythonapplication84\package1\packagea\test1.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
ModuleNotFoundError: No module named 'package1.packagea'
_________________ ERROR collecting package1/packagea/test2.py _________________
ImportError while importing test module 'c:\users\huvalo\source\repos\pythonapplication84\package1\packagea\test2.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
ModuleNotFoundError: No module named 'package1.packagea'
_________________ ERROR collecting package1/packagea/test1.py _________________
ImportError while importing test module 'c:\users\huvalo\source\repos\pythonapplication84\package1\packagea\test1.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
ModuleNotFoundError: No module named 'package1.packagea'
!!!!!!!!!!!!!!!!!!! Interrupted: 3 errors during collection !!!!!!!!!!!!!!!!!!!
=========================== 3 error in 0.20 seconds ===========================
Traceback (most recent call last):
  File "C:\USERS\HUVALO\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_D1270DCBEXP\EXTENSIONS\MICROSOFT CORPORATION\PYTHON\16.0.0\PythonFiles\testing_tools\run_adapter.py", line 16, in <module>
    main(tool, cmd, subargs, toolargs)
  File "C:\USERS\HUVALO\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_D1270DCBEXP\EXTENSIONS\MICROSOFT CORPORATION\PYTHON\16.0.0\PythonFiles\testing_tools\adapter\__main__.py", line 122, in main
    parents, result = run(toolargs, **subargs)
  File "C:\USERS\HUVALO\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_D1270DCBEXP\EXTENSIONS\MICROSOFT CORPORATION\PYTHON\16.0.0\PythonFiles\testing_tools\adapter\__main__.py", line 35, in pytest_discover
    return pytest.discover(pytestargs, _ignored)
  File "C:\USERS\HUVALO\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_D1270DCBEXP\EXTENSIONS\MICROSOFT CORPORATION\PYTHON\16.0.0\PythonFiles\testing_tools\adapter\pytest\_discovery.py", line 34, in discover
    raise Exception('pytest discovery failed (exit code {})'.format(ec))
Exception: pytest discovery failed (exit code 2)

[8/1/2019 6:06:11.725 PM Warning] No test is available in c:\users\huvalo\source\repos\pythonapplication84\package1\packagea\test1.py c:\users\huvalo\source\repos\pythonapplication84\package1\packagea\test2.py c:\users\huvalo\source\repos\pythonapplication84\package1\packagea\__init__.py c:\users\huvalo\source\repos\pythonapplication84\package1\__init__.py. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
[8/1/2019 6:06:11.740 PM Informational] ========== Discovery finished: 0 tests found (0:00:02.8603913) ==========

```

From command line pytest:
```
C:\Users\huvalo\source\repos\PythonApplication84>pytest package1\packageA\test1.py package1\packageA\test2.py
================================================= test session starts =================================================
platform win32 -- Python 3.6.8, pytest-5.0.1, py-1.8.0, pluggy-0.12.0
rootdir: C:\Users\huvalo\source\repos\PythonApplication84
collected 3 items

package1\packageA\test1.py .                                                                                     [ 33%]
package1\packageA\test2.py F.                                                                                    [100%]

====================================================== FAILURES =======================================================
__________________________________________________ Test_test2.test_A __________________________________________________

self = <package1.packageA.test2.Test_test2 testMethod=test_A>

    def test_A(self):
>       self.fail("todo implement this test")
E       AssertionError: todo implement this test

package1\packageA\test2.py:5: AssertionError
========================================= 1 failed, 2 passed in 0.09 seconds ==========================================

```

**Comment by huguesv** [comment]
Slightly different error using today's latest:
![image](https://user-images.githubusercontent.com/1696845/62905846-1aa37080-bd21-11e9-915c-87fdb80db61d.png)

```
[8/12/2019 4:47:16.498 PM Informational] ---------- Discovery started ----------
[8/12/2019 4:47:17.689 PM Informational] Starting pytest discovery for the PythonApplication8 project. This can take up to 60 seconds.
[8/12/2019 4:47:17.692 PM Informational] cd C:\Users\huvalo\Source\Repos\PythonApplication8\
[8/12/2019 4:47:17.692 PM Informational] set PYTHONPATH=C:\Users\huvalo\Source\Repos\PythonApplication8\
[8/12/2019 4:47:17.694 PM Informational] C:\Program Files\Python37\python.exe C:\USERS\HUVALO\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_B2FDD7DEEXP\EXTENSIONS\MICROSOFT CORPORATION\PYTHON\16.0.0\PythonFiles\testing_tools\run_adapter.py discover pytest --output-file C:\Users\huvalo\AppData\Local\Temp\tmpE92E.tmp -- C:\Users\huvalo\Source\Repos\PythonApplication8\package1\test_1.py C:\Users\huvalo\Source\Repos\PythonApplication8\package1\test_2.py C:\Users\huvalo\Source\Repos\PythonApplication8\package1\__init__.py C:\Users\huvalo\Source\Repos\PythonApplication8\PythonApplication8.py --cache-clear
[8/12/2019 4:47:18.437 PM Informational] ========== Discovery finished: 3 tests found (0:00:01.9361445) ==========
[8/12/2019 4:47:18.452 PM Informational] ---------- Run started ----------
[8/12/2019 4:47:19.726 PM Informational] cd C:\Users\huvalo\Source\Repos\PythonApplication8\
[8/12/2019 4:47:19.730 PM Informational] set PYTHONPATH=C:\Users\huvalo\Source\Repos\PythonApplication8\
[8/12/2019 4:47:19.749 PM Informational] "C:\Program Files\Python37\python.exe" "C:\USERS\HUVALO\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_B2FDD7DEEXP\EXTENSIONS\MICROSOFT CORPORATION\PYTHON\16.0.0\testlauncher.py" C:\Users\huvalo\Source\Repos\PythonApplication8\ pytest "" 0 "C:\USERS\HUVALO\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_B2FDD7DEEXP\EXTENSIONS\MICROSOFT CORPORATION\PYTHON\16.0.0\Packages" dummyfilename package1\test_2.py::test_second package1\test_1.py::Test_test1::test_A --junitxml=C:\Users\huvalo\Source\Repos\PythonApplication8\TestResults\junitresults_34879adf-2755-41db-89d8-a0a0ace2d158.xml
[8/12/2019 4:47:20.207 PM Informational] ============================= test session starts =============================
[8/12/2019 4:47:20.207 PM Informational] platform win32 -- Python 3.7.3, pytest-5.0.1, py-1.8.0, pluggy-0.12.0
[8/12/2019 4:47:20.209 PM Informational] rootdir: C:\Users\huvalo\Source\Repos\PythonApplication8
[8/12/2019 4:47:20.218 PM Informational] collected 2 items
[8/12/2019 4:47:20.224 PM Informational] package1\test_2.py .                                                     [ 50%]
[8/12/2019 4:47:20.241 PM Informational] package1\test_1.py .                                                     [100%]
[8/12/2019 4:47:20.241 PM Informational] - generated xml file: C:\Users\huvalo\Source\Repos\PythonApplication8\TestResults\junitresults_34879adf-2755-41db-89d8-a0a0ace2d158.xml -
[8/12/2019 4:47:20.242 PM Informational] ========================== 2 passed in 0.04 seconds ===========================
[8/12/2019 4:47:20.276 PM Error] Testcase not found for test result: <testcase classname="package1.test_2" file="package1\test_2.py" line="0" name="test_second" time="0.003">
  <system-out>second test
</system-out>
</testcase>
[8/12/2019 4:47:20.277 PM Error] Testcase not found for test result: <testcase classname="package1.test_1.Test_test1" file="package1\test_1.py" line="3" name="test_A" time="0.001">
  <system-out>Not implemented
</system-out>
</testcase>
[8/12/2019 4:47:20.435 PM Informational] ========== Run finished: 2 tests run (0:00:01.9114691) ==========
```
