### ISSUE TITLE
An unexcepted error occurred after installing pytest.

### ISSUE THREAD

**Issue by zhouwangyang** [microsoft/PTVS#5557]
**Steps to Reproduce**
1.Create python application
2.Right click in Project and select Properties->Test, change Test Framework to Pytest, and save it
3.Unload and reload this project
4.Install pytest when prompt to install it in info bar

**Expected behavior**
Pytest should be installed successfully without any errors

**Actual behavior**
Pytest can be installed successfully, but after that vs is deadlocked and an unexcepted error occurred.
![image](https://user-images.githubusercontent.com/39871640/62683285-a1d6a880-b9f0-11e9-82ac-6df56570abbe.png)

Test Environment:
![image](https://user-images.githubusercontent.com/39871640/62683555-553f9d00-b9f1-11e9-9987-46d6642db322.png)

**Comment by bschnurr** [comment]
![image](https://user-images.githubusercontent.com/1946977/62725357-d4b97600-b9c9-11e9-8f35-8a6cdf13b84a.png)

**Comment by bschnurr** [comment]
![image](https://user-images.githubusercontent.com/1946977/62725416-f4e93500-b9c9-11e9-984c-2e1d85ed5247.png)

**Comment by bschnurr** [comment]
![image](https://user-images.githubusercontent.com/1946977/62725462-07636e80-b9ca-11e9-9dbf-7e8375f8a2b3.png)

**Comment by zhouwangyang** [comment]
I have added some error info about this issue @huguesv 
**Error info:**
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[V] Show details  [Close]

[Expanded Information]
```
Build: 16.3.19214.1

System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Item in the VirtualizingTreeView cannot be null
   at Microsoft.Internal.VisualStudio.PlatformUI.VirtualizingTreeView.GetTreeNodesCore(Object item)
   at Microsoft.Internal.VisualStudio.PlatformUI.VirtualizingTreeView.GetFirstTreeNode(Object item)
   at Microsoft.VisualStudio.PlatformUI.SolutionNavigatorPane.OnItemAdded(Object sender, HierarchyItemEventArgs eventArgs)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Microsoft.VisualStudio.PlatformUI.ExtensionMethods.RaiseEvent[TEventArgs](EventHandler`1 eventHandler, Object source, TEventArgs args)
   at Microsoft.VisualStudio.PlatformUI.HierarchyEventSink.OnItemAdded(UInt32 itemidParent, UInt32 itemidSiblingPrev, UInt32 itemidAdded, Boolean ensureVisible)
   at Microsoft.VisualStudio.PlatformUI.HierarchyEventSink.OnItemAdded(UInt32 itemidParent, UInt32 itemidSiblingPrev, UInt32 itemidAdded)
   at Microsoft.VisualStudio.PlatformUI.HierarchyEventSink.<>c__DisplayClass32_0.<Microsoft.VisualStudio.Shell.Interop.IVsHierarchyEvents.OnItemAdded>b__0()
   at Microsoft.VisualStudio.Shell.ThreadHelper.Invoke[TResult](Func`1 method)
   at Microsoft.VisualStudio.PlatformUI.HierarchyEventSink.Microsoft.VisualStudio.Shell.Interop.IVsHierarchyEvents.OnItemAdded(UInt32 itemidParent, UInt32 itemidSiblingPrev, UInt32 itemidAdded)
   at Microsoft.VisualStudioTools.Project.ProjectNode.OnItemAdded(HierarchyNode parent, HierarchyNode child, HierarchyNode previousVisible)
   at Microsoft.VisualStudioTools.Project.HierarchyNode.AddChild(HierarchyNode node)
   at Microsoft.PythonTools.Project.InterpretersNode.<>c__DisplayClass25_0.<RefreshPackagesAsync>b__0()
   at Microsoft.VisualStudioTools.UIThread.<>c__DisplayClass12_0.<<InvokeAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Project.InterpretersNode.<RefreshPackagesAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   --- End of inner exception stack trace ---
   at System.AggregateException.Handle(Func`2 predicate)
   at Microsoft.PythonTools.Infrastructure.TaskExtensions.<>c__9`1.<SilenceException>b__9_0(Task t)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
---> (Inner Exception #0) System.InvalidOperationException: Item in the VirtualizingTreeView cannot be null
   at Microsoft.Internal.VisualStudio.PlatformUI.VirtualizingTreeView.GetTreeNodesCore(Object item)
   at Microsoft.Internal.VisualStudio.PlatformUI.VirtualizingTreeView.GetFirstTreeNode(Object item)
   at Microsoft.VisualStudio.PlatformUI.SolutionNavigatorPane.OnItemAdded(Object sender, HierarchyItemEventArgs eventArgs)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Microsoft.VisualStudio.PlatformUI.ExtensionMethods.RaiseEvent[TEventArgs](EventHandler`1 eventHandler, Object source, TEventArgs args)
   at Microsoft.VisualStudio.PlatformUI.HierarchyEventSink.OnItemAdded(UInt32 itemidParent, UInt

**Comment by RaymonGulati1** [comment]
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/966028

**Comment by huguesv** [comment]
Shell team has fixed their bug, and we fixed ours.
