### ISSUE TITLE
CreatePkgDef fails loading Microsoft.VisualStudio.Threading

### ISSUE THREAD

**Issue by huguesv** [microsoft/PTVS#5596]
That assembly seems to have moved to a subfolder:
`PublicAssemblies\Microsoft.VisualStudio.Threading.16.0`

There's are redirect with a codebase in devenv.exe.config:
```
        <dependentAssembly>
          <assemblyIdentity name="Microsoft.VisualStudio.Threading" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
          <bindingRedirect oldVersion="12.0.0.0-16.3.0.0" newVersion="16.3.0.0"/>
          <codeBase version="16.3.0.0" href="PublicAssemblies\Microsoft.VisualStudio.Threading.16.0\Microsoft.VisualStudio.Threading.dll"/>
        </dependentAssembly>

```

Might need to have the codebase in the CreatePkgDef.exe.config as well, because it doesn't have it right now:
```
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.VisualStudio.Threading" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-16.3.0.0" newVersion="16.3.0.0" />
      </dependentAssembly>

```

Edit: adding it there doesn't solve it though, because it is invoked via msbuild task, so probably doesn't launch the createpkgdef.exe

```
29>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Microsoft\VisualStudio\v16.0\VSSDK\Microsoft.VsSDK.targets(1149,5): error : CreatePkgDef : error : ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
29>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Microsoft\VisualStudio\v16.0\VSSDK\Microsoft.VsSDK.targets(1149,5): error :    at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
29>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Microsoft\VisualStudio\v16.0\VSSDK\Microsoft.VsSDK.targets(1149,5): error :    at System.Reflection.RuntimeModule.GetTypes()
29>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Microsoft\VisualStudio\v16.0\VSSDK\Microsoft.VsSDK.targets(1149,5): error :    at System.Reflection.Assembly.GetTypes()
29>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Microsoft\VisualStudio\v16.0\VSSDK\Microsoft.VsSDK.targets(1149,5): error :    at Microsoft.VisualStudio.Tools.CreatePkgDef.ProcessAssembly(String fileName, Hive hive, PkgDefContext context, Boolean register, RegistrationMode mode)
29>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Microsoft\VisualStudio\v16.0\VSSDK\Microsoft.VsSDK.targets(1149,5): error :    at Microsoft.VisualStudio.Tools.CreatePkgDef.DoCreatePkgDef(InputArguments inputArguments)
29>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Microsoft\VisualStudio\v16.0\VSSDK\Microsoft.VsSDK.targets(1149,5): error :    at Microsoft.VisualStudio.Tools.CreatePkgDef.Main(String[] arguments)
29>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Microsoft\VisualStudio\v16.0\VSSDK\Microsoft.VsSDK.targets(1149,5): error : Could not load file or assembly 'Microsoft.VisualStudio.Threading, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
29>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Microsoft\VisualStudio\v16.0\VSSDK\Microsoft.VsSDK.targets(1149,5): error : Could not load file or assembly 'Microsoft.VisualStudio.Threading, Version=16.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
29>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Microsoft\VisualStudio\v16.0\VSSDK\Microsoft.VsSDK.targets(1149,5): error : 
29>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Microsoft\VisualStudio\v16.0\VSSDK\Microsoft.VsSDK.targets(1149,5): error : 

```

**Comment by huguesv** [comment]
changing createpkgdef.exe.config from:
```
<bindingRedirect oldVersion="0.0.0.0-16.3.0.0" newVersion="16.3.0.0" />
```
back to what it was in 16.2:
```
<bindingRedirect oldVersion="0.0.0.0-16.0.0.0" newVersion="16.0.0.0" />
```

and now I can build successfully

**Comment by huguesv** [comment]
Filed internal bug 967716
