### ISSUE TITLE
devenv.exe

### ISSUE THREAD

**Issue by Sraza11** [microsoft/PTVS#5725]
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 16.2.19178.1

System.NotSupportedException: version 98 is no longer in memory
   at Microsoft.PythonTools.Intellisense.LocationTracker.GetLineLocations(Int32 version)
   at Microsoft.PythonTools.Intellisense.LocationTracker.Translate(SourceLocation loc, Int32 fromVersion, Int32 toVersion)
   at Microsoft.PythonTools.Intellisense.LocationTracker.Translate(SourceSpan span, Int32 fromVersion, Int32 toVersion)
   at Microsoft.PythonTools.Intellisense.TaskProviderItem.CreateSquiggleSpan(SimpleTagger`1 tagger)
   at Microsoft.PythonTools.Intellisense.TaskProvider.<RefreshAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.PythonTools.Intellisense.TaskProvider.Refresh()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by huguesv** [comment]
Thanks. I suspect this will be difficult to reproduce.
We're currently working on completely replacing the IntelliSense implementation as part of https://github.com/microsoft/PTVS/issues/5210, which should take care of this, as well as many other IntelliSense improvements.

**Comment by vformanyuk** [comment]
Got this exception today, but with different stack trace.
Issue happened when I copied existing python file in solution explorer, rename it and start editing source.

[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 16.4.19310.1

System.NotSupportedException: version 0 is no longer in memory
   at Microsoft.PythonTools.Intellisense.LocationTracker.GetLineLocations(Int32 version)
   at Microsoft.PythonTools.Intellisense.BufferParser.GetChanges(PythonTextBufferInfo buffer, ITextVersion curVersion)
   at Microsoft.PythonTools.Intellisense.BufferParser.<GetUpdatesForSnapshot>d__45.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.PythonTools.Intellisense.BufferParser.<ParseBuffersAsync>d__46.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```
