### ISSUE TITLE
Unhandled exception in WorkspaceInterpreterFactoryProvider

### ISSUE THREAD

**Issue by zooba** [microsoft/PTVS#5809]
I opened a folder that contained a couple of Python 3.8.0rc1 "installs" (not real venvs or installs, just extracted Nuget packages) and kept getting the crash below.

I _believe_ this means that 3.8 is not a valid version in my install of PTVS (which was a fairly recent preview, but not the latest - upgrading now), but the exception shouldn't be allowed to tear down VS completely in the case where my build has a totally different version number.

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at Microsoft.PythonTools.Parsing.PythonLanguageVersionExtensions.ToLanguageVersion(System.Version)
   at Microsoft.PythonTools.Interpreter.Ast.AstPythonInterpreterFactory..ctor(Microsoft.PythonTools.Interpreter.InterpreterConfiguration, Microsoft.PythonTools.Interpreter.InterpreterFactoryCreationOptions, Boolean)

Exception Info: System.ArgumentException
   at Microsoft.PythonTools.Interpreter.Ast.AstPythonInterpreterFactory..ctor(Microsoft.PythonTools.Interpreter.InterpreterConfiguration, Microsoft.PythonTools.Interpreter.InterpreterFactoryCreationOptions, Boolean)
   at Microsoft.PythonTools.Interpreter.InterpreterFactoryCreator.CreateInterpreterFactory(Microsoft.PythonTools.Interpreter.InterpreterConfiguration, Microsoft.PythonTools.Interpreter.InterpreterFactoryCreationOptions)
   at Microsoft.PythonTools.Interpreter.WorkspaceInterpreterFactoryProvider.CreateFactory(Microsoft.PythonTools.Interpreter.PythonInterpreterInformation)
   at Microsoft.PythonTools.Interpreter.PythonInterpreterInformation.GetOrCreateFactory(System.Func`2<Microsoft.PythonTools.Interpreter.PythonInterpreterInformation,Microsoft.PythonTools.Interpreter.IPythonInterpreterFactory>)
   at Microsoft.PythonTools.Interpreter.WorkspaceInterpreterFactoryProvider.GetInterpreterFactory(System.String)
   at Microsoft.PythonTools.Interpreter.InterpreterRegistryService.FindInterpreter(System.String)
   at Microsoft.PythonTools.EnvironmentsList.ToolWindow+<>c__DisplayClass29_1.<UpdateEnvironments>b__3(Microsoft.PythonTools.Interpreter.InterpreterConfiguration)
   at Microsoft.PythonTools.Infrastructure.ObservableCollectionExtensions.Merge[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.ObjectModel.ObservableCollection`1<System.__Canon>, System.Collections.Generic.IEnumerable`1<System.__Canon>, System.Func`2<System.__Canon,System.__Canon>, System.Func`2<System.__Canon,System.__Canon>, System.Func`2<System.__Canon,System.__Canon>, System.Collections.Generic.IEqualityComparer`1<System.__Canon>, System.Collections.Generic.IComparer`1<System.__Canon>)
   at Microsoft.PythonTools.EnvironmentsList.ToolWindow.UpdateEnvironments(System.String)
   at Microsoft.PythonTools.EnvironmentsList.ToolWindow.<Service_InterpretersChanged>b__42_0()
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.PythonTools.EnvironmentsList.ToolWindow+<Service_InterpretersChanged>d__42.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory+SingleExecuteProtector.TryExecute()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory+SingleExecuteProtector+<>c.<.cctor>b__20_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

**Comment by huguesv** [comment]
3.8 enum member has been defined for a while and conversion of that value should work from that code path. You don't have a 3.9 in one of those subfolders right, because that would cause this failure.

You've made me realize that cookiecutter's copy of that conversion code does need to be udpated though.

In any case, as you've said, we shouldn't crash.
