### ISSUE TITLE
add py 3,7,4 env to vs 2019 comm latest version

### ISSUE THREAD

**Issue by pertetotale** [microsoft/PTVS#5850]
**Describe the bug**
add an installed working py 3,7,4 env to vs 2019 comm latest version

**Steps to Reproduce**
1.https://docs.microsoft.com/en-us/visualstudio/python/overview-of-python-tools-for-visual-studio?view=vs-2019
2. click on  py 3,7 64 bit
3. an unexp error occured

**Expected behavior**
no error

**Additional context and screenshots**
[Window Title]
devenv.exe
![afbeelding](https://user-images.githubusercontent.com/47835521/67721414-bbc3ce00-f9d6-11e9-9ff6-80aa00ea63f6.png)

[Main Instruction]
An unexpected error occurred

[Content]
An error occurred opening this interactive window.

Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Sluiten]

[Expanded Information]
```
Build: 16.3.19252.1

Microsoft.VisualStudio.Composition.CompositionFailedException: Expected 1 export(s) with contract name "Microsoft.VisualStudio.InteractiveWindow.IInteractiveWindowFactoryService" but found 0 after applying applicable constraints.
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports(ImportDefinition importDefinition)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports(String contractName, ImportCardinality cardinality, Type type, Type metadataViewType, IMetadataViewProvider& metadataViewProvider)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports[T,TMetadataView](String contractName, ImportCardinality cardinality)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T,TMetadataView](String contractName)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T](String contractName)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T]()
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExportedValue[T]()
   at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetService[T]()
   at Microsoft.VisualStudio.InteractiveWindow.Shell.VsInteractiveWindow.OnCreate()
   at Microsoft.VisualStudio.Shell.WindowPane.Microsoft.VisualStudio.Shell.Interop.IVsUIElementPane.CreateUIElementPane(Object& uiElement)
   at Microsoft.VisualStudio.Platform.WindowManagement.UIElementDocumentObject.Init(Boolean initSize)
   at Microsoft.VisualStudio.Platform.WindowManagement.DocumentObjectSite.InitializeDocumentObject(Object punkView)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.InitializeDocumentSite(Boolean creatingStubFrame, Boolean replacingStubView, Object punkView, Object punkData, IServiceProvider pServiceProvider, IVsUIHierarchy pUIHierarchy, UInt32 vsid)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowManagerService.CreateContentPane(FrameMoniker frameMoniker, Boolean isDocument, String lpstrMkDoc, UInt32 eCreateWindowFlags, Object punkView, Object punkData, IServiceProvider pServiceProvider, IVsUIHierarchy pUIHierarchy, UInt32 vsid, Guid rguidCmdUI, ViewGroup parent, IVsWindowFrame& ppWindowFrame)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowManagerService.CreateContentPane(String pszName, Int32 fDockViewOn, Int32 fDocument, String lpstrMkDoc, UInt32 eCreateWindowFlags, UInt32 dwToolWinId, Object punkView, Object punkData, IServiceProvider pServiceProvider, IVsUIHierarchy pUIHierarchy, UInt32 vsid, Int32& pfDefaultPosition, Guid& rguidCmdUI, IVsWindowFrame& ppWindowFrame)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.ErrorHandler.ThrowOnFailure(Int32 hr, Int32[] expectedHRFailure)
   at Microsoft.VisualStudio.InteractiveWindow.Shell.VsInteractiveWindow..ctor(IComponentModel model, Guid providerId, Int32 instanceId, String title, IInteractiveEvaluator evaluator, __VSCREATETOOLWIN creationFlags, Guid toolbarCommandSet, UInt32 toolbarId, IOleCommandTarget toolbarCommandTarget)
   at Microsoft.VisualStudio.InteractiveWindow.Shell.VsInteractiveWindowFactory.Create(Guid providerId, Int32 instanceId, String title, IInteractiveEvaluator evaluator, __VSCREATETOOLWIN creationFlags, Guid toolbarCommandSet, UInt32 toolbarId, IOleCommandTarget toolbarCommandTarget)
   at Microsoft.PythonTools.Repl.InteractiveWindowProvider.CreateInteractiveWindowInternal(IInteractiveEvaluator evaluator, IContentType contentType, Boolean alwaysCreate, Int32 id, String title, Guid languageServiceGuid, String replId)
   at Microsoft.PythonTools.Repl.InteractiveWindowProvider.Create(String replId, Int32 curId)
   at Microsoft.PythonTools.Repl.InteractiveWindowProvider.OpenOrCreate(String

**Sample Code**
```
XXX
```

**Configuration information (If you are providing a diagnostics file (see below), skip this section)**
VS Version: [Can be found under "Help->About Microsoft Visual Studio"]
PTVS version: [Can be found under "Help->About Microsoft Visual Studio->Installed products"]
Python version:
Debugger Type (if applicable): [New debugger or legacy debugger?]

**Diagnostics file**
The diagnostics file contains information such as the Python version, environments, loaded assemblies, configuration options, etc. This file makes it easier for us to reproduce and fix bugs, so we would really appreciate it if you could provide it to us. This file can be generated by going to Tools->Options->Python->Diagnostics.
You can attach the file to this issue or email it to us at ptvshelp@microsoft.com. If you email it, please add a link to this issue.
```
XXX
```

**Comment by bschnurr** [comment]
Was this a one time crash? or is it happening 100%?

**Comment by pertetotale** [comment]
I upgraded before a retest from 16.3.6 to 16.3.7. Now clickin the py 3.7.4 button in vs 2019 did not got the cat in the trees.

**Comment by bschnurr** [comment]
closing for now, no repro
