### ISSUE TITLE
LSC: Report inconsistent whitespace

### ISSUE THREAD

**Issue by huguesv** [microsoft/PTVS#5891]
When mixing tabs and spaces, we used to report it with a squiggle in the editor "inconsistent whitespace".

From VS 2019 16.4:
![image](https://user-images.githubusercontent.com/1696845/69094851-faf9a380-0a05-11ea-9fe9-43f85ae5fbfb.png)

This doesn't appear to work anymore. I tried in VS Code and it is not reported there either.

We have an option in tools/options/python that used to control the behavior:

![image](https://user-images.githubusercontent.com/1696845/69094690-b66e0800-0a05-11ea-8ad7-5baeccf7a743.png)

If you run the code, Python will give an error:
```
Traceback (most recent call last):
  File "c:\Users\huvalo\.vscode\extensions\ms-python.python-2019.11.49689\pythonFiles\ptvsd_launcher.py", line 43__main__.py
43, in <module>
    main(ptvsdArgs)
  File "c:\Users\huvalo\.vscode\extensions\ms-python.python-2019.11.49689\pythonFiles\lib\python\old_ptvsd\ptvsd\d\__main__.py", line 432, in main
    run()
  File "c:\Users\huvalo\.vscode\extensions\ms-python.python-2019.11.49689\pythonFiles\lib\python\old_ptvsd\ptvsd\d\__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "C:\Program Files\Python38\lib\runpy.py", line 261, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "C:\Program Files\Python38\lib\runpy.py", line 236, in _get_code_from_file
    code = compile(f.read(), fname, 'exec')
  File "c:\Projects\GitHub\huguesv\PTVS\Python\Tests\TestData\InconsistentIndentation\Program.py", line 3        
    print('goodbye')
                   ^
TabError: inconsistent use of tabs and spaces in indentation
PS C:\Projects\GitHub\huguesv\PTVS\Python\Tests\TestData\InconsistentIndentation>
```

Affected tests:
```
EditorTests.IndentationInconsistencyWarning
EditorTests.IndentationInconsistencyError
EditorTests.IndentationInconsistencyIgnore
```

**Comment by huguesv** [comment]
We are now tracking this task in our internal Pylance Azure DevOps.
