### ISSUE TITLE
LSC: Installed workload - language features don't work

### ISSUE THREAD

**Issue by huguesv** [microsoft/PTVS#5907]
I've made a build of VS and the language server doesn't start, editor LS features are working, obviously.

Activity log has these entries:
```
Still unable to load MEF component DLL: Could not load file or assembly 'Microsoft.Windows.Design.Extensibility, Version=4.3.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
          C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\PREVIEW\COMMON7\IDE\COMMONEXTENSIONS\DATADESIGN\Microsoft.VisualStudio.DataDesign.WpfComponents.dll
Still unable to load MEF component DLL: Could not load file or assembly 'Microsoft.Windows.Design.Host, Version=4.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
          C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\PREVIEW\COMMON7\IDE\EXTENSIONS\MICROSOFT\PYTHON\CORE\Microsoft.PythonTools.XamlDesignerSupport.dll
Still unable to load MEF component DLL: Could not load file or assembly 'Microsoft.VisualStudio.ProjectSystem.Managed.VS, Version=16.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
          C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\PREVIEW\COMMON7\IDE\EXTENSIONS\MICROSOFT\WEB TOOLS\Package Management\Microsoft.WebTools.PackageManagement.dll
Still unable to load MEF component DLL: Could not load file or assembly 'Microsoft.VisualStudio.TextTemplating.Interfaces.11.0, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
          c:\program files (x86)\microsoft visual studio\2019\preview\common7\ide\extensions\microsoft\web tools\scaffolding\Microsoft.AspNet.Scaffolding.12.0.dll
Still unable to load MEF component DLL: Could not load file or assembly 'Microsoft.VisualStudio.LiveShare.Razor, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.
          C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\PREVIEW\COMMON7\IDE\EXTENSIONS\MICROSOFT\LIVESHARE\Microsoft.VisualStudio.LiveShare.Razor.dll
Still unable to load MEF component DLL: Could not load file or assembly 'Microsoft.Windows.Simulator.Client, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
          c:\program files (x86)\microsoft visual studio\2019\preview\common7\ide\commonextensions\platform\diagnosticshub\Microsoft.DiagnosticsHub.VisualStudio.Package.dll
Still unable to load MEF component DLL: Could not load file or assembly 'Microsoft.VisualStudio.ProjectSystem.Managed, Version=16.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
          C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\PREVIEW\COMMON7\IDE\EXTENSIONS\MICROSOFT\LIVESHARE\Microsoft.VisualStudio.LiveShare.CPS.16.0.dll
Still unable to load MEF component DLL: Could not load file or assembly 'Microsoft.VisualStudio.ProjectSystem.Managed.VS, Version=16.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
          c:\program files (x86)\microsoft visual studio\2019\preview\common7\ide\extensions\microsoft\web tools\projectsystem\Microsoft.WebTools.ProjectSystem.dll
```

**Comment by huguesv** [comment]
Initialization fails. Looks like it is related to the code action changes that went in to the latest builds of the language server.

```
---------------------------

---------------------------
PythonLanguageClient:OnServerInitializeFailedAsync:1
Error reading boolean. Unexpected token: StartObject. Path 'codeActionProvider'.
   at Newtonsoft.Json.JsonReader.ReadAsBoolean()

   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)

   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)

   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)

   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)

   at Newtonsoft.Json.Linq.JToken.ToObject[T]()

   at Microsoft.VisualStudio.LanguageServer.Protocol.VSExtensionConverter`2.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)

   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)

   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)

   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)

   at StreamJsonRpc.JsonMessageFormatter.JsonRpcResult.GetResult[T]()

   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__101`1.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)

   at Microsoft.VisualStudio.LanguageServer.Client.RemoteLanguageClientInstance.<InitializeAsync>d__64.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.VisualStudio.Threading.ThreadingTools.<WithCancellationSlow>d__12.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.VisualStudio.LanguageServer.Client.RemoteLanguageClientInstance.<ActivateLanguageClientAsync>d__62.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
---------------------------
OK   
---------------------------
```

**Comment by huguesv** [comment]
Looks like the same root cause as https://github.com/microsoft/PTVS/issues/5888
Internal issue 1026382

**Comment by huguesv** [comment]
Fixed in VSLanguageServerClient. Need to wait for it to be inserted into VS.

**Comment by huguesv** [comment]
Verified that fix is now in.
