### ISSUE TITLE
Live Share: Failed to create a collaboration. 

### ISSUE THREAD

**Issue by zhouwangyang** [microsoft/PTVS#5910]
**Steps to Reproduce**
1.Open VS and create python application
2.Click Live Share, click "Leave Live Share Session" in client after Live Share connected successfully.
3.Close Live Share window in client
4.Click "End Live Share Session" in host to stop Live Share
5.Click "Live Share" in host to connect again

**Expected behavior**
no errors and can be shared

**Actual behavior**
Error popup in info bar, no error info in output window.
![image](https://user-images.githubusercontent.com/39871640/69512071-9ac2ae80-0f7d-11ea-8042-421cfe419f7a.png)

**Reproed video**
[video_1.zip](https://github.com/microsoft/PTVS/files/3884839/video_1.zip)

**VS and Python info**
![image](https://user-images.githubusercontent.com/39871640/69512145-dd848680-0f7d-11ea-8709-47480ab8cba6.png)

**Comment by huguesv** [comment]
I did get this assertion after trying to start a session when the previous client VS was closed/shut down.
```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Exception on sharing workspace: 

System.InvalidOperationException

   at Microsoft.VisualStudio.Cascade.Commands.ShareWorkspaceCommand.<ShareWorkspaceInternalAsync>d__33.MoveNext()

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()

   at System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation.<>c.<.cctor>b__8_0(Object state)

   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.SingleExecuteProtector.TryExecute()

   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.SingleExecuteProtector.<>c.<.cctor>b__20_0(Object state)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.DispatcherOperation.InvokeImpl()

   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)

   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Windows.Threading.DispatcherOperation.Invoke()

   at System.Windows.Threading.Dispatcher.ProcessQueue()

   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)

   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)


---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by huguesv** [comment]
Can also be reproduced using C# projects.

**Comment by daytonellwanger** [comment]
This is a Live Share bug. You can track the issue over at [3053](https://github.com/MicrosoftDocs/live-share/issues/3053)
