### ISSUE TITLE
Unexpected Error while loading python project

### ISSUE THREAD

**Issue by a-jaeger** [microsoft/PTVS#5935]
Loading a python project in Visual Studio in Administrator-Mode shows an error dialog: An unexpected error occured
**Steps to Reproduce**
1. Start Visual Studio
2. Open Python Project

**Expected behavior**
No error

**Additional context and screenshots**
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Schließen]

[Expanded Information]
```

Build: 16.4.19310.1

System.AggregateException: One or more errors occurred. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: first
   at System.Linq.Enumerable.Union[TSource](IEnumerable`1 first, IEnumerable`1 second)
   at Microsoft.PythonTools.Interpreter.CondaPackageManager.<GetEnvironmentVariables>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.PythonTools.Interpreter.CondaPackageManager.<CacheInstalledPackagesAsync>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Interpreter.CondaPackageManager.<GetInstalledPackagesAsync>d__64.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Project.InterpretersNode.<RefreshPackagesAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   --- End of inner exception stack trace ---
   at System.AggregateException.Handle(Func`2 predicate)
   at Microsoft.PythonTools.Infrastructure.TaskExtensions.<>c__9`1.<SilenceException>b__9_0(Task t)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
---> (Inner Exception #0) System.ArgumentNullException: Value cannot be null.
Parameter name: first
   at System.Linq.Enumerable.Union[TSource](IEnumerable`1 first, IEnumerable`1 second)
   at Microsoft.PythonTools.Interpreter.CondaPackageManager.<GetEnvironmentVariables>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.PythonTools.Interpreter.CondaPackageManager.<CacheInstalledPackagesAsync>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Interpreter.CondaPackageManager.<GetInstalledPackagesAsync>d__64.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Project.InterpretersNode.<RefreshPackagesAsync>d_
```

**Configuration information (If you are providing a diagnostics file (see below), skip this section)**
VS Version: Version 16.4.1
PTVS version: 16.4.19310.1
Python version:
Debugger Type (if applicable): [New debugger or legacy debugger?]

**Diagnostics file**
[Diagnostic Info 2019-12-11T105749.txt](https://github.com/microsoft/PTVS/files/3949660/Diagnostic.Info.2019-12-11T105749.txt)

**Comment by RaymonGulati1** [comment]
Thank you for reporting the issue. 

A temporary workaround is to remove the Conda environment from the project which allow you to open the project without issues. If you need the conda environment for development, try using the Conda base environment (see below on how to add it) or recreate the conda virtual environment. 

Let me know if any of these workarounds work for you or if you need more help. 

![image](https://user-images.githubusercontent.com/3315992/70661001-3740ae00-1c18-11ea-9b5d-0b91b1f3d2e0.png)
