### ISSUE TITLE
Live Share: An error pops up in Live Share client and IntelliSense is invalid after join Live Share. 

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#5964]
## Environment data

Build of Visual Studio: 16.5.0 Preview 2.0 [29709.165.master]
Build of Python Package: 16.5.19345.1

## Expected behaviour

Without any error.

## Actual behaviour

An error pops up.
![image](https://user-images.githubusercontent.com/59192491/72135670-03e17280-33c2-11ea-8335-23b74123f900.png)

## Steps to reproduce:
1. Oen VS and create python application
2. Click Live Share, make sure the client can be joined successfully.
3. Wait a moment, the error will happened.

""ActivityLog.xml**
[ActivityLog.zip](https://github.com/microsoft/PTVS/files/4051868/ActivityLog.zip)

**Comment by huguesv** [comment]
```
Microsoft.Assumes+InternalErrorException: Cannot find an instance of the Microsoft.VisualStudio.RpcContracts.OutputChannel.IOutputChannelStore service.
at Microsoft.Assumes.Fail(String message)
at Microsoft.Assumes.Present[T](T component)
at Microsoft.VisualStudio.PlatformUI.OutputChannelConsumer.<SubscribeToClientAsync>d__16.MoveNext() --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.VisualStudio.Shell.VsTaskLibraryHelper.<>c__DisplayClass32_0.<<FileAndForget>b__0>d.MoveNext() --- End of stack trace from previous location where exception was thrown --- 
at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by huguesv** [comment]
The call stack matches the one from internal bug 1052823. They have a fix in master for 16.5 Preview 3, but I was able to reproduce in 16.5.0 Preview 3.0 [29714.154.master]. Maybe try again in a few days.

**Comment by zhouwangyang** [comment]
I was able to reproduce in 16.5.0 Preview 3.0 [29814.53.d16.5]
