### ISSUE TITLE
An error pops up when edit in Python Application project.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#5965]
Build of Visual Studio: 16.5.0 Preview 3.0 [29712.7.master]
Build of Python Package: 16.5.20009.1

**Steps to Reproduce**
1. Launch visual studio and create a new python application project
2. Add some code in project

**Expected behavior**
Without any error.

**Additional context and screenshots**
An error pops up.
![image](https://user-images.githubusercontent.com/59192491/72231328-ded54580-35f5-11ea-8047-3f640cd6ea71.png)

**ActivityLog.xml**
[ActivityLog.zip](https://github.com/microsoft/PTVS/files/4051988/ActivityLog.zip)

**Comment by huguesv** [comment]
```
System.NullReferenceException: Object reference not set to an instance of an object.
at Microsoft.VisualStudio.Text.AdornmentLibrary.ToolTip.Implementation.MouseTrackingWpfToolTipPresenter.SubscribeToContainerUnderMouse()
at Microsoft.VisualStudio.Text.AdornmentLibrary.ToolTip.Implementation.MouseTrackingWpfToolTipPresenter.StartOrUpdate(ITrackingSpan applicableToSpan, IEnumerable`1 content)at Microsoft.VisualStudio.Text.AdornmentLibrary.ToolTip.Implementation.GuardedToolTipPresenter.<>c__DisplayClass10_0.<StartOrUpdate>b__0()
at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call) --- End of stack trace from previous location where exception was thrown --- 
at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by huguesv** [comment]
I just encountered this in a C# project. Looks like internal bug 1051061

**Comment by huguesv** [comment]
This was fixed in VS.
