### ISSUE TITLE
VS2019 - No intellisense:  "Python source analysis is not up to date"

### ISSUE THREAD

**Issue by tigreye007** [microsoft/PTVS#5983]
**Describe the bug**
A very large Python 3.5 / Django 1.11 project that has intellisense working in VS2017 CE, but is not working in VS2019.  Right-clicking a variable and clicking "Go To Definition" results in the status bar showing a message "Python source analysis is not up to date"

**Steps to Reproduce**
I do not have exact steps to reproduce unfortunately, and to top it off it may very well be a duplicate related to this:  https://github.com/Microsoft/PTVS/issues/5213.  However, I have no direction as to how to find these missing files that are discussed.

**Expected behavior**
Intellisense autocompletes variables, and allows you to navigate to method/variable definitions/references

**Configuration information (If you are providing a diagnostics file (see below), skip this section)**
VS Version: 16.4.3
PTVS version: Unsure (no listing for PVTS in "Installed products")
Python version:  3.5
Debugger Type (if applicable): Unknown

**Diagnostics file**
[Diagnostic Info 2020-01-16T161611.txt](https://github.com/microsoft/PTVS/files/4074006/Diagnostic.Info.2020-01-16T161611.txt)

**Comment by huguesv** [comment]
Thanks for the feedback, and sorry for the delay.

The missing files was manifesting in no IntelliSense anywhere in the project, on any type ie. anything as simple as `a = 10; a.`. Basically the analyzer was not responding to any messages from the IDE.

The log you have attached shows a null reference exception when analyzing the url definitions in your project. I am curious, if you comment out all of your `url()` or `path()`, and reload your project, if that makes any difference or not. If it helps, maybe put them back one by one until it breaks.

We've made changes to support Django 2.x for VS 2019, maybe we made a change incompatible with 1.11.

**Comment by huguesv** [comment]
The exception from the log:
```
[01/16/2020 14:46:44] AnalysisWarning: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.PythonTools.Django.Analysis.DjangoAnalyzer.UrlProcessor(Node node, AnalysisUnit unit, IAnalysisSet[] args, NameExpression[] keywordArgNames)
   at Microsoft.PythonTools.Analysis.Values.SpecializedCallable.Call(Node node, AnalysisUnit unit, IAnalysisSet[] args, NameExpression[] keywordArgNames)
   at Microsoft.PythonTools.Analysis.Analyzer.ExpressionEvaluator.EvaluateCall(ExpressionEvaluator ee, Node node)
   at Microsoft.PythonTools.Analysis.Analyzer.ExpressionEvaluator.EvaluateWorker(Node node)
   at Microsoft.PythonTools.Analysis.Analyzer.ExpressionEvaluator.MakeSequence(ExpressionEvaluator ee, Node node)
   at Microsoft.PythonTools.Analysis.Analyzer.ExpressionEvaluator.EvaluateWorker(Node node)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(AugmentedAssignStatement node)
   at Microsoft.PythonTools.Parsing.Ast.AugmentedAssignStatement.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(SuiteStatement node)
   at Microsoft.PythonTools.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(ForStatement node)
   at Microsoft.PythonTools.Parsing.Ast.ForStatement.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(SuiteStatement node)
   at Microsoft.PythonTools.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Analysis.Analyzer.FunctionAnalysisUnit.AnalyzeWorker(DDG ddg, CancellationToken cancel)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Analyze(Deque`1 queue, CancellationToken cancel, Action`1 reportQueueSize, Int32 reportQueueInterval)
   at Microsoft.PythonTools.Analysis.PythonAnalyzer.AnalyzeQueuedEntries(CancellationToken cancel)
   at Microsoft.PythonTools.Intellisense.AnalysisQueue.GroupAnalysis.Analyze(CancellationToken cancel)
   at Microsoft.PythonTools.Intellisense.AnalysisQueue.<HandleAnalyzable>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.PythonTools.Intellisense.AnalysisQueue.<ConsumerLoop>d__25.MoveNext()

```

**Comment by tigreye007** [comment]
Sorry about the delay - I should have some time next week to try out your recommendations and let you know the results.

**Comment by tigreye007** [comment]
@huguesv Removing all calls to url() fixed intellisense in my case (across 30 files).  Hope that helps debug the issue!

**Comment by tigreye007** [comment]
@huguesv When I brought back the first file's calls to url(), intellisense continued to work.  The 2nd file's calls to url() immediately caused intellisense to stop working:

**sample url() call from first file:**

urlpatterns = [
    url(r'^test/(?P<slug>[\w-]+)/.*$', TestView.as_view(), name='test_page')
]

**Exact url() call from second file:**

action_urls += [
                url(r'^{0}/inline/create/$'.format(f.field_identifier), self.admin_site.admin_view(create_view), name="{0}_{1}_inline_create".format(f.field_identifier, self.unique_id)),
                url(r'^{0}/inline/(?P<obj_id>.+)/(?P<rel_obj_id>.+)/delete/$'.format(f.field_identifier), self.admin_site.admin_view(delete_view), name="{0}_{1}_inline_delete".format(f.field_identifier, self.unique_id)),
                url(r'^{0}/inline/update-order/$'.format(f.field_identifier), self.admin_site.admin_view(update_view), name="{0}_{1}_inline_update_order".format(f.field_identifier, self.unique_id)),
            ]

**Comment by huguesv** [comment]
Thanks @tigreye007, we'll have a look.

**Comment by lefig** [comment]
I have the same problem. Intellisense has broken yet again.

**Comment by Badiboy** [comment]
Micro project (1 files) works fine.
Small projects (2-3 files) works partially: colors and references works, class and function lists empty.
Large project (30+ files) does not work at all: no navigation, no completeion, no lists.

VS2019 and everything inside it is totally up to date.

**Comment by lefig** [comment]
I have the same problem. Intellisense has broken yet again as of today.

And again the problem is intermittent.

**Comment by thrmotta** [comment]
> I have the same problem. Intellisense has broken yet again as of today.
> 
> And again the problem is intermittent.

Cant testify for VS2015, but the same thing happens to me. Even after updating Visual Studio to 16.5.1 (launched today) the same behavior persists. No Intellisense at all. "Go To Definition" does nothing, no autocomplete, cant even collapse functions, comments or classes. Class and function lists are also completely empty.

**Comment by thrmotta** [comment]
After searching for a solution for the past two days, I decided to try some new things... 

- I recreated my visual studio solution and went with the "Existing python code" option. (The problem still persisted though)
- After reimporting everything that passed the default importing regex, the problem still persisted.
- I manually excluded some folders from project, namely those with lots (10+) files (Problem disappeared completely)
- Reimported folders folders with fewer files (Problem still gone)
- When reimporting those folders with lots of file, I _manually excluded all folders that didn't have any .py file_.
- Deleted all ___pycache___ folders from the entire solution directory
- Removed _internal requirements.txt_ files (some internal folders were cloned from other repositories and left "as it is")
- Removed _internal .gitignore_ files (no idea if this had any effects)
- Removed _internal .vs hidden folders_ (there were some internal solutions on the directory structures, but those were maintained)
- Removed from solution and deleted _.ipynb_checkpoints folders_

After that, IntelliSense was finally working again. Hope this is related to the problem or other people can relate to this.

**Comment by linette-zyy** [comment]
PUBLIC community feedback: https://developercommunity.visualstudio.com/content/problem/917794/intellisence-not-working-with-python-language.html
