### ISSUE TITLE
Unable to execute command in command prompt for remote debugger.

### ISSUE THREAD

**Issue by zhouwangyang** [microsoft/PTVS#5991]
**Describe the bug**

**Steps to Reproduce**
1.Create python application named Testing in VS
2.using "pip install ptvsd" to install ptvsd in python 3.7(64-bit) environment
3.In command prompt(right-click the python environment and select "Open Command Prompt Here…"), execute:
python -m ptvsd --host 127.0.0.1 --port 4022 C:\Users\vslab1\source\repos\PythonApplication1\PythonApplication1\PythonApplication1.py

**Expected behavior**
no any error in command prompt wondow

**Additional context and screenshots**
execute command failed with errors
![image](https://user-images.githubusercontent.com/39871640/72875020-590c7500-3d2e-11ea-81b2-831f8c81a231.png)

**VS version**
![image](https://user-images.githubusercontent.com/39871640/72875062-72152600-3d2e-11ea-8bcd-23aa884708f2.png)

**Comment by huguesv** [comment]
I tried with ptvsd==5.0.0a12 as well.

My application is just `print('hello')`

After starting with `python -m ptvsd --host 127.0.0.1 --port 4022 C:\Users\huvalo\source\repos\Testing\Testing.py`, the application prints hello, ends and returns to the command prompt.

If I look at task manager, I see that python.exe is still running. If I try to launch it again, it complains about socket address being in use:
```
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python37\lib\site-packages\ptvsd\__main__.py", line 45, in <module>
    cli.main()
  File "C:\Program Files\Python37\lib\site-packages\ptvsd\server\cli.py", line 361, in main
    run()
  File "C:\Program Files\Python37\lib\site-packages\ptvsd\server\cli.py", line 189, in run_file
    setup_debug_server(options.target)
  File "C:\Program Files\Python37\lib\site-packages\ptvsd\server\cli.py", line 182, in setup_debug_server
    debug(address=options, multiprocess=options)
  File "C:\Program Files\Python37\lib\site-packages\ptvsd\__init__.py", line 81, in enable_attach
    return api.enable_attach(address, log_dir)
  File "C:\Program Files\Python37\lib\site-packages\ptvsd\server\api.py", line 75, in debug
    raise log.exception("{0}() failed:", func.__name__, level="info")
  File "C:\Program Files\Python37\lib\site-packages\ptvsd\server\api.py", line 73, in debug
    return func(start_patterns, end_patterns)
  File "C:\Program Files\Python37\lib\site-packages\ptvsd\server\api.py", line 167, in enable_attach
    raise RuntimeError(str(endpoints["error"]))
RuntimeError: Can't listen for IDE connections: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted
```

Manually killing the python.exe fixes it.

**Comment by huguesv** [comment]
This is specific to the scenario where you launch with ptvsd but never attach to it and the application ends. It would be good to cleanup the adapter process that is left running.
