### ISSUE TITLE
Conda activation not working

### ISSUE THREAD

**Issue by huguesv** [microsoft/PTVS#5993]
**Describe the bug**
We had a bug filed by multiple users where conda activation code would lead to a crash. We've changed to the code to avoid the crash. I've just checked and activation doesn't work.

**Steps to Reproduce**
Easiest way to demonstrate is to check if numpy loads successfully in a conda env.

1. Create a new python app
2. Create a conda environment and install `python=3.7 numpy`
3. Run this code

```
import numpy
print(numpy.__version__)
```

**Expected behavior**
Runs without error

**Additional context and screenshots**
```
Loaded 'numpy.core'
Loaded 'numpy'
Loaded '__main__'
Loaded 'runpy'
Traceback (most recent call last):
  File "C:\Users\huvalo\.conda\envs\condaenv23b\lib\site-packages\numpy\core\__init__.py", line 24, in <module>
    from . import multiarray
  File "C:\Users\huvalo\.conda\envs\condaenv23b\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "C:\Users\huvalo\.conda\envs\condaenv23b\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: The specified module could not be found.
```

This happens while using miniconda bundled with VS and also when using latest Anaconda 2019.10 (3.x 64-bit).

**Comment by huguesv** [comment]
[ptvsd.launcher-10228.log](https://github.com/microsoft/PTVS/files/4105545/ptvsd.launcher-10228.log)
[ptvsd.server-11724.log](https://github.com/microsoft/PTVS/files/4105546/ptvsd.server-11724.log)
[ptvsd.adapter-10092.log](https://github.com/microsoft/PTVS/files/4105547/ptvsd.adapter-10092.log)

One thing that is suspicious is that the launcher logs show that the environment variables used by the adapter to launch the program have both a `PATH` entry and a `Path` entry.
