### ISSUE TITLE
Failed to install 'pytest' in python 2.7 virtual environment.

### ISSUE THREAD

**Issue by zhouwangyang** [microsoft/PTVS#6006]
**Test Environment**
![image](https://user-images.githubusercontent.com/39871640/73924061-d75c4000-4906-11ea-9c26-0748159662b9.png)

**Steps to Reproduce**
1.Create python application in VS
2.Create virtual environment with python 2.7 named env1
3.Right click in the virtual environment env1 and click Mange Python Packages...
4.inpute pytest in the search box to install pytest

**Expected behavior**
pytest can be installed sucessfully

**Actual behavior**
Failed to install 'pytest' 

**Output Window**

----- Installing 'pytest' -----
You are using pip version 6.1.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting pytest
  Using cached https://files.pythonhosted.org/packages/f0/5f/41376614e41f7cdee02d22d1aec1ea028301b4c6c4523a5f7ef8e960fe0b/pytest-5.3.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "c:\users\vwazho\appdata\local\temp\pip-build-p6jtap\pytest\setup.py", line 42, in <module>
        main()
      File "c:\users\vwazho\appdata\local\temp\pip-build-p6jtap\pytest\setup.py", line 37, in main
        install_requires=INSTALL_REQUIRES,
      File "C:\Python27amd64\Lib\distutils\core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "C:\Users\vwazho\source\repos\PythonApplication1\PythonApplication1\env\lib\site-packages\setuptools\dist.py", line 265, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "C:\Users\vwazho\source\repos\PythonApplication1\PythonApplication1\env\lib\site-packages\setuptools\dist.py", line 310, in fetch_build_eggs
        replace_conflicting=True,
      File "C:\Users\vwazho\source\repos\PythonApplication1\PythonApplication1\env\lib\site-packages\pkg_resources\__init__.py", line 824, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "C:\Users\vwazho\source\repos\PythonApplication1\PythonApplication1\env\lib\site-packages\pkg_resources\__init__.py", line 1069, in best_match
        return self.obtain(req, installer)
      File "C:\Users\vwazho\source\repos\PythonApplication1\PythonApplication1\env\lib\site-packages\pkg_resources\__init__.py", line 1081, in obtain
        return installer(requirement)
      File "C:\Users\vwazho\source\repos\PythonApplication1\PythonApplication1\env\lib\site-packages\setuptools\dist.py", line 377, in fetch_build_egg
        return cmd.easy_install(req)
      File "C:\Users\vwazho\source\repos\PythonApplication1\PythonApplication1\env\lib\site-packages\setuptools\command\easy_install.py", line 617, in easy_install
        not self.always_copy, self.local_index
      File "C:\Users\vwazho\source\repos\PythonApplication1\PythonApplication1\env\lib\site-packages\setuptools\package_index.py", line 601, in fetch_distribution
        return dist.clone(location=self.download(dist.location, tmpdir))
      File "C:\Users\vwazho\source\repos\PythonApplication1\PythonApplication1\env\lib\site-packages\setuptools\package_index.py", line 517, in download
        found = self._download_url(scheme.group(1), spec, tmpdir)
      File "C:\Users\vwazho\source\repos\PythonApplication1\PythonApplication1\env\lib\site-packages\setuptools\package_index.py", line 758, in _download_url
        return self._attempt_download(url, filename)
      File "C:\Users\vwazho\source\repos\PythonApplication1\PythonApplication1\env\lib\site-packages\setuptools\package_index.py", line 764, in _attempt_download
        headers = self._download_to(url, filename)
      File "C:\Users\vwazho\source\repos\PythonApplication1\PythonApplication1\env\lib\site-packages\setuptools\package_index.py", line 664, in _download_to
        fp = self.open_url(strip_fragment(url))
      File "C:\Users\vwazho\source\repos\PythonApplication1\PythonApplication1\env\lib\site-packages\setuptools\package_index.py", line 714, in open_url
        % (url, v.reason))
    distutils.errors.DistutilsError: Download error for https://files.pythonhosted.org/packages/42/3e/2464120172859e5d103e5500315fb5555b1e908c0dacc73d80d35a9480ca/setuptools-45.1.0.zip#sha256=91f72d83602a6e5e4a9e4fe296e27185854038d7cbda49dcd7006c4d3b3b89d5: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)
    
    Command "python setup.py egg_info" failed with error code 1 in c:\users\vwazho\appdata\local\temp\pip-build-p6jtap\pytest
----- Failed to install 'pytest' -----

**Comment by huguesv** [comment]
According to pypi.org, pytest 5.x requires python 3.5 or later. Anyone still on python 2.7 will have to use the older pytest 4.x.
