### ISSUE TITLE
Tests are detected but do not appear in test explorer treeview

### ISSUE THREAD

**Issue by huguesv** [microsoft/PTVS#6010]
Install VS with Python workload only
Create python application
Add a test file
Set test framework to unittest in project properties
Open test explorer

Notice that the tests output shows it detected tests, the test explorer toolbar shows it detected tests, but the test explorer tree view is empty!

![image](https://user-images.githubusercontent.com/1696845/73977821-de238c80-48df-11ea-9745-81e39464b45a.png)

~~I was able to work around it by going back to the VS installer and adding the .NET desktop development workload. Then the tests started appearing in the tree view. Strangely, uninstalling the .NET desktop workload did not break it, it was still working after that.~~

~~Maybe we need to add a new dependency in the Python workload installer definition?~~

**Comment by huguesv** [comment]
I just tried it again with the latest dogfood build. I'm also seeing errors in the output window.
```
Log level is set to Informational (Default).
System.ArgumentException: There is already a command handler for the menu command 'c488519c-6c2f-411f-9a2f-f4c395864b06 : 256'.
   at System.ComponentModel.Design.MenuCommandService.AddCommand(MenuCommand command)
   at Microsoft.TeamFoundation.TestManagement.TestMethodAssociationExtension.ViewModels.AssociateTestCaseCommand.InitializeCommands()
   at Microsoft.VisualStudio.TestWindow.UI.TestWindowToolWindowServicesProvider.<>c__DisplayClass11_1.<CreateAsync>b__1()
   at Microsoft.VisualStudio.TestWindow.Extensibility.ILoggerExtensions.CallInternalWithLogging(ILogger2 log, Action action, Boolean shouldThrow)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
System.ArgumentException: There is already a command handler for the menu command '1e198c22-5980-4e7e-92f3-f73168d1fb63 : 1024'.
   at System.ComponentModel.Design.MenuCommandService.AddCommand(MenuCommand command)
   at Microsoft.VisualStudio.TestWindow.VsHost.ToolWindowMenuCommandFactory.CreateMenuCommand(MenuCommandDefinition commandDefinition)
   at Microsoft.VisualStudio.TestWindow.Controller.MenuCommandContainer.InitializeCommands()
   at Microsoft.VisualStudio.TestWindow.UI.TestWindowToolWindowServicesProvider.<>c__DisplayClass11_1.<CreateAsync>b__1()
   at Microsoft.VisualStudio.TestWindow.Extensibility.ILoggerExtensions.CallInternalWithLogging(ILogger2 log, Action action, Boolean shouldThrow)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
System.ArgumentException: There is already a command handler for the menu command '1e198c22-5980-4e7e-92f3-f73168d1fb63 : 768'.
   at System.ComponentModel.Design.MenuCommandService.AddCommand(MenuCommand command)
   at Microsoft.VisualStudio.TestWindow.VsHost.ToolWindowMenuCommandFactory.CreateMenuCommand(MenuCommandDefinition commandDefinition)
   at Microsoft.VisualStudio.TestWindow.Controller.MenuCommandContainer.InitializeCommands()
   at Microsoft.VisualStudio.TestWindow.UI.TestWindowToolWindowServicesProvider.<>c__DisplayClass11_1.<CreateAsync>b__1()
   at Microsoft.VisualStudio.TestWindow.Extensibility.ILoggerExtensions.CallInternalWithLogging(ILogger2 log, Action action, Boolean shouldThrow)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
System.ArgumentException: There is already a command handler for the menu command '1e198c22-5980-4e7e-92f3-f73168d1fb63 : 4650'.
   at System.ComponentModel.Design.MenuCommandService.AddCommand(MenuCommand command)
   at Microsoft.VisualStudio.TestWindow.VsHost.ToolWindowMenuCommandFactory.CreateMenuCommand(MenuCommandDefinition commandDefinition)
   at Microsoft.VisualStudio.TestWindow.Controller.MenuCommandContainer.InitializeCommands()
   at Microsoft.VisualStudio.TestWindow.UI.TestWindowToolWindowServicesProvider.<>c__DisplayClass11_1.<CreateAsync>b__1()
   at Microsoft.VisualStudio.TestWindow.Extensibility.ILoggerExtensions.CallInternalWithLogging(ILogger2 log, Action action, Boolean shouldThrow)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
System.ArgumentException: There is already a command handler for the menu command '1e198c22-5980-4e7e-92f3-f73168d1fb63 : 4643'.
   at System.ComponentModel.Design.MenuCommandService.AddCommand(MenuCommand command)
   at Microsoft.VisualStudio.TestWindow.VsHost.ToolWindowMenuCommandFactory.CreateMenuCommand(MenuCommandDefinition commandDefinition)
   at Microsoft.VisualStudio.TestWindow.Controller.MenuCommandContainer.InitializeCommands()
   at Microsoft.VisualStudio.TestWindow.UI.TestWindowToolWindowServicesProvider.<>c__DisplayClass11_1.<CreateAsync>b__1()
   at Microsoft.VisualStudio.TestWindow.Extensibility.ILoggerExtensions.CallInternalWithLogging(ILogger2 log, Action action, Boolean shouldThrow)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
System.ArgumentException: There is already a command handler for the menu command '7aa1a7f4-56d9-4653-b67a-f915e05c0ca2 : 1536'.
   at System.ComponentModel.Design.MenuCommandService.AddCommand(MenuCommand command)
   at Microsoft.VisualStudio.TestWindow.CodeCoverage.AnalyzeCodeCoverageCommandBase.InitializeCommands()
   at Microsoft.VisualStudio.TestWindow.UI.TestWindowToolWindowServicesProvider.<>c__DisplayClass11_1.<CreateAsync>b__1()
   at Microsoft.VisualStudio.TestWindow.Extensibility.ILoggerExtensions.CallInternalWithLogging(ILogger2 log, Action action, Boolean shouldThrow)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
System.ArgumentException: There is already a command handler for the menu command '7aa1a7f4-56d9-4653-b67a-f915e05c0ca2 : 1537'.
   at System.ComponentModel.Design.MenuCommandService.AddCommand(MenuCommand command)
   at Microsoft.VisualStudio.TestWindow.CodeCoverage.AnalyzeCodeCoverageCommandBase.InitializeCommands()
   at Microsoft.VisualStudio.TestWindow.UI.TestWindowToolWindowServicesProvider.<>c__DisplayClass11_1.<CreateAsync>b__1()
   at Microsoft.VisualStudio.TestWindow.Extensibility.ILoggerExtensions.CallInternalWithLogging(ILogger2 log, Action action, Boolean shouldThrow)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
Error opening test data: Failed to deserialize Microsoft.VisualStudio.TestWindow.Records.LogEntry value.
Test data was cleared upon opening.
Test data store opened in 0.008 sec.
---------- Starting test discovery ----------
Starting unittest discovery for the PythonApplication4 project. This can take up to 60 seconds.
cd C:\Users\huvalo\source\repos\PythonApplication4\
set PYTHONPATH=C:\Users\huvalo\source\repos\PythonApplication4\
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\python.exe C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\PREVIEW\COMMON7\IDE\EXTENSIONS\MICROSOFT\PYTHON\CORE\PythonFiles\testing_tools\run_adapter.py discover unittest --output-file C:\Users\huvalo\AppData\Local\Temp\tmpD6E4.tmp -- . test*.py
========== Test discovery finished: 3 Tests found in 2.3 sec ==========

```

**Comment by huguesv** [comment]
Okay, this may not have anything to do with installation/.NET workload.

If I open VS and the Test Explorer tool window is already visible at startup, then the tests appear fine and there is no error in output window.

If I open VS and the Test Explorer tool window is NOT visible, then when I open Test Explorer I get the errors and the tests do not appear.

If I do the same on my dev machine with C# unit tests, for some reason it works fine in both scenarios.

**Comment by RaymonGulati1** [comment]
Fixed by VS test explorer team
