### ISSUE TITLE
Error in LiveShare when creating new project after session has started

### ISSUE THREAD

**Issue by huguesv** [microsoft/PTVS#6029]
1.Create a python application project named Project1
2.Click "Live Share" to connect host and client on the same machine.
3.After connected successfully, click file->new->project->python application to create new project on the host.
4.Open the default .py file to edit on the host and client
5.Waiting a few seconds, error will appear in client.

![image](https://user-images.githubusercontent.com/1696845/74868959-f053f080-530b-11ea-91df-45fb9e824afe.png)

```
Coauthoring exception Object reference not set to an instance of an object. at:
at Microsoft.VisualStudio.LiveShare.Coauthoring.BufferManager.ApplyFileOpenAcknowledge(FileOpenAcknowledgeMessage message, Int32 eventId)
at Microsoft.VisualStudio.LiveShare.Coauthoring.CoauthoringManagerBase.<>c__DisplayClass94_0.<<HandleSourceEventServiceEvent>b__0>d.MoveNext()
 while processing Microsoft.Cascade.Contracts.Coauthoring.FileOpenAcknowledgeMessage
```

**Comment by huguesv** [comment]
Same repro steps, slightly different error.

![image](https://user-images.githubusercontent.com/1696845/74869886-a79d3700-530d-11ea-9cce-90589be59818.png)


```
Coauthoring exception The specified ITextSnapshot doesn't belong to the correct TextBuffer. at:
at Microsoft.VisualStudio.Text.Implementation.TrackingSpan.GetSpan(ITextSnapshot snapshot)
at Microsoft.VisualStudio.Cascade.Coauthoring.UI.CoauthoringService.JumpToClient(Int32 clientId)
at Microsoft.VisualStudio.LiveShare.Coauthoring.CoauthoringManagerBase.<>c__DisplayClass94_0.<<HandleSourceEventServiceEvent>b__0>d.MoveNext()
 while processing Microsoft.Cascade.Contracts.Coauthoring.SelectionChangeMessage

Coauthoring error: selection record for /PythonApplication7.py is stale
```
