### ISSUE TITLE
python runpy.py bug

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6035]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/934283/python-runpypy-bug.html)._

---
when running the below cmd line processing logic, VS runpy.py code trips up on main exit:
```py
import sys

if __name__=="__main__":
    args=sys.argv
    args.pop(0)
    print("Hello world!")
    exit(0)
```

The error is:
```
Traceback (most recent call last):
  File "c:\program files (x86)\microsoft visual studio\2019\enterprise\common7\ide\extensions\microsoft\python\core\ptvsd_launcher.py", line 119, in <module>
    vspd.debug(filename, port_num, debug_id, debug_options, run_as)
  File "c:\program files (x86)\microsoft visual studio\2019\enterprise\common7\ide\extensions\microsoft\python\core\Packages\ptvsd\debugger.py", line 39, in debug
    run()
  File "c:\program files (x86)\microsoft visual studio\2019\enterprise\common7\ide\extensions\microsoft\python\core\Packages\ptvsd\__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 59, in __exit__
    sys.argv[0] = self._saved_value
IndexError: list assignment index out of range
```
---
#### Visual Studio Feedback System on 3/1/2020, 03:01 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by huguesv** [comment]
Repros on 16.5 with debugpy as well.

```
import sys

if __name__=="__main__":
    args=sys.argv
    args.pop(0)
    print("Hello world!")
    exit(0)
```

Press F5.

```
Hello world!
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\huvalo\source\repos\PythonApplication11\PythonApplication11.py", line 8, in <module>
    exit(0)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\program files (x86)\microsoft visual studio\2019\preview\common7\ide\extensions\microsoft\python\core\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\program files (x86)\microsoft visual studio\2019\preview\common7\ide\extensions\microsoft\python\core\debugpy/..\debugpy\server\cli.py", line 361, in main
    run()
  File "c:\program files (x86)\microsoft visual studio\2019\preview\common7\ide\extensions\microsoft\python\core\debugpy/..\debugpy\server\cli.py", line 203, in run_file
    runpy.run_path(options.target, run_name="__main__")
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 59, in __exit__
    sys.argv[0] = self._saved_value
IndexError: list assignment index out of range
Press any key to continue . . .
```

**Comment by int19h** [comment]
The contract for `sys.argv` is that it always contains at least one entry, which is the name of the file or module used to start the process. Popping something from argv breaks that contract, which in turn breaks the standard `runpy` module that we use to simulate the behavior of the Python interpreter. If it's a bug, it's a `runpy` bug, but I think that's just not expected to work by design.

In any case, I don't think we can really do anything here. The exception happens inside `runpy`, and it's inside the call that we make to run the target script. We can't just catch any `IndexError` that comes out of that code, and we can't distinguish this particular case from others (I guess we could look at the stack, but then we'd be depending on runpy internals).
