### ISSUE TITLE
ModuleNotFoundError when running tests from subfolders

### ISSUE THREAD

**Issue by Artfunkel** [microsoft/PTVS#6048]
**Describe the bug**
Running `unittest` tests from project subfolders is very fragile. It's common to receive the error "ModuleNotFoundError: No module named '[your test module]' when executing.

The following seems to work:
- Test modules in the root of the project
- Test modules in a subfolder, with the same name as the subfolder

Everything else fails.

**Steps to Reproduce**
1. Unzip [TestErrors.zip](https://github.com/microsoft/PTVS/files/4363187/TestErrors.zip) and try to execute tests.

**Expected behavior**
Test methods are executed.

**Additional context and screenshots**
```
    Failed to import test module: tests_foo
    Traceback (most recent call last):
      File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\unittest\loader.py", line 154, in loadTestsFromName
        module = __import__(module_name)
    ModuleNotFoundError: No module named 'tests_foo'
```

**Sample Code**
[TestErrors.zip](https://github.com/microsoft/PTVS/files/4363187/TestErrors.zip)

**Diagnostics file**
[Diagnostic Info 2020-03-21T162604.txt](https://github.com/microsoft/PTVS/files/4363188/Diagnostic.Info.2020-03-21T162604.txt)

**Comment by bschnurr** [comment]
Thank you for the detailed report. 
Try adding  __init__.py in the import and module directories.
Discovery for unittest pattern matches on that https://docs.python.org/3.3/library/unittest.html

**Comment by Artfunkel** [comment]
Thanks, that fixes everything.

But...until recently I was using VS Code, which does not have this requirement. It also isn't at all obvious thing to do, at least for me; the error mentions the .py file, and in project settings I configured a mask to select which individual .py files to run within the folder.

Do you think you could work around this limitation somehow?

**Comment by tiliabell** [comment]
Thanks for the suggestion; it appears that in the project I am working in, there is a `__init__.py` in both the test subdirectory as well as the module subdirectory, but I seem to still have this problem. 

```
ModuleNotFoundError: No module named 'github_info'
```
I have tried importing the module by name, and by `subdirectory.name` and neither way works. 
```
from github_info import TwilioGithub, Branch, Repo
from pe_tools.github_info import TwilioGithub, Branch, Repo
```

**Comment by PeterRusznak** [comment]
To my experience the problem is still exist. 
__init__py
-pp
----__innit__.py
----person.py
-test_pp
----__init__py
----test_person.py

```from pp.person import Person```
throws Error:
```
ModuleNotFoundError: No module named 'pp'
```

**Comment by bschnurr** [comment]
Are you opening the root folder in Vscode?

**Comment by PeterRusznak** [comment]
yes

**Comment by bschnurr** [comment]
please attach the logs from the "Python Language Server" output window

**Comment by PeterRusznak** [comment]
´´´
Traceback (most recent call last):
  File "/home/pr/gyak/unites/test_pp/test_person.py", line 2, in <module>
    from pp.person import Person
ModuleNotFoundError: No module named 'pp'
```

**Comment by bschnurr** [comment]
Oh, sorry, my fault. I was thinking this was VSCode.

you could try adding the pp folder to your search path.

**Comment by svabra** [comment]
> by name, and by `subdirectory.name`

did you fix/workaround this?

**Comment by ryan-hallman** [comment]
This is old but I was dealing with this issue recently and adding this before importing project modules fixed the issue:

    sys.path.append(os.path.dirname(os.path.abspath(__file__)).replace('app/unit_tests',''))
    from app import app, db, config # and whatever other module imports

This is for a project that is structured like this:

project_dir/
--app/
--app/__init__py
----unit_tests/
