### ISSUE TITLE
Visual Studio crashes when typing Python code.

### ISSUE THREAD

**Issue by zhouwangyang** [microsoft/PTVS#6076]
**Steps to Reproduce**
1.Create application project.
2.typing code:
class X:
    def __init__ (self):
        self._Y = 0
        # Typing a period after the "self" fails if X is renamed to Y
        self
3.type a period after the self in the marked spot (self.
4.change the name of the class X to Y 
5.repeat step 3

**Expected behavior**
VS shows intellisense information

**Actual behavior**
vs creashed and error shows below.
![image](https://user-images.githubusercontent.com/39871640/78651378-d8075780-78f2-11ea-9614-8968f33f192b.png)

**Environment**
![image](https://user-images.githubusercontent.com/39871640/78651830-7693b880-78f3-11ea-9237-fdd90ba3dac3.png)

**Comment by zhouwangyang** [comment]
Related to the issue: https://developercommunity.visualstudio.com/content/problem/905681/visual-studio-crashes-when-typing-python-code.html

**Comment by huguesv** [comment]
The exception info was:
```
Exception Info: System.NullReferenceException
   at Microsoft.PythonTools.Intellisense.CompletionAnalysis+<>c.<GetCompletions>b__12_0(Microsoft.Python.LanguageServer.CompletionItem)
   at System.Linq.Enumerable+WhereSelectArrayIterator`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Linq.Buffer`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]..ctor(System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at System.Linq.Enumerable.ToArray[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at Microsoft.PythonTools.Intellisense.CompletionAnalysis.GetCompletions(Microsoft.VisualStudio.Language.Intellisense.IGlyphService)
   at Microsoft.PythonTools.Intellisense.CompletionSource.AugmentCompletionSession(Microsoft.VisualStudio.Language.Intellisense.ICompletionSession, System.Collections.Generic.IList`1<Microsoft.VisualStudio.Language.Intellisense.CompletionSet>)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionSession.Start()
   at Microsoft.PythonTools.Intellisense.IntellisenseController+<TriggerCompletionSession>d__42.MoveNext()
   at Microsoft.PythonTools.Infrastructure.TaskExtensions.ReThrowTaskException(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

```
