### ISSUE TITLE
When debugged a second time, VS loses its response and restarts.

### ISSUE THREAD

**Issue by zhouwangyang** [microsoft/PTVS#6099]
![image](https://user-images.githubusercontent.com/39871640/80357349-73b23500-88ad-11ea-871e-c39aa83e45aa.png)

**Steps to Reproduce**
1.Add unit test test_1.py in python application
2.Typing code in test_1.py
import unittest
class Test_test_1(unittest.TestCase):
    def test_A(self):
        self.assertEqual(1,1)

if __name__ == '__main__':
    unittest.main()
3.Set bk in the code
4.In TE, select the test and right-click to select Debug Selected tests
5.After the first successful debug, debug the current test again.

**Expected behavior**
The test can be debugged successfully

**Actual behavior**
When debugged a second time, VS loses its response and restarts.

**Debug Adapter Host Log**
 ```
1> DebugAdapterHost version: 16.7.40413.2 commit:b7937c15e33a949e648926944d211d657e3684f0
 1> [DebugAdapter] <--   E (output): {"seq": 1, "type": "event", "event": "output", "body": {"category": "telemetry", "output": "ptvsd", "data": {"packageVersion": "1.0.0b5"}}}
 1> [DebugAdapter] --> C (initialize-1): {"type":"request","command":"initialize","arguments":{"pathFormat":"path","clientID":"visualstudio","clientName":"Visual Studio","adapterID":null,"locale":"en-US","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsRunInTerminalRequest":true,"supportsMemoryReferences":true,"supportsProgressReporting":true,"supportsHandshakeRequest":true},"seq":1}
 1> [DebugAdapter] <--   E (output): {"seq": 2, "type": "event", "event": "output", "body": {"category": "telemetry", "output": "debugpy", "data": {"packageVersion": "1.0.0b5"}}}
 1> [DebugAdapter] <--   R (initialize-1) [167 ms]: {"seq": 3, "type": "response", "request_seq": 1, "success": true, "command": "initialize", "body": {"supportsCompletionsRequest": true, "supportsConditionalBreakpoints": true, "supportsConfigurationDoneRequest": true, "supportsDebuggerProperties": true, "supportsDelayedStackTraceLoading": true, "supportsEvaluateForHovers": true, "supportsExceptionInfoRequest": true, "supportsExceptionOptions": true, "supportsHitConditionalBreakpoints": true, "supportsLogPoints": true, "supportsModulesRequest": true, "supportsSetExpression": true, "supportsSetVariable": true, "supportsValueFormattingOptions": true, "supportsTerminateDebuggee": true, "supportsGotoTargetsRequest": true, "exceptionBreakpointFilters": [{"filter": "raised", "label": "Raised Exceptions", "default": false}, {"filter": "uncaught", "label": "Uncaught Exceptions", "default": true}]}}
 1> [DebugAdapter] --> C (attach-2): {"type":"request","command":"attach","arguments":{"host":"localhost","port":52468,"stopOnEntry":true,"promptBeforeRunningWithBuildError":true,"redirectOutput":true,"waitOnAbnormalExit":true,"waitOnNormalExit":true,"breakOnSystemExitZero":false,"debugStdLib":false,"showReturnValue":true,"rules":[{"path":"c:\\program files (x86)\\microsoft visual studio\\2019\\preview\\common7\\ide\\extensions\\microsoft\\python\\core\\","include":false}]},"seq":2}
 1> [DebugAdapter] <--   E (debugpyWaitingForServer): {"seq": 4, "type": "event", "event": "debugpyWaitingForServer", "body": {"host": "127.0.0.1", "port": 52521}}
 1> WARNING: No handler registered for event of type 'debugpyWaitingForServer'!
 1> [DebugAdapter] <--   E (initialized): {"seq": 5, "type": "event", "event": "initialized"}
 1> [DebugAdapter] --> C (debugpySystemInfo-3): {"type":"request","command":"debugpySystemInfo","arguments":{},"seq":3}
 1> [DebugAdapter] <--   R (debugpySystemInfo-3) [16 ms]: {"seq": 6, "type": "response", "request_seq": 3, "success": true, "command": "debugpySystemInfo", "body": {"debugpy": {"version": "1.0.0b5"}, "python": {"version": "3.7.7final0", "implementation": {"name": "cpython", "version": "3.7.7final0", "description": "CPython"}}, "platform": {"name": "win32"}, "process": {"pid": 4668, "ppid": 6728, "executable": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python37_64\\python.exe", "bitness": 64}, "pydevd": {"usingCython": false, "usingFrameEval": false}}}
 1> [DebugAdapter] --> C (setDebuggerProperty-4): {"type":"request","command":"setDebuggerProperty","arguments":{"AllowOutOfProcessSymbols":1},"seq":4}
 1> [DebugAdapter] --> C (setDebuggerProperty-5): {"type":"request","command":"setDebuggerProperty","arguments":{"DisableJITOptimization":0},"seq":5}
 1> [DebugAdapter] --> C (setDebuggerProperty-6): {"type":"request","command":"setDebuggerProperty","arguments":{"EnableFastEvaluate":1},"seq":6}
 1> [DebugAdapter] --> C (setDebuggerProperty-7): {"type":"request","command":"setDebuggerProperty","arguments":{"InterpreterOptions":1},"seq":7}
 1> [DebugAdapter] --> C (setDebuggerProperty-8): {"type":"request","command":"setDebuggerProperty","arguments":{"JustMyCodeStepping":1},"seq":8}
 1> [DebugAdapter] --> C (setDebuggerProperty-9): {"type":"request","command":"setDebuggerProperty","arguments":{"StopOnExceptionCrossingManagedBoundary":0},"seq":9}
 1> [DebugAdapter] --> C (setDebuggerProperty-10): {"type":"request","command":"setDebuggerProperty","arguments":{"WarnIfNoUserCodeOnLaunch":1},"seq":10}
 1> [DebugAdapter] --> C (setDebuggerProperty-11): {"type":"request","command":"setDebuggerProperty","arguments":{"EnableStepFiltering":true},"seq":11}
 1> [DebugAdapter] <--   R (setDebuggerProperty-4) [6 ms]: {"seq": 7, "type": "response", "request_seq": 4, "success": true, "command": "setDebuggerProperty"}
 1> [DebugAdapter] <--   R (setDebuggerProperty-5) [6 ms]: {"seq": 8, "type": "response", "request_seq": 5, "success": true, "command": "setDebuggerProperty"}
 1> [DebugAdapter] <--   R (setDebuggerProperty-6) [6 ms]: {"seq": 9, "type": "response", "request_seq": 6, "success": true, "command": "setDebuggerProperty"}
 1> [DebugAdapter] <--   R (setDebuggerProperty-7) [7 ms]: {"seq": 10, "type": "response", "request_seq": 7, "success": true, "command": "setDebuggerProperty"}
 1> [DebugAdapter] <--   R (setDebuggerProperty-8) [7 ms]: {"seq": 11, "type": "response", "request_seq": 8, "success": true, "command": "setDebuggerProperty"}
 1> [DebugAdapter] <--   R (setDebuggerProperty-9) [8 ms]: {"seq": 12, "type": "response", "request_seq": 9, "success": true, "command": "setDebuggerProperty"}
 1> [DebugAdapter] <--   R (setDebuggerProperty-10) [9 ms]: {"seq": 13, "type": "response", "request_seq": 10, "success": true, "command": "setDebuggerProperty"}
 1> [DebugAdapter] <--   R (setDebuggerProperty-11) [10 ms]: {"seq": 14, "type": "response", "request_seq": 11, "success": true, "command": "setDebuggerProperty"}
 1> [DebugAdapter] --> C (setBreakpoints-12): {"type":"request","command":"setBreakpoints","arguments":{"source":{"path":"c:\\Users\\vwazho\\source\\repos\\PythonApplication1\\PythonApplication1\\Test_a\\test_ut.py","sources":[],"checksums":[]},"breakpoints":[{"line":8,"column":1}],"lines":[8]},"seq":12}
 1> [DebugAdapter] --> C (setBreakpoints-13): {"type":"request","command":"setBreakpoints","arguments":{"source":{"path":"c:\\Users\\vwazho\\source\\repos\\PythonApplication1\\PythonApplication1\\Test_a\\test_pta.py","sources":[],"checksums":[]},"breakpoints":[{"line":5,"column":1}],"lines":[5]},"seq":13}
 1> [DebugAdapter] --> C (setBreakpoints-14): {"type":"request","command":"setBreakpoints","arguments":{"source":{"path":"c:\\Users\\vwazho\\source\\repos\\PythonApplication1\\PythonApplication1\\test_1.py","sources":[],"checksums":[]},"breakpoints":[{"line":5,"column":1}],"lines":[5]},"seq":14}
 1> [DebugAdapter] <--   R (setBreakpoints-12) [35 ms]: {"seq": 15, "type": "response", "request_seq": 12, "success": true, "command": "setBreakpoints", "body": {"breakpoints": [{"verified": true, "id": 0, "source": {"path": "c:\\Users\\vwazho\\source\\repos\\PythonApplication1\\PythonApplication1\\Test_a\\test_ut.py", "sources": [], "checksums": []}, "line": 8}]}}
 1> [DebugAdapter] <--   R (setBreakpoints-13) [28 ms]: {"seq": 16, "type": "response", "request_seq": 13, "success": true, "command": "setBreakpoints", "body": {"breakpoints": [{"verified": true, "id": 1, "source": {"path": "c:\\Users\\vwazho\\source\\repos\\PythonApplication1\\PythonApplication1\\Test_a\\test_pta.py", "sources": [], "checksums": []}, "line": 5}]}}
 1> [DebugAdapter] <--   R (setBreakpoints-14) [29 ms]: {"seq": 17, "type": "response", "request_seq": 14, "success": true, "command": "setBreakpoints", "body": {"breakpoints": [{"verified": true, "id": 2, "source": {"path": "c:\\Users\\vwazho\\source\\repos\\PythonApplication1\\PythonApplication1\\test_1.py", "sources": [], "checksums": []}, "line": 5}]}}
 1> [DebugAdapter] --> C (setExceptionBreakpoints-15): {"type":"request","command":"setExceptionBreakpoints","arguments":{"filters":[],"exceptionOptions":[{"breakMode":"userUnhandled","path":[{"names":["Python Exceptions"]}]},{"breakMode":"unhandled","path":[{"names":["Python Exceptions"]},{"names":["GeneratorExit","IndexError","StopIteration","AttributeError","KeyError"]}]}]},"seq":15}
 1> [DebugAdapter] <--   R (setExceptionBreakpoints-15) [20 ms]: {"seq": 18, "type": "response", "request_seq": 15, "success": true, "command": "setExceptionBreakpoints"}
 1> [DebugAdapter] --> C (configurationDone-16): {"type":"request","command":"configurationDone","arguments":{},"seq":16}
 1> [DebugAdapter] <--   R (configurationDone-16) [5 ms]: {"seq": 19, "type": "response", "request_seq": 16, "success": true, "command": "configurationDone"}
 1> [DebugAdapter] <--   R (attach-2) [376 ms]: {"seq": 20, "type": "response", "request_seq": 2, "success": true, "command": "attach"}
 1> [DebugAdapter] <--   E (process): {"seq": 21, "type": "event", "event": "process", "body": {"name": "C:\\PROGRAM FILES (X86)\\MICROSOFT VISUAL STUDIO\\2019\\PREVIEW\\COMMON7\\IDE\\EXTENSIONS\\MICROSOFT\\PYTHON\\CORE\\testlauncher.py", "systemProcessId": 4668, "isLocalProcess": true, "startMethod": "attach"}}
 1> [DebugAdapter] <--   E (thread): {"seq": 22, "type": "event", "event": "thread", "body": {"reason": "started", "threadId": 1}}
 1> [DebugAdapter] <--   E (output): {"seq": 23, "type": "event", "event": "output", "body": {"output": "============================= test session starts =============================", "category": "stdout", "source": {}}}
 1> [DebugAdapter] <--   E (output): {"seq": 24, "type": "event", "event": "output", "body": {"output": "\n", "category": "stdout", "source": {}}}
 1> [DebugAdapter] <--   E (output): {"seq": 25, "type": "event", "event": "output", "body": {"output": "platform win32 -- Python 3.7.7, pytest-5.4.1, py-1.8.1, pluggy-0.13.1", "category": "stdout", "source": {}}}
 1> [DebugAdapter] <--   E (output): {"seq": 26, "type": "event", "event": "output", "body": {"output": "\n", "category": "stdout", "source": {}}}
 1> [DebugAdapter] <--   E (output): {"seq": 27, "type": "event", "event": "output", "body": {"output": "rootdir: C:\\Users\\vwazho\\source\\repos\\PythonApplication1\\PythonApplication1", "category": "stdout", "source": {}}}
 1> [DebugAdapter] <--   E (output): {"seq": 28, "type": "event", "event": "output", "body": {"output": "\n", "category": "stdout", "source": {}}}
 1> [DebugAdapter] <--   E (output): {"seq": 29, "type": "event", "event": "output", "body": {"output": "collected 1 item", "category": "stdout", "source": {}}}
 1> [DebugAdapter] <--   E (output): {"seq": 30, "type": "event", "event": "output", "body": {"output": "\n", "category": "stdout", "source": {}}}
 1> [DebugAdapter] <--   E (output): {"seq": 31, "type": "event", "event": "output", "body": {"output": "\n", "category": "stdout", "source": {}}}
 1> [DebugAdapter] <--   E (output): {"seq": 32, "type": "event", "event": "output", "body": {"output": "test_1.py ", "category": "stdout", "source": {}}}
 1> [DebugAdapter] <--   E (stopped): {"seq": 33, "type": "event", "event": "stopped", "body": {"reason": "breakpoint", "threadId": 1, "preserveFocusHint": false, "allThreadsStopped": true}}
 1> [DebugAdapter] --> C (threads-17): {"type":"request","command":"threads","arguments":{},"seq":17}
 1> [DebugAdapter] <--   R (threads-17) [3 ms]: {"seq": 34, "type": "response", "request_seq": 17, "success": true, "command": "threads", "body": {"threads": [{"id": 1, "name": "MainThread"}]}}
 1> [DebugAdapter] --> C (stackTrace-18): {"type":"request","command":"stackTrace","arguments":{"threadId":1,"startFrame":0,"levels":1,"format":{"includeAll":true}},"seq":18}
 1> [DebugAdapter] <--   R (stackTrace-18) [18 ms]: {"seq": 35, "type": "response", "request_seq": 18, "success": true, "command": "stackTrace", "body": {"stackFrames": [{"id": 2, "name": "test_A", "line": 5, "column": 1, "source": {"path": "C:\\Users\\vwazho\\source\\repos\\PythonApplication1\\PythonApplication1\\test_1.py", "sourceReference": 0}}], "totalFrames": 1}}
 1> [DebugAdapter] <--   E (module): {"seq": 36, "type": "event", "event": "module", "body": {"reason": "new", "module": {"id": 0, "name": "test_1", "path": "C:\\Users\\vwazho\\source\\repos\\PythonApplication1\\PythonApplication1\\test_1.py"}}}
 1> [DebugAdapter] --> C (stackTrace-19): {"type":"request","command":"stackTrace","arguments":{"threadId":1,"startFrame":0,"levels":1000,"format":{"parameters":true,"parameterTypes":true,"parameterNames":true,"line":true,"module":true}},"seq":19}
 1> [DebugAdapter] <--   E (module): {"seq": 37, "type": "event", "event": "module", "body": {"reason": "new", "module": {"id": 1, "name": "_pytest.python", "path": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python37_64\\Lib\\site-packages\\_pytest\\python.py", "package": "_pytest"}}}
 1> [DebugAdapter] <--   E (module): {"seq": 38, "type": "event", "event": "module", "body": {"reason": "new", "module": {"id": 2, "name": "pluggy.callers", "path": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python37_64\\Lib\\site-packages\\pluggy\\callers.py", "package": "pluggy"}}}
 1> [DebugAdapter] <--   E (module): {"seq": 39, "type": "event", "event": "module", "body": {"reason": "new", "module": {"id": 3, "name": "pluggy.manager", "path": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python37_64\\Lib\\site-packages\\pluggy\\manager.py", "package": "pluggy"}}}
 1> [DebugAdapter] <--   E (module): {"seq": 40, "type": "event", "event": "module", "body": {"reason": "new", "module": {"id": 4, "name": "pluggy.hooks", "path": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python37_64\\Lib\\site-packages\\pluggy\\hooks.py", "package": "pluggy"}}}
 1> [DebugAdapter] <--   E (module): {"seq": 41, "type": "event", "event": "module", "body": {"reason": "new", "module": {"id": 5, "name": "_pytest.unittest", "path": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python37_64\\Lib\\site-packages\\_pytest\\unittest.py", "package": "_pytest"}}}
 1> [DebugAdapter] <--   E (module): {"seq": 42, "type": "event", "event": "module", "body": {"reason": "new", "module": {"id": 6, "name": "unittest.case", "path": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python37_64\\Lib\\unittest\\case.py", "package": "unittest"}}}
 1> [DebugAdapter] <--   E (module): {"seq": 43, "type": "event", "event": "module", "body": {"reason": "new", "module": {"id": 7, "name": "_pytest.runner", "path": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python37_64\\Lib\\site-packages\\_pytest\\runner.py", "package": "_pytest"}}}
 1> [DebugAdapter] <--   E (module): {"seq": 44, "type": "event", "event": "module", "body": {"reason": "new", "module": {"id": 8, "name": "_pytest.main", "path": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python37_64\\Lib\\site-packages\\_pytest\\main.py", "package": "_pytest"}}}
 1> [DebugAdapter] <--   E (module): {"seq": 45, "type": "event", "event": "module", "body": {"reason": "new", "module": {"id": 9, "name": "_pytest.config", "path": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python37_64\\Lib\\site-packages\\_pytest\\config\\__init__.py", "package": "_pytest.config"}}}
 1> [DebugAdapter] <--   E (module): {"seq": 46, "type": "event", "event": "module", "body": {"reason": "new", "module": {"id": 10, "name": "__main__", "path": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Preview\\Common7\\IDE\\Extensions\\Microsoft\\Python\\Core\\testlauncher.py", "package": "None"}}}
 1> [DebugAdapter] <--   R (stackTrace-19) [7 ms]: {"seq": 47, "type": "response", "request_seq": 19, "success": true, "command": "stackTrace", "body": {"stackFrames": [{"id": 2, "name": "test_1.test_A : 5", "line": 5, "column": 1, "source": {"path": "C:\\Users\\vwazho\\source\\repos\\PythonApplication1\\PythonApplication1\\test_1.py", "sourceReference": 0}}], "totalFrames": 1}}
 1> [DebugAdapter] --> C (stackTrace-20): {"type":"request","command":"stackTrace","arguments":{"threadId":1,"startFrame":0,"levels":1,"format":{"includeAll":true}},"seq":20}
 1> [DebugAdapter] <--   R (stackTrace-20) [2 ms]: {"seq": 48, "type": "response", "request_seq": 20, "success": true, "command": "stackTrace", "body": {"stackFrames": [{"id": 2, "name": "test_A", "line": 5, "column": 1, "source": {"path": "C:\\Users\\vwazho\\source\\repos\\PythonApplication1\\PythonApplication1\\test_1.py", "sourceReference": 0}}], "totalFrames": 1}}
 1> [DebugAdapter] --> C (evaluate-21): {"type":"request","command":"evaluate","arguments":{"context":"hover","expression":"test_A","frameId":2,"noSideEffects":true,"timeout":5000},"seq":21}
 1> [DebugAdapter] --> C (evaluate-22): {"type":"request","command":"evaluate","arguments":{"context":"hover","expression":"Test_test_1","frameId":2,"noSideEffects":true,"timeout":5000},"seq":22}
 1> [DebugAdapter] --> C (evaluate-23): {"type":"request","command":"evaluate","arguments":{"context":"hover","expression":"unittest.TestCase","frameId":2,"noSideEffects":true,"timeout":5000},"seq":23}
 1> [DebugAdapter] <--   R (evaluate-21) [42 ms]: {"seq": 49, "type": "response", "request_seq": 21, "success": false, "command": "evaluate", "message": "Exception occurred during evaluation."}
 1> [DebugAdapter] <--   R (evaluate-22) [45 ms]: {"seq": 50, "type": "response", "request_seq": 22, "success": true, "command": "evaluate", "body": {"result": "<class 'test_1.Test_test_1'>", "variablesReference": 3, "type": "type", "presentationHint": {}}}
 1> [DebugAdapter] <--   R (evaluate-23) [32 ms]: {"seq": 51, "type": "response", "request_seq": 23, "success": true, "command": "evaluate", "body": {"result": "<class 'unittest.case.TestCase'>", "variablesReference": 4, "type": "type", "presentationHint": {}}}
 1> [DebugAdapter] --> C (next-24): {"type":"request","command":"next","arguments":{"threadId":1},"seq":24}
 1> [DebugAdapter] <--   R (next-24) [4 ms]: {"seq": 52, "type": "response", "request_seq": 24, "success": true, "command": "next"}
 1> [DebugAdapter] <--   E (output): {"seq": 53, "type": "event", "event": "output", "body": {"output": ".", "category": "stdout", "source": {}}}
 1> [DebugAdapter] <--   E (output): {"seq": 54, "type": "event", "event": "output", "body": {"output": "                                                              [100%]", "category": "stdout", "source": {}}}
 1> [DebugAdapter] <--   E (output): {"seq": 55, "type": "event", "event": "output", "body": {"output": "\n", "category": "stdout", "source": {}}}
 1> [DebugAdapter] <--   E (output): {"seq": 56, "type": "event", "event": "output", "body": {"output": "\n", "category": "stdout", "source": {}}}
 1> [DebugAdapter] <--   E (output): {"seq": 57, "type": "event", "event": "output", "body": {"output": "- generated xml file: C:\\Users\\vwazho\\source\\repos\\PythonApplication1\\TestResults\\junitresults_96063626-8e02-4a76-b063-c1d220785f39.xml -", "category": "stdout", "source": {}}}
 1> [DebugAdapter] <--   E (output): {"seq": 58, "type": "event", "event": "output", "body": {"output": "\n", "category": "stdout", "source": {}}}
 1> [DebugAdapter] <--   E (output): {"seq": 59, "type": "event", "event": "output", "body": {"output": "============================== 1 passed in 1.43s ==============================", "category": "stdout", "source": {}}}
 1> [DebugAdapter] <--   E (output): {"seq": 60, "type": "event", "event": "output", "body": {"output": "\n", "category": "stdout", "source": {}}}
 1> [DebugAdapter] <--   E (thread): {"seq": 61, "type": "event", "event": "thread", "body": {"reason": "exited", "threadId": 1}}
 1> [DebugAdapter] <--   E (terminated): {"seq": 62, "type": "event", "event": "terminated"}
 1> [DebugAdapter] --> C (disconnect-25): {"type":"request","command":"disconnect","arguments":{},"seq":25}
 1> [DebugAdapter] <--   R (disconnect-25) [6 ms]: {"seq": 63, "type": "response", "request_seq": 25, "success": true, "command": "disconnect"}
 1> Debug adapter process exited.
 1> WARNING: Stopping due to fatal error: AggregateException: One or more errors occurred.
 1> ERROR: Unexpected error

AggregateException: One or more errors occurred.

System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
System.Threading.Tasks.Task`1.get_Result()
Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.Protocol.DebugProtocol.ReaderThreadProc()

Aggregate exception: 
    IOException: Unable to read data from the transport connection: A blocking operation was interrupted by a call to WSACancelBlockingCall.
    Inner Exception: 
        SocketException: A blocking operation was interrupted by a call to WSACancelBlockingCall
Inner Exception: 
    IOException: Unable to read data from the transport connection: A blocking operation was interrupted by a call to WSACancelBlockingCall.

System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
Microsoft.PythonTools.Debugger.DebugRemoteAdapterProcessStream.Read(Byte[] buffer, Int32 offset, Int32 count)
System.IO.Stream.<>c.<BeginReadInternal>b__39_0(Object <p0>)
System.Threading.Tasks.Task`1.InnerInvoke()
System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.IO.Stream.EndRead(IAsyncResult asyncResult)
System.IO.Stream.<>c.<BeginEndReadAsync>b__43_1(Stream stream, IAsyncResult asyncResult)
System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
    Inner Exception: 
        SocketException: A blocking operation was interrupted by a call to WSACancelBlockingCall

System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)

 1> ERROR: One or more errors occurred.

Unable to read data from the transport connection: A blocking operation was interrupted by a call to WSACancelBlockingCall.

A blocking operation was interrupted by a call to WSACancelBlockingCall
 1> ERROR: Exception while reporting error.

NullReferenceException: Object reference not set to an instance of an object.

Microsoft.VisualStudio.Debugger.VSCodeDebuggerHost.AD7.Implementation.EngineCallback.Send(IAD7DebugEvent eventObject, IDebugThread2 thread)
Microsoft.VisualStudio.Debugger.VSCodeDebuggerHost.AD7.Implementation.EngineCallback.OnError(String errorMessage)


```

**Comment by huguesv** [comment]
I see a hang and sometimes a crash, at the end of the first debug. Happens with legacy and debugpy.

Error in event log:
```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Microsoft.VisualStudio.TestWindow.Internal.UI.EventProcessor+TestSelection+<>c.<get_HasGroupSelection>b__13_0(Microsoft.VisualStudio.TestWindow.Messages.ITestNode)
   at System.Linq.Enumerable.Any[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>, System.Func`2<System.__Canon,Boolean>)
   at Microsoft.VisualStudio.TestWindow.Internal.UI.EventProcessor+TestSelection.get_HasGroupSelection()
   at Microsoft.VisualStudio.TestWindow.Internal.UI.EventProcessor+TestSelection.get_HasSingleTestSelection()
   at Microsoft.VisualStudio.TestWindow.Internal.Commands.SelectionCommands.OnQueryGoToTest(System.ComponentModel.Design.MenuCommand)
   at Microsoft.VisualStudio.TestWindow.VsHost.ObservableMenuCommand.OnQueryStatus(System.Object, System.EventArgs)
   at Microsoft.VisualStudio.TestWindow.VsHost.ObservableMenuCommand.ForceQueryStatus()
   at Microsoft.VisualStudio.TestWindow.Controller.MenuCommandContainer.ForceQueryStatus()
   at Microsoft.VisualStudio.TestWindow.Internal.Commands.SelectionCommands.OnSelectionChanged(System.Object, System.EventArgs)
   at Microsoft.VisualStudio.TestWindow.Internal.TestWindowViewModel.QueueDetailsUpdate()
   at Microsoft.VisualStudio.TestWindow.Internal.TestWindowViewModel.OnSelectionChanged(System.Object, System.EventArgs)
   at Microsoft.VisualStudio.TestWindow.Internal.UI.EventProcessor+TestSelection.UpdateSelectionOnIdle()
   at Microsoft.VisualStudio.TestWindow.Internal.UI.EventProcessor+TestSelection.OnTableControlLoaded(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(System.Windows.DependencyObject, System.Windows.RoutedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(System.Object)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(System.Object)
   at System.Windows.Media.MediaContext.RenderMessageHandler(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)


```

**Comment by huguesv** [comment]
For the error I'm getting (call stack from error log above), this is internal bug 1109718

**Comment by zhouwangyang** [comment]
Works now in 16.7.0 Preview 2.0 [30105.175.master]
