### ISSUE TITLE
System.ObjectDisposedException occured after reopen folder in workspace.

### ISSUE THREAD

**Issue by zhouwangyang** [microsoft/PTVS#6128]
**Steps to Reproduce**
1.Open Folder in vs
2.Right click ->add new item->python->Empty Module, rename as test_1.py
3.Typing test code in test_1.py
4.Enable unittest 
5.test_a can be found in TE at this time, no error in Output-> Tests tab, and the click File->close folder and reopen this folder.

**Expected behavior**
test_1 should be found in TE with no error

**Actual behavior**
test_1 could not be found, and error occurred.

**Output->Tests log**
```
Log level is set to Informational (Default).
Test data store opened in 0.053 sec.
---------- Starting test discovery ----------
Starting unittest discovery for the New folder (5) workspace. This can take up to 60 seconds.
cd C:\Users\vwazho\Downloads\New folder (5)
set PYTHONPATH=C:\Users\vwazho\Downloads\New folder (5)\
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\python.exe C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\PREVIEW\COMMON7\IDE\EXTENSIONS\MICROSOFT\PYTHON\CORE\PythonFiles\testing_tools\run_adapter.py discover unittest --output-file C:\Users\vwazho\AppData\Local\Temp\tmp2D9C.tmp -- . test*.py
========== Test discovery finished: 2 Tests found in 3.6 sec ==========
System.ObjectDisposedException: The CancellationTokenSource has been disposed.
   at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
   at Microsoft.VisualStudio.TestWindow.Internal.TestWindowViewModel.CancelOrStopProgressBarSpinning()
   at Microsoft.VisualStudio.TestWindow.Internal.TestWindowViewModel.<<OnStateChanged>b__80_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Extensibility.ILoggerExtensions.<CallWithCatchAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
System.InvalidOperationException: Failed to perform operation, the store is closed.
   at Microsoft.VisualStudio.TestWindow.Host.TestWindowStoreService.ThrowOnClosedStore()
   at Microsoft.VisualStudio.TestWindow.Host.TestWindowStoreService.<>c__DisplayClass25_0.<RemoveViewAsync>b__0()
   at Microsoft.VisualStudio.TestWindow.Extensibility.ILoggerExtensions.<CallWithCatchAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
System.InvalidOperationException: Failed to perform operation, the store is closed.
   at Microsoft.VisualStudio.TestWindow.Host.TestWindowStoreService.ThrowOnClosedStore()
   at Microsoft.VisualStudio.TestWindow.Host.TestWindowStoreService.<>c__DisplayClass25_0.<RemoveViewAsync>b__0()
   at Microsoft.VisualStudio.TestWindow.Extensibility.ILoggerExtensions.<CallWithCatchAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
Test data store opened in 0.030 sec.
---------- Starting test discovery ----------
========== Test discovery finished: 0 Tests found in 4.6 sec ==========
```
![image](https://user-images.githubusercontent.com/39871640/83506605-fc01a680-a4f9-11ea-80b4-1f4f6b44d1cf.png)

**build info**
![image](https://user-images.githubusercontent.com/39871640/83506573-f015e480-a4f9-11ea-9384-081d28b1a0f8.png)

**Comment by huguesv** [comment]
Filed internal bug 1134815
