### ISSUE TITLE
InvalidOperationException happened when open a new folder in an opened project.

### ISSUE THREAD

**Issue by zhouwangyang** [microsoft/PTVS#6129]
**Steps to Reproduce**
1.Create a python app project and open Test Exploer
2.Click File->Open->Folder in the opening project window.
3.The new Folder can be opened with no errors.

**Expected behavior**
The new Folder can be opened with no errors.

**Actual behavior**
folder can be opened but errors in output->tests tab
```
Log level is set to Informational (Default).
Test data store opened in 0.122 sec.
System.InvalidOperationException: Failed to perform operation, the store is closed.
   at Microsoft.VisualStudio.TestWindow.Host.TestWindowStoreService.ThrowOnClosedStore()
   at Microsoft.VisualStudio.TestWindow.Host.TestWindowStoreService.<>c__DisplayClass25_0.<RemoveViewAsync>b__0()
   at Microsoft.VisualStudio.TestWindow.Extensibility.ILoggerExtensions.<CallWithCatchAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
Test data store opened in 0.000 sec.
```

**build**
![image](https://user-images.githubusercontent.com/39871640/83507994-e2f9f500-a4fb-11ea-9d1c-a41d3c24692c.png)

**Comment by huguesv** [comment]
Internal bug 1134815

**Comment by judej** [comment]
This has been fixed. Please reopen if this is still a problem
