### ISSUE TITLE
Python project - publish button crash

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6142]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1062419/python-project-publish-button-crash.html)._

---
<p>When i click publish button in project settings - Visual studio crashed</p><p><a href="https://developercommunity.visualstudio.com/storage/attachments/139440-screenshot-8.png"> Image:139440-screenshot-8.png</a></p><p><a href="https://developercommunity.visualstudio.com/storage/attachments/139451-vs-python-crash.gif"> Image:139451-vs-python-crash.gif</a></p><p></p>

---
#### Visual Studio Feedback System on 6/3/2020, 04:54 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by huguesv** [comment]
Thanks for the feedback.

It looks like it only works with an absolute path right now.

If I try to use a relative path, this is the exception:
```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
An unhandled exception is about to terminate the process:

This operation is not supported for a relative URI.

System.InvalidOperationException: This operation is not supported for a relative URI.

   at System.Uri.get_Scheme()

   at Microsoft.VisualStudioTools.Project.CommonProjectNode.Publish(PublishProjectOptions publishOptions, Boolean async) in C:\Projects\GitHub\huguesv\PTVS\Common\Product\SharedProject\CommonProjectNode.cs:line 355

   at Microsoft.PythonTools.Project.PythonProjectNode.Publish(PublishProjectOptions publishOptions, Boolean async) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Project\PythonProjectNode.cs:line 2087

   at Microsoft.PythonTools.Project.PublishPropertyControl._pubNowButton_Click(Object sender, EventArgs e) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Project\PublishPropertyControl.cs:line 74

   at System.Windows.Forms.Control.OnClick(EventArgs e)

   at System.Windows.Forms.Button.OnClick(EventArgs e)

   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)

   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)

   at System.Windows.Forms.Control.WndProc(Message& m)

   at System.Windows.Forms.ButtonBase.WndProc(Message& m)

   at System.Windows.Forms.Button.WndProc(Message& m)

   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)

   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)

   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

   at Microsoft.VisualStudioTools.CommonPackage.<>c.<.ctor>b__9_0(Object sender, UnhandledExceptionEventArgs e) in C:\Projects\GitHub\huguesv\PTVS\Common\Product\SharedProject\CommonPackage.cs:line 67

   at System.Uri.get_Scheme()

   at Microsoft.VisualStudioTools.Project.CommonProjectNode.Publish(PublishProjectOptions publishOptions, Boolean async) in C:\Projects\GitHub\huguesv\PTVS\Common\Product\SharedProject\CommonProjectNode.cs:line 355

   at Microsoft.PythonTools.Project.PythonProjectNode.Publish(PublishProjectOptions publishOptions, Boolean async) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Project\PythonProjectNode.cs:line 2087

   at Microsoft.PythonTools.Project.PublishPropertyControl._pubNowButton_Click(Object sender, EventArgs e) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Project\PublishPropertyControl.cs:line 74

   at System.Windows.Forms.Control.OnClick(EventArgs e)

   at System.Windows.Forms.Button.OnClick(EventArgs e)

   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)

   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)

   at System.Windows.Forms.Control.WndProc(Message& m)

   at System.Windows.Forms.ButtonBase.WndProc(Message& m)

   at System.Windows.Forms.Button.WndProc(Message& m)

   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)

   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)

   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


---------------------------
Abort   Retry   Ignore   
---------------------------
```
