### ISSUE TITLE
LSC: Pylance initialization fails due to LSP deserialization exception

### ISSUE THREAD

**Issue by huguesv** [microsoft/PTVS#6171]
VS protocol assembly is not aware of WorkDoneProgressOptions in general. Some of the ServerCapabilities fields need to handle both bool and an Options type.
```
Newtonsoft.Json.JsonReaderException: Error reading boolean. Unexpected token: StartObject. Path 'result.capabilities.definitionProvider', line 1, position 93.

   at Newtonsoft.Json.JsonReader.ReadAsBoolean()

   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)

   at Newtonsoft.Json.Serialization.JsonSerializerProxy.DeserializeInternal(JsonReader reader, Type objectType)

   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)

   at Microsoft.VisualStudio.LanguageServer.Protocol.VSExtensionConverter`2.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)

   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)

   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)

   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)

   at StreamJsonRpc.JsonMessageFormatter.JsonRpcResult.GetResult[T]()

   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__118`1.MoveNext()

--- End of stack trace from previous location where exception was thrown ---
```

internal issue 1155697

**Comment by huguesv** [comment]
We are now tracking this task in our internal Pylance Azure DevOps.
