### ISSUE TITLE
An unexpected error occurred

### ISSUE THREAD

**Issue by araud** [microsoft/PTVS#6204]
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 16.7.20181.2

System.ArgumentException: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
   at EnvDTE.ConfigurationManager.get_ActiveConfiguration()
   at Microsoft.PythonTools.Project.PythonProjectNode.SetCurrentConfiguration()
   at Microsoft.VisualStudioTools.Project.ProjectNode.GetMsBuildProperty(String propertyName, Boolean resetCache)
   at Microsoft.VisualStudioTools.Project.ProjectNode.GetProjectProperty(String propertyName, Boolean resetCache)
   at Microsoft.PythonTools.Project.CondaEnvCreateProjectInfoBar.<CheckAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Project.PythonProjectNode.<TriggerInfoBarsAsync>d__106.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by huguesv** [comment]
Thanks for the report. We haven't been able to reproduce it so far. I wonder if you have a consistent repro for it?

**Comment by araud** [comment]
If the stack is not enough, I am afraid I can't share more, as this is Intel's solution. The work on minimizing and abstracting the reproducer won't be prioritised... Seems like I will be just trying to reinstall it from scratch. You can close it.

**Comment by jpribele** [comment]
I can reproduce this fairly consistency

**Comment by huguesv** [comment]
FYI this code path can be eliminated by disabling the notification bars:
![image](https://user-images.githubusercontent.com/1696845/91345285-fbdd1400-e793-11ea-9b5d-8c9a677d86cd.png)

@jpribele does your .pyproj have any changes (compared to the default project template), when it comes to configuration definitions?

**Comment by jpribele** [comment]
Yes. I've been messy around with it to figure out if those changes are the cause. 
Changing those settings did not work btw
