### ISSUE TITLE
wont run adafruit Clue Spirit Level

### ISSUE THREAD

**Issue by soky** [microsoft/PTVS#6242]
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[V] Show details  [Close]

[Expanded Information]
```
Build: 15.9.18254.1

System.NotSupportedException: Debugging is not supported for Python 2.5 and earlier.
   at Microsoft.PythonTools.Debugger.DebugLaunchHelper.CreateDebugTargetInfo(IServiceProvider provider, LaunchConfiguration config)
   at Microsoft.PythonTools.Project.DefaultPythonLauncher.StartWithDebugger(LaunchConfiguration config)
   at Microsoft.PythonTools.Project.DefaultPythonLauncher.Launch(LaunchConfiguration config, Boolean debug)
   at Microsoft.PythonTools.Project.DefaultPythonLauncher.LaunchFile(String file, Boolean debug)
   at Microsoft.PythonTools.PythonToolsPackage.LaunchFile(IServiceProvider provider, String filename, Boolean debug, Boolean saveDirtyFiles)
   at Microsoft.PythonTools.Language.EditFilter.ExecWorker(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.PythonTools.Language.EditFilter.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```**Describe the bug**
[A clear and concise description of the bug]

**Steps to Reproduce**
1.
2.
3.

**Expected behavior**
[A clear and concise description of your expectation]

**Additional context and screenshots**
[Add any other information such as screenshots, error message, or stack trace]

**Sample Code**
```
XXX
```

**Configuration information (If you are providing a diagnostics file (see below), skip this section)**
VS Version: [Can be found under "Help->About Microsoft Visual Studio"]
PTVS version: [Can be found under "Help->About Microsoft Visual Studio->Installed products"]
Python version:
Debugger Type (if applicable): [New debugger or legacy debugger?]

**Diagnostics file**
The diagnostics file contains information such as the Python version, environments, loaded assemblies, configuration options, etc. This file makes it easier for us to reproduce and fix bugs, so we would really appreciate it if you could provide it to us. This file can be generated by going to Tools->Options->Python->Diagnostics.
You can attach the file to this issue or email it to us at ptvshelp@microsoft.com. If you email it, please add a link to this issue.
```
XXX
```

**Comment by huguesv** [comment]
What's the actual version of Python? This is likely a case where it does not recognize the version and defaults it to 0.0, leading to that "2.5 and earlier" error.

VS 2019 16.8 will recognize newer versions of Python: https://github.com/microsoft/PTVS/issues/6049

**Comment by r-pankevicius** [comment]
@huguesv  Do you mean that "System.NotSupportedException: Debugging is not supported for Python 2.5 and earlier." may appear in "newer versions of Python"?

I don't see any relation to #6049 here....

Maybe just a misleading error message?

**Comment by huguesv** [comment]
Correct, that message will appear with newer versions of Python, because newer versions of Python are detected as 0.0 "unknown", and 0.0 < 2.5. I mentioned a workaround in #6049 for this.

**Comment by soky** [comment]
I tried Python 3.7 and 3.85 with no luck

**Comment by huguesv** [comment]
3.8 version cannot be detected properly by VS 2017, the only way to use that one would be to add a custom environment via the Python environments tool window and set the version manually to 3.6.

I would have expected 3.7 to be detected correctly, if it's the standard Python 3.7 from python.org. You could try to add it as a custom env as well and see if that helps.

VS 2017 officially only supports up to Python 3.6.
