### ISSUE TITLE
Team Explorer Work Items Not Connecting to Azure DevOps (TFS)

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6250]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1171948/team-explorer-work-items-not-connecting-to-azure-d.html)._

---
I was trying to create a python script to automatically check-in our standard "directory" structure and merge in some standard libraries. I am pretty sure in doing this I broke something and have not been able to fix it. Note, Team Explorer was working at one point. I have done the obvious things of restarting my computer, uninstalling and installing VS2019 several times. I do have access to the "project" and Azure DevOps via a webpage.

When I do get into Team Explorer, and go through Manage Connections and try to add the Azure DevOps server, the server comes up with the correct port and tfs (http://<server>:8080/tfs). However, when I add it and click on it (or double click) the list of "projects" does not show up.

When I start VS2019 on a Windows 10 machine I sometimes get the first attached error window (VS2019_WorkItemTracking_Erorr.png).
I continue on into VS and try and open the Team Explorer and I get another error window (VS2019_WindowSearch_Error.png).
And I get this error in the Output Window.

**TF205020: Could not connect to server ‘<server>\<project>’. This server was used in your last session, but it might be offline or unreachable. Confirm that the server is available on the network. To attempt to connect again, or to a different server, click ‘Connect To Azure DevOps Server’ in Team Explorer or the Team menu.

The server returned the following error: Method not found: 'Void Microsoft.TeamFoundation.Client.ProjectSettings.TpcSettingsStore.InitializeSettingsCache()'.**

I hit OK. Team Explorer does not open. I try again and get the following exception in the Team Explorer Window.

**An exception was encountered while constructing the content of this frame.  This information is also logged in "C:\Users\<username>\AppData\Roaming\Microsoft\VisualStudio\16.0_2025f24c\ActivityLog.xml".

Exception details:
System.InvalidOperationException: The window search was not yet setup for this search host.
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowSearchHost.ThrowIfSearchNotSetup()
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowSearchHost.set_HelpTopic(String value)
   at Microsoft.VisualStudio.TeamFoundation.TeamExplorer.ToolWindowTeamExplorer.OnToolWindowCreated()
   at Microsoft.VisualStudio.Shell.Package.HandleToolWindowCreation(ToolWindowCreationResult result, Int32 id, Guid persistenceGuid, IVsWindowFrame frame)
   at Microsoft.VisualStudio.Shell.Package.<>c__DisplayClass81_0. <CreateToolWindow>g__CreateToolWindowWorker|1()
   at Microsoft.VisualStudio.Shell.Package.CreateToolWindow(Type toolWindowType, Int32 id, UInt32 flags, Object context, Guid persistenceGuid)
   at Microsoft.VisualStudio.Shell.Package.<>c__DisplayClass91_1. <<FindToolWindow>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask. <JoinAsync>d__68.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask`1. <JoinAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Shell.Package.<>c__DisplayClass91_0. <<FindToolWindow>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Shell.ToolWindowCollection.ToolWindowListener.<>c__DisplayClass1_0. <<-ctor>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.AwaitExtensions.ExecuteContinuationSynchronouslyAwaiter`1.GetResult()
   at Microsoft.VisualStudio.Threading.AsyncLazy`1.<>c__DisplayClass13_0. <<GetValueAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at Microsoft.VisualStudio.Threading.AsyncLazy`1.GetValue(CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Shell.Package.FindToolWindow(Type toolWindowType, Int32 id, Boolean create, ProvideToolWindowAttribute tool)
   at Microsoft.VisualStudio.Shell.Package.CreateToolWindow(Guid& toolWindowType, Int32 id)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.ConstructContent()**

---
#### Feedback Bot on 9/3/2020, 10:59 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Yingying Zhang [MSFT] on 9/8/2020, 05:39 PM: 

<p>Please refer the below link to see if it can help you?<br>
<a target='_blank' href="https://docs.microsoft.com/en-us/azure/devops/organizations/projects/connect-to-projects?view=azure-devops&amp;tabs=visual-studio-2019#visual-studio">https://docs.microsoft.com/en-us/azure/devops/organizations/projects/connect-to-projects?view=azure-devops&amp;tabs=visual-studio-2019#visual-studio</a></p>

#### Michael Isherwood on 9/9/2020, 00:18 AM: 

<p>When I connect to project, I get the server name but no projects under it to connect.</p><p>If I refresh the server, I get this error.</p><p><img alt=""></p>

---
### Original Solutions
(no solutions)

**Comment by huguesv** [comment]
Looks like a team explorer issue. I've reopened the feedback ticket and moved passed it on to the Team Explorer team.
