### ISSUE TITLE
Recursion limit when searching for file

### ISSUE THREAD

**Issue by teeks99** [microsoft/PTVS#6253]
**Describe the bug**
When attaching the debugger we get an immediate crash of our program, digging in we get the following traceback:

```
Traceback (most recent call last):
  File "file.py", line 125, in new_connection_thread
    s = ServerSession(client, addr)
  File "file.py", line 158, in init
    threading.Thread.init(self)
  File "D:\obj\Windows-Release\37win32_Release\msi_python\zip_win32\threading.py", line 794, in init
  File "D:\obj\Windows-Release\37win32_Release\msi_python\zip_win32\threading.py", line 500, in init
  File "D:\obj\Windows-Release\37win32_Release\msi_python\zip_win32\threading.py", line 227, in init
  File "c:\program files (x86)\microsoft visual studio\2019\professional\common7\ide\extensions\microsoft\python\core\ptvsd\debugger.py", line 929, in trace_func
    return self._even
  File "c:\program files (x86)\microsoft visual studio\2019\professional\common7\ide\extensions\microsoft\python\core\ptvsd\debugger.py", line 1185, in handle_exception
    if not DETACHED and should_debug_code(frame.f_code):
  File "c:\program files (x86)\microsoft visual studio\2019\professional\common7\ide\extensions\microsoft\python\core\ptvsd\debugger.py", line 582, in should_debug_code
    if is_file_in_zip(filename):
  File "c:\program files (x86)\microsoft visual studio\2019\professional\common7\ide\extensions\microsoft\python\core\ptvsd\debugger.py", line 391, in is_file_in_zip
    return is_file_in_zip(parent)
  File "c:\program files (x86)\microsoft visual studio\2019\professional\common7\ide\extensions\microsoft\python\core\ptvsd\debugger.py", line 391, in is_file_in_zip
    return is_file_in_zip(parent)
  File "c:\program files (x86)\microsoft visual studio\2019\professional\common7\ide\extensions\microsoft\python\core\ptvsd\debugger.py", line 391, in is_file_in_zip
    return is_file_in_zip(parent)
  [Previous line repeated 978 more times]
  File "c:\program files (x86)\microsoft visual studio\2019\professional\common7\ide\extensions\microsoft\python\core\ptvsd\debugger.py", line 379, in is_file_in_zip
    parent, name = path.split(path.abspath(filename))
  File "D:\obj\Windows-Release\37win32_Release\msi_python\zip_win32\ntpath.py", line 526, in abspath
  File "D:\obj\Windows-Release\37win32_Release\msi_python\zip_win32\ntpath.py", line 472, in normpath
  File "D:\obj\Windows-Release\37win32_Release\msi_python\zip_win32\ntpath.py", line 141, in splitdrive
RecursionError: maximum recursion depth exceeded while calling a Python object
```

I suspect that the recursive operation in `is_file_in_zip` may be hitting the root of the drive and continually returning a split with `parent` as `"C:"` and `name` as `""`. 

This occurred when trying to debug a python interpreter that was embedded within a C/C++ executable, using boost::python. We have had luck using PTVS for this in the past, but haven't tried it for a couple years. Our runtime is a somewhat ripped-apart setup, inside `%PYTHONHOME%` we have `python37.dll`, `python37.zip`, and a handful of `_*.pyd` files. 

**Steps to Reproduce**
1. Start windows executable
2. Attach to python
3. Crash

**Expected behavior**
Not crashing because of a blown up call stack.

**Additional context and screenshots**

**Sample Code**

**Configuration information (If you are providing a diagnostics file (see below), skip this section)**
VS Version: 16.6.2
PTVS version: 16.6.20100.1
Python version: 3.7 32-bit
Debugger Type (if applicable): New debugger

**Comment by teeks99** [comment]
We've also tried attaching a bit earlier and stepping towards the area in question, that caused a crash with some other logic that wasn't previously causing the crash. (socket vs. threading)

```
Traceback (most recent call last): 
  File "file.py", line 113, in accept_connections 
	self.new_connection_thread(s, threads) 
  File "file.py", line 123, in new_connection_thread 
	client, addr = sock.accept() 
  File "D:\obj\Windows-Release\37win32_Release\msi_python\zip_win32\socket.py", line 205, in accept 
  File "c:\program files (x86)\microsoft visual studio\2019\professional\common7\ide\extensions\microsoft\python\core\ptvsd\debugger.py", line 929, in trace_func 
	return self._eventsevent 
  File "c:\program files (x86)\microsoft visual studio\2019\professional\common7\ide\extensions\microsoft\python\core\ptvsd\debugger.py", line 991, in handle_call 
	if stepping is not STEPPING_NONE and should_debug_code(f_code): 
  File "c:\program files (x86)\microsoft visual studio\2019\professional\common7\ide\extensions\microsoft\python\core\ptvsd\debugger.py", line 582, in should_debug_code 
	if is_file_in_zip(filename): 
  File "c:\program files (x86)\microsoft visual studio\2019\professional\common7\ide\extensions\microsoft\python\core\ptvsd\debugger.py", line 391, in is_file_in_zip 
	return is_file_in_zip(parent) 
  File "c:\program files (x86)\microsoft visual studio\2019\professional\common7\ide\extensions\microsoft\python\core\ptvsd\debugger.py", line 391, in is_file_in_zip 
	return is_file_in_zip(parent) 
  File "c:\program files (x86)\microsoft visual studio\2019\professional\common7\ide\extensions\microsoft\python\core\ptvsd\debugger.py", line 391, in is_file_in_zip 
	return is_file_in_zip(parent) 
  [Previous line repeated 984 more times] 
  File "c:\program files (x86)\microsoft visual studio\2019\professional\common7\ide\extensions\microsoft\python\core\ptvsd\debugger.py", line 379, in is_file_in_zip 
	parent, name = path.split(path.abspath(filename)) 
  File "D:\obj\Windows-Release\37win32_Release\msi_python\zip_win32\ntpath.py", line 526, in abspath 
  File "D:\obj\Windows-Release\37win32_Release\msi_python\zip_win32\ntpath.py", line 472, in normpath 
  File "D:\obj\Windows-Release\37win32_Release\msi_python\zip_win32\ntpath.py", line 141, in splitdrive 
RecursionError: maximum recursion depth exceeded while calling a Python object 
```

**Comment by huguesv** [comment]
Thanks for the feedback.

I would suggest that you try using remote debugging with debugpy (the new debugger).
https://github.com/microsoft/debugpy#waiting-for-the-client-to-attach
https://docs.microsoft.com/en-us/visualstudio/python/debugging-python-code-on-remote-linux-machines?view=vs-2019#attach-remotely-from-python-tools

Note that for this you'll need to have debugpy installed in the Python environment.

The current implementation of debug->attach to process where you select a process id and the debugger gets injected in the running process does not support debugpy yet (https://github.com/microsoft/PTVS/issues/4738). So that type of attach loads the legacy ptvsd debugger regardless of your "use legacy debugger" setting.

**Comment by teeks99** [comment]
We were able to work around this issue and get what we needed. I think the bug is still valid though as there are possibilities to repeatedly fail `is_file_in_zip` and end up crashing.

**Comment by huguesv** [comment]
You're right, but fixing up the legacy debugger that we plan on removing is realistically not going to happen given our resources and priority (Pylance language server).

I'm pushing to prioritize https://github.com/microsoft/PTVS/issues/4738 so this code path ends up using debugpy, which is actively maintained.
