### ISSUE TITLE
Pylint does not install properly

### ISSUE THREAD

**Issue by gnychis** [Microsoft/PTVS#626]
I am trying to install Pylint for use with IronPython, but I ran in to two issues.  First, I had to have Visual Studio running as Administrator permission otherwise the installation of `pip` would fail due to permission errors.

Second, once I did get it to install `pip`, It can't manage to install pylint:

```
Unhandled exception:
Traceback (most recent call last):
  File "C:\Program Files (x86)\IronPython 2.7\Lib\runpy.py", line 170, in run_module
  File "C:\Program Files (x86)\IronPython 2.7\Lib\runpy.py", line 101, in _get_module_details
  File "C:\Program Files (x86)\IronPython 2.7\Lib\pkgutil.py", line 456, in get_loader
  File "C:\Program Files (x86)\IronPython 2.7\Lib\pkgutil.py", line 466, in find_loader
  File "C:\Program Files (x86)\IronPython 2.7\Lib\pkgutil.py", line 422, in iter_importers
  File "C:\Program Files (x86)\IronPython 2.7\lib\site-packages\pip\__init__.py", line 13, in <module>
  File "C:\Program Files (x86)\IronPython 2.7\lib\site-packages\pip\utils\__init__.py", line 18, in <module>
  File "C:\Program Files (x86)\IronPython 2.7\lib\site-packages\pip\compat\__init__.py", line 8, in <module>
  File "C:\Program Files (x86)\IronPython 2.7\lib\site-packages\pip\_vendor\six.py", line 675, in <module>
  File "C:\Program Files (x86)\IronPython 2.7\lib\site-packages\pip\_vendor\six.py", line 665, in exec_
  File "C:\Program Files (x86)\IronPython 2.7\Lib\runpy.py", line 109, in _get_module_details
AttributeError: 'module' object has no attribute '_getframe'
Unhandled exception:
Traceback (most recent call last):
  File "C:\Program Files (x86)\IronPython 2.7\Lib\runpy.py", line 170, in run_module
  File "C:\Program Files (x86)\IronPython 2.7\Lib\pkgutil.py", line 456, in get_loader
  File "C:\Program Files (x86)\IronPython 2.7\Lib\pkgutil.py", line 466, in find_loader
  File "C:\Program Files (x86)\IronPython 2.7\Lib\pkgutil.py", line 422, in iter_importers
  File "C:\Program Files (x86)\IronPython 2.7\Lib\runpy.py", line 101, in _get_module_details
ImportError: No module named pylint
```

**Comment by zooba** [comment]
I don't know that IronPython is supported by pylint at all, and it'll be nice if/when pip or six figures out a way to avoid needing _getframe (it's not actually needed for pip).

Best workaround here is to do:

```
ipy.exe -X:Frames -m pip install pylint
```

from an elevated command prompt. When we detect that it's already installed, we won't try to do it again and this error won't appear. But like I said, pylint may not work on IronPython either, and there's nothing we can do about that.
