### ISSUE TITLE
Debugging broken in 16.7.x-16.8.0 (The parameter is incorrect E_INVALIDARG)

### ISSUE THREAD

**Issue by forderud** [microsoft/PTVS#6305]
I'm experiencing `The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))` pop-up messages when attempting to run or debug python scripts in Visual Studio 2019 16.7.x-16.8.0. This used to work fine in previous versions of VS2019.

Related issues: https://github.com/microsoft/PTVS/issues/6204 & https://github.com/microsoft/PTVS/issues/6278 (both are closed)

The exception occurs in the following scenarios:
* When opening the "Debug" and "Publish" configuration pages for the project.
* When attempting to run a script using "Start without Debugging" or "Start with Debugging"

Details:
```
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Expanded Information]
Build: 16.8.20241.2

System.ArgumentException: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
   at EnvDTE.ConfigurationManager.get_ActiveConfiguration()
   at Microsoft.PythonTools.Project.PythonProjectNode.SetCurrentConfiguration()
   at Microsoft.VisualStudioTools.Project.ProjectNode.GetMsBuildProperty(String propertyName, Boolean resetCache)
   at Microsoft.VisualStudioTools.Project.ProjectNode.GetProjectProperty(String propertyName, Boolean resetCache)
   at Microsoft.PythonTools.Project.CondaEnvCreateProjectInfoBar.<CheckAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Project.PythonProjectNode.<TriggerInfoBarsAsync>d__107.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by huguesv** [comment]
Thanks for the feedback.

I have double checked that the build includes this commit: https://github.com/microsoft/PTVS/commit/d5a192974e542eb9a9b40d04826c087185dcbce5

But it appears we should have added a catch for `ArgumentException` in addition to `COMException`.

We were never able to reproduce this issue ourselves, and so were not able to verify the fix. I still can't, so if you're able to share a minimal repro project and/or steps, that would be helpful to ensure that we really fix it properly this time.

**Comment by forderud** [comment]
> We were never able to reproduce this issue ourselves, and so were not able to verify the fix. I still can't, so if you're able to share a minimal repro project and/or steps, that would be helpful to ensure that we really fix it properly this time.

Minimal project to reproduce: https://github.com/forderud/CMakePTVS

**Comment by huguesv** [comment]
Thanks for the minimal project, I am now able to reproduce.

**Comment by alkatar21** [comment]
Is there any progress here? The workaround from https://github.com/forderud/CMakePTVS#cmakeptvs does not work at least for me.

**Comment by masariello** [comment]
This issue shows up also as a "false error" during builds of solutions that contain a pyproj.

`Error: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))`

It would be really useful if it was fixed. Thank you
