### ISSUE TITLE
The VS is crash after clicking "Open additional output for this result"

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6324]
**Envitonment**
![image](https://user-images.githubusercontent.com/59192491/101736495-75f49700-3afe-11eb-91d1-d5a0b0d3e66d.png)

**Steps to Reproduce**
1. Open/Create a Python project, right-click project, select Add > New Item …, then select "Python Unit Test" followed by "Add" 
2. Open the Property page ->Test-> Change the Test Framework to unittest
3. Run the test
4. Check the result and click "Open additional output for this result"
![image](https://user-images.githubusercontent.com/59192491/101737081-5ad65700-3aff-11eb-9306-580165f7baa4.png)

**Expected behavior**
The result page display without any error.

**Actual result**
The VS is crash.

**Error events log**
[Error events.zip](https://github.com/microsoft/PTVS/files/5671078/Error.events.zip)

**Comment by AdamYoblick** [comment]
Hi Linette,

I'm not able to repro this on VS public preview:

![image](https://user-images.githubusercontent.com/29436557/102549560-ea40b480-4081-11eb-8565-e3c6b2458896.png)

When I click on `Open additional output for this result`, I see the full callstack in the right pane:

![image](https://user-images.githubusercontent.com/29436557/102549607-03496580-4082-11eb-9724-faaab33cb4ed.png)

I will try again shortly on Int-Preview (preview 3) and report back.

**Comment by AdamYoblick** [comment]
Also unable to repro on the latest preview 3 version:

![image](https://user-images.githubusercontent.com/29436557/102552334-a56b4c80-4086-11eb-9a5e-7b1053059f98.png)

![image](https://user-images.githubusercontent.com/29436557/102552344-ac925a80-4086-11eb-8760-a1c9c003a7b2.png)

Can you try the latest int preview version, or public preview? Maybe uninstall the python workload and re-install it?

**Comment by bschnurr** [comment]
looking at the error.zip details, seems there was bad icon string or null string
```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at Microsoft.Internal.VisualStudio.Shell.Validate.IsNotWhiteSpace(System.String, System.String)
   at Microsoft.VisualStudio.Services.VsImageService.GetImageMonikerForFile(System.String)
   at Microsoft.VisualStudio.PlatformUI.HierarchyManager.LoadIconFromImageService(Microsoft.VisualStudio.PlatformUI.HierarchyItem)
   at Microsoft.VisualStudio.PlatformUI.HierarchyManager.GetImageMonikerFromHierarchy(Microsoft.VisualStudio.PlatformUI.HierarchyItem, Int32, Int32, Int32, Int32, Microsoft.VisualStudio.Imaging.Interop.IImageHandle ByRef)
   at Microsoft.VisualStudio.PlatformUI.HierarchyManager.GetExpandedIconMoniker(Microsoft.VisualStudio.PlatformUI.HierarchyItem, Microsoft.VisualStudio.Imaging.Interop.IImageHandle ByRef)
   at Microsoft.VisualStudio.PlatformUI.HierarchyItem.<EnsureIcon>b__73_0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

**Comment by AdamYoblick** [comment]
I've been unable to repro this, so I'm going to close it out. If it repros again, please re-open. Thanks.
