### ISSUE TITLE
ImportError:when run new azure cloud service

### ISSUE THREAD

**Issue by SokolovVV** [Microsoft/PTVS#635]
Hi All, when i start debuging new azure cloud service, i catch the some ImportError

Error occurred while reading WSGI handler:
Traceback (most recent call last):
  File "C:\temp_vs_projects\Azure123\AzureCloudService1\WebRole1\bin\wfastcgi.py", line 779, in main
    env, handler = read_wsgi_handler(response.physical_path)
  File "C:\temp_vs_projects\Azure123\AzureCloudService1\WebRole1\bin\wfastcgi.py", line 621, in read_wsgi_handler
    handler = get_wsgi_handler(os.getenv('WSGI_HANDLER'))
 File "C:\temp_vs_projects\Azure123\AzureCloudService1\WebRole1\bin\wfastcgi.py", line 605, in get_wsgi_handler
    raise ValueError('"%s" could not be imported%s' % (handler_name, last_tb))
ValueError: "app.wsgi_app" could not be imported: Traceback (most recent call last):
  File "C:\temp_vs_projects\Azure123\AzureCloudService1\WebRole1\bin\wfastcgi.py", line 589, in get_wsgi_handler
    handler = **import**(module_name, fromlist=[name_list[0][0]])
ImportError: No module named app
StdOut: 
StdErr:

**Comment by zooba** [comment]
Did you select the empty "Web Role" or one that is built around a framework like Django or Bottle?

If you picked the empty one, you've got a bit of work to do to get something that can run (though if you have an existing Python web app it's much easier to import it into the empty one).

I'd suggest picking one of the framework templates if you are starting a new site.

You can find more helpful information on our documentation pages for [Cloud Projects](https://github.com/Microsoft/PTVS/wiki/Cloud-Project) and [Web Projects](https://github.com/Microsoft/PTVS/wiki/Web-Project).
