### ISSUE TITLE
Filename required error on clicking around environments tab

### ISSUE THREAD

**Issue by timsneath** [Microsoft/PTVS#638]
Clicked custom environment, then clicked through other pages in Environments dropdown. Got this error message. 

[Window Title]
Python Tools for Visual Studio

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
System.ArgumentException: Filename required
Parameter name: filename
   at Microsoft.VisualStudioTools.Project.ProcessOutput.Run(String filename, IEnumerable`1 arguments, String workingDirectory, IEnumerable`1 env, Boolean visible, Redirector redirector, Boolean quoteArgs, Boolean elevate, Encoding outputEncoding, Encoding errorEncoding)
   at Microsoft.PythonTools.EnvironmentsList.PipExtensionProvider.<GetInstalledPackagesAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.EnvironmentsList.PipEnvironmentView.<RefreshInstalledPackages>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.EnvironmentsList.PipEnvironmentView.<RefreshPackages>d__38.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.EnvironmentsList.PipEnvironmentView.<FinishInitialization>d__14.MoveNext()

**Comment by zooba** [comment]
Thankyou. I hope that going back to "Configure" and filling out the interpreter resolves this, yes?

**Comment by timsneath** [comment]
Yes, it doesn't leave it in a fundamentally broken state.

**Comment by zooba** [comment]
Should have been fixed
