### ISSUE TITLE
Failed to create "GitHub->cookiecutter-flask/cookiecutter-flask" template in cookiecutter.

### ISSUE THREAD

**Issue by zhouwangyang** [microsoft/PTVS#6390]
![image](https://user-images.githubusercontent.com/39871640/107008091-53b18980-67ce-11eb-8f00-a236f79789c4.png)

**Steps to Reproduce**
1.Launch VS
2.Click "View->Cookiecutter Explorer"
3.Select "GitHub->cookiecutter-flask/cookiecutter-flask" to click "Next"
4.Wait for load successfully and then click "Create and Open Folder"

**Expected behavior**
It should create successfully

**Additional context and screenshots**
Error occurs when create template
![image](https://user-images.githubusercontent.com/39871640/107007943-282e9f00-67ce-11eb-9133-3caf9ceac83a.png)

Error detail info:

```
----- Creating files using template 'cookiecutter-flask/cookiecutter-flask' -----
DEBUG main.py: context_file is C:\Users\vwazho\.cookiecutters\cookiecutter-flask\cookiecutter.json
DEBUG generate.py: Context generated is {'cookiecutter': OrderedDict([('full_name', ''), ('email', ''), ('github_username', ''), ('project_name', ''), ('app_name', ''), ('project_short_description', ''), ('use_pipenv', ''), ('python_version', ''), ('node_version', ''), ('use_heroku', '')])}
DEBUG utils.py: Making sure path exists: C:\Users\vwazho/.cookiecutter_replay/
DEBUG find.py: Searching C:\Users\vwazho\.cookiecutters\cookiecutter-flask for the project template.
DEBUG find.py: The project template appears to be C:\Users\vwazho\.cookiecutters\cookiecutter-flask\{{cookiecutter.app_name}}
DEBUG generate.py: Generating project from C:\Users\vwazho\.cookiecutters\cookiecutter-flask\{{cookiecutter.app_name}}...
DEBUG generate.py: Rendered dir  must exist in output_dir C:\Users\vwazho\AppData\Local\Temp\c9c1c313-9b3a-44ee-aaac-cf47cc29e746
Traceback (most recent call last):
  File "c:\program files (x86)\microsoft visual studio\2019\preview\common7\ide\extensions\microsoft\cookiecutter\cookiecutter_run.py", line 46, in <module>
    sys.exit(int(main() or 0))
  File "c:\program files (x86)\microsoft visual studio\2019\preview\common7\ide\extensions\microsoft\cookiecutter\cookiecutter_run.py", line 42, in main
    config_file=user_config_path,
  File "C:\Users\vwazho\AppData\Local\Microsoft\CookiecutterTools\env\lib\site-packages\cookiecutter\main.py", line 144, in cookiecutter
    output_dir=output_dir
  File "C:\Users\vwazho\AppData\Local\Microsoft\CookiecutterTools\env\lib\site-packages\cookiecutter\generate.py", line 269, in generate_files
    overwrite_if_exists
  File "C:\Users\vwazho\AppData\Local\Microsoft\CookiecutterTools\env\lib\site-packages\cookiecutter\generate.py", line 211, in render_and_create_dir
    raise OutputDirExistsException(msg)
cookiecutter.exceptions.OutputDirExistsException: Error: "C:\Users\vwazho\AppData\Local\Temp\c9c1c313-9b3a-44ee-aaac-cf47cc29e746" directory already exists
C:\Users\vwazho\AppData\Local\Microsoft\CookiecutterTools\env\scripts\python.exe returned an exit code of 1.
----- Failed to create files using template 'cookiecutter-flask/cookiecutter-flask' -----

```

**Comment by gramster** [comment]
It looks like the problem is just that the folder already exists. Can you try with a folder that does not exist?
