### ISSUE TITLE
Error in VS2019 when interacting with Python

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6400]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Error-in-VS2019-when-interacting-with-Py/1340318)._

---
[severity:It's more difficult to complete my work]
Error in VS2019 when interacting with Python
I see this error when opening .py files and when building the solution which runs the py file.

[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[V] Show details  [Close]

[Expanded Information]
```
Build: 16.7.20248.6

System.ArgumentException: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
   at EnvDTE.ConfigurationManager.get_ActiveConfiguration()
   at Microsoft.PythonTools.Project.PythonProjectNode.SetCurrentConfiguration()
   at Microsoft.VisualStudioTools.Project.ProjectNode.GetMsBuildProperty(String propertyName, Boolean resetCache)
   at Microsoft.VisualStudioTools.Project.ProjectNode.GetProjectProperty(String propertyName, Boolean resetCache)
   at Microsoft.PythonTools.Project.CondaEnvCreateProjectInfoBar. <CheckAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Project.PythonProjectNode. <TriggerInfoBarsAsync>d__106.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions. <HandleAllExceptions>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

---
#### Feedback Bot on 2/17/2021, 11:46 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### chuck.moidel on 2/17/2021, 11:50 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ogunrinde72** [comment]
I need help, this is from visual studio and anytime i run my code i get this errors. it says name not define
  _run_code(code, mod_globals, init_globals,
  File "C:\Users\USER\.conda\envs\env3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\USER\source\repos\HELLOW WORLD\HELLOW WORLD\HELLOW_WORLD.py", line 1, in <module>
    PRINT("HELLO WORLD")
NameError: name 'PRINT' is not defined
The thread 'MainThread' (0x1) has exited with code 0 (0x0).
The program 'python.exe' has exited with code 1 (0x1).
