### ISSUE TITLE
Python projects stopped working in visual studio 2019

### ISSUE THREAD

**Issue by JosephTeicher** [microsoft/PTVS#6447]
with no warning I can't debug or run my python projects from visual studio at all.  I got a window that said to copy paste the error here. 

[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 16.4.19310.1

System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Interpreter.CondaUtils.<GetActivationEnvironmentVariablesForPrefixAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.PythonTools.Interpreter.LaunchConfigurationUtils.GetFullEnvironment(LaunchConfiguration config, IServiceProvider serviceProvider)
   at Microsoft.PythonTools.Debugger.DebugLaunchHelper.CreateDebugTargetInfo(IServiceProvider provider, LaunchConfiguration config)
   at Microsoft.PythonTools.Project.DefaultPythonLauncher.StartWithDebugger(LaunchConfiguration config)
   at Microsoft.PythonTools.Project.DefaultPythonLauncher.Launch(LaunchConfiguration config, Boolean debug)
   at Microsoft.PythonTools.Project.DefaultPythonLauncher.LaunchFile(String file, Boolean debug)
   at Microsoft.PythonTools.PythonToolsPackage.LaunchFile(IServiceProvider provider, String filename, Boolean debug, Boolean saveDirtyFiles)
   at Microsoft.PythonTools.Language.EditFilter.ExecWorker(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.PythonTools.Language.EditFilter.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by redcatbluedog** [comment]
i have the same problem today, worked all day yesterday but this morning nothing
