### ISSUE TITLE
version 872 is no longer in memory

### ISSUE THREAD

**Issue by MGBergweiler** [microsoft/PTVS#6671]
**Describe the bug**
"An unexpected error occurred"

**Steps to Reproduce**
Not sure, was just editing a python source
and above message popped up, with below details.

**Additional context and screenshots**
```
Build: 16.10.21111.19

System.NotSupportedException: version 872 is no longer in memory
   at Microsoft.PythonTools.Intellisense.LocationTracker.GetLineLocations(Int32 version)
   at Microsoft.PythonTools.Intellisense.LocationTracker.Translate(SourceLocation loc, Int32 fromVersion, Int32 toVersion)
   at Microsoft.PythonTools.Intellisense.LocationTracker.Translate(SourceSpan span, Int32 fromVersion, Int32 toVersion)
   at Microsoft.PythonTools.Intellisense.TaskProviderItem.CreateSquiggleSpan(SimpleTagger`1 tagger)
   at Microsoft.PythonTools.Intellisense.TaskProvider.<RefreshAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.PythonTools.Intellisense.TaskProvider.Refresh()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by greazer** [comment]
@MGBergweiler, this is fixed in the next major release of Visual Studio. VS 2022
