### ISSUE TITLE
VS will restart with System.AccessViolationException.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6684]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/130565915-2cb4018d-4585-4363-a170-917e4615c317.png)

**Steps to Reproduce**
1. Launch VS
2. Select View > Cookiecutter Explorer
3. Load some templates
4. Choose one and right click to delete

**Expected behavior**
This template was deleted.

**Actual result**
VS restarts and the template was not deleted.

Here's is the .NET exception I pulled out of Event Manager
```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at Microsoft.CookiecutterTools.Infrastructure.ShellUtils+NativeMethods.SHFileOperation(SHFILEOPSTRUCT ByRef)
   at Microsoft.CookiecutterTools.Infrastructure.ShellUtils+NativeMethods.RecursivelyDeleteDirectory(System.String, Boolean)
   at Microsoft.CookiecutterTools.Model.LocalTemplateSource+<DeleteTemplateAsync>d__5.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.CookiecutterTools.Model.LocalTemplateSource+<DeleteTemplateAsync>d__5, Microsoft.CookiecutterTools, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](<DeleteTemplateAsync>d__5 ByRef)
   at Microsoft.CookiecutterTools.Model.LocalTemplateSource.DeleteTemplateAsync(System.String)
   at Microsoft.CookiecutterTools.ViewModel.CookiecutterViewModel+<DeleteTemplateAsync>d__198.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.CookiecutterTools.ViewModel.CookiecutterViewModel+<DeleteTemplateAsync>d__198, Microsoft.CookiecutterTools, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](<DeleteTemplateAsync>d__198 ByRef)
   at Microsoft.CookiecutterTools.ViewModel.CookiecutterViewModel.DeleteTemplateAsync(Microsoft.CookiecutterTools.ViewModel.TemplateViewModel)
   at Microsoft.CookiecutterTools.View.CookiecutterContainerPage.DeleteSelection()
   at Microsoft.CookiecutterTools.Commands.DeleteInstalledTemplateCommand.DoCommand(System.Object, System.EventArgs)
   at Microsoft.VisualStudio.Shell.OleMenuCommand.Invoke(System.Object, IntPtr, Microsoft.VisualStudio.OLE.Interop.OLECMDEXECOPT)
   at Microsoft.VisualStudio.Shell.OleMenuCommandService.Microsoft.VisualStudio.OLE.Interop.IOleCommandTarget.Exec(System.Guid ByRef, UInt32, UInt32, IntPtr, IntPtr)
   at Microsoft.VisualStudio.Shell.Interop.IVsUIDataSource.Invoke(System.String, System.Object, System.Object ByRef)
   at Microsoft.VisualStudio.PlatformUI.VsCommand.Execute(System.Object)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(System.Windows.Input.ICommandSource, Boolean)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at Microsoft.VisualStudio.PlatformUI.NativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowManagerService+<>c.<PushMessageLoopOnContextMenuTrackingComponent>b__245_1(System.Object, Microsoft.VisualStudio.PlatformUI.OleComponentSupport.PreTranslateMessageEventArgs)
   at Microsoft.VisualStudio.PlatformUI.OleComponentSupport.OleComponent.FPreTranslateMessageCore(Microsoft.VisualStudio.OLE.Interop.MSG[])
   at Microsoft.VisualStudio.PlatformUI.OleComponentSupport.OleComponent+<>c__DisplayClass24_0.<Microsoft.VisualStudio.OLE.Interop.IOleComponent.FPreTranslateMessage>b__0()
   at Microsoft.VisualStudio.PlatformUI.OleComponentSupport.OleComponent.CallAndReturnOnException(System.Func`1<Int32>, Int32)
   at Microsoft.VisualStudio.OLE.Interop.IOleComponentManager.FPushMessageLoop(UInt32, UInt32, IntPtr)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowManagerService.PushMessageLoopOnContextMenuTrackingComponent()
   at Microsoft.VisualStudio.Shell.Interop.IVsUIShell.ShowContextMenu(UInt32, System.Guid ByRef, Int32, Microsoft.VisualStudio.Shell.Interop.POINTS[], Microsoft.VisualStudio.OLE.Interop.IOleCommandTarget)
   at Microsoft.CookiecutterTools.CookiecutterPackage.ShowContextMenu(System.ComponentModel.Design.CommandID, Int32, Int32, Microsoft.VisualStudio.OLE.Interop.IOleCommandTarget)
   at Microsoft.CookiecutterTools.CookiecutterToolWindow.ShowContextMenu(System.Windows.Point)
   at Microsoft.CookiecutterTools.CookiecutterToolWindow.OnContextMenuRequested(System.Object, Microsoft.CookiecutterTools.View.PointEventArgs)
   at Microsoft.CookiecutterTools.View.CookiecutterContainerPage.UserControl_MouseRightButtonUp(System.Object, System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.ReRaiseEventAs(System.Windows.DependencyObject, System.Windows.RoutedEventArgs, System.Windows.RoutedEvent)
   at System.Windows.UIElement.OnMouseUpThunk(System.Object, System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs)
   at System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr, System.Windows.Input.InputMode, Int32, System.Windows.Input.RawMouseActions, Int32, Int32, Int32)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr, Boolean ByRef)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

**Comment by linette-zyy** [comment]
This issue also reproduced when load https://github.com/Microsoft/python-sklearn-classifier-cookiecutter

**Comment by StellaHuang95** [comment]
Can't repro in Microsoft Visual Studio Enterprise 2022 (64-bit) - Int Preview Version 17.3.0 Preview 2.0 [32601.540.main]. Please reopen the ticket if the issue persists.
