### ISSUE TITLE
The VS will restart automictically after clicking "Analyze Code Coverage".

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6691]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/130737634-d375f446-d28b-4e88-88db-611de38e7588.png)

**Steps to Reproduce**
1. From Test Explorer, select Analyzer Code Coverage for Selected Tests
2. Check Output Window / Tests pane for a warning message indicating that 'coverage' package must be installed.
3. Install 'coverage' into your environment and try again, by selecting multiple tests.
![image](https://user-images.githubusercontent.com/59192491/130737781-32992a40-66d1-45f4-8a1e-8e79d1fee88b.png)

**Expected behavior**
The Code Coverage Results tool window appear.

**Actual result **
The VS will restart automictically after clicking "Analyze Code Coverage".
![Analyzer Code Coverage](https://user-images.githubusercontent.com/59192491/130738367-5b548a26-f609-4219-90d8-e5d94f2cacb0.gif)

**Event log**
Here's is the .NET exception I pulled out of Event Manager
```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Microsoft.VisualStudio.TestTools.CodeCoverage.CodeCoverageStatsToolWindow+ProviderComboItem..ctor(Microsoft.VisualStudio.TestTools.CodeCoverage.IHierarchyElement)
   at Microsoft.VisualStudio.TestTools.CodeCoverage.CodeCoverageStatsToolWindow.UpdateSelectedProvider()
   at Microsoft.VisualStudio.TestTools.CodeCoverage.CodeCoverageStatsToolWindow.Initialize()
   at Microsoft.VisualStudio.TestTools.CodeCoverage.CodeCoverageStatsWindowHost..ctor()

Exception Info: System.Reflection.TargetInvocationException
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
   at System.Reflection.RuntimeConstructorInfo.Invoke(System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at System.RuntimeType.CreateInstanceImpl(System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo, System.Object[], System.Threading.StackCrawlMark ByRef)
   at System.Activator.CreateInstance(System.Type, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo, System.Object[])
   at System.Activator.CreateInstance(System.Type, System.Object[])
   at Microsoft.VisualStudio.Shell.Package.InstantiateToolWindow(System.Type, System.Object)
   at Microsoft.VisualStudio.Shell.Package+<>c__DisplayClass84_0.<CreateToolWindow>g__CreateToolWindowWorker|1()
   at Microsoft.VisualStudio.Shell.Package.CreateToolWindow(System.Type, Int32, UInt32, System.Object, System.Guid)
   at Microsoft.VisualStudio.Shell.Package.CreateToolWindow(System.Type, Int32, System.Object)
   at Microsoft.VisualStudio.Shell.AsyncPackage+<CompleteToolWindowCreationAsync>d__38.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.Shell.AsyncPackage+<CreateToolWindowCoreAsync>d__37.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.Shell.AsyncPackage+<CreateToolWindowAsync>d__36.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.Shell.AsyncPackage+<>c__DisplayClass45_0+<<FindToolWindowAsync>b__0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.Shell.ToolWindowCollection+ToolWindowListener+<>c__DisplayClass1_0+<<-ctor>b__0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.Threading.AwaitExtensions+ExecuteContinuationSynchronouslyAwaiter`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetResult()
   at Microsoft.VisualStudio.Threading.AsyncLazy`1+<>c__DisplayClass13_0+<<GetValueAsync>b__0>d[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.Shell.AsyncPackage+<FindToolWindowAsync>d__45.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.Shell.AsyncPackage+<FindToolWindowAsync>d__43.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.TestTools.TestCaseManagement.QualityToolsPackage+<>c__DisplayClass66_0`1+<<InitToolWindowVariableAsync>b__0>d[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.TestTools.TestCaseManagement.QualityToolsPackage+<InitToolWindowVariableAsync>d__66`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.TestTools.TestCaseManagement.QualityToolsPackage+<CreateToolWindowAsync>d__67`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.TestTools.TestCaseManagement.QualityToolsPackage+<OpenCoverageStatisticsWindowAsync>d__77.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.TestTools.TestCaseManagement.QualityToolsPackage+<OnMenuViewCodeCoverageStatisticsAsync>d__62.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory+SingleExecuteProtector.TryExecute()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

```

**Comment by rchiodo** [comment]
Needs the creation of a bug for whomever owns Microsoft.VisualStudio.TestTools.CodeCoverage.CodeCoverageStatsToolWindow

**Comment by linette-zyy** [comment]
On today's build
![image](https://user-images.githubusercontent.com/59192491/131800424-ac3b7161-414a-4eb2-ab16-5c4d51a69fad.png)
After clicking  "Analyze Code Coverage", an error dialog pop up.
![image](https://user-images.githubusercontent.com/59192491/131800315-b356725a-6a67-41a4-95ea-24d281855cae.png)

**Comment by linette-zyy** [comment]
This issue is also reproduced on today's build.
![image](https://user-images.githubusercontent.com/59192491/133734326-18e179d2-5470-4193-a20f-37fd0de6761a.png)
The VS is crash after clicking "Analyze Code Coverage".

**Comment by jakubch1** [comment]
@linette-zyy could you please check latest release? If you can still reproduce it could you please send me your solution? I was not able to reproduce it.

**Comment by linette-zyy** [comment]
@jakubch1 I check it on the latest release 17.0.0 Preview 5.0 [31729.338.main], this is issue is not reproduce.
![image](https://user-images.githubusercontent.com/59192491/135368147-9df87218-9246-4073-bc61-512f3a046215.png)

**Comment by linette-zyy** [comment]
On this environment
![image](https://user-images.githubusercontent.com/59192491/141250830-a88d289c-e811-4293-8ea3-b5d9d734f029.png)
After install the package "coverage" and then to click "Analyze Code Coverage", this error page display.
![image](https://user-images.githubusercontent.com/59192491/141251046-fb6c55e3-8a1b-4f81-b06f-a63f55a8246c.png)
When second time to click "Analyze Code Coverage", it works well.
![image](https://user-images.githubusercontent.com/59192491/141251275-f13b37f1-29b8-406c-8053-7d4296c38c1c.png)

**Comment by fhnaseer** [comment]
@linette-zyy Is it still reproducible on latest preview?

**Comment by linette-zyy** [comment]
@fhnaseer 
I try on this environment.
![image](https://user-images.githubusercontent.com/59192491/144340321-a471cc7b-0d6b-46af-a8d8-d6cc8ac6436b.png)
This issue is not reproduce, it works well.
![image](https://user-images.githubusercontent.com/59192491/144340384-295732b9-6a18-4791-9fa8-a2a9a9985a24.png)

**Comment by ttSpace** [comment]
In today's build ```17.1.0 Preview 3.0 [32029.61.main]```, Click "Analyze Code Coverage" for the first time and get this. Then click again, work normally.

![image](https://user-images.githubusercontent.com/82852072/147726128-327b51a0-4a0a-4d1d-8903-f6e5a5575485.png)

**Comment by judej** [comment]
Is this still repo?

**Comment by linette-zyy** [comment]
@judej 
I verify this issue on the latest build.
![image](https://user-images.githubusercontent.com/59192491/153998862-4300b44f-4543-4a2a-9803-01890b57cb39.png)
This issue is not reproduced.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/59192491/153998887-eddde11a-d2b1-4f7d-9310-adf97ecdc75f.png)
