### ISSUE TITLE
Unexpected error - Devenv.exe

### ISSUE THREAD

**Issue by jswilliamstu** [microsoft/PTVS#6801]
**Describe the bug**
[A clear and concise description of the bug]

**Steps to Reproduce**
1.
2.
3.

**Expected behavior**
[A clear and concise description of your expectation]

**Additional context and screenshots**
[Add any other information such as screenshots, error message, or stack trace]

**Sample Code**
```
XXX
```

**Configuration information (If you are providing a diagnostics file (see below), skip this section)**
VS Version: [Can be found under "Help->About Microsoft Visual Studio"]
PTVS version: [Can be found under "Help->About Microsoft Visual Studio->Installed products"]
Python version:
Debugger Type (if applicable): [New debugger or legacy debugger?]

**Diagnostics file**
The diagnostics file contains information such as the Python version, environments, loaded assemblies, configuration options, etc. This file makes it easier for us to reproduce and fix bugs, so we would really appreciate it if you could provide it to us. This file can be generated by going to Tools->Options->Python->Diagnostics.
You can attach the file to this issue or email it to us at ptvshelp@microsoft.com. If you email it, please add a link to this issue.
```
XXX
```
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 17.0.21295.2

System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'StreamJsonRpc.JsonRpc'.
   at Microsoft.Verify.NotDisposed(IDisposableObservable disposedValue, String message)
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__139`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.LanguageServerClient.PythonLanguageClient.<NotifyWithParametersAsync>d__75.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.LanguageServerClient.ReplDocument.<OnReplDidChangeTextDocumentAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by AdamYoblick** [comment]
Can you please provide a code sample so we can try to repro this?

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
