### ISSUE TITLE
Unable to Create DjangoWebProject after following Configuration Read Me for setting up SuperUser: devenv.exe project issue tracker says:>

### ISSUE THREAD

**Issue by grahamsmithwick** [microsoft/PTVS#6838]
**Describe the bug**
****[A clear and concise description of the bug]****

**Steps to Reproduce**
1.Follow Configuration |Read-Me Instructions for seetting up "SuperUser"
   (1) Open Solution Explorer
   (2) Right-click the Project Node and Select > Python > Create Django Superuser 

2. "Create A Project" from https://docs.djangoproject.com/en/4.0/intro/tutorial01/  by entering this Command in the Django Management Console:>  

3 $ django-admin startproject mysite. 
3.
_____________________________________________________
**Expected behavior**
[A clear and concise description of your expectation]

> START PROJECT >
___________________________________________________________________
**Additional context and screenshots**
[Add any other information such as screenshots, error message, or stack trace]

HERE IS THE ERROR MESSAGE:

[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 17.0.21293.2

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.PythonTools.Repl.ReplEditFilter.<PasteReplCode>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.PythonTools.Infrastructure.TaskExtensions.ReThrowTaskException(Object state)
   at Microsoft.PythonTools.Infrastructure.TaskExtensions.DoNotWait(Task task)
   at Microsoft.PythonTools.Repl.ReplEditFilter.ExecWorker(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.PythonTools.Repl.ReplEditFilter.Microsoft.VisualStudio.OLE.Interop.IOleCommandTarget.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by grahamsmithwick** [comment]
Not sure about triage.  All I know is that either I should have got a confimation of Superuser set up OR the command given in the Tutorial didn't Start Project

**Comment by AdamYoblick** [comment]
We are prioritizing other tasks at the moment, so I'm closing this out. If this continues to repro for you, please re-open this issue.
