### ISSUE TITLE
Unexpected error displayed on the Test output window when discovery unittest.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6892]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/155453260-ad0ec551-f9c5-43e5-a25f-96cfeaf5edf8.png)

**Steps to Reproduce**
1. Create a new Python Application project
2. Right-click project, select Add > New Item …, then select "Python Unit Test" followed by "Add"
3. Go to property page to enable unittest
![image](https://user-images.githubusercontent.com/59192491/155453435-dff2b5d7-cdb0-4cb5-af08-592234241761.png)
4. Check Test output window

**Expected behavior**
The test can be found without any error.

**Additional context and screenshots**
Unexpected error displayed on the Test output window. 

**Test Output window**
```
Log level is set to Informational (Default).
Source code repository not available. Some features may not work as expected.
Connected to test environment '< Local Windows Environment >'
Test data store opened in 0.015 sec.
========== Starting test discovery ==========
Loaded 0 test records from the solution cache in 0.878 sec.
Starting unittest discovery for the PythonApplication1 project. This can take up to 60 seconds.
cd C:\Users\vyizh12\source\repos\PythonApplication1\PythonApplication1\
set PYTHONPATH=C:\Users\vyizh12\source\repos\PythonApplication1\PythonApplication1\
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\python.exe C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\PREVIEW\COMMON7\IDE\EXTENSIONS\MICROSOFT\PYTHON\CORE\PythonFiles\testing_tools\run_adapter.py discover unittest --output-file C:\Users\vyizh12\AppData\Local\Temp\tmp749C.tmp -- . test*.py
========== Test discovery finished: 1 Tests found in 4.2 sec ==========
System.InvalidCastException: Unable to cast object of type 'Microsoft.VisualStudioTools.TestAdapter.TestContainer' to type 'Microsoft.VisualStudio.TestWindow.Client.TestContainer.DefaultTestContainer'.
   at System.Linq.Enumerable.<CastIterator>d__97`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.VisualStudio.TestWindow.Controller.DiscoveryOperation.<PerformDiscoveryAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Controller.DiscoverSelectedOperation.<ExecuteInternalAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Controller.Operation.<<ExecuteAsync>b__43_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Logging.ILoggerExtensions.<CallWithCatchAsync>d__11`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
System.InvalidCastException: Unable to cast object of type 'Microsoft.VisualStudioTools.TestAdapter.TestContainer' to type 'Microsoft.VisualStudio.TestWindow.Client.TestContainer.DefaultTestContainer'.
   at System.Linq.Enumerable.<CastIterator>d__97`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.VisualStudio.TestWindow.Controller.RunOperation.<RunTestsAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.TestWindow.Controller.RunOperation.<RunTestsAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Controller.Operation.<<ExecuteAsync>b__43_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Logging.ILoggerExtensions.<CallWithCatchAsync>d__11`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by linette-zyy** [comment]
And The test failed to run and debug.
When run and debug the test, the error message display:
![image](https://user-images.githubusercontent.com/59192491/155453867-e1d0e025-cb0a-4a10-a619-308013139f56.png)

**Comment by linette-zyy** [comment]
This issue is also reproduced on pytest.
![image](https://user-images.githubusercontent.com/59192491/155492000-6cedfdff-8d02-44f4-bac6-865bac258442.png)

**Comment by ttSpace** [comment]
In today's build ```17.2.0 Preview 2.0 [32301.385.main]``, this problem does not occur.

**Comment by AdamYoblick** [comment]
If this doesn't occur anymore, I'm going to close this out. Please re-open or open a new issue if it occurs again. Thanks!
