### ISSUE TITLE
An error pops up after clicking Add environment.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6976]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/165426986-3f9e4418-af73-4a5e-8ce4-0decefb64664.png)

**Steps to Reproduce**
1. Create a new Python application
2. Right click Python Environments  -> Add Environment
![image](https://user-images.githubusercontent.com/59192491/165206339-8eef9969-b9bd-4029-9c1d-cafc993d6329.png)
3. Observes

**Expected behavior**
Add environment window pops up.

**Additional context and screenshots**
An error pops up after clicking Add environment.
![image](https://user-images.githubusercontent.com/59192491/165206216-2f18b65d-2559-4a38-b66e-8be3403603b8.png)

**log**
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Expanded Information]
```
Build: 17.0.22114.1

System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Microsoft.VisualStudio.PlatformUI.SetupPackagesCache.GetPackages(String& language, DateTime& installDate, DateTime& lastUpdatedDate, Uri& currentReleaseUri, String& currentProductDisplayVersion, String& currentProductDisplayName)
   at Microsoft.VisualStudio.PlatformUI.SetupPackagesCache.Refresh()
   at Microsoft.VisualStudio.PlatformUI.SetupPackagesCache..ctor()
   at Microsoft.VisualStudio.PlatformUI.SetupPackagesCache.<>c.<.cctor>b__36_0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Microsoft.VisualStudio.PlatformUI.SetupCompositionService.GetSetupPackagesInfo(UInt32 numberofPackages, IVsSetupPackageInfo[] packageInfo, UInt32& pcActual)
   at Microsoft.PythonTools.Environments.AddInstalledEnvironmentView.GetPackages(IVsSetupCompositionService setupService)
   at Microsoft.PythonTools.Environments.AddInstalledEnvironmentView..ctor(IServiceProvider serviceProvider, ProjectView[] projects, ProjectView selectedProject)
   at Microsoft.PythonTools.Environments.AddEnvironmentDialog.<ShowDialogAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Environments.AddEnvironmentDialog.<ShowAddVirtualEnvironmentDialogAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Environments.AddEnvironmentDialog.<ShowAddEnvironmentDialogAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
```

**Comment by AdamYoblick** [comment]
I can't repro this on the latest int preview.

@linette-zyy , can you please try this again on the latest? Here's my version:

![image](https://user-images.githubusercontent.com/29436557/165373176-8abe7459-b90e-4ad0-95f9-b59edc7abd57.png)

**Comment by linette-zyy** [comment]
@AdamYoblick 
I verified on the latest build and found this issue still occurred.
![image](https://user-images.githubusercontent.com/59192491/165426865-921e5ed7-e077-4142-9e9e-d7256662155a.png)
![image](https://user-images.githubusercontent.com/59192491/165426898-e37d300e-d672-4bab-8621-54d7c76dec68.png)

**Comment by AdamYoblick** [comment]
I can't repro this on the latest version. @linette-zyy , does this still happen to you? I just fixed a different bug where I was adding environments all day long.

Does it occur after adding a new environment? Is it only when choosing "Add installed environment" instead of "add virtual environment"?

**Comment by linette-zyy** [comment]
@AdamYoblick 
I can't repro this on the latest version. "add virtual environment"; "add conda environment"; "add existing environment"; "add installed environment" are all normal
