### ISSUE TITLE
Building a Python env crashes the program.

### ISSUE THREAD

**Issue by CyberJester** [microsoft/PTVS#6989]
**Describe the bug**
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 17.0.21344.1

System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Python310\Lib'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.EnumerateDirectories(String path, String searchPattern, SearchOption searchOption)
   at Microsoft.PythonTools.Interpreter.PackageManagerFactoryExtensions.<GetModulesInLib>d__1.MoveNext()
   at Microsoft.PythonTools.Interpreter.PackageManagerFactoryExtensions.<>c__DisplayClass0_0.<HasModuleAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Interpreter.PackageManagerFactoryExtensions.<HasModuleAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Environments.AddVirtualEnvironmentView.<UpdateInterpreterAsync>d__107.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Steps to Reproduce**
1.clone the repository at https://github.com/CorentinJ/Real-Time-Voice-Cloning.
2.open the demo_toolbox.py in the editor.
3. Message bar appears under the main menu bar that says ""Python package specification file 'requirements.txt' was detected in project 'Real-Time-Voice-Cloning".
4. click the "Create virtual enviroment" link in the bar.
5. See attached image for what all the settings were on the Add enviroment page.
6. the problem "seems" to have fixed itself. all I did differently was add a description for the enviroment and it work fine.
7. Wierd bug maybe?

![5-2-2022 10-43-56 PM](https://user-images.githubusercontent.com/25764573/166398104-7bfff705-f164-410f-befc-d90835bc06bb.png)

**Comment by StellaHuang95** [comment]
Hi @CyberJester, to answer your question posted on 5/6,  "name" specifies the path on disk and is typically something like "env" or ".venv". You can't change it once you've created it, while the description is a readable name (e.g. "Python 3.10 64-bit") that is more useful in the Environments window. Making the venv available globally will put it in that list, and you're likely only doing that if you want it to be separate from any particular project, which means it won't have that context. A venv in a project is obviously related to that project, but one outside of it might be for a single tool, or a particular configuration, and so the description might be the only reminder of what it's for. But I agree that this UI could have been designed better.:blush: Hope that answers your question.
