### ISSUE TITLE
Failed to launch debug adapter.  Additional information may be available in the output window. An unexpected error occurred in devenv.exe 

### ISSUE THREAD

**Issue by spring-jo** [microsoft/PTVS#7008]
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 16.11.21196.2

System.InvalidOperationException: Operation cannot be started because pip is not installed in the environment at 'C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3312.0_x64__qbz5n2kfra8p0'.
   at Microsoft.PythonTools.Interpreter.PipPackageManager.<AbortIfNotReady>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Interpreter.PipPackageManager.<InstallAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Project.TestFrameworkInfoBar.<InstallPyTestAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Project.TestFrameworkInfoBar.<InstallPytestActionAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by spring-jo** [comment]
---------------------------
Initial message
---------------------------
Failed to launch debug adapter.  Additional information may be available in the output window.



Access is denied
---------------------------

**Comment by AdamYoblick** [comment]
Hi @spring-jo ! Based on the environment path you provided, this looks like a bug specific to the Microsoft store install of python. Can you verify a couple things for me please?

- Does this repro in VS 16.11 with python installed from python.org instead of through the Microsoft Store?
- Does this repro in the latest VS 17.X with python installed from the Microsoft Store? (I ask this because I fixed some related bugs in VS2022 and this looks very much like one of them)

Thank you!

**Comment by spring-jo** [comment]
It's VS 2019 Community version, 16.11, and the python version I have problem with is 3.9 and it was installed using Microsoft store.

The scenario is: I started the program then stopped it using Close "x", immediately before the program start running, chose another startup item and when I pressed run again the error showed up.
  
Apparently VS does not have any problem with python 3.7 as it works fine with me.

Another thing is that I deleted python 3.9, and now whenever I try to download it from the store it fails at installation time and it give me this "Code: 0x80073D0A".

**Comment by AdamYoblick** [comment]
Can you please try with python 3.9 downloaded from python.org? Or try with VS2022?

**Comment by spring-jo** [comment]
Thank you, I tried python from python.org and it's working.

**Comment by AdamYoblick** [comment]
No problem at all, I will report this to the windows store team and close out this issue.
