### ISSUE TITLE
VS2022 Debugger Does Not Enumerate ctypes Arrays

### ISSUE THREAD

**Issue by TheRealQuantam** [microsoft/PTVS#7133]
**Describe the bug**
The debugger in Visual Studio 2022 does not treat ctypes arrays as containers, and hovering over them or looking at them in the variables window does not show length or allow the items to be enumerated like a list or dict. This is a new problem in VS2022, and did not occur in VS2017 or VS2019, which is why I've only recently started using VS2022 and this problem is making it very unpleasant as I use ctypes extensively in my work.

Ordinarily I would post in a forum to ask if there is some setting that's set incorrectly (the settings are default for Python), but as there's no forum here I'm making a bug report.

**Steps to Reproduce**
For me this occurs any and all times I use ctypes arrays in any context, so I don't really have any specific instructions to reproduce. The only thing worth noting is that this occurs regardless of whether "Enable debugging of the Python standard library" is enabled (I mostly work with it enabled). Maybe read a random binary file into a bytearray and do something like

x = (ctypes.c_uint8 * len(file_bytes)).from_buffer(file_bytes)

Then hover over x (or look at it in the variables window). It will only show "special variables" and "protected variables".

**Expected behavior**
In past VS versions the debugger would display as if it was a list, showing the length and list of all elements.

**Configuration information**
VS Version: Community 2022 (64-bit) 17.3.0
PTVS version: 17.0.22179.3
Python version: 3.9 64-bit (x64)
Debugger Type: I don't think this is relevant for VS2022?

**Comment by AdamYoblick** [comment]
I wasn't even able to get past the `import ctypes` statement in VS.

Here's the code I ran:

```python
import ctypes

prime_numbers = [2, 3, 5, 7]
byte_array = bytearray(prime_numbers)
x = (ctypes.c_uint8 * len(byte_array)).from_buffer(byte_array)

print(x)
```

Here's vscode running this just fine:

![image](https://user-images.githubusercontent.com/29436557/186035092-b60103a3-220d-4adc-8383-81d89af59783.png)

But when I try the same code in VS, I get an exception from the debugger process:

![image](https://user-images.githubusercontent.com/29436557/186035179-211dc5bb-72f4-4ece-8854-5d715584f947.png)

```
Traceback (most recent call last):
  File "C:\Users\advolker\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\advolker\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\users\advolker\appdata\local\microsoft\visualstudio\17.0_f467929dexp\extensions\microsoft corporation\python\17.0.0\debugpy\__main__.py", line 37, in <module>
    from debugpy.server import cli
  File "c:\users\advolker\appdata\local\microsoft\visualstudio\17.0_f467929dexp\extensions\microsoft corporation\python\17.0.0\debugpy/..\debugpy\server\__init__.py", line 7, in <module>
    import debugpy._vendored.force_pydevd  # noqa
  File "c:\users\advolker\appdata\local\microsoft\visualstudio\17.0_f467929dexp\extensions\microsoft corporation\python\17.0.0\debugpy/..\debugpy\_vendored\force_pydevd.py", line 36, in <module>
    preimport('pydevd', [
  File "c:\users\advolker\appdata\local\microsoft\visualstudio\17.0_f467929dexp\extensions\microsoft corporation\python\17.0.0\debugpy/..\debugpy\_vendored\__init__.py", line 126, in preimport
    import_module(name)
  File "C:\Users\advolker\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "c:\users\advolker\appdata\local\microsoft\visualstudio\17.0_f467929dexp\extensions\microsoft corporation\python\17.0.0\debugpy\_vendored\pydevd\pydevd.py", line 45, in <module>
    from _pydevd_bundle import pydevd_utils
  File "c:\users\advolker\appdata\local\microsoft\visualstudio\17.0_f467929dexp\extensions\microsoft corporation\python\17.0.0\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_utils.py", line 9, in <module>
    import ctypes
  File "C:\Users\advolker\source\repos\ctypes\ctypes\ctypes.py", line 6, in <module>
    x = (ctypes.c_uint8 * len(byte_array)).from_buffer(byte_array)
AttributeError: partially initialized module 'ctypes' has no attribute 'c_uint8' (most likely due to a circular import)
Press any key to continue . . .
```

And if I try to remove the import statement, I get an error that ctypes is not defined.

**Comment by AdamYoblick** [comment]
@int19h Are you able to look into this whenever you can? I'm not really sure what's going on here.

**Comment by TheRealQuantam** [comment]
Very strange that you can't import ctypes in VS. At least it looks like you're able to reproduce it on VSCode. In VS _length_ is hidden away under "protected variables" (as with all variables that start with _), but your image doesn't show enumeration of entries.

**Comment by int19h** [comment]
@AdamYoblick The error is because your sample is named ctypes.py, so when you `import ctypes` it imports itself.

Aside from that I'm pretty sure the behavior is identical between VS and VSCode - we don't do anything special in debugpy that'd make a difference. 

ctypes arrays have `len()` and are iterable though, so not showing items is a bug for sure.

**Comment by AdamYoblick** [comment]
> @AdamYoblick Adam Yoblick FTE The error is because your sample is named ctypes.py, so when you `import ctypes` it imports itself.

aaaand I feel like a fool 😆 

@TheRealQuantam I see what you're saying about the variable data being presented in a slightly different way.

Here's VSCode:

![image](https://user-images.githubusercontent.com/29436557/186228038-a0a297b4-aebd-4d98-a524-164fd2ebb8da.png)

And here's VS:

![image](https://user-images.githubusercontent.com/29436557/186228105-a40349d5-6f0e-449d-af58-6c34963abff0.png)

This has to do with Visual Studio variable presentation options found in `Tools -> Options -> Python -> Debugging`.

If you don't want protected variables to be shown in a group, select `Inline` for that option, then restart debugging:

![image](https://user-images.githubusercontent.com/29436557/186228439-02208dd5-1d62-47a7-905a-ae703625d0cb.png)

Then the view will look like VSCode:

![image](https://user-images.githubusercontent.com/29436557/186228524-c6d207aa-3b53-4ed6-bb29-c6f2ca3b8a69.png)


Please let me know if this fixes your issue and I can close this out :)

**Comment by AdamYoblick** [comment]
@int19h I was under the impression that VSCode used group for everything, but it sounds like it uses inline for some things. I'd like to change the default behavior of VS to match VSCode. Can you please point me to variable presentation options passed to debugpy from VSCode if the user doesn't change anything?

**Comment by int19h** [comment]
VSCode doesn't actually wire it up in any special way - whatever is in launch.json is flown through as is, and if it's not there, debugpy defaults are used, which are to group everything except for "protected":

https://github.com/microsoft/debugpy/blob/db43846a8d053199c27eda599c28f95c504dd7e6/src/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_api.py#L72-L74

Note though that showing `_length_` as an attribute directly under the variable is separate from showing the actual items and length for a collection. If you expand `prime_numbers` in the repro, you'll see all the items, and length represented as a synthetic member `len()`. This is what the ctypes array should be doing as well.

**Comment by AdamYoblick** [comment]
Ok so I'll create a new issue to have protected variables be presented as Inline, to match the vs code defaults. And I'll move this issue to debugpy per Pavel's instructions.
