### ISSUE TITLE
One warning pops up when validate Javascript completions in a <script> section

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7164]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/190328264-4599c639-261a-48e5-bf4b-beb1275042de.png)

**Steps to Reproduce**
1.Launch VS and create a Django Web Project
2.Validate html completions in app/about.html
3.Javascript completions in a <script> section
4.Define a int variable myvar

**Actual behavior**
![image](https://user-images.githubusercontent.com/59192491/190329510-8f88aa7b-1531-4138-9c8a-50a6a06fce55.png)
![warnings_script](https://user-images.githubusercontent.com/59192491/190329109-66bdb3da-4ee6-478e-8e9d-dcc00036cbf6.gif)

**Show Stack Trace**
```
System.InvalidOperationException : Unexpected null - line 90
   at Roslyn.Utilities.Contract.Fail(String message,Int32 lineNumber)
   at Roslyn.Utilities.Contract.ThrowIfNull[T](T value,Int32 lineNumber)
   at async Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.RentServiceAsync[TService](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at async Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.TryInvokeAsync[TService](<Unknown Parameters>)
```

**Comment by StellaHuang95** [comment]
This is not a PTVS issue, the "Task List" not available issue occurs on all projects in Visual Studio.
