### ISSUE TITLE
AccessViolationException when deleting a profiling performance session

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#723]
VS 2015, PTVS 2.2 RTM

I had 3 profiling sessions in Python Performance tool window, and started removing (delete option) 2 of the sessions.  Instead of deleting the 3rd session, I decided to remove its report instead.

![profiling-crash](https://cloud.githubusercontent.com/assets/1696845/9211273/da27b492-4035-11e5-967f-9acd9b8f4777.png)

After I clicked delete, I was able to debug in VS and see the following call stack:

```
System.AccessViolationException was unhandled
  HResult=-2147467261
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=Microsoft.VisualStudio.Shell.Interop
  StackTrace:
       at Microsoft.VisualStudio.Shell.Interop.IVsHierarchyEvents.OnInvalidateItems(UInt32 itemidParent)
       at Microsoft.PythonTools.Profiling.BaseHierarchyNode.OnInvalidateItems(UInt32 itemidParent)
       at Microsoft.PythonTools.Profiling.SessionNode.DeleteItem(UInt32 dwDelItemOp, UInt32 itemid)
       at Microsoft.VisualStudio.OLE.Interop.IOleCommandTarget.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
       at Microsoft.VisualStudio.Platform.WindowManagement.DocumentObjectSite.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
       at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
       at Microsoft.VisualStudio.Shell.Interop.IVsUIDataSource.Invoke(String verb, Object pvaIn, Object& pvaOut)
       at Microsoft.Internal.VisualStudio.PlatformUI.DataSource.Invoke(String verb, Object pvaIn, Object& pvaOut)
       at Microsoft.VisualStudio.PlatformUI.VsCommand.Execute(Object parameter)
       at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
       at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.DispatcherOperation.InvokeImpl()
       at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Windows.Threading.DispatcherOperation.Invoke()
       at System.Windows.Threading.Dispatcher.ProcessQueue()
       at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       at Microsoft.VisualStudio.PlatformUI.NativeMethods.DispatchMessage(MSG& lpmsg)
       at Microsoft.VisualStudio.Platform.WindowManagement.WindowManagerService.<>c.<PushMessageLoopOnContextMenuTrackingComponent>b__218_1(Object sender, PreTranslateMessageEventArgs args)
       at Microsoft.VisualStudio.PlatformUI.OleComponentSupport.OleComponent.FPreTranslateMessageCore(MSG[] pMsg)
       at Microsoft.VisualStudio.PlatformUI.OleComponentSupport.OleComponent.<>c__DisplayClass23_0.<Microsoft.VisualStudio.OLE.Interop.IOleComponent.FPreTranslateMessage>b__0()
       at Microsoft.VisualStudio.PlatformUI.OleComponentSupport.OleComponent.CallAndReturnOnException(Func`1 method, Int32 retValueOnException)
       at Microsoft.VisualStudio.PlatformUI.OleComponentSupport.OleComponent.Microsoft.VisualStudio.OLE.Interop.IOleComponent.FPreTranslateMessage(MSG[] pMsg)
       at Microsoft.VisualStudio.OLE.Interop.IOleComponentManager.FPushMessageLoop(UInt32 dwComponentID, UInt32 uReason, IntPtr pvLoopData)
       at Microsoft.VisualStudio.Platform.WindowManagement.WindowManagerService.PushMessageLoopOnContextMenuTrackingComponent()
       at Microsoft.VisualStudio.Shell.Interop.IVsUIShell.ShowContextMenu(UInt32 dwCompRole, Guid& rclsidActive, Int32 nMenuId, POINTS[] pos, IOleCommandTarget pCmdTrgtActive)
       at Microsoft.PythonTools.Profiling.SessionNode.ExecCommand(UInt32 itemid, Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
  InnerException: 
```

**Comment by zooba** [comment]
I can't reproduce this. I wonder if it was a VS specific issue that's been resolved in an update?

**Comment by huguesv** [comment]
I can't repro either (on VS 2017).
