### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by poodit** [microsoft/PTVS#7399]
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[V] Show details  [Close]

[Expanded Information]
```
Build: 16.5.20041.1

System.ArgumentException: Unsupported Python version: 3.9 ---> System.InvalidOperationException: Unsupported Python version: 3.9
   at Microsoft.PythonTools.Parsing.PythonLanguageVersionExtensions.ToLanguageVersion(Version version)
   at Microsoft.PythonTools.Interpreter.Ast.AstPythonInterpreterFactory..ctor(InterpreterConfiguration config, InterpreterFactoryCreationOptions options, Boolean useDefaultDatabase)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   --- End of inner exception stack trace ---
   at Microsoft.PythonTools.Interpreter.Ast.AstPythonInterpreterFactory..ctor(InterpreterConfiguration config, InterpreterFactoryCreationOptions options, Boolean useDefaultDatabase)
   at Microsoft.PythonTools.Interpreter.InterpreterFactoryCreator.CreateInterpreterFactory(InterpreterConfiguration configuration, InterpreterFactoryCreationOptions options)
   at Microsoft.PythonTools.Interpreter.MSBuildProjectInterpreterFactoryProvider.ConfiguredFactoryInfo.CreateFactory()
   at Microsoft.PythonTools.Interpreter.MSBuildProjectInterpreterFactoryProvider.GetInterpreterFactory(String id)
   at Microsoft.PythonTools.Interpreter.InterpreterRegistryService.FindInterpreter(String id)
   at Microsoft.PythonTools.Project.PythonProjectNode.<get_InterpreterFactories>b__69_0(InterpreterConfiguration x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.PythonTools.Project.CondaEnvCreateProjectInfoBar.<CheckAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Project.PythonProjectNode.<TriggerInfoBarsAsync>d__106.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
```

**Comment by StellaHuang95** [comment]
Hi @poodit, could you try updating to the latest version of VS and see if that repros? If so, could you provide repro steps so that we can further investigate? Thanks!

**Comment by StellaHuang95** [comment]
Going to close this out. If the issue still persists, please reopen with the information requested. Thanks.😊
