### ISSUE TITLE
Test Explorer could not find the test.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#7573]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/236388284-c358d7b9-c9a7-476e-8ec5-48fcfbc3f80e.png)

**Steps to Reproduce**

1. Create a Python Application project.
2. Right-click project, select Add > New Item …, then select "Python Unit Test" followed by "Add".
3. Add test_1.py file with code
```
import unittest

class Test_test_1(unittest.TestCase):
    def test_A(self):
        self.fail("Not implemented")

if __name__ == '__main__':
    unittest.main()

```
4. Set Test framework as "unittest" in python project properties page.
5. Open TE with the Test > Windows > Test Explorer menu command

**Expected behavior**

Test Explorer successfully found the tests.

**Additional context and screenshots**

Test Explorer did not find test. BTW, Can't find tests using **pytest** framework either.

![image](https://user-images.githubusercontent.com/82852072/236389816-b641762a-dd2c-4d34-be5a-0d934349a3e7.png)

## Output

<details>

<summary>Output for <code>Tests</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Tests</code>)
</summary>

<p>

```
Log level is set to Informational (Default).
Source code repository not available. Some features may not work as expected.
Connected to test environment '< Local Windows Environment >'
Test data store opened in 0.052 sec.
Downloaded solution cache containers in 0.085 sec.
Loaded 0 test records from 0 solution cache containers in 0.222 sec.
Aborting test discovery because solution is being closed.
Source code repository not available. Some features may not work as expected.
Microsoft.TestPlatform.VsTestConsole.TranslationLayer.TransationLayerException: C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\ServiceHub\Hosts\ServiceHub.Host.AnyCPU\ServiceHub.TestWindowStoreHost.exe process failed to connect to vstest.console process after 90 seconds. This may occur due to machine slowness, please set environment variable VSTEST_CONNECTION_TIMEOUT to increase timeout.
   at Microsoft.TestPlatform.VsTestConsole.TranslationLayer.VsTestConsoleWrapper.WaitForConnection() in /_/src/Microsoft.TestPlatform.VsTestConsole.TranslationLayer/VsTestConsoleWrapper.cs:line 1043
   at Microsoft.TestPlatform.VsTestConsole.TranslationLayer.VsTestConsoleWrapper.EnsureInitialized() in /_/src/Microsoft.TestPlatform.VsTestConsole.TranslationLayer/VsTestConsoleWrapper.cs:line 1019
   at Microsoft.TestPlatform.VsTestConsole.TranslationLayer.VsTestConsoleWrapper.InitializeExtensions(IEnumerable`1 pathToAdditionalExtensions) in /_/src/Microsoft.TestPlatform.VsTestConsole.TranslationLayer/VsTestConsoleWrapper.cs:line 263
   at Microsoft.VisualStudio.TestWindow.Messaging.RemoteAgent.BaseTestAgentBridge.InitializeExtensionsAsync(IEnumerable`1 extensions)
   at Microsoft.VisualStudio.TestWindow.Host.TestPlatformAgentPool.<>c__DisplayClass26_0.<<UpdateAgentUnderRequestPumpAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Utilities.EventPumpExtensions.<>c__DisplayClass4_0`1.<<EnqueueAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Extensibility.TaskCompletionSourceExtensions.<RunTaskWithCatchAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Logging.ILoggerExtensions.<CallWithCatchAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Host.TestWindowStoreService.<>c__DisplayClass38_0.<<InitializeExtensionsAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Logging.ILoggerExtensions.<CallWithCatchAsync>d__10.MoveNext()
Microsoft.TestPlatform.VsTestConsole.TranslationLayer.TransationLayerException: C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\ServiceHub\Hosts\ServiceHub.Host.AnyCPU\ServiceHub.TestWindowStoreHost.exe process failed to connect to vstest.console process after 90 seconds. This may occur due to machine slowness, please set environment variable VSTEST_CONNECTION_TIMEOUT to increase timeout.
   at Microsoft.TestPlatform.VsTestConsole.TranslationLayer.VsTestConsoleWrapper.WaitForConnection() in /_/src/Microsoft.TestPlatform.VsTestConsole.TranslationLayer/VsTestConsoleWrapper.cs:line 1043
   at Microsoft.TestPlatform.VsTestConsole.TranslationLayer.VsTestConsoleWrapper.EnsureInitialized() in /_/src/Microsoft.TestPlatform.VsTestConsole.TranslationLayer/VsTestConsoleWrapper.cs:line 1019
   at Microsoft.TestPlatform.VsTestConsole.TranslationLayer.VsTestConsoleWrapper.InitializeExtensions(IEnumerable`1 pathToAdditionalExtensions) in /_/src/Microsoft.TestPlatform.VsTestConsole.TranslationLayer/VsTestConsoleWrapper.cs:line 263
   at Microsoft.VisualStudio.TestWindow.Messaging.RemoteAgent.BaseTestAgentBridge.InitializeExtensionsAsync(IEnumerable`1 extensions)
   at Microsoft.VisualStudio.TestWindow.Host.TestPlatformAgentPool.<>c__DisplayClass26_0.<<UpdateAgentUnderRequestPumpAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Utilities.EventPumpExtensions.<>c__DisplayClass4_0`1.<<EnqueueAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Extensibility.TaskCompletionSourceExtensions.<RunTaskWithCatchAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Logging.ILoggerExtensions.<CallWithCatchAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Host.TestWindowStoreService.<>c__DisplayClass38_0.<<InitializeExtensionsAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Logging.ILoggerExtensions.<CallWithCatchAsync>d__10.MoveNext()
Test data store opened in 0.001 sec.
========== Starting test discovery ==========
Microsoft.TestPlatform.VsTestConsole.TranslationLayer.TransationLayerException: C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\ServiceHub\Hosts\ServiceHub.Host.AnyCPU\ServiceHub.TestWindowStoreHost.exe process failed to connect to vstest.console process after 90 seconds. This may occur due to machine slowness, please set environment variable VSTEST_CONNECTION_TIMEOUT to increase timeout.
   at Microsoft.TestPlatform.VsTestConsole.TranslationLayer.VsTestConsoleWrapper.WaitForConnection() in /_/src/Microsoft.TestPlatform.VsTestConsole.TranslationLayer/VsTestConsoleWrapper.cs:line 1043
   at Microsoft.TestPlatform.VsTestConsole.TranslationLayer.VsTestConsoleWrapper.EnsureInitialized() in /_/src/Microsoft.TestPlatform.VsTestConsole.TranslationLayer/VsTestConsoleWrapper.cs:line 1007
   at Microsoft.TestPlatform.VsTestConsole.TranslationLayer.VsTestConsoleWrapper.DiscoverTests(IEnumerable`1 sources, String discoverySettings, TestPlatformOptions options, ITestDiscoveryEventsHandler2 discoveryEventsHandler) in /_/src/Microsoft.TestPlatform.VsTestConsole.TranslationLayer/VsTestConsoleWrapper.cs:line 289
   at Microsoft.VisualStudio.TestWindow.Messaging.RemoteAgent.SessionController.VsTestConsoleRunner.DiscoverTestsAsync(IEnumerable`1 sources, String discoverySettings, TestPlatformOptions options, ITestDiscoveryEventsHandler2 eventHandler, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestWindow.Messaging.RemoteAgent.SessionController.<>c__DisplayClass23_0.<DiscoverTestsAsync>b__1(IGrouping`2 grp)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Threading.Tasks.Task.WhenAll(IEnumerable`1 tasks)
   at Microsoft.VisualStudio.TestWindow.Messaging.RemoteAgent.SessionController.DiscoverTestsAsync(IEnumerable`1 sources, String discoverySettings, TestPlatformOptions options, ITestDiscoveryEventsHandler2 eventHandler, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestWindow.Messaging.RemoteAgent.BaseTestAgentBridge.<DiscoverTestsAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.TestWindow.Host.TestPlatformProvider.<DiscoverTestsAsync>d__21.MoveNext()
========== Test discovery aborted: 0 Tests found in 1.5 min ==========
========== Starting test discovery ==========
Microsoft.TestPlatform.VsTestConsole.TranslationLayer.TransationLayerException: C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\ServiceHub\Hosts\ServiceHub.Host.AnyCPU\ServiceHub.TestWindowStoreHost.exe process failed to connect to vstest.console process after 90 seconds. This may occur due to machine slowness, please set environment variable VSTEST_CONNECTION_TIMEOUT to increase timeout.
   at Microsoft.TestPlatform.VsTestConsole.TranslationLayer.VsTestConsoleWrapper.WaitForConnection() in /_/src/Microsoft.TestPlatform.VsTestConsole.TranslationLayer/VsTestConsoleWrapper.cs:line 1043
   at Microsoft.TestPlatform.VsTestConsole.TranslationLayer.VsTestConsoleWrapper.EnsureInitialized() in /_/src/Microsoft.TestPlatform.VsTestConsole.TranslationLayer/VsTestConsoleWrapper.cs:line 1007
   at Microsoft.TestPlatform.VsTestConsole.TranslationLayer.VsTestConsoleWrapper.DiscoverTests(IEnumerable`1 sources, String discoverySettings, TestPlatformOptions options, ITestDiscoveryEventsHandler2 discoveryEventsHandler) in /_/src/Microsoft.TestPlatform.VsTestConsole.TranslationLayer/VsTestConsoleWrapper.cs:line 289
   at Microsoft.VisualStudio.TestWindow.Messaging.RemoteAgent.SessionController.VsTestConsoleRunner.DiscoverTestsAsync(IEnumerable`1 sources, String discoverySettings, TestPlatformOptions options, ITestDiscoveryEventsHandler2 eventHandler, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestWindow.Messaging.RemoteAgent.SessionController.<>c__DisplayClass23_0.<DiscoverTestsAsync>b__1(IGrouping`2 grp)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Threading.Tasks.Task.WhenAll(IEnumerable`1 tasks)
   at Microsoft.VisualStudio.TestWindow.Messaging.RemoteAgent.SessionController.DiscoverTestsAsync(IEnumerable`1 sources, String discoverySettings, TestPlatformOptions options, ITestDiscoveryEventsHandler2 eventHandler, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestWindow.Messaging.RemoteAgent.BaseTestAgentBridge.<DiscoverTestsAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.TestWindow.Host.TestPlatformProvider.<DiscoverTestsAsync>d__21.MoveNext()
========== Test discovery aborted: 0 Tests found in 1.5 min ==========
========== Starting test discovery ==========
Microsoft.TestPlatform.VsTestConsole.TranslationLayer.TransationLayerException: C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\ServiceHub\Hosts\ServiceHub.Host.AnyCPU\ServiceHub.TestWindowStoreHost.exe process failed to connect to vstest.console process after 90 seconds. This may occur due to machine slowness, please set environment variable VSTEST_CONNECTION_TIMEOUT to increase timeout.
   at Microsoft.TestPlatform.VsTestConsole.TranslationLayer.VsTestConsoleWrapper.WaitForConnection() in /_/src/Microsoft.TestPlatform.VsTestConsole.TranslationLayer/VsTestConsoleWrapper.cs:line 1043
   at Microsoft.TestPlatform.VsTestConsole.TranslationLayer.VsTestConsoleWrapper.EnsureInitialized() in /_/src/Microsoft.TestPlatform.VsTestConsole.TranslationLayer/VsTestConsoleWrapper.cs:line 1007
   at Microsoft.TestPlatform.VsTestConsole.TranslationLayer.VsTestConsoleWrapper.DiscoverTests(IEnumerable`1 sources, String discoverySettings, TestPlatformOptions options, ITestDiscoveryEventsHandler2 discoveryEventsHandler) in /_/src/Microsoft.TestPlatform.VsTestConsole.TranslationLayer/VsTestConsoleWrapper.cs:line 289
   at Microsoft.VisualStudio.TestWindow.Messaging.RemoteAgent.SessionController.VsTestConsoleRunner.DiscoverTestsAsync(IEnumerable`1 sources, String discoverySettings, TestPlatformOptions options, ITestDiscoveryEventsHandler2 eventHandler, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestWindow.Messaging.RemoteAgent.SessionController.<>c__DisplayClass23_0.<DiscoverTestsAsync>b__1(IGrouping`2 grp)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Threading.Tasks.Task.WhenAll(IEnumerable`1 tasks)
   at Microsoft.VisualStudio.TestWindow.Messaging.RemoteAgent.SessionController.DiscoverTestsAsync(IEnumerable`1 sources, String discoverySettings, TestPlatformOptions options, ITestDiscoveryEventsHandler2 eventHandler, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestWindow.Messaging.RemoteAgent.BaseTestAgentBridge.<DiscoverTestsAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.TestWindow.Host.TestPlatformProvider.<DiscoverTestsAsync>d__21.MoveNext()
========== Test discovery aborted: 0 Tests found in 1.5 min ==========
========== Starting test discovery ==========
Microsoft.TestPlatform.VsTestConsole.TranslationLayer.TransationLayerException: C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\ServiceHub\Hosts\ServiceHub.Host.AnyCPU\ServiceHub.TestWindowStoreHost.exe process failed to connect to vstest.console process after 90 seconds. This may occur due to machine slowness, please set environment variable VSTEST_CONNECTION_TIMEOUT to increase timeout.
   at Microsoft.TestPlatform.VsTestConsole.TranslationLayer.VsTestConsoleWrapper.WaitForConnection() in /_/src/Microsoft.TestPlatform.VsTestConsole.TranslationLayer/VsTestConsoleWrapper.cs:line 1043
   at Microsoft.TestPlatform.VsTestConsole.TranslationLayer.VsTestConsoleWrapper.EnsureInitialized() in /_/src/Microsoft.TestPlatform.VsTestConsole.TranslationLayer/VsTestConsoleWrapper.cs:line 1007
   at Microsoft.TestPlatform.VsTestConsole.TranslationLayer.VsTestConsoleWrapper.DiscoverTests(IEnumerable`1 sources, String discoverySettings, TestPlatformOptions options, ITestDiscoveryEventsHandler2 discoveryEventsHandler) in /_/src/Microsoft.TestPlatform.VsTestConsole.TranslationLayer/VsTestConsoleWrapper.cs:line 289
   at Microsoft.VisualStudio.TestWindow.Messaging.RemoteAgent.SessionController.VsTestConsoleRunner.DiscoverTestsAsync(IEnumerable`1 sources, String discoverySettings, TestPlatformOptions options, ITestDiscoveryEventsHandler2 eventHandler, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestWindow.Messaging.RemoteAgent.SessionController.<>c__DisplayClass23_0.<DiscoverTestsAsync>b__1(IGrouping`2 grp)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Threading.Tasks.Task.WhenAll(IEnumerable`1 tasks)
   at Microsoft.VisualStudio.TestWindow.Messaging.RemoteAgent.SessionController.DiscoverTestsAsync(IEnumerable`1 sources, String discoverySettings, TestPlatformOptions options, ITestDiscoveryEventsHandler2 eventHandler, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestWindow.Messaging.RemoteAgent.BaseTestAgentBridge.<DiscoverTestsAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.TestWindow.Host.TestPlatformProvider.<DiscoverTestsAsync>d__21.MoveNext()
========== Test discovery aborted: 0 Tests found in 1.5 min ==========
========== Starting test discovery ==========
Microsoft.TestPlatform.VsTestConsole.TranslationLayer.TransationLayerException: C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\ServiceHub\Hosts\ServiceHub.Host.AnyCPU\ServiceHub.TestWindowStoreHost.exe process failed to connect to vstest.console process after 90 seconds. This may occur due to machine slowness, please set environment variable VSTEST_CONNECTION_TIMEOUT to increase timeout.
   at Microsoft.TestPlatform.VsTestConsole.TranslationLayer.VsTestConsoleWrapper.WaitForConnection() in /_/src/Microsoft.TestPlatform.VsTestConsole.TranslationLayer/VsTestConsoleWrapper.cs:line 1043
   at Microsoft.TestPlatform.VsTestConsole.TranslationLayer.VsTestConsoleWrapper.EnsureInitialized() in /_/src/Microsoft.TestPlatform.VsTestConsole.TranslationLayer/VsTestConsoleWrapper.cs:line 1007
   at Microsoft.TestPlatform.VsTestConsole.TranslationLayer.VsTestConsoleWrapper.DiscoverTests(IEnumerable`1 sources, String discoverySettings, TestPlatformOptions options, ITestDiscoveryEventsHandler2 discoveryEventsHandler) in /_/src/Microsoft.TestPlatform.VsTestConsole.TranslationLayer/VsTestConsoleWrapper.cs:line 289
   at Microsoft.VisualStudio.TestWindow.Messaging.RemoteAgent.SessionController.VsTestConsoleRunner.DiscoverTestsAsync(IEnumerable`1 sources, String discoverySettings, TestPlatformOptions options, ITestDiscoveryEventsHandler2 eventHandler, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestWindow.Messaging.RemoteAgent.SessionController.<>c__DisplayClass23_0.<DiscoverTestsAsync>b__1(IGrouping`2 grp)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Threading.Tasks.Task.WhenAll(IEnumerable`1 tasks)
   at Microsoft.VisualStudio.TestWindow.Messaging.RemoteAgent.SessionController.DiscoverTestsAsync(IEnumerable`1 sources, String discoverySettings, TestPlatformOptions options, ITestDiscoveryEventsHandler2 eventHandler, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestWindow.Messaging.RemoteAgent.BaseTestAgentBridge.<DiscoverTestsAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.TestWindow.Host.TestPlatformProvider.<DiscoverTestsAsync>d__21.MoveNext()
========== Test discovery aborted: 0 Tests found in 1.5 min ==========
```

</p>
</details>

**Comment by StellaHuang95** [comment]
Test explorer team has an active issue tracking this. https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1813742?src=WorkItemMention&src-action=artifact_link. Closing it as it's not ours to fix.
