### ISSUE TITLE
Error while enumerating installed packages.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#7720]
**Describe the bug**

![image](https://github.com/microsoft/PTVS/assets/82852072/be2dd9af-3175-46a5-ac14-a4ae1463f884)

**Steps to Reproduce**

1. Create a Python Application project.
2. Type
```
import debugpy
print(debugpy.__version__)
debugpy.listen(("localhost", 5678))
debugpy.wait_for_client()
print('hello')
```
3. Set a breakpoint on the ```print('hello')```. 
4. Start Without Debugging.

**Expected behavior**
 
No error.

**Additional context and screenshots**

Error while enumerating installed packages.

![image](https://github.com/microsoft/PTVS/assets/82852072/b8b42b8b-fd43-4b91-8722-0b9849f72172)

## Logs

<details>
<p>

```
1.7.0
E+00000.047: Error while enumerating installed packages.

             Traceback (most recent call last):
               File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\debugpy\common\log.py", line 361, in get_environment_description
                 report("    {0}=={1}\n", pkg.name, pkg.version)
             AttributeError: 'PathDistribution' object has no attribute 'name'

             Stack where logged:
               File "C:\Users\vting\source\repos\PythonApplication2\PythonApplication2\PythonApplication2.py", line 4, in <module>
                 debugpy.listen(("localhost", 5678))
               File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\debugpy\public_api.py", line 31, in wrapper
                 return wrapped(*args, **kwargs)
               File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\debugpy\server\api.py", line 122, in debug
                 ensure_logging()
               File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\debugpy\server\api.py", line 61, in ensure_logging
                 log.describe_environment("Initial environment:")
               File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\debugpy\common\log.py", line 369, in describe_environment
                 info("{0}", get_environment_description(header))
               File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\debugpy\common\log.py", line 363, in get_environment_description
                 swallow_exception("Error while enumerating installed packages.")
               File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\debugpy\common\log.py", line 215, in swallow_exception
                 _exception(format_string, *args, **kwargs)
```

</p>
</details>

**Comment by StellaHuang95** [comment]
Could you also install the `importlib-metadata` and try again?
