### ISSUE TITLE
Unexpected Error

### ISSUE THREAD

**Issue by Action25** [microsoft/PTVS#7880]
**Describe the bug**
Happens when I open my assignemnt in Visual Studio 2022

[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 17.0.23262.1

System.ObjectDisposedException: Cannot access a disposed object.
   at Microsoft.VisualStudioTools.Project.ProjectNode.GetMsBuildProperty(String propertyName, Boolean resetCache)
   at Microsoft.VisualStudioTools.Project.ProjectNode.GetProjectProperty(String propertyName, Boolean resetCache)
   at Microsoft.PythonTools.Project.CondaEnvCreateProjectInfoBar.<CheckAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
```

**Comment by StellaHuang95** [comment]
Thanks for reporting the issue. Is your code in a public repo or could you provide code samples that help us repro this issue? Does this repro constantly for you? Could you also share your conda env?

**Comment by StellaHuang95** [comment]
Thanks for the report. Unfortunately, this is not enough information for us to investigate this issue. If the issue still persists, please reopen with the information requested. Thanks.
