### ISSUE TITLE
NullReferenceError getting IronPython signature

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#791]
Got this exception while bringing up signature help on an IronPython static method:

```
System.NullReferenceException: Object reference not set to an instance of an object.
 at Microsoft.PythonTools.Intellisense.SignatureHelpSource.AugmentSignatureHelpSession(ISignatureHelpSession session, IList`1 signatures) in D:\PTVS\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\SignatureHelpSource.cs:line 49
 at Microsoft.VisualStudio.Language.Intellisense.Implementation.SignatureHelpSession.Recalculate()
 at Microsoft.VisualStudio.Language.Intellisense.Implementation.SignatureHelpSession.Start()
 at Microsoft.VisualStudio.Language.Intellisense.Implementation.SignatureHelpBroker.TriggerSignatureHelp(ITextView textView)
 at Microsoft.PythonTools.Intellisense.IntellisenseController.TriggerSignatureHelp() in D:\PTVS\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\IntellisenseController.cs:line 767
 at Microsoft.PythonTools.Intellisense.IntellisenseController.OpenParenStartSignatureSession() in D:\PTVS\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\IntellisenseController.cs:line 603
 at Microsoft.PythonTools.Intellisense.IntellisenseController.HandleChar(Char ch) in D:\PTVS\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\IntellisenseController.cs:line 216
 at Microsoft.PythonTools.Intellisense.IntellisenseController.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) in D:\PTVS\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\IntellisenseController.cs:line 864
 at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
 at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
 at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.SendCommand(Guid cmdGroup, UInt32 cmdID, Object inParam)
 at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.TextInput(TextCompositionEventArgs args)
 at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c.<DispatchTextInputEvents>b__6_0(KeyProcessor p, TextCompositionEventArgs args)
 at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c__DisplayClass10_1`1.<Dispatch>b__0()
 at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)
```

**Comment by zooba** [comment]
Cannot repro, and the location according to the stack trace is a standard code pattern that is used throughout VS - some other state must have been corrupted when the error occurred.
