### ISSUE TITLE
Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED)) [FindActiveProjectCfg @ SolutionBuildManager.cs:2222]

### ISSUE THREAD

**Issue by aschiffl** [microsoft/PTVS#7930]
**Describe the bug**
Error dialog when launching solution.

```
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
Build: 17.0.24064.1

Microsoft.VisualStudio.CommonIDE.Solutions.HResultExtensions+WrapperCOMException (0x8000FFFF): Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED)) [FindActiveProjectCfg @ SolutionBuildManager.cs:2222] ---> System.Runtime.InteropServices.COMException (0x8000FFFF): Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED)) [FindActiveProjectCfg @ SolutionBuildManager.cs:2222]
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudioTools.Project.ProjectNode.SetCurrentConfiguration()
   at Microsoft.PythonTools.Project.PythonProjectNode.SetCurrentConfiguration()
   at Microsoft.VisualStudioTools.Project.ProjectNode.GetMsBuildProperty(String propertyName, Boolean resetCache)
   at Microsoft.VisualStudioTools.Project.ProjectNode.GetProjectProperty(String propertyName, Boolean resetCache)
   at Microsoft.PythonTools.Project.CondaEnvCreateProjectInfoBar.<CheckAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
```

**Configuration information**

Installed Version: Enterprise

ASP.NET and Web Tools   17.10.341.11210
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.10.341.11210
Azure App Service Tools v3.0.0

C# Tools   4.10.0-3.24303.7+bef690dda43733707d7dccea9868fe51f34eb8a0
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   17.0.24064.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

GitHub Copilot   0.2.889.30432
GitHub Copilot is an AI pair programmer that helps you write code faster and with less work.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

NuGet Package Manager   6.10.1
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Python - Profiling support   17.0.24064.1
Profiling support for Python projects.

Python with Pylance   17.0.24064.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Razor (ASP.NET Core)   17.10.3.2427201+4f57d1de251e654812adde201c0265a8ca7ca31d
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.10.172.0
Microsoft SQL Server Data Tools

TypeScript Tools   17.0.30327.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.10.0-3.24303.7+bef690dda43733707d7dccea9868fe51f34eb8a0
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.10.0-beta.24228.1+dd749058c91585e9b5dae62b0f8df892429ee28f
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

**Comment by StellaHuang95** [comment]
Thanks for reporting the issue. Is your code in a public repo or could you provide code samples that help us repro this issue? Does this repro constantly for you? Could you also share more detailed repro steps? Thanks!

**Comment by aschiffl** [comment]
Internal repository, so can't share.  Repro's 100%.

Repro steps: open solution from command line (i.e., type XYZ.sln in repo root and hit enter). Error dialog shows during the load of approx. 100 subprojects of different types including C# and python. Solution completes loading and projects do not seem to be affected once error dialog has been dismissed.

**Comment by SerinitySW** [comment]
Unfortunately, I am also having this issue, also with an internal repo. It doesn't seem to be happening on anyone else's devices.

```
Build: 17.0.24064.1

Microsoft.VisualStudio.CommonIDE.Solutions.HResultExtensions+WrapperCOMException (0x8000FFFF): Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED)) [FindActiveProjectCfg @ SolutionBuildManager.cs:2222] ---> System.Runtime.InteropServices.COMException (0x8000FFFF): Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED)) [FindActiveProjectCfg @ SolutionBuildManager.cs:2222]
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudioTools.Project.ProjectNode.SetCurrentConfiguration()
   at Microsoft.PythonTools.Project.PythonProjectNode.SetCurrentConfiguration()
   at Microsoft.VisualStudioTools.Project.ProjectNode.GetMsBuildProperty(String propertyName, Boolean resetCache)
   at Microsoft.VisualStudioTools.Project.ProjectNode.GetProjectProperty(String propertyName, Boolean resetCache)
   at Microsoft.PythonTools.Project.CondaEnvCreateProjectInfoBar.<CheckAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
```

**Comment by SerinitySW** [comment]
Resolved by deleting the .vs folder from the project directory.

**Comment by StellaHuang95** [comment]
The same crash has been reported multiple times and I think we should fix it. 

The stack trace is a good starting point. ` at Microsoft.PythonTools.Project.CondaEnvCreateProjectInfoBar.<CheckAsync>d__4.MoveNext()`

**Comment by judej** [comment]
This is not a Python issue and has been seen in C++ as well. The solution there too has been to delete the .vs folder from the project directory as @SerinitySW discovered.
