### ISSUE TITLE
Cannot run all tests in a large number of tests.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#7984]
**Describe the bug**

![image](https://github.com/user-attachments/assets/0251189c-1340-4db6-8208-3265da801da0)

**Steps to Reproduce**

1. "New Project->Python->From Existing Python code" to bring up dialog
2. Select a folder that contains multiple tests. 
(**Note**: You can copy tests from the python distribution ```/lib/test```, such as ```C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\Lib\test```）
4. Open a "test_*.py" file to enable unittest.
5. Wait for tests to be discovered and run all tests.

**Expected behavior**

All tests should load and run successfully.

**Additional context and screenshots**

Some tests did not run.

![image](https://github.com/user-attachments/assets/3f1ab8bf-c403-4754-8c35-a16b8e50fb26)

## Logs

<details>

<summary>Output for <code>Tests</code> in the <code>Output</code> panel 
</summary>

<p>

```
Log level is set to Informational (Default).
Connected to test environment '< Local Windows Environment >'
Source code repository not available. Some features may not work as expected.
Test data store opened in 0.005 sec.
========== Starting test discovery ==========
Starting unittest discovery for the Folder4 project. This can take up to 60 seconds.
cd C:\Users\vting\source\repos\Folder4\
set PYTHONPATH=C:\Users\vting\source\repos\Folder4\
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\python.exe C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\PREVIEW\COMMON7\IDE\EXTENSIONS\MICROSOFT\PYTHON\CORE\PythonFiles\testing_tools\run_adapter.py discover unittest --output-file C:\Users\vting\AppData\Local\Temp\tmp3469.tmp -- . test*.py
========== Test discovery finished: 1295 Tests found in 4.9 sec ==========
========== Starting test run ==========
cd C:\Users\vting\source\repos\Folder4\
set PYTHONPATH=C:\Users\vting\source\repos\Folder4;C:\Users\vting\source\repos\Folder4\
"C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\python.exe" "C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\PREVIEW\COMMON7\IDE\EXTENSIONS\MICROSOFT\PYTHON\CORE\visualstudio_py_testlauncher.py" --test-list C:\Users\vting\AppData\Local\Temp\tmp6D4B.tmp -r 59071
Connected to socket
Connection event fired
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\unittest\case.py", line 592, in run
    self._callTestMethod(testMethod)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\unittest\case.py", line 550, in _callTestMethod
    method()
  File "C:\Users\vting\source\repos\Folder4\test_baseexception.py", line 31, in test_inheritance
    inheritance_tree = open(os.path.join(os.path.split(__file__)[0],
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\vting\\source\\repos\\Folder4\\exception_hierarchy.txt'
AVAILABLE_TARGETS = []
EXPECTED_C_LOCALE_EQUIVALENTS = ['C', 'invalid.ascii']
EXPECTED_C_LOCALE_STREAM_ENCODING = 'ascii'
EXPECTED_C_LOCALE_FS_ENCODING = 'ascii'
EXPECT_COERCION_IN_DEFAULT_LOCALE = True
_C_UTF8_LOCALES = ('C.UTF-8', 'C.utf8', 'UTF-8')
_check_nl_langinfo_CODESET = False
========== Test run finished: 518 Tests (505 Passed, 1 Failed, 12 Skipped) run in 23.1 sec ==========

```

</p>
</details>

[Tests.zip](https://github.com/user-attachments/files/16671421/Tests.zip)

**Comment by StellaHuang95** [comment]
@ttSpace Does this still repro?

**Comment by ttSpace** [comment]
@StellaHuang95  I can repro in today's build.

![Image](https://github.com/user-attachments/assets/ccee4b37-7cc7-4f5c-aa5f-1f72cae15afa)
