### ISSUE TITLE
VS Crashes When Loading Cookie Template.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#7995]
**Describe the bug**

![image](https://github.com/user-attachments/assets/c4e25919-8e92-455f-99c6-2e0696c97242)

**Steps to Reproduce**

1. Launch VS.
2. Click "View->Cookiecutter Explorer".
3. Load Cookie template under Github or Recommended.

**Expected behavior**

It should load successfully.

**Additional context and screenshots**

VS Crashes When Loading Cookie Template.

![crash](https://github.com/user-attachments/assets/25f4dbe1-24a0-4d63-9d02-4157ad836334)

## Logs

<details>

<summary>Log for <code>Event Viewer</code> in the <code>General</code> panel 
</summary>

<p>

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: Microsoft.CookiecutterTools.Model.ProcessException
   at Microsoft.CookiecutterTools.Model.CookiecutterClient+<WaitForOutput>d__45.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.CookiecutterTools.Model.CookiecutterClient+<CreateVenvWithoutPipThenInstallPip>d__16.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.CookiecutterTools.Model.CookiecutterClient+<CreateCookiecutterEnv>d__12.MoveNext()

Exception Info: Microsoft.CookiecutterTools.Infrastructure.CriticalException
   at Microsoft.CookiecutterTools.Model.CookiecutterClient+<CreateCookiecutterEnv>d__12.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.CookiecutterTools.ViewModel.CookiecutterViewModel+<EnsureCookiecutterIsInstalledAsync>d__216.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.CookiecutterTools.ViewModel.CookiecutterViewModel+<RefreshContextAsync>d__219.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.CookiecutterTools.ViewModel.CookiecutterViewModel+<LoadTemplateAsync>d__201.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.CookiecutterTools.Infrastructure.VSTaskExtensions+<HandleAllExceptions>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.CookiecutterTools.Infrastructure.TaskExtensions.ReThrowTaskException(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

```

</p>
</details>

**Comment by linette-zyy** [comment]
This issue is also repro on today's build.
![Image](https://github.com/user-attachments/assets/2b428d44-cd6a-4217-b106-55a21492a37f)

**Comment by ttSpace** [comment]
I can repro this in today's build.

![Image](https://github.com/user-attachments/assets/c80c2ce8-892e-42d4-8504-051942441b47)

**Comment by StellaHuang95** [comment]
@ttSpace Does this still repro? I can't seem to repro. Did you log in your github account?

**Comment by ttSpace** [comment]
@StellaHuang95 I can't repro in today's build, and I didn't log into my GitHub account.

![Image](https://github.com/user-attachments/assets/72c5f1d6-c794-4b27-83a6-3443e62289c3)
