### ISSUE TITLE
Issues Attaching Debugger to Python Application

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#8052]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Issues-Attaching-Debugger-to-Python-Appl/10778955)._

---
We have an Embedded Python specific application that we can’t use breakpoints when attaching with the debugger using Visual Studio 2022. Visual Studio 2017 does not have the issue.

We can successfully debug with Python 3.7.7 and Visual Studio 2017 with breakpoints using these steps:

1.  Run the application
2.  In Visual Studio 2017, go to Debug &gt; Attach to Process
3.  Set connection type: as local
4.  Set Code type to Python code

We can successfully attach to the process, but not use breakpoints, with Visual Studio 2022 with these steps:

1.  Run the application
2.  In Visual Studio, go to Debug &gt; Attach to Process
3.  Set connection type: as local
4.  Set Code type to Python (native) code

If we use Python code instead of Python (native), we get the following error or something similar:

“Failed to launch debug adapter. Timed out waiting for debug server to connect.”

If we compile the application and run the debugger through the sln, we can debug the C++ code.  We cant debug py code this way either.

---
#### Tim Lakdawala on 10/30/2024, 08:56 AM: 

(private comment, text removed)
#### Tim Lakdawala on 10/30/2024, 09:02 AM: 

(private comment, text removed)
#### Feedback Bot on 10/30/2024, 09:39 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
#### Feedback Bot solved on 10/30/2024, 04:57 PM, undefined votes: 

<p>Thanks for taking the time to report this issue! It seems to us that it’s describing the same thing as another one. We’ve closed this one as a duplicate and transferred all votes from this ticket to the other one. Please follow along on the linked ticket to communicate with the team, see updates on status, and help provide any needed diagnostic info. For more information, see our <a target='_blank' href="https://aka.ms/vsfeedbackguidelines">issue reporting guidelines</a>.</p>
<p>Happy coding!</p>

#### Tim Lakdawala on 10/31/2024, 03:06 AM: 

<p>Could we please get a link to the ticket this was moved over to? I don’t see one in the resolution.</p>

#### Tim Lakdawala on 10/31/2024, 06:13 AM: 

<p>I never received the link to the other ticket so I can’t confirm if they are different.</p>

#### Lisa Gao (CSI Interfusion Inc) [MSFT] on 11/1/2024, 01:14 PM: 

<p>Hi, this issue was traced by <a target='_blank' href="https://github.com/microsoft/PTVS/issues/6993">https://github.com/microsoft/PTVS/issues/6993</a>.</p>

#### Tim Lakdawala on 11/2/2024, 01:18 AM: 

<p>Hey Lisa,</p>
<p>Thanks for sharing the github issue.  The issue isnt exactly our issue.  In our case we are attempting to attach to an already compiled exe that has embedded python.  Can we please have this request reopened?</p>

**Comment by rchiodo** [comment]
Thanks for the issue. I'm going to need some more information to diagnose the problem.

First, what version of Python are you using? Second, are you attaching with just the Python debugger or are you using Python(Native) (or mixed mode).

**Comment by tlakdawala** [comment]
Hey rchiodo,

Thanks for the quick response.  First question is there an expectation when Python 3.10 will be supported by Native debugging?

We have run into this issue with both Python 3.7.7 and 3.10.  Below is some additional output.  Please let me know what else I can provide.

```
Attaching to PID: 39428 (elapsed: 1.01s).
Attaching to PID: 39428 (elapsed: 2.02s).
Attaching to PID: 39428 (elapsed: 3.03s).
Attaching to PID: 39428 (elapsed: 4.05s).
Attaching to PID: 39428 (elapsed: 5.05s).
Attaching to PID: 39428 (elapsed: 6.06s).
Attaching to PID: 39428 (elapsed: 7.07s).
Attaching to PID: 39428 (elapsed: 8.09s).
Attaching to PID: 39428 (elapsed: 9.10s).
Attaching to PID: 39428 (elapsed: 10.11s).
--- Starting attach to pid: 39428 ---
--- Connecting to 64 bits target (current process is: 64) ---
--- Injecting attach dll: attach_amd64.dll into pid: 39428 ---
Running executable to inject dll.
OpenProcess with pid: 39428
VirtualAllocEx in pid: 39428
WriteProcessMemory in pid: 39428
loadLibraryAddress: 39428
Waiting for LoadLibraryA to complete.
Ok, finished dll injection.
--- Injecting run code dll: run_code_on_dllmain_amd64.dll into pid: 39428 ---
Running executable to inject dll.
OpenProcess with pid: 39428
VirtualAllocEx in pid: 39428
WriteProcessMemory in pid: 39428
loadLibraryAddress: 39428
Waiting for LoadLibraryA to complete.
Ok, finished dll injection.
Attaching to PID: 39428 (elapsed: 11.11s).
Attaching to PID: 39428 (elapsed: 12.12s).
Attaching to PID: 39428 (elapsed: 13.14s).
Attaching to PID: 39428 (elapsed: 14.15s).
From Embedded Python App..
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:program filesmicrosoft visual studio2022professionalcommon7deextensionsmicrosoftpythoncoredebugpy/..debugpyserverattach_pid_injected.py", line 90, in attach
    log.reraise_exception()
  File "c:program filesmicrosoft visual studio2022professionalcommon7deextensionsmicrosoftpythoncoredebugpy/..debugpyserverattach_pid_injected.py", line 77, in attach
    debugpy.connect(
  File "c:program filesmicrosoft visual studio2022professionalcommon7deextensionsmicrosoftpythoncoredebugpypublic_api.py", line 31, in wrapper
    return wrapped(*args, **kwargs)
  File "c:program filesmicrosoft visual studio2022professionalcommon7deextensionsmicrosoftpythoncoredebugpyserverapi.py", line 143, in debug
    log.reraise_exception("{0}() failed:", func.__name__, level="info")
  File "c:program filesmicrosoft visual studio2022professionalcommon7deextensionsmicrosoftpythoncoredebugpyserverapi.py", line 141, in debug
    return func(address, settrace_kwargs, **kwargs)
  File "c:program filesmicrosoft visual studio2022professionalcommon7deextensionsmicrosoftpythoncoredebugpyserverapi.py", line 297, in connect
    _settrace(host=host, port=port, client_access_token=access_token, **settrace_kwargs)
  File "c:program filesmicrosoft visual studio2022professionalcommon7deextensionsmicrosoftpythoncoredebugpyserverapi.py", line 45, in _settrace
    return pydevd.settrace(*args, **kwargs)
  File "c:program filesmicrosoft visual studio2022professionalcommon7deextensionsmicrosoftpythoncoredebugpy_vendoredpydevdpydevd.py", line 2821, in settrace
    _locked_settrace(
  File "c:program filesmicrosoft visual studio2022professionalcommon7deextensionsmicrosoftpythoncoredebugpy_vendoredpydevdpydevd.py", line 2902, in _locked_settrace
    py_db.connect(host, port)  # Note: connect can raise error.
  File "c:program filesmicrosoft visual studio2022professionalcommon7deextensionsmicrosoftpythoncoredebugpy_vendoredpydevdpydevd.py", line 1421, in connect
    s = start_client(host, port)
  File "c:program filesmicrosoft visual studio2022professionalcommon7deextensionsmicrosoftpythoncoredebugpy_vendoredpydevd_pydevd_bundlepydevd_comm.py", line 493, in start_client
    s.connect((host, port))
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
```

**Comment by rchiodo** [comment]
That callstack looks like you're doing plain 'Python' debugging, not mixed mode. That would require python to actually be loaded in the embedded app before attaching. 

In VS 2022 we switched how our debugging works. 

For normal python debugging (non mixed mode), we use something called https://github.com/Microsoft/DEBUGPY. Debugpy is a soft-mode debugger, meaning it runs using APIs provided by the python runtime in order to debug. If the Python runtime isn't started yet, you'd get the error you show above.

For mixed mode debugging (also called Python Native), we use the [concord](https://github.com/Microsoft/ConcordExtensibilitySamples/wiki/Overview) to implement a hard-mode debugger that uses the native C++ debugger in VS to listen to Windows debug events. 

You might also be selecting both types of debugging at the same time. That isn't necessary. If you want to debug in mixed mode, just pick `Python (Native)` and `Native` in this drop down:

![Image](https://github.com/user-attachments/assets/a80514ee-9086-42cc-bc2c-1673f10c3deb)

**Comment by rchiodo** [comment]
Support for 3.10/11/12/13 is a work in progress for mixed mode. Not sure when it will ship.

**Comment by tlakdawala** [comment]
We did mixed mode debugging (Native and Python (native)) using both 3.7.7 and 3.10 with VS2022.  It connects but if you set a breakpoint in the Python code it will not stop at the breakpoint. We don't get any other output.

Is there any log we can check for more information?

**Comment by tlakdawala** [comment]
"That callstack looks like you're doing plain 'Python' debugging, not mixed mode. That would require python to actually be loaded in the embedded app before attaching."

The main developer wanted to also provide a note for this comment.  The embedded Python is loaded before attaching.  We utilize the PyObject_CallObject to first run our script.  Further calls to PyObject_CallObject occur due to Window OS events such, as button presses.  None of breakpoints are hit on these.

**Comment by rchiodo** [comment]
With mixed mode you can actually just debug the C++ app from the start. That might fix the breakpoints binding. There was a bug in 3.9 mixed mode where breakpoints wouldn't bind during attach. Launching would have fixed that problem. Maybe there's something wrong in 3.7.

3.10 shouldn't work at all. I'd be surprised if the debugger even started.

Ideally if you could share your app, I could just debug the problem. 

You could also try the sample app we have here and see if attach works. I wrote it to debug another customer's attach situation.
https://github.com/microsoft/PTVS/tree/main/Examples/PythonNative

**Comment by rchiodo** [comment]
I'm not entirely sure `PyObject_CallObject` loads the full runtime in order for debugpy (non mixed mode) to attach. I'd need a piece of sample code to verify.

But mixed mode should work regardless how you load Python.

**Comment by tlakdawala** [comment]
Thanks for this info.  The Main dev is going to look at your mention of the bug above and the sample you provided.  He is also going to setup a Github account to be able to respond directly on the thread.

I am asking internally if we have permission to share the app.  Do you have a private upload location that we can use if we can?

**Comment by rchiodo** [comment]
>  Do you have a private upload location that we can use if we can?

Just my e-mail address. It's my github id at microsoft dot com.

**Comment by tlakdawala** [comment]
I confirmed with our Infosec team we are unable to share the app.  We can test the sample app instead.

**Comment by stevetm2w** [comment]
I took a look at the example code.  We perform some different steps when we first run a python script from our C++ code, as we are importing a module rather than running a simple file...

if (m_pModule)// finalize the last ran module (if there was one) just before reload
{
	Py_DECREF((PyObject *)m_pModule);
	Py_Finalize();
}
// other Py_SetPath and PyImport_AppendInittab code is here
Py_Initialize();
m_pModule = PyImport_ImportModule("Python_program");//name of the script to import
pFunc = PyObject_GetAttrString((PyObject*)m_pModule, "main"); // method ptr
PyObject_CallObject(pFunc, NULL);


We do have a number of embedded methods we regester using PyImport_AppendInittab and its callbacks.  Also, on exit we call the above Py_Finalize block.

**Comment by rchiodo** [comment]
None of that should matter if you're using mixed mode debugging. Mixed mode is actually all just a C++ debugger that displays C++ frames as their equivalent Python frames. 

It's only the normal Python debugging that might not work with those calls.

**Comment by stevetm2w** [comment]
"Launching would have fixed that problem. Maybe there's something wrong in 3.7." - so if I do launch the C++ app with embedded python 3.10, how do I tell it to use mixed mode?  I normally just press F5 to launch the C++ app btw...  I've only noticed the "Python (native)" and "Native" options when using the Attach method.

**Comment by rchiodo** [comment]
3.10 won't work as mixed mode isn't working for that yet. It should work for 3.7 but 3.9 would be the safest bet as that's gotten the most bug fixes in VS 2022.

In the Debugger properties for the vcxproj there should be an option to pick Python/Native debugging

![Image](https://github.com/user-attachments/assets/511728c4-20b5-4591-b181-15f459152a62)

**Comment by tlakdawala** [comment]
We were able to get Python 3.7.7 working with mixed mode debugging with the direct debugger and attach to process.  Thank you for all the helpful information!

Could we please get an update in this ticket once Python 3.10 is supported with mixed mode debugging?

**Comment by rchiodo** [comment]
Or you can just ping me here because I do get an e-mail every time somebody updates an issue I'm assigned.

**Comment by tlakdawala** [comment]
Sounds good! Ill set a reminder to watch out for it early next year.  I can ping you if we need to follow up.

**Comment by glechapelain** [comment]
Hi !

**Comment by stevetm2w** [comment]
Hey...  just wanted to add a note this comment from Tim "We were able to get Python 3.7.7 working with mixed mode debugging with the direct debugger and attach to process"...  this is true for VS2022, however I cannot change the execution line after hitting a breakpint, eg I cannot change the Py Program Counter via the "Set Next Statement" right click option.  Just a heads up on that, as that works with VS2017.

**Comment by rchiodo** [comment]
The old debugger was hacking CPython to let it do that:
https://github.com/microsoft/PTVS/blob/cfdced90c7834d9ff3260f90f651720ad8817422/Python/Product/PythonTools/visualstudio_py_debugger.py#L1919

It seems it could be possible to do the same in the new debugger though, just it was never implemented:
https://docs.python.org/3/reference/datamodel.html#frame.f_lineno

**Comment by rchiodo** [comment]
I'll enter a new bug to see how popular set next statement is.

**Comment by cbirace** [comment]
We are in need of the >= 3.10 fix as well.

**Comment by tlakdawala** [comment]
Hey rchiodo,

Wanted to check in and see if there is an updated ETA for 3.10 support with mixed mode?

**Comment by rchiodo** [comment]
It may already be out. It should have shipped with 17.13. I'm not sure if that's gone GA or not yet.

**Comment by rchiodo** [comment]
Yeah looks like it's already shipped:
https://devblogs.microsoft.com/visualstudio/visual-studio-2022-v17-13-is-now-available/

**Comment by tlakdawala** [comment]
Thanks we will confirm that this version adds the expected features.  If not, we will reopen the issue.

**Comment by tlakdawala** [comment]
Hey @rchiodo,

@stevetm2w has been testing with VS22 17.14.18 with mixed mode.  It works, but it seems to be inconsistent on attaching and regularly takes over 2.5 min to attach (compared to about 4 seconds with VS2017).  We wanted to see if we can get some help improving this.

Here are some example logs from the debugger when we are trying to attach:

```
Attaching to PID: 18404 (elapsed: 1.02s).
Attaching to PID: 18404 (elapsed: 2.02s).
Attaching to PID: 18404 (elapsed: 3.03s).
Attaching to PID: 18404 (elapsed: 4.04s).
Attaching to PID: 18404 (elapsed: 5.05s).
Attaching to PID: 18404 (elapsed: 6.06s).
Attaching to PID: 18404 (elapsed: 7.07s).
Attaching to PID: 18404 (elapsed: 8.07s).
Attaching to PID: 18404 (elapsed: 9.08s).
Attaching to PID: 18404 (elapsed: 10.09s).
--- Starting attach to pid: 18404 ---
--- Connecting to 64 bits target (current process is: 64) ---

--- Injecting attach dll: attach_amd64.dll into pid: 18404 ---
Running executable to inject dll.
OpenProcess with pid: 18404
VirtualAllocEx in pid: 18404
WriteProcessMemory in pid: 18404
loadLibraryAddress: 18404
Waiting for LoadLibraryA to complete.
Ok, finished dll injection.

--- Injecting run code dll: run_code_on_dllmain_amd64.dll into pid: 18404 ---
Running executable to inject dll.
OpenProcess with pid: 18404
VirtualAllocEx in pid: 18404
WriteProcessMemory in pid: 18404
loadLibraryAddress: 18404
Waiting for LoadLibraryA to complete.
Ok, finished dll injection.
Attaching to PID: 18404 (elapsed: 11.10s).
Attaching to PID: 18404 (elapsed: 12.10s).
Attaching to PID: 18404 (elapsed: 13.11s).
Attaching to PID: 18404 (elapsed: 14.13s).
Attaching to PID: 18404 (elapsed: 15.13s).
```

```
Traceback (most recent call last):
  File "c:program filesmicrosoft visual studio2022professionalcommon7deextensionsmicrosoftpythoncoredebugpy/..debugpyserverattach_pid_injected.py", line 77, in attach
    debugpy.connect(
  File "c:program filesmicrosoft visual studio2022professionalcommon7deextensionsmicrosoftpythoncoredebugpypublic_api.py", line 31, in wrapper
    return wrapped(*args, **kwargs)
  File "c:program filesmicrosoft visual studio2022professionalcommon7deextensionsmicrosoftpythoncoredebugpyserverapi.py", line 132, in debug
    log.reraise_exception("{0}() failed:", func.__name__, level="info")
  File "c:program filesmicrosoft visual studio2022professionalcommon7deextensionsmicrosoftpythoncoredebugpyserverapi.py", line 130, in debug
    return func(address, settrace_kwargs, **kwargs)
  File "c:program filesmicrosoft visual studio2022professionalcommon7deextensionsmicrosoftpythoncoredebugpyserverapi.py", line 296, in connect
    _settrace(host=host, port=port, client_access_token=access_token, **settrace_kwargs)
  File "c:program filesmicrosoft visual studio2022professionalcommon7deextensionsmicrosoftpythoncoredebugpyserverapi.py", line 45, in _settrace
    pydevd.settrace(*args, **kwargs)
  File "c:program filesmicrosoft visual studio2022professionalcommon7deextensionsmicrosoftpythoncoredebugpy_vendoredpydevdpydevd.py", line 3020, in settrace
    _locked_settrace(
  File "c:program filesmicrosoft visual studio2022professionalcommon7deextensionsmicrosoftpythoncoredebugpy_vendoredpydevdpydevd.py", line 3124, in _locked_settrace
    additional_info = set_additional_thread_info(t)
TypeError: 'NoneType' object is not callable
E+00012.141: Traceback (most recent call last):
               File "c:program filesmicrosoft visual studio2022professionalcommon7deextensionsmicrosoftpythoncoredebugpy/..debugpyserverattach_pid_injected.py", line 77, in attach
                 debugpy.connect(
               File "c:program filesmicrosoft visual studio2022professionalcommon7deextensionsmicrosoftpythoncoredebugpypublic_api.py", line 31, in wrapper
                 return wrapped(*args, **kwargs)
               File "c:program filesmicrosoft visual studio2022professionalcommon7deextensionsmicrosoftpythoncoredebugpyserverapi.py", line 132, in debug
                 log.reraise_exception("{0}() failed:", func.__name__, level="info")
               File "c:program filesmicrosoft visual studio2022professionalcommon7deextensionsmicrosoftpythoncoredebugpyserverapi.py", line 130, in debug
                 return func(address, settrace_kwargs, **kwargs)
               File "c:program filesmicrosoft visual studio2022professionalcommon7deextensionsmicrosoftpythoncoredebugpyserverapi.py", line 296, in connect
                 _settrace(host=host, port=port, client_access_token=access_token, **settrace_kwargs)
               File "c:program filesmicrosoft visual studio2022professionalcommon7deextensionsmicrosoftpythoncoredebugpyserverapi.py", line 45, in _settrace
                 pydevd.settrace(*args, **kwargs)
               File "c:program filesmicrosoft visual studio2022professionalcommon7deextensionsmicrosoftpythoncoredebugpy_vendoredpydevdpydevd.py", line 3020, in settrace
                 _locked_settrace(
               File "c:program filesmicrosoft visual studio2022professionalcommon7deextensionsmicrosoftpythoncoredebugpy_vendoredpydevdpydevd.py", line 3124, in _locked_settrace
                 additional_info = set_additional_thread_info(t)
             TypeError: 'NoneType' object is not callable
             
             Stack where logged:
               File "<string>", line 1, in <module>
               File "c:program filesmicrosoft visual studio2022professionalcommon7deextensionsmicrosoftpythoncoredebugpy/..debugpyserverattach_pid_injected.py", line 90, in attach
                 log.reraise_exception()
               File "c:program filesmicrosoft visual studio2022professionalcommon7deextensionsmicrosoftpythoncoredebugpycommonlog.py", line 222, in reraise_exception
                 _exception(format_string, *args, **kwargs)
             

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:program filesmicrosoft visual studio2022professionalcommon7deextensionsmicrosoftpythoncoredebugpy/..debugpyserverattach_pid_injected.py", line 90, in attach
    log.reraise_exception()
  File "c:program filesmicrosoft visual studio2022professionalcommon7deextensionsmicrosoftpythoncoredebugpy/..debugpyserverattach_pid_injected.py", line 77, in attach
    debugpy.connect(
  File "c:program filesmicrosoft visual studio2022professionalcommon7deextensionsmicrosoftpythoncoredebugpypublic_api.py", line 31, in wrapper
    return wrapped(*args, **kwargs)
  File "c:program filesmicrosoft visual studio2022professionalcommon7deextensionsmicrosoftpythoncoredebugpyserverapi.py", line 132, in debug
    log.reraise_exception("{0}() failed:", func.__name__, level="info")
  File "c:program filesmicrosoft visual studio2022professionalcommon7deextensionsmicrosoftpythoncoredebugpyserverapi.py", line 130, in debug
    return func(address, settrace_kwargs, **kwargs)
  File "c:program filesmicrosoft visual studio2022professionalcommon7deextensionsmicrosoftpythoncoredebugpyserverapi.py", line 296, in connect
    _settrace(host=host, port=port, client_access_token=access_token, **settrace_kwargs)
  File "c:program filesmicrosoft visual studio2022professionalcommon7deextensionsmicrosoftpythoncoredebugpyserverapi.py", line 45, in _settrace
    pydevd.settrace(*args, **kwargs)
  File "c:program filesmicrosoft visual studio2022professionalcommon7deextensionsmicrosoftpythoncoredebugpy_vendoredpydevdpydevd.py", line 3020, in settrace
    _locked_settrace(
  File "c:program filesmicrosoft visual studio2022professionalcommon7deextensionsmicrosoftpythoncoredebugpy_vendoredpydevdpydevd.py", line 3124, in _locked_settrace
    additional_info = set_additional_thread_info(t)
TypeError: 'NoneType' object is not callable
```

@stevetm2w also saw this behavior:

So it didnt connect but VS was sat thinking it was... so I clicked break, then a file (with the name 'ScriptDocument0 _string.txt") popped up in VS containing the below...  I saw this before and figured it was irrelevant.  But this time I did a single-step over all of that, then my "DEBUGGER ATTACHED" print popped up on the embedded python TTY!

`LOAD_CONST(0), LOAD_CONST(None), IMPORT_NAME(codecs), STORE_NAME(codecs), LOAD_CONST(0), LOAD_CONST(None), IMPORT_NAME(json), STORE_NAME(json), LOAD_CONST(0), LOAD_CONST(None), IMPORT_NAME(sys), STORE_NAME(sys),     LOAD_FAST(s), LOAD_CONST(None), IS_OP{1}, POP_JUMP_IF_FALSE(to 26), LOAD_GLOBAL(codecs), LOAD_METHOD(utf_8_decode), bytearray(s), CALL_METHOD{1}, LOAD_CONST(0), BINARY_SUBSCR, RETURN_VALUE, return |26|None, LOAD_CONST(code), LOAD_CONST('<lambda>'), MAKE_FUNCTION, STORE_NAME(decode), LOAD_NAME(decode), BUILD_LIST, LOAD_CONST((99, 58, 92, 112, 114, 111, 103, 114, 97, 109, 32, 102, 105, 108, 101, 115, 92, 109, 105, 99, 114, 111, 115, 111, 102, 116, 32, 118, 105, 115, 117, 97, 108, 32, 115, 116, 117, 100, 105, 111, 92, 50, 48, 50, 50, 92, 112, 114, 111, 102, 101, 115, 115, 105, 111, 110, 97, 108, 92, 99, 111, 109, 109, 111, 110, 55, 92, 105, 100, 101, 92, 101, 120, 116, 101, 110, 115, 105, 111, 110, 115, 92, 109, 105, 99, 114, 111, 115, 111, 102, 116, 92, 112, 121, 116, 104, 111, 110, 92, 99, 111, 114, 101, 92, 100, 101, 98, 117, 103, 112, 121, 47, 46, 46, 92, 100, 101, 98, 117, 103, 112, 121, 92, 115, 101, 114, 118, 101, 114)), LIST_EXTEND{1}, CALL_FUNCTION{1}, STORE_NAME(script_dir), LOAD_NAME(json), LOAD_METHOD(loads), LOAD_NAME(decode), BUILD_LIST, LOAD_CONST((123, 34, 109, 111, 100, 101, 34, 58, 32, 34, 99, 111, 110, 110, 101, 99, 116, 34, 44, 32, 34, 97, 100, 100, 114, 101, 115, 115, 34, 58, 32, 91, 34, 49, 50, 55, 46, 48, 46, 48, 46, 49, 34, 44, 32, 54, 48, 52, 48, 54, 93, 44, 32, 34, 119, 97, 105, 116, 95, 102, 111, 114, 95, 99, 108, 105, 101, 110, 116, 34, 58, 32, 102, 97, 108, 115, 101, 44, 32, 34, 108, 111, 103, 95, 116, 111, 34, 58, 32, 110, 117, 108, 108, 44, 32, 34, 97, 100, 97, 112, 116, 101, 114, 95, 97, 99, 99, 101, 115, 115, 95, 116, 111, 107, 101, 110, 34, 58, 32, 34, 55, 48, 98, 54, 55, 57, 51, 49, 98, 52, 48, 102, 48, 102, 102, 102, 53, 51, 56, 102, 54, 48, 97, 51, 51, 99, 50, 100, 50, 55, 100, 49, 100, 54, 55, 52, 98, 50, 98, 53, 53, 54, 57, 99, 48, 54, 101, 97, 53, 98, 101, 48, 55, 100, 49, 102, 55, 101, 49, 54, 57, 50, 53, 49, 34, 125)), LIST_EXTEND{1}, CALL_FUNCTION{1}, CALL_METHOD{1}, STORE_NAME(setup), LOAD_NAME(sys.path), LOAD_METHOD(insert), LOAD_CONST(0), LOAD_NAME(script_dir), CALL_METHOD{2}, POP_TOP, LOAD_CONST(0), LOAD_CONST(None), IMPORT_NAME(attach_pid_injected), STORE_NAME(attach_pid_injected), LOAD_NAME(sys.path), LOAD_CONST(0), DELETE_SUBSCR, LOAD_NAME(attach_pid_injected), LOAD_METHOD(attach), LOAD_NAME(setup), CALL_METHOD{1}, POP_TOP, return None`

**Comment by rchiodo** [comment]
Like I mentioned above, it looks like you're trying to attach just the python debugger, not the mixed mode debugger. Mixed mode debugger is really just a C++ debugger. It won't have all of those debugpy messages.

If you want mixed mode debugging pick these options in the attach dialog:

<img width="364" height="211" alt="Image" src="https://github.com/user-attachments/assets/56e23f97-8db6-42d9-bd46-c327f5055739" />

**Comment by tlakdawala** [comment]
Thanks for getting back to us @rchiodo.  @stevetm2w confirmed he was only using Python (native).  We swapped to mixed mode and ran into problems.  Here is what we saw:

1. Set the Native and Native (Python) options - it took a few seconds to connect
2. Set a breakpoint and then when we tried to hit it we received the following error:

<img width="300" height="129" alt="Image" src="https://github.com/user-attachments/assets/5f82e5b5-9f3f-41d3-bb8f-8b258d08d767" />

3. We don't get any additional output from the debugger
4. We then swapped back to Native (Python) only.  Now it takes 10 seconds (instead of the 2.5 min) and seems to be working after a few reconnects.

**Comment by rchiodo** [comment]
I'm not sure if conditional breakpoints are supported in mixed mode. Evaling the condition would be difficult given that the debugger is using native code and you'd want to eval a python condition. It might depend upon the condition. 

If you have a minimal repro, we can take a look and see.

**Comment by tlakdawala** [comment]
Hey @rchiodo,

Apologies for the super slow response.  @stevetm2w did some additional digging and was not able to get mixed mode working at all.  He was able to get the Python (Native) option working.  What he found is it was a timing issue. The Python app opens a port and Visual Studio checks consistently to see if its open.  If its not on the same timing they never connect.  He increased how often the check occurs and it seemed to have fixed it.

From our perspective, we can call this closed.  Thanks again for all your help!
