### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by ShanekaArm** [microsoft/PTVS#8097]
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[V] Show details  [Close]

[Expanded Information]
```
Build: 17.0.23262.1

System.ObjectDisposedException: Cannot access a disposed object.
   at Microsoft.VisualStudioTools.Project.ProjectNode.GetMsBuildProperty(String propertyName, Boolean resetCache)
   at Microsoft.VisualStudioTools.Project.ProjectNode.GetProjectProperty(String propertyName, Boolean resetCache)
   at Microsoft.PythonTools.Project.CondaEnvCreateProjectInfoBar.<CheckAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
```

**Comment by BE-Joerg-Gerigk** [comment]
Got the same error with Build: 17.0.24138.2 while creating a new micromamba env in powershell with VS running in the background

**Comment by StellaHuang95** [comment]
The problem is corruption in the .vs folder. Could you please delete the .vs folder in your project folder and see if the problem disappears?

When you delete the .vs folder, VS will rebuild it automatically when VS is restarted.

Please see https://github.com/microsoft/PTVS/issues/8027 for more details.

If this does not work, please reopen the issue. Thanks for raising this issue.
