### ISSUE TITLE
Unhandled exception in PythonNavigateToItemProvider

### ISSUE THREAD

**Issue by kunom** [Microsoft/PTVS#831]
I have several times the following entry in ActivityLog.xml of Visual Studio 2015. This is with PTVS 2.2.30718.00, the output of "Tools > Python Tools > Diagnostic Info" is available at [https://gist.github.com/kunom/c1e8d8457f62e9b4170c].

```
Unhandled exception in Microsoft.PythonTools.Navigation.NavigateTo.PythonNavigateToItemProvider.StartSearch (C:\PTVS\PTVS\Python\Product\PythonTools\PythonTools\Navigation\NavigateTo\PythonNavigateToItemProvider.cs:162)
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudioTools.VsTaskExtensions.<HandleAllExceptions>d__4.MoveNext()
```

**Comment by ditrytus** [comment]
I am using Visual Studio 2015 Community with Update 3 and Python Tools in version 2.2.4 and I still have this error when I type `ĆTRL+,`
```
Unhandled exception in Microsoft.PythonTools.Navigation.NavigateTo.PythonNavigateToItemProvider.StartSearch (D:\PTVS\PTVS22\Python\Product\PythonTools\PythonTools\Navigation\NavigateTo\PythonNavigateToItemProvider.cs:162)
System.ObjectDisposedException: The CancellationTokenSource has been disposed.
   at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
   at Microsoft.PythonTools.Navigation.NavigateTo.PythonNavigateToItemProvider.<>c__DisplayClass6_0.<StartSearch>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudioTools.VsTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
```

**Comment by zooba** [comment]
@ditrytus Thanks. It's actually a subtly different error (coming from inside the operation, whereas the previous one was outside the operation), so I'll file a new issue.
