### ISSUE TITLE
Unhandled exception in Microsoft.PythonTools.Navigation.NavigateTo.PythonNavigateToItemProvider.StartSearch

### ISSUE THREAD

**Issue by tmat** [Microsoft/PTVS#833]
Repro (not consistent)
- Open Roslyn.sln in VS with PTVS installed.
- Ctrl+Comma to search for a symbol. Enter some value.

From activity log:
```
  <entry>
    <record>696</record>
    <time>2015/09/13 17:57:54.841</time>
    <type>Error</type>
    <source>Python Tools for Visual Studio</source>
    <description>Unhandled exception in Microsoft.PythonTools.Navigation.NavigateTo.PythonNavigateToItemProvider.StartSearch (C:\PTVS\PTVS\Python\Product\PythonTools\PythonTools\Navigation\NavigateTo\PythonNavigateToItemProvider.cs:162)
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudioTools.VsTaskExtensions.&lt;HandleAllExceptions&gt;d__4.MoveNext()</description>
  </entry>
```

**Comment by zooba** [comment]
Dup of #831.
