### ISSUE TITLE
Intellisense Parsing Crashes/Hangs

### ISSUE THREAD

**Issue by nickos556** [Microsoft/PTVS#90]
I am using PTVS 2.2 RC with Visual Studio Express 2013, with the Anaconda v2.2.0 python distribution. I have added various thris party packages to my python environment via pip install. The intellsense parser runs for a while but then either hangs or crashes.
I have seen lots of similar issues reported.
Is there a wiki page somewhere that has tips for how to fix this issue? E.g. the first step in my mind is to find out which package it is failing to parse. Is there a log somewhere that contains this info?

**Comment by zooba** [comment]
Under the Tools, Python Tools, Diagnostic Info menu you'll find most of the information you need. There's usually a lot of content in there though, so feel free to post it in a gist and we'll take a look.

We really should set up a wiki, but in general the best thing to do is get in touch with us just like you have.

**Comment by nlassesen** [comment]
I have the same problem - also using PTVS 2.2 RC but on VS 2013 Professional. I also had the problem on VS2010 using PTVS 2.1 and 2.0.

The problem to me seems to be related to specific packages that fail - this is a dump of my most recent log, where it fails when saving info for the package 'enaml'. Removing that package allows the analyzer to continue until it meets another package that fails.

```
...
2015-05-05T09:59:37: Analyzing "enaml.workbench.ui.window_model"
2015-05-05T09:59:37: Analyzing "enaml.workbench.ui.workspace"
2015-05-05T09:59:37: Analyzing "enaml.workbench.ui"
2015-05-05T09:59:37: Starting analysis of 292 modules
2015-05-05T09:59:38: Analysis complete
2015-05-05T09:59:38: Saving group "C:\dev\Anaconda\lib\site-packages\enaml"
2015-05-05T09:59:39: [ERROR] Analysis failed
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GetMemberKind(AnalysisValue type, ModuleInfo declModule, Boolean isRef)
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GetMemberKind(AnalysisValue type, ModuleInfo declModule, Boolean isRef)
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GetMemberValue(IAnalysisSet types, ModuleInfo declModule, Boolean isRef)
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GenerateMember(VariableDef variableDef, ModuleInfo declModule, Boolean isRef)
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GetClassMembers(ClassInfo ci, ModuleInfo declModule)
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GenerateClass(ClassInfo ci, ModuleInfo declModule)
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GetMemberValueInternal(AnalysisValue type, ModuleInfo declModule, Boolean isRef)
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GetMemberValue(IAnalysisSet types, ModuleInfo declModule, Boolean isRef)
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GenerateMember(VariableDef variableDef, ModuleInfo declModule, Boolean isRef)
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GenerateMembers(ModuleInfo moduleInfo, IEnumerable`1 children)
   at Microsoft.PythonTools.Analysis.SaveAnalysis.SerializeModule(ModuleInfo moduleInfo)
   at Microsoft.PythonTools.Analysis.SaveAnalysis.Save(PythonAnalyzer state, String outDir)
   at Microsoft.PythonTools.Analysis.PyLibAnalyzer.Analyze()
   at Microsoft.PythonTools.Analysis.PyLibAnalyzer.<RunWorker>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Analysis.PyLibAnalyzer.<Run>d__30.MoveNext()
```

Until now I have worked around these errors by removing the packages that cause errors - fortunately I have only had these errors with packages that I currently do not need.

A nice feature would be if these errors would not cause the process to abort, but that they were logged and that the process could then continue looking at all the remaining packages

**Comment by zooba** [comment]
I agree it would be nice to continue, and we've probably got enough separation between high level tasks that we could make that work now.

At the time we decided to let these crashes propagate, it was because everything was so entwined that you'd get no useful behaviour at all, and people simply assumed that we sucked rather than having an obscure bug that we could fix if only someone would tell us about it :) (plus, nobody checks the logs unless something crashes, myself included...)

**Comment by zooba** [comment]
I think I have fixed this one in the latest builds... note to self to test against latest enaml.

**Comment by nickos556** [comment]
Great work Steve... I'm out of the office but will check on my return.

**Comment by nickos556** [comment]
Steve, I've installed dev build 2015-05-28 for VS 2013. The intellisense parser is still going round & round in an infinite loop, consuming 100% of one CPU. Obviously its crashing somewhere along the line. I have posted diagnostic info in this Gist. 
https://gist.github.com/nickos556/d4e1ef8af1b4f0f45398

Any ideas? Its making it very very difficult to use PTVs which is a shame as its a great product.

**Comment by zooba** [comment]
Looks like you've hit the next bug, which I've also fixed, but the 100% CPU is more concerning.

I assume you're looking in Task Manager? Do you see the memory usage changing for the analyzer process or is it staying completely static? Either way, what library is being analyzed at the time (you can see this inside VS in the Python Environments window)?

**Comment by nickos556** [comment]
Hi Steve, actually, the CPU usage has now stopped. It seems like maybe the
analyzer process tries 3 times and then gives up perhaps?
Could you make the analyzer process more tolerant of errors. E.g. if
analyzing a particular library causes it to throw an exception, it should
log this (with the name & location of the library of course), and then move
onto the next library.
At the moment, if it encounters a problem, it appears to crash. So, if i
have 200 libraries, and it crashes on #3, the remaining 197 libraries don't
get parsed, and I don't get intellisense information for them.
regards
Nick

**Comment by nickos556** [comment]
![image](https://cloud.githubusercontent.com/assets/8463492/7953953/5485c296-0a0e-11e5-8413-eee8dfaf65f8.png)

Steve, it looks like the analyzer seems to start automatically in the background... here is a screenshot of it using 100% of one core on my machine...

**Comment by zooba** [comment]
As long as it is making progress, then the 100% CPU usage is expected - this isn't some cheap trick we're doing, it's a serious amount of work to get really good code suggestions, and by front-loading it we ensure that once it completes we don't have to be constantly running at 100% while you're working.

You can disable the auto-start on the Tools, Options, Python Tools, General page, though that won't help it complete. We'll be releasing an updated build soon that will have the crash fix you're encountering right now in the previous unstable build, but until we can add new UI to make users aware that something has not worked (and make it really easy for them to tell us about it), we won't be making it easier to ignore the problems.

We really appreciate you working with us to sort these errors out. It will make our next stable release much better for everyone.

**Comment by int19h** [comment]
RC2 is out now - @nickos556, can you check it out to verify that the crash that you were hitting is fixed there?

**Comment by int19h** [comment]
Please reopen if it still repros.

**Comment by nickos556** [comment]
Hi guys... I've pulled down the latest RC (PTVS 2.2 RC2 for VS 2013), ran the intellisense parser and it ran through my Anaconda python distribution and completed without any errors. Code completion is now working great. 
Many thanks for all your assistance and for your efforts in building the Python ecosystem!
Maybe you guys could build a 'grid' widget next that could be used to view tabular data such as pandas DataFrames :) ?

thanks again!

**Comment by int19h** [comment]
> Maybe you guys could build a 'grid' widget next that could be used to view tabular data such as pandas DataFrames :) ?

The magic 8-ball says: outlook good!
