### ISSUE TITLE
OOM handling REPL prompt change

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#927]
Got this exception during tests.

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.OutOfMemoryException
   at Microsoft.PythonTools.Debugger.Extensions.ReadString(System.IO.Stream)
   at Microsoft.PythonTools.Repl.BasePythonReplEvaluator+CommandProcessorThread.HandlePromptChanged()
   at Microsoft.PythonTools.Repl.BasePythonReplEvaluator+CommandProcessorThread.OutputThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

It occurred during common initialization of each test and appears to be random.

**Comment by zooba** [comment]
Closing as wontfix, since it has not occurred outside of tests and we are likely to entirely replace this code for next release.
