### ISSUE TITLE
Add existing virtual environment (venv) doesn't work

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#994]
PTVS 2.2.31105
VS 2013 Update 4
Python 3.5 64-bit all-user install

I create a virtual env from 'Test' dir using venv:

```
py -3.5 -m venv env
```
I create an empty .py file in 'Test' dir then use Project From Existing Code and point it to the 'Test' dir.  I leave it to auto-detect virtual env, but after project is created the only env listed is my global default.

When I try to add existing virtual env, it gives me an error.  I originally was trying with Python 3.4 (64-bit) and got same result.

At this point I don't know if it's broken just for my machine or not.

![add-existing-venv](https://cloud.githubusercontent.com/assets/1696845/11309200/4779cee6-8f77-11e5-8902-8d3a5bed2ac8.png)

**Comment by huguesv** [comment]
Turns out I can't create a venv for Python 3.5 64-bit from inside PTVS:
```
Installing 'pip' package manager.
pip is already available.
'pip' was installed successfully.
Installing 'pip' package manager.
pip is already available.
'pip' was installed successfully.
Collecting https://go.microsoft.com/fwlink/?LinkID=317969
  Using cached https://go.microsoft.com/fwlink/?LinkID=317969
  Cannot determine compression type for file C:\Users\huvalo\AppData\Local\Temp\pip-nua4_q1h-unpack\fwlink.obj
Installing collected packages: virtualenv
  Running setup.py install for virtualenv
    Complete output from command "C:\Program Files\Python 3.5\python.exe" -c "import setuptools, tokenize;__file__='C:\\Users\\huvalo\\AppData\\Local\\Temp\\pip-t09r0g1g-build\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\huvalo\AppData\Local\Temp\pip-h70aovhk-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib
    copying virtualenv.py -> build\lib
    creating build\lib\virtualenv_support
    copying virtualenv_support\__init__.py -> build\lib\virtualenv_support
    copying virtualenv_support\pip-6.1.1-py2.py3-none-any.whl -> build\lib\virtualenv_support
    copying virtualenv_support\setuptools-15.0-py2.py3-none-any.whl -> build\lib\virtualenv_support
    running install_lib
    copying build\lib\virtualenv.py -> C:\Program Files\Python 3.5\Lib\site-packages
    error: could not create 'C:\Program Files\Python 3.5\Lib\site-packages\virtualenv.py': Permission denied
    
    ----------------------------------------
Command ""C:\Program Files\Python 3.5\python.exe" -c "import setuptools, tokenize;__file__='C:\\Users\\huvalo\\AppData\\Local\\Temp\\pip-t09r0g1g-build\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\huvalo\AppData\Local\Temp\pip-h70aovhk-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\huvalo\AppData\Local\Temp\pip-t09r0g1g-build
System.InvalidOperationException: Virtual environment was not created at 'C:\Projects\temp\TestAutoRest4\env\'
   at Microsoft.PythonTools.Project.VirtualEnv.<CreateAndInstallDependencies>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Project.PythonProjectNode.<CreateOrAddVirtualEnvironment>d__148.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Project.AddVirtualEnvironmentOperation.<Run>d__10.MoveNext()
```

I can create one for Python 3.5 32-bit though.  Both Python 3.5 are installed in program files (all-user).

**Comment by zooba** [comment]
Funny that it wants to use `virtualenv` and not `venv`... any ideas why that may be?

**Comment by huguesv** [comment]
I don't know how I end up in these situations where virtualenv is installed in my Python 3 environments.  See what the dialog says it's going to do, and the list of packages in my 3.5-32bit in this screenshot:
![python35-virtualenv-instal](https://cloud.githubusercontent.com/assets/1696845/11312696/b344f726-8f8c-11e5-9d33-0d83857aac66.png)

**Comment by zooba** [comment]
Can you grab the diagnostic info off that machine for me? I can't repro on my own.

**Comment by huguesv** [comment]
Saved it here: \\pytools\bugs\994

**Comment by zooba** [comment]
So your Python 3.5 32-bit isn't installed in Program Files, which is why it worked, though I don't see why it wants to install pip and virtualenv here.
